In [27]:
from pathlib import Path
import warnings

import numpy as np
import pandas as pd

from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import HistGradientBoostingRegressor

warnings.filterwarnings("ignore")

DATA_DIR = Path("data")

train = pd.read_csv(DATA_DIR / "train.csv")
test = pd.read_csv(DATA_DIR / "test_x.csv")

TARGET = "bilissel_performans_skoru"

X = train.drop(columns=["id", TARGET])
y = train[TARGET]

test_ids = test["id"]
X_test = test.drop(columns=["id"])

print("Train:", X.shape)
print("Test:", X_test.shape)

Train: (56000, 22)
Test: (24000, 22)

In [28]:
def prepare_features(X, X_test):
    X_fe = X.copy()
    X_test_fe = X_test.copy()

    log_cols = [
        "uyku_oncesi_kafein_mg",
        "uyku_oncesi_ekran_suresi_dk"
    ]

    for col in log_cols:
        if col in X_fe.columns:
            X_fe[col] = np.log1p(X_fe[col])
            X_test_fe[col] = np.log1p(X_test_fe[col])

    def add_features(df):
        df = df.copy()

        if "stres_skoru" in df.columns and "gunluk_calisma_saati" in df.columns:
            df["stres_calisma_yuku"] = df["stres_skoru"] * df["gunluk_calisma_saati"]

        if "rem_yuzdesi" in df.columns and "derin_uyku_yuzdesi" in df.columns:
            df["uyku_kalitesi_orani"] = df["rem_yuzdesi"] + df["derin_uyku_yuzdesi"]

        if "gecelik_uyanma_sayisi" in df.columns and "uykuya_dalma_suresi_dk" in df.columns:
            df["uyku_bozulma_skoru"] = df["gecelik_uyanma_sayisi"] + df["uykuya_dalma_suresi_dk"]

        if "uyku_oncesi_ekran_suresi_dk" in df.columns and "uyku_oncesi_kafein_mg" in df.columns:
            df["dijital_kafein_yuku"] = df["uyku_oncesi_ekran_suresi_dk"] * df["uyku_oncesi_kafein_mg"]

        if "gunluk_adim_sayisi" in df.columns and "stres_skoru" in df.columns:
            df["aktivite_stres_orani"] = df["gunluk_adim_sayisi"] / (df["stres_skoru"] + 1)

        return df

    X_fe = add_features(X_fe)
    X_test_fe = add_features(X_test_fe)

    return X_fe, X_test_fe


X_fe, X_test_fe = prepare_features(X, X_test)

print("X_fe:", X_fe.shape)
print("X_test_fe:", X_test_fe.shape)

X_fe: (56000, 27)
X_test_fe: (24000, 27)

In [29]:
cv = KFold(n_splits=5, shuffle=True, random_state=42)

def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

In [ ]:
from catboost import CatBoostRegressor

def get_catboost_oof(X_fe, y, X_test_fe, cv):
    X_cb = X_fe.copy()
    X_test_cb = X_test_fe.copy()

    cat_cols = X_cb.select_dtypes(include="object").columns.tolist()

    for col in cat_cols:
        X_cb[col] = X_cb[col].fillna("Bilinmiyor").astype(str)
        X_test_cb[col] = X_test_cb[col].fillna("Bilinmiyor").astype(str)

    cat_features_idx = [X_cb.columns.get_loc(col) for col in cat_cols]

    oof_preds = np.zeros(len(X_cb))
    test_preds = np.zeros(len(X_test_cb))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_cb), 1):
        X_train_fold = X_cb.iloc[train_idx]
        X_val_fold = X_cb.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        model = CatBoostRegressor(
            loss_function="RMSE",
            eval_metric="RMSE",
            iterations=1500,
            learning_rate=0.035,
            depth=6,
            l2_leaf_reg=5,
            random_seed=42,
            verbose=200,
            early_stopping_rounds=100
        )

        model.fit(
            X_train_fold,
            y_train_fold,
            cat_features=cat_features_idx,
            eval_set=(X_val_fold, y_val_fold),
            use_best_model=True
        )

        val_pred = model.predict(X_val_fold)
        test_pred = model.predict(X_test_cb)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"CatBoost Fold {fold} RMSE:", fold_rmse)

    print("CatBoost Fold RMSE:", fold_scores)
    print("CatBoost Mean RMSE:", np.mean(fold_scores))
    print("CatBoost OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores


oof_cat, test_cat, scores_cat = get_catboost_oof(X_fe, y, X_test_fe, cv)

In [ ]:
def get_hgb_oof(X_fe, y, X_test_fe, cv):
    num_cols = X_fe.select_dtypes(include=np.number).columns.tolist()
    cat_cols = X_fe.select_dtypes(include="object").columns.tolist()

    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median", add_indicator=True))
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="constant", fill_value="Bilinmiyor")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, num_cols),
            ("cat", categorical_transformer, cat_cols)
        ]
    )

    oof_preds = np.zeros(len(X_fe))
    test_preds = np.zeros(len(X_test_fe))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_fe), 1):
        X_train_fold = X_fe.iloc[train_idx]
        X_val_fold = X_fe.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        model = HistGradientBoostingRegressor(
            max_iter=700,
            learning_rate=0.04,
            max_leaf_nodes=31,
            min_samples_leaf=20,
            l2_regularization=0.1,
            random_state=42
        )

        pipeline = Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("model", model)
        ])

        pipeline.fit(X_train_fold, y_train_fold)

        val_pred = pipeline.predict(X_val_fold)
        test_pred = pipeline.predict(X_test_fe)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"HGB Fold {fold} RMSE:", fold_rmse)

    print("HGB Fold RMSE:", fold_scores)
    print("HGB Mean RMSE:", np.mean(fold_scores))
    print("HGB OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores


oof_hgb, test_hgb, scores_hgb = get_hgb_oof(X_fe, y, X_test_fe, cv)

HGB Fold 1 RMSE: 1.228499560987444
HGB Fold 2 RMSE: 1.2290440992060874
HGB Fold 3 RMSE: 1.2159707118361172
HGB Fold 4 RMSE: 1.2243227403073043
HGB Fold 5 RMSE: 1.2450227212554872
HGB Fold RMSE: [np.float64(1.228499560987444), np.float64(1.2290440992060874), np.float64(1.2159707118361172), np.float64(1.2243227403073043), np.float64(1.2450227212554872)]
HGB Mean RMSE: 1.228571966718488
HGB OOF RMSE: 1.2286084071060954

In [ ]:
from scipy.optimize import minimize

oof_matrix = np.column_stack([
    oof_cat,
    oof_hgb
])

test_matrix = np.column_stack([
    test_cat,
    test_hgb
])

def blend_rmse(weights):
    preds = oof_matrix @ weights
    return rmse(y, preds)

n_models = oof_matrix.shape[1]

initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result = minimize(
    blend_rmse,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights = result.x
best_oof_preds = oof_matrix @ best_weights
best_test_preds = test_matrix @ best_weights

print("Best weights:", best_weights)
print("Blend OOF RMSE:", rmse(y, best_oof_preds))

Best weights: [0.84412931 0.15587069]
Blend OOF RMSE: 1.2164008947511131

## Deney 12 - LightGBM OOF

In [ ]:
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

In [ ]:
def get_lgbm_oof(X_fe, y, X_test_fe, cv):
    num_cols = X_fe.select_dtypes(include=np.number).columns.tolist()
    cat_cols = X_fe.select_dtypes(include="object").columns.tolist()

    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median", add_indicator=True))
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="constant", fill_value="Bilinmiyor")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, num_cols),
            ("cat", categorical_transformer, cat_cols)
        ]
    )

    oof_preds = np.zeros(len(X_fe))
    test_preds = np.zeros(len(X_test_fe))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_fe), 1):
        X_train_fold = X_fe.iloc[train_idx]
        X_val_fold = X_fe.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        model = LGBMRegressor(
            objective="regression",
            n_estimators=1500,
            learning_rate=0.03,
            num_leaves=31,
            max_depth=-1,
            min_child_samples=25,
            subsample=0.9,
            colsample_bytree=0.9,
            reg_alpha=0.05,
            reg_lambda=0.1,
            random_state=42,
            n_jobs=-1,
            verbose=-1
        )

        pipeline = Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("model", model)
        ])

        pipeline.fit(X_train_fold, y_train_fold)

        val_pred = pipeline.predict(X_val_fold)
        test_pred = pipeline.predict(X_test_fe)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"LightGBM Fold {fold} RMSE:", fold_rmse)

    print("LightGBM Fold RMSE:", fold_scores)
    print("LightGBM Mean RMSE:", np.mean(fold_scores))
    print("LightGBM OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores


oof_lgbm, test_lgbm, scores_lgbm = get_lgbm_oof(X_fe, y, X_test_fe, cv)

LightGBM Fold 1 RMSE: 1.2309181643011173
LightGBM Fold 2 RMSE: 1.2325901907249033
LightGBM Fold 3 RMSE: 1.216643647877837
LightGBM Fold 4 RMSE: 1.227986278236269
LightGBM Fold 5 RMSE: 1.2480293215439149
LightGBM Fold RMSE: [np.float64(1.2309181643011173), np.float64(1.2325901907249033), np.float64(1.216643647877837), np.float64(1.227986278236269), np.float64(1.2480293215439149)]
LightGBM Mean RMSE: 1.2312335205368083
LightGBM OOF RMSE: 1.2312747344414328

## Deney 13 - XGBoost OOF

In [ ]:
def get_xgb_oof(X_fe, y, X_test_fe, cv):
    num_cols = X_fe.select_dtypes(include=np.number).columns.tolist()
    cat_cols = X_fe.select_dtypes(include="object").columns.tolist()

    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median", add_indicator=True))
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="constant", fill_value="Bilinmiyor")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, num_cols),
            ("cat", categorical_transformer, cat_cols)
        ]
    )

    oof_preds = np.zeros(len(X_fe))
    test_preds = np.zeros(len(X_test_fe))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_fe), 1):
        X_train_fold = X_fe.iloc[train_idx]
        X_val_fold = X_fe.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        model = XGBRegressor(
            objective="reg:squarederror",
            eval_metric="rmse",
            n_estimators=1200,
            learning_rate=0.035,
            max_depth=5,
            min_child_weight=3,
            subsample=0.9,
            colsample_bytree=0.9,
            reg_alpha=0.05,
            reg_lambda=1.0,
            random_state=42,
            n_jobs=-1,
            tree_method="hist"
        )

        pipeline = Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("model", model)
        ])

        pipeline.fit(X_train_fold, y_train_fold)

        val_pred = pipeline.predict(X_val_fold)
        test_pred = pipeline.predict(X_test_fe)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"XGBoost Fold {fold} RMSE:", fold_rmse)

    print("XGBoost Fold RMSE:", fold_scores)
    print("XGBoost Mean RMSE:", np.mean(fold_scores))
    print("XGBoost OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores


oof_xgb, test_xgb, scores_xgb = get_xgb_oof(X_fe, y, X_test_fe, cv)

XGBoost Fold 1 RMSE: 1.229662159932237
XGBoost Fold 2 RMSE: 1.231117587938982
XGBoost Fold 3 RMSE: 1.2179742670775981
XGBoost Fold 4 RMSE: 1.2286724371160755
XGBoost Fold 5 RMSE: 1.2481196945798023
XGBoost Fold RMSE: [np.float64(1.229662159932237), np.float64(1.231117587938982), np.float64(1.2179742670775981), np.float64(1.2286724371160755), np.float64(1.2481196945798023)]
XGBoost Mean RMSE: 1.231109229328939
XGBoost OOF RMSE: 1.2311473988025852

## Deney 14 — 4 Model OOF Optimized Blend

In [ ]:
from scipy.optimize import minimize

oof_matrix_4 = np.column_stack([
    oof_cat,
    oof_hgb,
    oof_lgbm,
    oof_xgb
])

test_matrix_4 = np.column_stack([
    test_cat,
    test_hgb,
    test_lgbm,
    test_xgb
])

model_names = [
    "CatBoost",
    "HGB",
    "LightGBM",
    "XGBoost"
]

def blend_rmse_4(weights):
    preds = oof_matrix_4 @ weights
    return rmse(y, preds)

n_models = oof_matrix_4.shape[1]
initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result_4 = minimize(
    blend_rmse_4,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights_4 = result_4.x
best_oof_preds_4 = oof_matrix_4 @ best_weights_4
best_test_preds_4 = test_matrix_4 @ best_weights_4

print("Optimization success:", result_4.success)
print("Best weights:")
for name, weight in zip(model_names, best_weights_4):
    print(f"{name}: {weight:.6f}")

print("4-Model Blend OOF RMSE:", rmse(y, best_oof_preds_4))

Optimization success: True
Best weights:
CatBoost: 0.814445
HGB: 0.117379
LightGBM: 0.068176
XGBoost: 0.000000
4-Model Blend OOF RMSE: 1.2163393057392826

In [ ]:
submission_exp14 = pd.DataFrame({
    "id": test_ids,
    TARGET: best_test_preds_4
})

submission_exp14[TARGET] = submission_exp14[TARGET].clip(0, 10)

print(submission_exp14.shape)
print(submission_exp14.head())
print(submission_exp14[TARGET].describe())

submission_exp14.to_csv("submission_exp14_4model_oof_blend.csv", index=False)

(24000, 2)
   id  bilissel_performans_skoru
0   1                   5.991153
1   2                   6.700747
2   3                   3.031903
3   4                   7.185300
4   5                   3.656060
count    24000.000000
mean         5.936518
std          1.860162
min          0.000000
25%          4.652755
50%          6.042710
75%          7.321258
max         10.000000
Name: bilissel_performans_skoru, dtype: float64

## KNN ile Deney

In [ ]:
# ============================================================
# Deney - KNN OOF Regressor
# Tek blok: veri okuma + feature engineering + KNN OOF
# ============================================================

from pathlib import Path
import warnings

import numpy as np
import pandas as pd

from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

warnings.filterwarnings("ignore")

# ----------------------------
# 1. Veri okuma
# ----------------------------
DATA_DIR = Path("data")

train = pd.read_csv(DATA_DIR / "train.csv")
test = pd.read_csv(DATA_DIR / "test_x.csv")

TARGET = "bilissel_performans_skoru"

X = train.drop(columns=["id", TARGET])
y = train[TARGET]

test_ids = test["id"]
X_test = test.drop(columns=["id"])

print("Train:", X.shape)
print("Test:", X_test.shape)

# ----------------------------
# 2. Feature engineering
# ----------------------------
def prepare_features(X, X_test):
    X_fe = X.copy()
    X_test_fe = X_test.copy()

    log_cols = [
        "uyku_oncesi_kafein_mg",
        "uyku_oncesi_ekran_suresi_dk"
    ]

    for col in log_cols:
        if col in X_fe.columns:
            X_fe[col] = np.log1p(X_fe[col])
            X_test_fe[col] = np.log1p(X_test_fe[col])

    def add_features(df):
        df = df.copy()

        if "stres_skoru" in df.columns and "gunluk_calisma_saati" in df.columns:
            df["stres_calisma_yuku"] = df["stres_skoru"] * df["gunluk_calisma_saati"]

        if "rem_yuzdesi" in df.columns and "derin_uyku_yuzdesi" in df.columns:
            df["uyku_kalitesi_orani"] = df["rem_yuzdesi"] + df["derin_uyku_yuzdesi"]

        if "gecelik_uyanma_sayisi" in df.columns and "uykuya_dalma_suresi_dk" in df.columns:
            df["uyku_bozulma_skoru"] = df["gecelik_uyanma_sayisi"] + df["uykuya_dalma_suresi_dk"]

        if "uyku_oncesi_ekran_suresi_dk" in df.columns and "uyku_oncesi_kafein_mg" in df.columns:
            df["dijital_kafein_yuku"] = (
                df["uyku_oncesi_ekran_suresi_dk"] * df["uyku_oncesi_kafein_mg"]
            )

        if "gunluk_adim_sayisi" in df.columns and "stres_skoru" in df.columns:
            df["aktivite_stres_orani"] = df["gunluk_adim_sayisi"] / (df["stres_skoru"] + 1)

        return df

    X_fe = add_features(X_fe)
    X_test_fe = add_features(X_test_fe)

    return X_fe, X_test_fe


X_fe, X_test_fe = prepare_features(X, X_test)

print("X_fe:", X_fe.shape)
print("X_test_fe:", X_test_fe.shape)

# ----------------------------
# 3. Ortak RMSE ve CV
# ----------------------------
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))


cv = KFold(n_splits=5, shuffle=True, random_state=42)

# ----------------------------
# 4. KNN OOF fonksiyonu
# ----------------------------
def get_knn_oof(X_fe, y, X_test_fe, cv):
    num_cols = X_fe.select_dtypes(include=np.number).columns.tolist()
    cat_cols = X_fe.select_dtypes(include="object").columns.tolist()

    print("Numeric columns:", len(num_cols))
    print("Categorical columns:", len(cat_cols))

    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="constant", fill_value="Bilinmiyor")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, num_cols),
            ("cat", categorical_transformer, cat_cols)
        ]
    )

    oof_preds = np.zeros(len(X_fe))
    test_preds = np.zeros(len(X_test_fe))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_fe), 1):
        X_train_fold = X_fe.iloc[train_idx]
        X_val_fold = X_fe.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        model = KNeighborsRegressor(
            n_neighbors=25,
            weights="distance",
            metric="minkowski",
            p=2,
            n_jobs=-1
        )

        pipeline = Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("model", model)
        ])

        pipeline.fit(X_train_fold, y_train_fold)

        val_pred = pipeline.predict(X_val_fold)
        test_pred = pipeline.predict(X_test_fe)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"KNN Fold {fold} RMSE:", fold_rmse)

    print("KNN Fold RMSE:", fold_scores)
    print("KNN Mean RMSE:", np.mean(fold_scores))
    print("KNN OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores


# ----------------------------
# 5. KNN çalıştır
# ----------------------------
oof_knn, test_knn, scores_knn = get_knn_oof(X_fe, y, X_test_fe, cv)

Train: (56000, 22)
Test: (24000, 22)
X_fe: (56000, 27)
X_test_fe: (24000, 27)
Numeric columns: 20
Categorical columns: 7
KNN Fold 1 RMSE: 1.4457580499194775
KNN Fold 2 RMSE: 1.4265810713502436
KNN Fold 3 RMSE: 1.431239952368049
KNN Fold 4 RMSE: 1.4327170571341614
KNN Fold 5 RMSE: 1.4536697571732202
KNN Fold RMSE: [np.float64(1.4457580499194775), np.float64(1.4265810713502436), np.float64(1.431239952368049), np.float64(1.4327170571341614), np.float64(1.4536697571732202)]
KNN Mean RMSE: 1.4379931775890307
KNN OOF RMSE: 1.438028624333987


## Deney 15 - CatBoost Seed Ensemble

 Mevcut oof_cat / test_cat seed=42 kabul edilerek sadece seed 2024 ve 3407 çalıştırılır.

In [ ]:
from catboost import CatBoostRegressor
import numpy as np

def get_catboost_oof_with_seed(X_fe, y, X_test_fe, cv, seed):
    X_cb = X_fe.copy()
    X_test_cb = X_test_fe.copy()

    cat_cols = X_cb.select_dtypes(include="object").columns.tolist()

    for col in cat_cols:
        X_cb[col] = X_cb[col].fillna("Bilinmiyor").astype(str)
        X_test_cb[col] = X_test_cb[col].fillna("Bilinmiyor").astype(str)

    cat_features_idx = [X_cb.columns.get_loc(col) for col in cat_cols]

    oof_preds = np.zeros(len(X_cb))
    test_preds = np.zeros(len(X_test_cb))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_cb), 1):
        X_train_fold = X_cb.iloc[train_idx]
        X_val_fold = X_cb.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        model = CatBoostRegressor(
            loss_function="RMSE",
            eval_metric="RMSE",
            iterations=1500,
            learning_rate=0.035,
            depth=6,
            l2_leaf_reg=5,
            random_seed=seed,
            verbose=200,
            early_stopping_rounds=100
        )

        model.fit(
            X_train_fold,
            y_train_fold,
            cat_features=cat_features_idx,
            eval_set=(X_val_fold, y_val_fold),
            use_best_model=True
        )

        val_pred = model.predict(X_val_fold)
        test_pred = model.predict(X_test_cb)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"Seed {seed} - Fold {fold} RMSE:", fold_rmse)

    print(f"Seed {seed} Fold RMSE:", fold_scores)
    print(f"Seed {seed} Mean RMSE:", np.mean(fold_scores))
    print(f"Seed {seed} OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores


seeds = [42, 2024, 3407]

cat_oof_list = []
cat_test_list = []
cat_seed_scores = {}

for seed in seeds:
    print("=" * 70)
    print(f"Running CatBoost seed: {seed}")
    print("=" * 70)

    oof_seed, test_seed, scores_seed = get_catboost_oof_with_seed(
        X_fe,
        y,
        X_test_fe,
        cv,
        seed
    )

    cat_oof_list.append(oof_seed)
    cat_test_list.append(test_seed)

    cat_seed_scores[seed] = {
        "fold_scores": scores_seed,
        "mean_rmse": np.mean(scores_seed),
        "oof_rmse": rmse(y, oof_seed)
    }

oof_cat_seed_ensemble = np.mean(cat_oof_list, axis=0)
test_cat_seed_ensemble = np.mean(cat_test_list, axis=0)

print("=" * 70)
print("CatBoost Seed Scores")
print("=" * 70)

for seed, result in cat_seed_scores.items():
    print(f"Seed {seed}")
    print("Mean RMSE:", result["mean_rmse"])
    print("OOF RMSE:", result["oof_rmse"])
    print()

print("CatBoost Seed Ensemble OOF RMSE:", rmse(y, oof_cat_seed_ensemble))

======================================================================
Running CatBoost seed: 42
======================================================================
0:	learn: 2.1899899	test: 2.2002100	best: 2.2002100 (0)	total: 8.09ms	remaining: 12.1s
200:	learn: 1.2203253	test: 1.2387517	best: 1.2387517 (200)	total: 1.49s	remaining: 9.66s
400:	learn: 1.1993460	test: 1.2270202	best: 1.2270202 (400)	total: 2.98s	remaining: 8.16s
600:	learn: 1.1871140	test: 1.2239233	best: 1.2238886 (596)	total: 4.43s	remaining: 6.63s
800:	learn: 1.1768064	test: 1.2228847	best: 1.2228847 (800)	total: 5.94s	remaining: 5.18s
1000:	learn: 1.1675482	test: 1.2223728	best: 1.2223562 (997)	total: 7.4s	remaining: 3.69s
1200:	learn: 1.1580040	test: 1.2223533	best: 1.2222052 (1149)	total: 8.89s	remaining: 2.21s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.222205227
bestIteration = 1149

Shrink model to first 1150 iterations.
Seed 42 - Fold 1 RMSE: 1.2222052278876236
0:	learn: 2.1933248	test: 2.1844791	best: 2.1844791 (0)	total: 7.6ms	remaining: 11.4s
200:	learn: 1.2219388	test: 1.2329316	best: 1.2329316 (200)	total: 1.68s	remaining: 10.8s
400:	learn: 1.2002286	test: 1.2200778	best: 1.2200778 (400)	total: 3.18s	remaining: 8.71s
600:	learn: 1.1871296	test: 1.2176941	best: 1.2176941 (600)	total: 4.64s	remaining: 6.95s
800:	learn: 1.1762848	test: 1.2171739	best: 1.2170671 (763)	total: 6.21s	remaining: 5.42s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.217067076
bestIteration = 763

Shrink model to first 764 iterations.
Seed 42 - Fold 2 RMSE: 1.2170670773120693
0:	learn: 2.1918263	test: 2.1904405	best: 2.1904405 (0)	total: 8.48ms	remaining: 12.7s
200:	learn: 1.2250183	test: 1.2180089	best: 1.2180089 (200)	total: 1.49s	remaining: 9.64s
400:	learn: 1.2056242	test: 1.2070444	best: 1.2070406 (398)	total: 2.98s	remaining: 8.17s
600:	learn: 1.1942344	test: 1.2045979	best: 1.2045979 (600)	total: 4.47s	remaining: 6.68s
800:	learn: 1.1837816	test: 1.2039099	best: 1.2037992 (744)	total: 5.98s	remaining: 5.22s
1000:	learn: 1.1738191	test: 1.2032492	best: 1.2032035 (997)	total: 7.48s	remaining: 3.73s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.203203521
bestIteration = 997

Shrink model to first 998 iterations.
Seed 42 - Fold 3 RMSE: 1.203203520627255
0:	learn: 2.1934695	test: 2.1834422	best: 2.1834422 (0)	total: 7.9ms	remaining: 11.8s
200:	learn: 1.2219774	test: 1.2222936	best: 1.2222936 (200)	total: 1.53s	remaining: 9.87s
400:	learn: 1.2004736	test: 1.2116241	best: 1.2116241 (400)	total: 3.04s	remaining: 8.32s
600:	learn: 1.1878463	test: 1.2101770	best: 1.2101636 (588)	total: 4.49s	remaining: 6.72s
800:	learn: 1.1767499	test: 1.2093664	best: 1.2093664 (800)	total: 5.94s	remaining: 5.18s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.209355609
bestIteration = 801

Shrink model to first 802 iterations.
Seed 42 - Fold 4 RMSE: 1.209355609525035
0:	learn: 2.1895988	test: 2.1992243	best: 2.1992243 (0)	total: 7.16ms	remaining: 10.7s
200:	learn: 1.2175895	test: 1.2466416	best: 1.2466416 (200)	total: 1.51s	remaining: 9.75s
400:	learn: 1.1977139	test: 1.2350245	best: 1.2350245 (400)	total: 3.04s	remaining: 8.35s
600:	learn: 1.1850715	test: 1.2324510	best: 1.2324510 (600)	total: 4.47s	remaining: 6.69s
800:	learn: 1.1742713	test: 1.2321750	best: 1.2320696 (757)	total: 5.95s	remaining: 5.19s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.232069558
bestIteration = 757

Shrink model to first 758 iterations.
Seed 42 - Fold 5 RMSE: 1.2320695587217365
Seed 42 Fold RMSE: [np.float64(1.2222052278876236), np.float64(1.2170670773120693), np.float64(1.203203520627255), np.float64(1.209355609525035), np.float64(1.2320695587217365)]
Seed 42 Mean RMSE: 1.216780198814744
Seed 42 OOF RMSE: 1.2168215144071908
======================================================================
Running CatBoost seed: 2024
======================================================================
0:	learn: 2.1897485	test: 2.2009035	best: 2.2009035 (0)	total: 6.99ms	remaining: 10.5s
200:	learn: 1.2196210	test: 1.2388326	best: 1.2388326 (200)	total: 1.47s	remaining: 9.5s
400:	learn: 1.1978061	test: 1.2263886	best: 1.2263886 (400)	total: 2.95s	remaining: 8.09s
600:	learn: 1.1853583	test: 1.2237320	best: 1.2237320 (600)	total: 4.41s	remaining: 6.6s
800:	learn: 1.1746302	test: 1.2225174	best: 1.2225174 (800)	total: 5.87s	remaining: 5.12s
1000:	learn: 1.1649147	test: 1.2216357	best: 1.2215961 (998)	total: 7.38s	remaining: 3.68s
1200:	learn: 1.1557212	test: 1.2214536	best: 1.2214084 (1183)	total: 8.85s	remaining: 2.2s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.221286297
bestIteration = 1299

Shrink model to first 1300 iterations.
Seed 2024 - Fold 1 RMSE: 1.221286297960883
0:	learn: 2.1937682	test: 2.1848561	best: 2.1848561 (0)	total: 7.08ms	remaining: 10.6s
200:	learn: 1.2214029	test: 1.2323032	best: 1.2323032 (200)	total: 1.75s	remaining: 11.3s
400:	learn: 1.1993893	test: 1.2200355	best: 1.2200355 (400)	total: 3.24s	remaining: 8.89s
600:	learn: 1.1860385	test: 1.2171426	best: 1.2171426 (596)	total: 4.76s	remaining: 7.12s
800:	learn: 1.1748271	test: 1.2164943	best: 1.2164829 (796)	total: 6.19s	remaining: 5.4s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.216362417
bestIteration = 850

Shrink model to first 851 iterations.
Seed 2024 - Fold 2 RMSE: 1.2163624180901644
0:	learn: 2.1923618	test: 2.1908398	best: 2.1908398 (0)	total: 9.81ms	remaining: 14.7s
200:	learn: 1.2249340	test: 1.2176364	best: 1.2176364 (200)	total: 1.51s	remaining: 9.79s
400:	learn: 1.2042437	test: 1.2054520	best: 1.2054520 (400)	total: 3s	remaining: 8.21s
600:	learn: 1.1910171	test: 1.2029645	best: 1.2029645 (600)	total: 4.45s	remaining: 6.66s
800:	learn: 1.1791850	test: 1.2023734	best: 1.2023734 (800)	total: 5.96s	remaining: 5.2s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.202299653
bestIteration = 812

Shrink model to first 813 iterations.
Seed 2024 - Fold 3 RMSE: 1.2022996520908928
0:	learn: 2.1940378	test: 2.1839759	best: 2.1839759 (0)	total: 7.76ms	remaining: 11.6s
200:	learn: 1.2233941	test: 1.2234447	best: 1.2234447 (200)	total: 1.51s	remaining: 9.79s
400:	learn: 1.2016172	test: 1.2125301	best: 1.2125301 (400)	total: 3.06s	remaining: 8.37s
600:	learn: 1.1876709	test: 1.2106173	best: 1.2106173 (600)	total: 4.55s	remaining: 6.81s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.210546253
bestIteration = 615

Shrink model to first 616 iterations.
Seed 2024 - Fold 4 RMSE: 1.210546253275008
0:	learn: 2.1897693	test: 2.1993677	best: 2.1993677 (0)	total: 7.22ms	remaining: 10.8s
200:	learn: 1.2173234	test: 1.2465478	best: 1.2465478 (200)	total: 1.47s	remaining: 9.51s
400:	learn: 1.1968780	test: 1.2348303	best: 1.2348303 (400)	total: 2.93s	remaining: 8.03s
600:	learn: 1.1828711	test: 1.2328465	best: 1.2328045 (598)	total: 4.4s	remaining: 6.58s
800:	learn: 1.1714131	test: 1.2323883	best: 1.2322991 (778)	total: 5.87s	remaining: 5.12s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.232150566
bestIteration = 868

Shrink model to first 869 iterations.
Seed 2024 - Fold 5 RMSE: 1.2321505662418946
Seed 2024 Fold RMSE: [np.float64(1.221286297960883), np.float64(1.2163624180901644), np.float64(1.2022996520908928), np.float64(1.210546253275008), np.float64(1.2321505662418946)]
Seed 2024 Mean RMSE: 1.2165290375317686
Seed 2024 OOF RMSE: 1.2165705451271958
======================================================================
Running CatBoost seed: 3407
======================================================================
0:	learn: 2.1904351	test: 2.2016217	best: 2.2016217 (0)	total: 7.18ms	remaining: 10.8s
200:	learn: 1.2206104	test: 1.2389390	best: 1.2389390 (200)	total: 1.49s	remaining: 9.64s
400:	learn: 1.1992415	test: 1.2266255	best: 1.2266255 (400)	total: 2.96s	remaining: 8.13s
600:	learn: 1.1867273	test: 1.2241364	best: 1.2241321 (598)	total: 4.41s	remaining: 6.6s
800:	learn: 1.1764877	test: 1.2227724	best: 1.2227693 (794)	total: 5.89s	remaining: 5.14s
1000:	learn: 1.1664773	test: 1.2226129	best: 1.2225458 (974)	total: 7.39s	remaining: 3.69s
1200:	learn: 1.1570132	test: 1.2224956	best: 1.2223651 (1137)	total: 8.87s	remaining: 2.21s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.222365094
bestIteration = 1137

Shrink model to first 1138 iterations.
Seed 3407 - Fold 1 RMSE: 1.2223650947220508
0:	learn: 2.1944713	test: 2.1858309	best: 2.1858309 (0)	total: 7.73ms	remaining: 11.6s
200:	learn: 1.2229435	test: 1.2329796	best: 1.2329796 (200)	total: 1.47s	remaining: 9.47s
400:	learn: 1.1997539	test: 1.2200301	best: 1.2200301 (400)	total: 2.99s	remaining: 8.2s
600:	learn: 1.1865721	test: 1.2179401	best: 1.2179401 (600)	total: 4.44s	remaining: 6.65s
800:	learn: 1.1763484	test: 1.2175005	best: 1.2174894 (799)	total: 5.9s	remaining: 5.15s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.217489397
bestIteration = 799

Shrink model to first 800 iterations.
Seed 3407 - Fold 2 RMSE: 1.217489397429045
0:	learn: 2.1931479	test: 2.1913556	best: 2.1913556 (0)	total: 7.71ms	remaining: 11.6s
200:	learn: 1.2251465	test: 1.2176941	best: 1.2176941 (200)	total: 1.54s	remaining: 9.93s
400:	learn: 1.2031549	test: 1.2049351	best: 1.2049292 (396)	total: 3.07s	remaining: 8.43s
600:	learn: 1.1910034	test: 1.2031650	best: 1.2030844 (588)	total: 4.52s	remaining: 6.76s
800:	learn: 1.1799594	test: 1.2025012	best: 1.2024581 (783)	total: 6.01s	remaining: 5.24s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.202439926
bestIteration = 823

Shrink model to first 824 iterations.
Seed 3407 - Fold 3 RMSE: 1.2024399258798242
0:	learn: 2.1947037	test: 2.1846926	best: 2.1846926 (0)	total: 8.03ms	remaining: 12s
200:	learn: 1.2234451	test: 1.2229714	best: 1.2229714 (200)	total: 1.51s	remaining: 9.77s
400:	learn: 1.2020058	test: 1.2124814	best: 1.2124814 (400)	total: 3.07s	remaining: 8.41s
600:	learn: 1.1897301	test: 1.2113094	best: 1.2112194 (587)	total: 4.57s	remaining: 6.84s
800:	learn: 1.1785506	test: 1.2109843	best: 1.2109214 (787)	total: 6.09s	remaining: 5.32s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.210921392
bestIteration = 787

Shrink model to first 788 iterations.
Seed 3407 - Fold 4 RMSE: 1.2109213922755
0:	learn: 2.1908891	test: 2.2003505	best: 2.2003505 (0)	total: 8.3ms	remaining: 12.4s
200:	learn: 1.2179541	test: 1.2467742	best: 1.2467742 (200)	total: 1.47s	remaining: 9.5s
400:	learn: 1.1969894	test: 1.2353386	best: 1.2353372 (399)	total: 2.96s	remaining: 8.12s
600:	learn: 1.1853127	test: 1.2332465	best: 1.2332465 (600)	total: 4.36s	remaining: 6.53s
800:	learn: 1.1746064	test: 1.2326134	best: 1.2325406 (750)	total: 5.84s	remaining: 5.09s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.232346031
bestIteration = 849

Shrink model to first 850 iterations.
Seed 3407 - Fold 5 RMSE: 1.2323460316475794
Seed 3407 Fold RMSE: [np.float64(1.2223650947220508), np.float64(1.217489397429045), np.float64(1.2024399258798242), np.float64(1.2109213922755), np.float64(1.2323460316475794)]
Seed 3407 Mean RMSE: 1.2171123683907998
Seed 3407 OOF RMSE: 1.2171545500046277
======================================================================
CatBoost Seed Scores
======================================================================
Seed 42
Mean RMSE: 1.216780198814744
OOF RMSE: 1.2168215144071908

Seed 2024
Mean RMSE: 1.2165290375317686
OOF RMSE: 1.2165705451271958

Seed 3407
Mean RMSE: 1.2171123683907998
OOF RMSE: 1.2171545500046277

CatBoost Seed Ensemble OOF RMSE: 1.216103050186402

## Deney 16 - CatBoost Seed Ensemble + HGB + LightGBM OOF Blend

In [ ]:
import numpy as np

from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

def get_hgb_oof(X_fe, y, X_test_fe, cv):
    num_cols = X_fe.select_dtypes(include=np.number).columns.tolist()
    cat_cols = X_fe.select_dtypes(include="object").columns.tolist()

    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median", add_indicator=True))
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="constant", fill_value="Bilinmiyor")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, num_cols),
            ("cat", categorical_transformer, cat_cols)
        ]
    )

    oof_preds = np.zeros(len(X_fe))
    test_preds = np.zeros(len(X_test_fe))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_fe), 1):
        X_train_fold = X_fe.iloc[train_idx]
        X_val_fold = X_fe.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        model = HistGradientBoostingRegressor(
            max_iter=700,
            learning_rate=0.04,
            max_leaf_nodes=31,
            min_samples_leaf=20,
            l2_regularization=0.1,
            random_state=42
        )

        pipeline = Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("model", model)
        ])

        pipeline.fit(X_train_fold, y_train_fold)

        val_pred = pipeline.predict(X_val_fold)
        test_pred = pipeline.predict(X_test_fe)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"HGB Fold {fold} RMSE:", fold_rmse)

    print("HGB Mean RMSE:", np.mean(fold_scores))
    print("HGB OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores


oof_hgb, test_hgb, scores_hgb = get_hgb_oof(X_fe, y, X_test_fe, cv)

HGB Fold 1 RMSE: 1.228499560987444
HGB Fold 2 RMSE: 1.2290440992060874
HGB Fold 3 RMSE: 1.2159707118361172
HGB Fold 4 RMSE: 1.2243227403073043
HGB Fold 5 RMSE: 1.2450227212554872
HGB Mean RMSE: 1.228571966718488
HGB OOF RMSE: 1.2286084071060954

In [ ]:
import numpy as np

from lightgbm import LGBMRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

def get_lgbm_oof(X_fe, y, X_test_fe, cv):
    num_cols = X_fe.select_dtypes(include=np.number).columns.tolist()
    cat_cols = X_fe.select_dtypes(include="object").columns.tolist()

    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median", add_indicator=True))
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="constant", fill_value="Bilinmiyor")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, num_cols),
            ("cat", categorical_transformer, cat_cols)
        ]
    )

    oof_preds = np.zeros(len(X_fe))
    test_preds = np.zeros(len(X_test_fe))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_fe), 1):
        X_train_fold = X_fe.iloc[train_idx]
        X_val_fold = X_fe.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        model = LGBMRegressor(
            objective="regression",
            n_estimators=1500,
            learning_rate=0.03,
            num_leaves=31,
            max_depth=-1,
            min_child_samples=25,
            subsample=0.9,
            colsample_bytree=0.9,
            reg_alpha=0.05,
            reg_lambda=0.1,
            random_state=42,
            n_jobs=-1,
            verbose=-1
        )

        pipeline = Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("model", model)
        ])

        pipeline.fit(X_train_fold, y_train_fold)

        val_pred = pipeline.predict(X_val_fold)
        test_pred = pipeline.predict(X_test_fe)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"LightGBM Fold {fold} RMSE:", fold_rmse)

    print("LightGBM Mean RMSE:", np.mean(fold_scores))
    print("LightGBM OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores


oof_lgbm, test_lgbm, scores_lgbm = get_lgbm_oof(X_fe, y, X_test_fe, cv)

LightGBM Fold 1 RMSE: 1.2309181643011173
LightGBM Fold 2 RMSE: 1.2325901907249033
LightGBM Fold 3 RMSE: 1.216643647877837
LightGBM Fold 4 RMSE: 1.227986278236269
LightGBM Fold 5 RMSE: 1.2480293215439149
LightGBM Mean RMSE: 1.2312335205368083
LightGBM OOF RMSE: 1.2312747344414328

In [ ]:
from scipy.optimize import minimize
import numpy as np

# Modeller:
# 1. oof_cat_seed_ensemble / test_cat_seed_ensemble
# 2. oof_hgb / test_hgb
# 3. oof_lgbm / test_lgbm

oof_matrix_seed_blend = np.column_stack([
    oof_cat_seed_ensemble,
    oof_hgb,
    oof_lgbm
])

test_matrix_seed_blend = np.column_stack([
    test_cat_seed_ensemble,
    test_hgb,
    test_lgbm
])

model_names_seed_blend = [
    "CatBoost Seed Ensemble",
    "HGB",
    "LightGBM"
]

def blend_rmse_seed(weights):
    preds = oof_matrix_seed_blend @ weights
    return rmse(y, preds)

n_models = oof_matrix_seed_blend.shape[1]
initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result_seed_blend = minimize(
    blend_rmse_seed,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights_seed_blend = result_seed_blend.x
best_oof_preds_seed_blend = oof_matrix_seed_blend @ best_weights_seed_blend
best_test_preds_seed_blend = test_matrix_seed_blend @ best_weights_seed_blend

print("Optimization success:", result_seed_blend.success)
print("Best weights:")

for name, weight in zip(model_names_seed_blend, best_weights_seed_blend):
    print(f"{name}: {weight:.6f}")

print("CatBoost Seed Ensemble OOF RMSE:", rmse(y, oof_cat_seed_ensemble))
print("Seed Ensemble Blend OOF RMSE:", rmse(y, best_oof_preds_seed_blend))

Optimization success: True
Best weights:
CatBoost Seed Ensemble: 0.856283
HGB: 0.118721
LightGBM: 0.024996
CatBoost Seed Ensemble OOF RMSE: 1.216103050186402
Seed Ensemble Blend OOF RMSE: 1.215848349720994

In [ ]:
submission_exp16 = pd.DataFrame({
    "id": test_ids,
    TARGET: best_test_preds_seed_blend
})

submission_exp16[TARGET] = submission_exp16[TARGET].clip(0, 10)

print(submission_exp16.shape)
print(submission_exp16.head())
print(submission_exp16[TARGET].describe())

submission_exp16.to_csv("submission_exp16_seed_ensemble_blend.csv", index=False)

(24000, 2)
   id  bilissel_performans_skoru
0   1                   6.000910
1   2                   6.693142
2   3                   3.031077
3   4                   7.161931
4   5                   3.653956
count    24000.000000
mean         5.935599
std          1.859681
min          0.000000
25%          4.651356
50%          6.043203
75%          7.316779
max         10.000000
Name: bilissel_performans_skoru, dtype: float64

# Deney 17 - Feature Engineering v2

In [ ]:
def prepare_features_v2(X, X_test):
    X_fe = X.copy()
    X_test_fe = X_test.copy()

    log_cols = [
        "uyku_oncesi_kafein_mg",
        "uyku_oncesi_ekran_suresi_dk"
    ]

    for col in log_cols:
        if col in X_fe.columns:
            X_fe[col] = np.log1p(X_fe[col])
            X_test_fe[col] = np.log1p(X_test_fe[col])

    def add_features(df):
        df = df.copy()

        # ----------------------------
        # Mevcut başarılı feature'lar
        # ----------------------------

        if "stres_skoru" in df.columns and "gunluk_calisma_saati" in df.columns:
            df["stres_calisma_yuku"] = df["stres_skoru"] * df["gunluk_calisma_saati"]

        if "rem_yuzdesi" in df.columns and "derin_uyku_yuzdesi" in df.columns:
            df["uyku_kalitesi_orani"] = df["rem_yuzdesi"] + df["derin_uyku_yuzdesi"]

        if "gecelik_uyanma_sayisi" in df.columns and "uykuya_dalma_suresi_dk" in df.columns:
            df["uyku_bozulma_skoru"] = df["gecelik_uyanma_sayisi"] + df["uykuya_dalma_suresi_dk"]

        if "uyku_oncesi_ekran_suresi_dk" in df.columns and "uyku_oncesi_kafein_mg" in df.columns:
            df["dijital_kafein_yuku"] = (
                df["uyku_oncesi_ekran_suresi_dk"] * df["uyku_oncesi_kafein_mg"]
            )

            df["ekran_kafein_toplam_yuku"] = (
                df["uyku_oncesi_ekran_suresi_dk"] + df["uyku_oncesi_kafein_mg"]
            )

        if "gunluk_adim_sayisi" in df.columns and "stres_skoru" in df.columns:
            df["aktivite_stres_orani"] = df["gunluk_adim_sayisi"] / (df["stres_skoru"] + 1)

        # ----------------------------
        # Yeni feature'lar v2
        # ----------------------------

        if "uyku_kalitesi_orani" in df.columns and "stres_skoru" in df.columns:
            df["stres_uyku_kalitesi_orani"] = df["stres_skoru"] / (df["uyku_kalitesi_orani"] + 1)

        if "uyku_kalitesi_orani" in df.columns and "gunluk_calisma_saati" in df.columns:
            df["calisma_uyku_kalitesi_orani"] = df["gunluk_calisma_saati"] / (df["uyku_kalitesi_orani"] + 1)

        if "uyku_bozulma_skoru" in df.columns and "stres_skoru" in df.columns:
            df["stres_uyku_bozulma"] = df["stres_skoru"] * df["uyku_bozulma_skoru"]

        if "gunluk_adim_sayisi" in df.columns and "gunluk_calisma_saati" in df.columns:
            df["adim_calisma_orani"] = df["gunluk_adim_sayisi"] / (df["gunluk_calisma_saati"] + 1)

        if "uyku_kalitesi_orani" in df.columns and "uyku_bozulma_skoru" in df.columns:
            df["uyku_verimlilik_proxy"] = df["uyku_kalitesi_orani"] / (df["uyku_bozulma_skoru"] + 1)

        if "dinlenik_nabiz_bpm" in df.columns and "vucut_kitle_indeksi" in df.columns:
            df["fizyolojik_yuk"] = df["dinlenik_nabiz_bpm"] * df["vucut_kitle_indeksi"]

        if "dinlenik_nabiz_bpm" in df.columns and "gunluk_adim_sayisi" in df.columns:
            df["nabiz_aktivite_orani"] = df["dinlenik_nabiz_bpm"] / (df["gunluk_adim_sayisi"] + 1)

        return df

    X_fe = add_features(X_fe)
    X_test_fe = add_features(X_test_fe)

    return X_fe, X_test_fe


X_fe_v2, X_test_fe_v2 = prepare_features_v2(X, X_test)

print("X_fe_v2:", X_fe_v2.shape)
print("X_test_fe_v2:", X_test_fe_v2.shape)

X_fe_v2: (56000, 35)
X_test_fe_v2: (24000, 35)

# Deney 17A - CatBoost Seed Ensemble with Feature Engineering v2

In [ ]:
seeds = [42, 2024, 3407]

cat_oof_list_v2 = []
cat_test_list_v2 = []
cat_seed_scores_v2 = {}

for seed in seeds:
    print("=" * 70)
    print(f"Running CatBoost v2 seed: {seed}")
    print("=" * 70)

    oof_seed, test_seed, scores_seed = get_catboost_oof_with_seed(
        X_fe_v2,
        y,
        X_test_fe_v2,
        cv,
        seed
    )

    cat_oof_list_v2.append(oof_seed)
    cat_test_list_v2.append(test_seed)

    cat_seed_scores_v2[seed] = {
        "fold_scores": scores_seed,
        "mean_rmse": np.mean(scores_seed),
        "oof_rmse": rmse(y, oof_seed)
    }

oof_cat_seed_ensemble_v2 = np.mean(cat_oof_list_v2, axis=0)
test_cat_seed_ensemble_v2 = np.mean(cat_test_list_v2, axis=0)

print("=" * 70)
print("CatBoost v2 Seed Scores")
print("=" * 70)

for seed, result in cat_seed_scores_v2.items():
    print(f"Seed {seed}")
    print("Mean RMSE:", result["mean_rmse"])
    print("OOF RMSE:", result["oof_rmse"])
    print()

print("CatBoost v2 Seed Ensemble OOF RMSE:", rmse(y, oof_cat_seed_ensemble_v2))

======================================================================
Running CatBoost v2 seed: 42
======================================================================
0:	learn: 2.1865986	test: 2.1976741	best: 2.1976741 (0)	total: 7.91ms	remaining: 11.9s
200:	learn: 1.2220695	test: 1.2389752	best: 1.2389752 (200)	total: 1.58s	remaining: 10.2s
400:	learn: 1.1996527	test: 1.2264201	best: 1.2264201 (400)	total: 3.17s	remaining: 8.69s
600:	learn: 1.1862719	test: 1.2236896	best: 1.2236811 (598)	total: 4.73s	remaining: 7.08s
800:	learn: 1.1753029	test: 1.2223126	best: 1.2223082 (796)	total: 6.27s	remaining: 5.47s
1000:	learn: 1.1639281	test: 1.2219127	best: 1.2218106 (955)	total: 7.93s	remaining: 3.95s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.221712751
bestIteration = 1058

Shrink model to first 1059 iterations.
Seed 42 - Fold 1 RMSE: 1.2217127517226791
0:	learn: 2.1909521	test: 2.1823133	best: 2.1823133 (0)	total: 8.25ms	remaining: 12.4s
200:	learn: 1.2242263	test: 1.2340560	best: 1.2340560 (200)	total: 1.66s	remaining: 10.7s
400:	learn: 1.2005147	test: 1.2218411	best: 1.2218411 (400)	total: 3.3s	remaining: 9.05s
600:	learn: 1.1862804	test: 1.2193651	best: 1.2193388 (595)	total: 4.83s	remaining: 7.22s
800:	learn: 1.1744540	test: 1.2186678	best: 1.2186407 (795)	total: 6.4s	remaining: 5.59s
1000:	learn: 1.1630199	test: 1.2185663	best: 1.2184015 (952)	total: 8.02s	remaining: 4s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.218401506
bestIteration = 952

Shrink model to first 953 iterations.
Seed 42 - Fold 2 RMSE: 1.2184015062893725
0:	learn: 2.1894690	test: 2.1878637	best: 2.1878637 (0)	total: 7.78ms	remaining: 11.7s
200:	learn: 1.2265850	test: 1.2207884	best: 1.2207884 (200)	total: 1.64s	remaining: 10.6s
400:	learn: 1.2047955	test: 1.2081746	best: 1.2081746 (400)	total: 3.25s	remaining: 8.91s
600:	learn: 1.1909320	test: 1.2057954	best: 1.2057726 (598)	total: 4.84s	remaining: 7.24s
800:	learn: 1.1804460	test: 1.2047778	best: 1.2047703 (798)	total: 6.44s	remaining: 5.62s
1000:	learn: 1.1695290	test: 1.2045228	best: 1.2043581 (954)	total: 8.05s	remaining: 4.01s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.204358146
bestIteration = 954

Shrink model to first 955 iterations.
Seed 42 - Fold 3 RMSE: 1.204358145027395
0:	learn: 2.1918470	test: 2.1818534	best: 2.1818534 (0)	total: 8.14ms	remaining: 12.2s
200:	learn: 1.2232702	test: 1.2236065	best: 1.2236065 (200)	total: 1.56s	remaining: 10.1s
400:	learn: 1.2000121	test: 1.2119913	best: 1.2119913 (400)	total: 3.16s	remaining: 8.67s
600:	learn: 1.1859730	test: 1.2101329	best: 1.2101005 (586)	total: 4.71s	remaining: 7.05s
800:	learn: 1.1738462	test: 1.2095640	best: 1.2095569 (799)	total: 6.26s	remaining: 5.46s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.209482003
bestIteration = 897

Shrink model to first 898 iterations.
Seed 42 - Fold 4 RMSE: 1.2094820035229865
0:	learn: 2.1872394	test: 2.1968104	best: 2.1968104 (0)	total: 7.54ms	remaining: 11.3s
200:	learn: 1.2180239	test: 1.2503272	best: 1.2503272 (200)	total: 1.57s	remaining: 10.1s
400:	learn: 1.1957738	test: 1.2372717	best: 1.2372353 (397)	total: 3.13s	remaining: 8.59s
600:	learn: 1.1827032	test: 1.2352338	best: 1.2352287 (598)	total: 4.7s	remaining: 7.03s
800:	learn: 1.1705991	test: 1.2344441	best: 1.2344082 (764)	total: 6.28s	remaining: 5.48s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.234164333
bestIteration = 885

Shrink model to first 886 iterations.
Seed 42 - Fold 5 RMSE: 1.2341643332402714
Seed 42 Fold RMSE: [np.float64(1.2217127517226791), np.float64(1.2184015062893725), np.float64(1.204358145027395), np.float64(1.2094820035229865), np.float64(1.2341643332402714)]
Seed 42 Mean RMSE: 1.217623747960541
Seed 42 OOF RMSE: 1.2176675357446483
======================================================================
Running CatBoost v2 seed: 2024
======================================================================
0:	learn: 2.1874382	test: 2.1985582	best: 2.1985582 (0)	total: 7.13ms	remaining: 10.7s
200:	learn: 1.2207857	test: 1.2398719	best: 1.2398719 (200)	total: 1.57s	remaining: 10.1s
400:	learn: 1.1980019	test: 1.2275596	best: 1.2275596 (400)	total: 3.21s	remaining: 8.79s
600:	learn: 1.1850697	test: 1.2245151	best: 1.2245151 (600)	total: 4.76s	remaining: 7.12s
800:	learn: 1.1735171	test: 1.2230329	best: 1.2230083 (788)	total: 6.34s	remaining: 5.53s
1000:	learn: 1.1629975	test: 1.2225821	best: 1.2225514 (952)	total: 7.94s	remaining: 3.96s
1200:	learn: 1.1528680	test: 1.2223752	best: 1.2222264 (1103)	total: 9.55s	remaining: 2.38s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.222226403
bestIteration = 1103

Shrink model to first 1104 iterations.
Seed 2024 - Fold 1 RMSE: 1.222226403641606
0:	learn: 2.1903441	test: 2.1818650	best: 2.1818650 (0)	total: 7ms	remaining: 10.5s
200:	learn: 1.2229982	test: 1.2325894	best: 1.2325894 (200)	total: 1.59s	remaining: 10.3s
400:	learn: 1.1993207	test: 1.2206290	best: 1.2206290 (400)	total: 3.2s	remaining: 8.77s
600:	learn: 1.1850425	test: 1.2184531	best: 1.2184208 (588)	total: 4.83s	remaining: 7.22s
800:	learn: 1.1733784	test: 1.2177462	best: 1.2177275 (796)	total: 6.34s	remaining: 5.53s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.217677597
bestIteration = 859

Shrink model to first 860 iterations.
Seed 2024 - Fold 2 RMSE: 1.2176775974504188
0:	learn: 2.1895360	test: 2.1871406	best: 2.1871406 (0)	total: 7.3ms	remaining: 10.9s
200:	learn: 1.2272711	test: 1.2204817	best: 1.2204817 (200)	total: 1.59s	remaining: 10.3s
400:	learn: 1.2047057	test: 1.2079625	best: 1.2079625 (400)	total: 3.15s	remaining: 8.62s
600:	learn: 1.1891871	test: 1.2056714	best: 1.2055737 (588)	total: 4.73s	remaining: 7.08s
800:	learn: 1.1773324	test: 1.2048785	best: 1.2048429 (794)	total: 6.32s	remaining: 5.51s
1000:	learn: 1.1656688	test: 1.2041888	best: 1.2041888 (1000)	total: 7.93s	remaining: 3.95s
1200:	learn: 1.1546400	test: 1.2041176	best: 1.2039899 (1127)	total: 9.58s	remaining: 2.38s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.203989943
bestIteration = 1127

Shrink model to first 1128 iterations.
Seed 2024 - Fold 3 RMSE: 1.203989942376052
0:	learn: 2.1912533	test: 2.1802899	best: 2.1802899 (0)	total: 6.79ms	remaining: 10.2s
200:	learn: 1.2260710	test: 1.2252838	best: 1.2252838 (200)	total: 1.64s	remaining: 10.6s
400:	learn: 1.2025224	test: 1.2129347	best: 1.2129193 (397)	total: 3.31s	remaining: 9.07s
600:	learn: 1.1872536	test: 1.2101819	best: 1.2101819 (600)	total: 4.91s	remaining: 7.35s
800:	learn: 1.1749825	test: 1.2097515	best: 1.2097067 (757)	total: 6.5s	remaining: 5.67s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.209706682
bestIteration = 757

Shrink model to first 758 iterations.
Seed 2024 - Fold 4 RMSE: 1.2097066822746279
0:	learn: 2.1875904	test: 2.1974654	best: 2.1974654 (0)	total: 7.72ms	remaining: 11.6s
200:	learn: 1.2181493	test: 1.2504724	best: 1.2504724 (200)	total: 1.61s	remaining: 10.4s
400:	learn: 1.1954002	test: 1.2377015	best: 1.2377015 (400)	total: 3.2s	remaining: 8.78s
600:	learn: 1.1808560	test: 1.2351154	best: 1.2351055 (598)	total: 4.82s	remaining: 7.21s
800:	learn: 1.1690491	test: 1.2346452	best: 1.2346308 (795)	total: 6.4s	remaining: 5.59s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.234454971
bestIteration = 832

Shrink model to first 833 iterations.
Seed 2024 - Fold 5 RMSE: 1.2344549717202884
Seed 2024 Fold RMSE: [np.float64(1.222226403641606), np.float64(1.2176775974504188), np.float64(1.203989942376052), np.float64(1.2097066822746279), np.float64(1.2344549717202884)]
Seed 2024 Mean RMSE: 1.2176111194925985
Seed 2024 OOF RMSE: 1.2176565385016278
======================================================================
Running CatBoost v2 seed: 3407
======================================================================
0:	learn: 2.1868390	test: 2.1979868	best: 2.1979868 (0)	total: 9.65ms	remaining: 14.5s
200:	learn: 1.2221773	test: 1.2397587	best: 1.2397587 (200)	total: 1.57s	remaining: 10.1s
400:	learn: 1.1996067	test: 1.2268554	best: 1.2268526 (399)	total: 3.16s	remaining: 8.66s
600:	learn: 1.1855584	test: 1.2239757	best: 1.2239737 (599)	total: 4.76s	remaining: 7.12s
800:	learn: 1.1743980	test: 1.2226971	best: 1.2226971 (800)	total: 6.34s	remaining: 5.54s
1000:	learn: 1.1641935	test: 1.2224175	best: 1.2223884 (999)	total: 7.92s	remaining: 3.95s
1200:	learn: 1.1534430	test: 1.2222730	best: 1.2221229 (1155)	total: 9.54s	remaining: 2.37s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.222122902
bestIteration = 1155

Shrink model to first 1156 iterations.
Seed 3407 - Fold 1 RMSE: 1.2221229032946
0:	learn: 2.1907963	test: 2.1823531	best: 2.1823531 (0)	total: 8.07ms	remaining: 12.1s
200:	learn: 1.2234535	test: 1.2332096	best: 1.2332096 (200)	total: 1.59s	remaining: 10.3s
400:	learn: 1.1994042	test: 1.2213819	best: 1.2213609 (398)	total: 3.21s	remaining: 8.8s
600:	learn: 1.1843448	test: 1.2193351	best: 1.2193212 (582)	total: 4.8s	remaining: 7.18s
800:	learn: 1.1728710	test: 1.2187598	best: 1.2187226 (799)	total: 6.38s	remaining: 5.57s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.218722592
bestIteration = 799

Shrink model to first 800 iterations.
Seed 3407 - Fold 2 RMSE: 1.2187225922328135
0:	learn: 2.1894596	test: 2.1875577	best: 2.1875577 (0)	total: 7.68ms	remaining: 11.5s
200:	learn: 1.2265088	test: 1.2194165	best: 1.2194165 (200)	total: 1.59s	remaining: 10.3s
400:	learn: 1.2033387	test: 1.2067303	best: 1.2067303 (400)	total: 3.18s	remaining: 8.72s
600:	learn: 1.1888995	test: 1.2037669	best: 1.2037669 (600)	total: 4.72s	remaining: 7.06s
800:	learn: 1.1773466	test: 1.2027543	best: 1.2026967 (757)	total: 6.28s	remaining: 5.48s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.202459726
bestIteration = 876

Shrink model to first 877 iterations.
Seed 3407 - Fold 3 RMSE: 1.2024597255200133
0:	learn: 2.1914438	test: 2.1812934	best: 2.1812934 (0)	total: 7.97ms	remaining: 12s
200:	learn: 1.2256122	test: 1.2252077	best: 1.2252077 (200)	total: 1.64s	remaining: 10.6s
400:	learn: 1.2017972	test: 1.2131326	best: 1.2131326 (400)	total: 3.21s	remaining: 8.81s
600:	learn: 1.1881334	test: 1.2106870	best: 1.2106738 (599)	total: 4.78s	remaining: 7.15s
800:	learn: 1.1759559	test: 1.2098955	best: 1.2098547 (759)	total: 6.44s	remaining: 5.62s
1000:	learn: 1.1636860	test: 1.2097916	best: 1.2096486 (931)	total: 8.05s	remaining: 4.01s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.209648625
bestIteration = 931

Shrink model to first 932 iterations.
Seed 3407 - Fold 4 RMSE: 1.2096486248398326
0:	learn: 2.1877502	test: 2.1973458	best: 2.1973458 (0)	total: 7.9ms	remaining: 11.8s
200:	learn: 1.2198330	test: 1.2507097	best: 1.2507097 (200)	total: 1.6s	remaining: 10.3s
400:	learn: 1.1973747	test: 1.2375295	best: 1.2375295 (400)	total: 3.22s	remaining: 8.83s
600:	learn: 1.1845878	test: 1.2354820	best: 1.2354577 (596)	total: 4.78s	remaining: 7.15s
800:	learn: 1.1732674	test: 1.2348970	best: 1.2348969 (799)	total: 6.37s	remaining: 5.55s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.234609564
bestIteration = 873

Shrink model to first 874 iterations.
Seed 3407 - Fold 5 RMSE: 1.2346095641341752
Seed 3407 Fold RMSE: [np.float64(1.2221229032946), np.float64(1.2187225922328135), np.float64(1.2024597255200133), np.float64(1.2096486248398326), np.float64(1.2346095641341752)]
Seed 3407 Mean RMSE: 1.217512682004287
Seed 3407 OOF RMSE: 1.2175622456779804
======================================================================
CatBoost v2 Seed Scores
======================================================================
Seed 42
Mean RMSE: 1.217623747960541
OOF RMSE: 1.2176675357446483

Seed 2024
Mean RMSE: 1.2176111194925985
OOF RMSE: 1.2176565385016278

Seed 3407
Mean RMSE: 1.217512682004287
OOF RMSE: 1.2175622456779804

CatBoost v2 Seed Ensemble OOF RMSE: 1.2168250669540972

# Deney 17B - HGB and LightGBM OOF with Feature Engineering v2

In [ ]:
oof_hgb_v2, test_hgb_v2, scores_hgb_v2 = get_hgb_oof(
    X_fe_v2,
    y,
    X_test_fe_v2,
    cv
)

oof_lgbm_v2, test_lgbm_v2, scores_lgbm_v2 = get_lgbm_oof(
    X_fe_v2,
    y,
    X_test_fe_v2,
    cv
)

HGB Fold 1 RMSE: 1.2310989337647074
HGB Fold 2 RMSE: 1.2326233657114194
HGB Fold 3 RMSE: 1.2169084824803957
HGB Fold 4 RMSE: 1.2250622629721526
HGB Fold 5 RMSE: 1.2443529842307368
HGB Mean RMSE: 1.2300092058318826
HGB OOF RMSE: 1.2300425276119096
LightGBM Fold 1 RMSE: 1.2324687563371692
LightGBM Fold 2 RMSE: 1.2334375406247986
LightGBM Fold 3 RMSE: 1.2173729895644247
LightGBM Fold 4 RMSE: 1.224969754798498
LightGBM Fold 5 RMSE: 1.2474545745352474
LightGBM Mean RMSE: 1.2311407231720275
LightGBM OOF RMSE: 1.2311814012070579

# Deney 17C - OOF Optimized Blend with Feature Engineering v2

In [ ]:
from scipy.optimize import minimize

oof_matrix_v2 = np.column_stack([
    oof_cat_seed_ensemble_v2,
    oof_hgb_v2,
    oof_lgbm_v2
])

test_matrix_v2 = np.column_stack([
    test_cat_seed_ensemble_v2,
    test_hgb_v2,
    test_lgbm_v2
])

model_names_v2 = [
    "CatBoost Seed Ensemble v2",
    "HGB v2",
    "LightGBM v2"
]

def blend_rmse_v2(weights):
    preds = oof_matrix_v2 @ weights
    return rmse(y, preds)

n_models = oof_matrix_v2.shape[1]
initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result_v2 = minimize(
    blend_rmse_v2,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights_v2 = result_v2.x
best_oof_preds_v2 = oof_matrix_v2 @ best_weights_v2
best_test_preds_v2 = test_matrix_v2 @ best_weights_v2

print("Optimization success:", result_v2.success)
print("Best weights:")

for name, weight in zip(model_names_v2, best_weights_v2):
    print(f"{name}: {weight:.6f}")

print("Feature v2 Blend OOF RMSE:", rmse(y, best_oof_preds_v2))

Optimization success: True
Best weights:
CatBoost Seed Ensemble v2: 0.858733
HGB v2: 0.078906
LightGBM v2: 0.062361
Feature v2 Blend OOF RMSE: 1.216549505068112

# Deney 18 - CatBoost v1 Feature Set ile 5 Seed Ensemble

In [ ]:
from catboost import CatBoostRegressor
import numpy as np

def get_catboost_oof_with_seed(X_fe, y, X_test_fe, cv, seed):
    X_cb = X_fe.copy()
    X_test_cb = X_test_fe.copy()

    cat_cols = X_cb.select_dtypes(include="object").columns.tolist()

    for col in cat_cols:
        X_cb[col] = X_cb[col].fillna("Bilinmiyor").astype(str)
        X_test_cb[col] = X_test_cb[col].fillna("Bilinmiyor").astype(str)

    cat_features_idx = [X_cb.columns.get_loc(col) for col in cat_cols]

    oof_preds = np.zeros(len(X_cb))
    test_preds = np.zeros(len(X_test_cb))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_cb), 1):
        X_train_fold = X_cb.iloc[train_idx]
        X_val_fold = X_cb.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        model = CatBoostRegressor(
            loss_function="RMSE",
            eval_metric="RMSE",
            iterations=1500,
            learning_rate=0.035,
            depth=6,
            l2_leaf_reg=5,
            random_seed=seed,
            verbose=200,
            early_stopping_rounds=100
        )

        model.fit(
            X_train_fold,
            y_train_fold,
            cat_features=cat_features_idx,
            eval_set=(X_val_fold, y_val_fold),
            use_best_model=True
        )

        val_pred = model.predict(X_val_fold)
        test_pred = model.predict(X_test_cb)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"Seed {seed} - Fold {fold} RMSE:", fold_rmse)

    print(f"Seed {seed} Mean RMSE:", np.mean(fold_scores))
    print(f"Seed {seed} OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores


# v1 feature set ile 5 seed çalıştırıyoruz
seeds_v1_5 = [42, 2024, 3407, 777, 999]

cat_oof_list_5 = []
cat_test_list_5 = []
cat_seed_scores_5 = {}

for seed in seeds_v1_5:
    print("=" * 70)
    print(f"Running CatBoost v1 seed: {seed}")
    print("=" * 70)

    oof_seed, test_seed, scores_seed = get_catboost_oof_with_seed(
        X_fe,
        y,
        X_test_fe,
        cv,
        seed
    )

    cat_oof_list_5.append(oof_seed)
    cat_test_list_5.append(test_seed)

    cat_seed_scores_5[seed] = {
        "fold_scores": scores_seed,
        "mean_rmse": np.mean(scores_seed),
        "oof_rmse": rmse(y, oof_seed)
    }

oof_cat_seed_ensemble_5 = np.mean(cat_oof_list_5, axis=0)
test_cat_seed_ensemble_5 = np.mean(cat_test_list_5, axis=0)

print("=" * 70)
print("CatBoost 5 Seed Scores")
print("=" * 70)

for seed, result in cat_seed_scores_5.items():
    print(f"Seed {seed}")
    print("Mean RMSE:", result["mean_rmse"])
    print("OOF RMSE:", result["oof_rmse"])
    print()

print("CatBoost 3 Seed Ensemble OOF RMSE eski değer: 1.216103")
print("CatBoost 5 Seed Ensemble OOF RMSE:", rmse(y, oof_cat_seed_ensemble_5))

======================================================================
Running CatBoost v1 seed: 42
======================================================================
0:	learn: 2.1899899	test: 2.2002100	best: 2.2002100 (0)	total: 8.78ms	remaining: 13.2s
200:	learn: 1.2203253	test: 1.2387517	best: 1.2387517 (200)	total: 1.7s	remaining: 11s
400:	learn: 1.1993460	test: 1.2270202	best: 1.2270202 (400)	total: 3.17s	remaining: 8.7s
600:	learn: 1.1871140	test: 1.2239233	best: 1.2238886 (596)	total: 4.69s	remaining: 7.01s
800:	learn: 1.1768064	test: 1.2228847	best: 1.2228847 (800)	total: 6.16s	remaining: 5.38s
1000:	learn: 1.1675482	test: 1.2223728	best: 1.2223562 (997)	total: 7.66s	remaining: 3.82s
1200:	learn: 1.1580040	test: 1.2223533	best: 1.2222052 (1149)	total: 9.13s	remaining: 2.27s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.222205227
bestIteration = 1149

Shrink model to first 1150 iterations.
Seed 42 - Fold 1 RMSE: 1.2222052278876236
0:	learn: 2.1933248	test: 2.1844791	best: 2.1844791 (0)	total: 7.19ms	remaining: 10.8s
200:	learn: 1.2219388	test: 1.2329316	best: 1.2329316 (200)	total: 1.74s	remaining: 11.2s
400:	learn: 1.2002286	test: 1.2200778	best: 1.2200778 (400)	total: 3.19s	remaining: 8.76s
600:	learn: 1.1871296	test: 1.2176941	best: 1.2176941 (600)	total: 4.69s	remaining: 7.02s
800:	learn: 1.1762848	test: 1.2171739	best: 1.2170671 (763)	total: 6.21s	remaining: 5.42s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.217067076
bestIteration = 763

Shrink model to first 764 iterations.
Seed 42 - Fold 2 RMSE: 1.2170670773120693
0:	learn: 2.1918263	test: 2.1904405	best: 2.1904405 (0)	total: 7.75ms	remaining: 11.6s
200:	learn: 1.2250183	test: 1.2180089	best: 1.2180089 (200)	total: 1.52s	remaining: 9.84s
400:	learn: 1.2056242	test: 1.2070444	best: 1.2070406 (398)	total: 2.99s	remaining: 8.2s
600:	learn: 1.1942344	test: 1.2045979	best: 1.2045979 (600)	total: 4.45s	remaining: 6.66s
800:	learn: 1.1837816	test: 1.2039099	best: 1.2037992 (744)	total: 5.93s	remaining: 5.18s
1000:	learn: 1.1738191	test: 1.2032492	best: 1.2032035 (997)	total: 7.44s	remaining: 3.71s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.203203521
bestIteration = 997

Shrink model to first 998 iterations.
Seed 42 - Fold 3 RMSE: 1.203203520627255
0:	learn: 2.1934695	test: 2.1834422	best: 2.1834422 (0)	total: 8.04ms	remaining: 12.1s
200:	learn: 1.2219774	test: 1.2222936	best: 1.2222936 (200)	total: 1.48s	remaining: 9.56s
400:	learn: 1.2004736	test: 1.2116241	best: 1.2116241 (400)	total: 3.02s	remaining: 8.28s
600:	learn: 1.1878463	test: 1.2101770	best: 1.2101636 (588)	total: 4.47s	remaining: 6.68s
800:	learn: 1.1767499	test: 1.2093664	best: 1.2093664 (800)	total: 5.9s	remaining: 5.15s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.209355609
bestIteration = 801

Shrink model to first 802 iterations.
Seed 42 - Fold 4 RMSE: 1.209355609525035
0:	learn: 2.1895988	test: 2.1992243	best: 2.1992243 (0)	total: 7.93ms	remaining: 11.9s
200:	learn: 1.2175895	test: 1.2466416	best: 1.2466416 (200)	total: 1.48s	remaining: 9.56s
400:	learn: 1.1977139	test: 1.2350245	best: 1.2350245 (400)	total: 2.92s	remaining: 8s
600:	learn: 1.1850715	test: 1.2324510	best: 1.2324510 (600)	total: 4.36s	remaining: 6.53s
800:	learn: 1.1742713	test: 1.2321750	best: 1.2320696 (757)	total: 5.85s	remaining: 5.11s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.232069558
bestIteration = 757

Shrink model to first 758 iterations.
Seed 42 - Fold 5 RMSE: 1.2320695587217365
Seed 42 Mean RMSE: 1.216780198814744
Seed 42 OOF RMSE: 1.2168215144071908
======================================================================
Running CatBoost v1 seed: 2024
======================================================================
0:	learn: 2.1897485	test: 2.2009035	best: 2.2009035 (0)	total: 6.6ms	remaining: 9.89s
200:	learn: 1.2196210	test: 1.2388326	best: 1.2388326 (200)	total: 1.7s	remaining: 11s
400:	learn: 1.1978061	test: 1.2263886	best: 1.2263886 (400)	total: 3.16s	remaining: 8.67s
600:	learn: 1.1853583	test: 1.2237320	best: 1.2237320 (600)	total: 4.62s	remaining: 6.92s
800:	learn: 1.1746302	test: 1.2225174	best: 1.2225174 (800)	total: 6.08s	remaining: 5.3s
1000:	learn: 1.1649147	test: 1.2216357	best: 1.2215961 (998)	total: 7.61s	remaining: 3.79s
1200:	learn: 1.1557212	test: 1.2214536	best: 1.2214084 (1183)	total: 9.1s	remaining: 2.27s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.221286297
bestIteration = 1299

Shrink model to first 1300 iterations.
Seed 2024 - Fold 1 RMSE: 1.221286297960883
0:	learn: 2.1937682	test: 2.1848561	best: 2.1848561 (0)	total: 7.24ms	remaining: 10.9s
200:	learn: 1.2214029	test: 1.2323032	best: 1.2323032 (200)	total: 1.68s	remaining: 10.8s
400:	learn: 1.1993893	test: 1.2200355	best: 1.2200355 (400)	total: 3.21s	remaining: 8.79s
600:	learn: 1.1860385	test: 1.2171426	best: 1.2171426 (596)	total: 4.66s	remaining: 6.98s
800:	learn: 1.1748271	test: 1.2164943	best: 1.2164829 (796)	total: 6.13s	remaining: 5.34s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.216362417
bestIteration = 850

Shrink model to first 851 iterations.
Seed 2024 - Fold 2 RMSE: 1.2163624180901644
0:	learn: 2.1923618	test: 2.1908398	best: 2.1908398 (0)	total: 8.2ms	remaining: 12.3s
200:	learn: 1.2249340	test: 1.2176364	best: 1.2176364 (200)	total: 1.55s	remaining: 10s
400:	learn: 1.2042437	test: 1.2054520	best: 1.2054520 (400)	total: 3.05s	remaining: 8.36s
600:	learn: 1.1910171	test: 1.2029645	best: 1.2029645 (600)	total: 4.55s	remaining: 6.8s
800:	learn: 1.1791850	test: 1.2023734	best: 1.2023734 (800)	total: 6.05s	remaining: 5.28s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.202299653
bestIteration = 812

Shrink model to first 813 iterations.
Seed 2024 - Fold 3 RMSE: 1.2022996520908928
0:	learn: 2.1940378	test: 2.1839759	best: 2.1839759 (0)	total: 8.2ms	remaining: 12.3s
200:	learn: 1.2233941	test: 1.2234447	best: 1.2234447 (200)	total: 1.55s	remaining: 10.1s
400:	learn: 1.2016172	test: 1.2125301	best: 1.2125301 (400)	total: 3.07s	remaining: 8.41s
600:	learn: 1.1876709	test: 1.2106173	best: 1.2106173 (600)	total: 4.58s	remaining: 6.85s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.210546253
bestIteration = 615

Shrink model to first 616 iterations.
Seed 2024 - Fold 4 RMSE: 1.210546253275008
0:	learn: 2.1897693	test: 2.1993677	best: 2.1993677 (0)	total: 7.57ms	remaining: 11.4s
200:	learn: 1.2173234	test: 1.2465478	best: 1.2465478 (200)	total: 1.53s	remaining: 9.92s
400:	learn: 1.1968780	test: 1.2348303	best: 1.2348303 (400)	total: 3.02s	remaining: 8.28s
600:	learn: 1.1828711	test: 1.2328465	best: 1.2328045 (598)	total: 4.48s	remaining: 6.7s
800:	learn: 1.1714131	test: 1.2323883	best: 1.2322991 (778)	total: 5.99s	remaining: 5.22s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.232150566
bestIteration = 868

Shrink model to first 869 iterations.
Seed 2024 - Fold 5 RMSE: 1.2321505662418946
Seed 2024 Mean RMSE: 1.2165290375317686
Seed 2024 OOF RMSE: 1.2165705451271958
======================================================================
Running CatBoost v1 seed: 3407
======================================================================
0:	learn: 2.1904351	test: 2.2016217	best: 2.2016217 (0)	total: 8.32ms	remaining: 12.5s
200:	learn: 1.2206104	test: 1.2389390	best: 1.2389390 (200)	total: 1.54s	remaining: 9.93s
400:	learn: 1.1992415	test: 1.2266255	best: 1.2266255 (400)	total: 3.04s	remaining: 8.33s
600:	learn: 1.1867273	test: 1.2241364	best: 1.2241321 (598)	total: 4.51s	remaining: 6.74s
800:	learn: 1.1764877	test: 1.2227724	best: 1.2227693 (794)	total: 5.96s	remaining: 5.2s
1000:	learn: 1.1664773	test: 1.2226129	best: 1.2225458 (974)	total: 7.44s	remaining: 3.71s
1200:	learn: 1.1570132	test: 1.2224956	best: 1.2223651 (1137)	total: 8.93s	remaining: 2.22s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.222365094
bestIteration = 1137

Shrink model to first 1138 iterations.
Seed 3407 - Fold 1 RMSE: 1.2223650947220508
0:	learn: 2.1944713	test: 2.1858309	best: 2.1858309 (0)	total: 8.07ms	remaining: 12.1s
200:	learn: 1.2229435	test: 1.2329796	best: 1.2329796 (200)	total: 1.56s	remaining: 10.1s
400:	learn: 1.1997539	test: 1.2200301	best: 1.2200301 (400)	total: 3.03s	remaining: 8.31s
600:	learn: 1.1865721	test: 1.2179401	best: 1.2179401 (600)	total: 4.51s	remaining: 6.75s
800:	learn: 1.1763484	test: 1.2175005	best: 1.2174894 (799)	total: 5.97s	remaining: 5.21s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.217489397
bestIteration = 799

Shrink model to first 800 iterations.
Seed 3407 - Fold 2 RMSE: 1.217489397429045
0:	learn: 2.1931479	test: 2.1913556	best: 2.1913556 (0)	total: 7.16ms	remaining: 10.7s
200:	learn: 1.2251465	test: 1.2176941	best: 1.2176941 (200)	total: 1.58s	remaining: 10.2s
400:	learn: 1.2031549	test: 1.2049351	best: 1.2049292 (396)	total: 3.05s	remaining: 8.37s
600:	learn: 1.1910034	test: 1.2031650	best: 1.2030844 (588)	total: 4.53s	remaining: 6.78s
800:	learn: 1.1799594	test: 1.2025012	best: 1.2024581 (783)	total: 6.02s	remaining: 5.25s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.202439926
bestIteration = 823

Shrink model to first 824 iterations.
Seed 3407 - Fold 3 RMSE: 1.2024399258798242
0:	learn: 2.1947037	test: 2.1846926	best: 2.1846926 (0)	total: 7.54ms	remaining: 11.3s
200:	learn: 1.2234451	test: 1.2229714	best: 1.2229714 (200)	total: 1.75s	remaining: 11.3s
400:	learn: 1.2020058	test: 1.2124814	best: 1.2124814 (400)	total: 3.39s	remaining: 9.3s
600:	learn: 1.1897301	test: 1.2113094	best: 1.2112194 (587)	total: 4.84s	remaining: 7.24s
800:	learn: 1.1785506	test: 1.2109843	best: 1.2109214 (787)	total: 6.32s	remaining: 5.51s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.210921392
bestIteration = 787

Shrink model to first 788 iterations.
Seed 3407 - Fold 4 RMSE: 1.2109213922755
0:	learn: 2.1908891	test: 2.2003505	best: 2.2003505 (0)	total: 7.69ms	remaining: 11.5s
200:	learn: 1.2179541	test: 1.2467742	best: 1.2467742 (200)	total: 1.51s	remaining: 9.76s
400:	learn: 1.1969894	test: 1.2353386	best: 1.2353372 (399)	total: 3s	remaining: 8.22s
600:	learn: 1.1853127	test: 1.2332465	best: 1.2332465 (600)	total: 4.45s	remaining: 6.65s
800:	learn: 1.1746064	test: 1.2326134	best: 1.2325406 (750)	total: 5.93s	remaining: 5.17s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.232346031
bestIteration = 849

Shrink model to first 850 iterations.
Seed 3407 - Fold 5 RMSE: 1.2323460316475794
Seed 3407 Mean RMSE: 1.2171123683907998
Seed 3407 OOF RMSE: 1.2171545500046277
======================================================================
Running CatBoost v1 seed: 777
======================================================================
0:	learn: 2.1887244	test: 2.1999243	best: 2.1999243 (0)	total: 8.48ms	remaining: 12.7s
200:	learn: 1.2199824	test: 1.2390334	best: 1.2390334 (200)	total: 1.54s	remaining: 9.98s
400:	learn: 1.1986023	test: 1.2265361	best: 1.2265361 (400)	total: 3.03s	remaining: 8.3s
600:	learn: 1.1864182	test: 1.2240029	best: 1.2240029 (600)	total: 4.46s	remaining: 6.67s
800:	learn: 1.1759933	test: 1.2229406	best: 1.2229239 (799)	total: 5.93s	remaining: 5.17s
1000:	learn: 1.1659755	test: 1.2221408	best: 1.2221065 (998)	total: 7.4s	remaining: 3.69s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.222106483
bestIteration = 998

Shrink model to first 999 iterations.
Seed 777 - Fold 1 RMSE: 1.222106483593927
0:	learn: 2.1928738	test: 2.1842232	best: 2.1842232 (0)	total: 7.11ms	remaining: 10.7s
200:	learn: 1.2210962	test: 1.2321478	best: 1.2321478 (200)	total: 1.66s	remaining: 10.7s
400:	learn: 1.1985621	test: 1.2201470	best: 1.2201470 (400)	total: 3.13s	remaining: 8.57s
600:	learn: 1.1846907	test: 1.2171482	best: 1.2171482 (600)	total: 4.59s	remaining: 6.87s
800:	learn: 1.1748380	test: 1.2167528	best: 1.2167420 (746)	total: 6.08s	remaining: 5.31s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.216742002
bestIteration = 746

Shrink model to first 747 iterations.
Seed 777 - Fold 2 RMSE: 1.216742002546174
0:	learn: 2.1912285	test: 2.1895986	best: 2.1895986 (0)	total: 7.24ms	remaining: 10.9s
200:	learn: 1.2257170	test: 1.2179015	best: 1.2179015 (200)	total: 1.55s	remaining: 10s
400:	learn: 1.2034332	test: 1.2055647	best: 1.2055647 (400)	total: 3.02s	remaining: 8.27s
600:	learn: 1.1901202	test: 1.2031263	best: 1.2031263 (600)	total: 4.51s	remaining: 6.75s
800:	learn: 1.1789256	test: 1.2019506	best: 1.2019109 (795)	total: 6.01s	remaining: 5.25s
1000:	learn: 1.1685161	test: 1.2019685	best: 1.2018392 (910)	total: 7.55s	remaining: 3.76s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.201839242
bestIteration = 910

Shrink model to first 911 iterations.
Seed 777 - Fold 3 RMSE: 1.2018392411539955
0:	learn: 2.1959485	test: 2.1849925	best: 2.1849925 (0)	total: 7.09ms	remaining: 10.6s
200:	learn: 1.2236073	test: 1.2227437	best: 1.2227437 (200)	total: 1.53s	remaining: 9.91s
400:	learn: 1.2014893	test: 1.2117744	best: 1.2117744 (400)	total: 3.04s	remaining: 8.34s
600:	learn: 1.1878049	test: 1.2100594	best: 1.2100516 (598)	total: 4.49s	remaining: 6.72s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.209955043
bestIteration = 621

Shrink model to first 622 iterations.
Seed 777 - Fold 4 RMSE: 1.2099550427830514
0:	learn: 2.1891773	test: 2.1987501	best: 2.1987501 (0)	total: 7.78ms	remaining: 11.7s
200:	learn: 1.2169149	test: 1.2468716	best: 1.2468716 (200)	total: 1.59s	remaining: 10.3s
400:	learn: 1.1954289	test: 1.2345758	best: 1.2345758 (400)	total: 3.16s	remaining: 8.65s
600:	learn: 1.1815442	test: 1.2325663	best: 1.2325508 (598)	total: 4.73s	remaining: 7.08s
800:	learn: 1.1706425	test: 1.2322302	best: 1.2321275 (736)	total: 6.25s	remaining: 5.46s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.232127504
bestIteration = 736

Shrink model to first 737 iterations.
Seed 777 - Fold 5 RMSE: 1.2321275046156661
Seed 777 Mean RMSE: 1.2165540549385627
Seed 777 OOF RMSE: 1.2165979050423
======================================================================
Running CatBoost v1 seed: 999
======================================================================
0:	learn: 2.1883948	test: 2.1996217	best: 2.1996217 (0)	total: 7.27ms	remaining: 10.9s
200:	learn: 1.2200418	test: 1.2394023	best: 1.2394023 (200)	total: 1.74s	remaining: 11.2s
400:	learn: 1.1986984	test: 1.2270605	best: 1.2270605 (400)	total: 3.4s	remaining: 9.31s
600:	learn: 1.1870825	test: 1.2246654	best: 1.2246654 (600)	total: 4.92s	remaining: 7.36s
800:	learn: 1.1768647	test: 1.2238070	best: 1.2236954 (714)	total: 6.45s	remaining: 5.63s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.22369543
bestIteration = 714

Shrink model to first 715 iterations.
Seed 999 - Fold 1 RMSE: 1.2236954305579204
0:	learn: 2.1945026	test: 2.1839415	best: 2.1839415 (0)	total: 7.5ms	remaining: 11.2s
200:	learn: 1.2221396	test: 1.2334365	best: 1.2334365 (200)	total: 1.74s	remaining: 11.2s
400:	learn: 1.1994565	test: 1.2211021	best: 1.2211021 (400)	total: 3.35s	remaining: 9.18s
600:	learn: 1.1871686	test: 1.2187533	best: 1.2187511 (599)	total: 4.78s	remaining: 7.15s
800:	learn: 1.1759743	test: 1.2183243	best: 1.2182528 (716)	total: 6.36s	remaining: 5.54s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.218252831
bestIteration = 716

Shrink model to first 717 iterations.
Seed 999 - Fold 2 RMSE: 1.218252831871912
0:	learn: 2.1922367	test: 2.1903351	best: 2.1903351 (0)	total: 7.46ms	remaining: 11.2s
200:	learn: 1.2232102	test: 1.2189157	best: 1.2189157 (200)	total: 1.62s	remaining: 10.5s
400:	learn: 1.2031007	test: 1.2068254	best: 1.2068254 (400)	total: 3.12s	remaining: 8.54s
600:	learn: 1.1926073	test: 1.2052558	best: 1.2052558 (600)	total: 4.48s	remaining: 6.71s
800:	learn: 1.1830494	test: 1.2042570	best: 1.2042083 (779)	total: 5.87s	remaining: 5.13s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.204208331
bestIteration = 779

Shrink model to first 780 iterations.
Seed 999 - Fold 3 RMSE: 1.204208330454984
0:	learn: 2.1940634	test: 2.1831473	best: 2.1831473 (0)	total: 7.56ms	remaining: 11.3s
200:	learn: 1.2234680	test: 1.2222931	best: 1.2222931 (200)	total: 1.52s	remaining: 9.8s
400:	learn: 1.2019215	test: 1.2115109	best: 1.2115109 (400)	total: 3.04s	remaining: 8.34s
600:	learn: 1.1890921	test: 1.2095240	best: 1.2095235 (599)	total: 4.53s	remaining: 6.77s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.209276489
bestIteration = 676

Shrink model to first 677 iterations.
Seed 999 - Fold 4 RMSE: 1.2092764891097654
0:	learn: 2.1896915	test: 2.1992058	best: 2.1992058 (0)	total: 8.85ms	remaining: 13.3s
200:	learn: 1.2186287	test: 1.2477166	best: 1.2477166 (200)	total: 1.55s	remaining: 10s
400:	learn: 1.1971849	test: 1.2349786	best: 1.2349786 (400)	total: 3.05s	remaining: 8.36s
600:	learn: 1.1843548	test: 1.2327802	best: 1.2327697 (599)	total: 4.53s	remaining: 6.78s
800:	learn: 1.1736432	test: 1.2322725	best: 1.2322160 (714)	total: 5.97s	remaining: 5.21s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.231845838
bestIteration = 866

Shrink model to first 867 iterations.
Seed 999 - Fold 5 RMSE: 1.2318458379608423
Seed 999 Mean RMSE: 1.2174557839910847
Seed 999 OOF RMSE: 1.2174959521809128
======================================================================
CatBoost 5 Seed Scores
======================================================================
Seed 42
Mean RMSE: 1.216780198814744
OOF RMSE: 1.2168215144071908

Seed 2024
Mean RMSE: 1.2165290375317686
OOF RMSE: 1.2165705451271958

Seed 3407
Mean RMSE: 1.2171123683907998
OOF RMSE: 1.2171545500046277

Seed 777
Mean RMSE: 1.2165540549385627
OOF RMSE: 1.2165979050423

Seed 999
Mean RMSE: 1.2174557839910847
OOF RMSE: 1.2174959521809128

CatBoost 3 Seed Ensemble OOF RMSE eski değer: 1.216103
CatBoost 5 Seed Ensemble OOF RMSE: 1.2160032376608407

# Deney 19 - 5 Seed CatBoost + HGB + LightGBM OOF Blend

In [ ]:
from scipy.optimize import minimize
import numpy as np

oof_matrix_5seed_blend = np.column_stack([
    oof_cat_seed_ensemble_5,
    oof_hgb,
    oof_lgbm
])

test_matrix_5seed_blend = np.column_stack([
    test_cat_seed_ensemble_5,
    test_hgb,
    test_lgbm
])

model_names_5seed_blend = [
    "CatBoost 5 Seed Ensemble",
    "HGB",
    "LightGBM"
]

def blend_rmse_5seed(weights):
    preds = oof_matrix_5seed_blend @ weights
    return rmse(y, preds)

n_models = oof_matrix_5seed_blend.shape[1]
initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result_5seed_blend = minimize(
    blend_rmse_5seed,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights_5seed_blend = result_5seed_blend.x
best_oof_preds_5seed_blend = oof_matrix_5seed_blend @ best_weights_5seed_blend
best_test_preds_5seed_blend = test_matrix_5seed_blend @ best_weights_5seed_blend

print("Optimization success:", result_5seed_blend.success)
print("Best weights:")

for name, weight in zip(model_names_5seed_blend, best_weights_5seed_blend):
    print(f"{name}: {weight:.6f}")

print("Deney 16 OOF RMSE eski en iyi: 1.215848")
print("5 Seed Blend OOF RMSE:", rmse(y, best_oof_preds_5seed_blend))

Optimization success: True
Best weights:
CatBoost 5 Seed Ensemble: 0.862233
HGB: 0.113767
LightGBM: 0.024001
Deney 16 OOF RMSE eski en iyi: 1.215848
5 Seed Blend OOF RMSE: 1.2157831137897666

In [ ]:
submission_exp19 = pd.DataFrame({
    "id": test_ids,
    TARGET: best_test_preds_5seed_blend
})

submission_exp19[TARGET] = submission_exp19[TARGET].clip(0, 10)

print(submission_exp19.shape)
print(submission_exp19.head())
print(submission_exp19[TARGET].describe())

submission_exp19.to_csv("submission_exp19_5seed_blend.csv", index=False)

(24000, 2)
   id  bilissel_performans_skoru
0   1                   6.004932
1   2                   6.703876
2   3                   3.025952
3   4                   7.165925
4   5                   3.647632
count    24000.000000
mean         5.934777
std          1.859313
min          0.000000
25%          4.650256
50%          6.042210
75%          7.316993
max         10.000000
Name: bilissel_performans_skoru, dtype: float64

# Deney 20 - Missing Indicators + Categorical Interactions

In [14]:
def prepare_features_v3(X, X_test):
    X_fe = X.copy()
    X_test_fe = X_test.copy()

    # --------------------------------------------------------
    # 1. Missing indicator'ları ekle
    # Train ve test için aynı kolonlarda indicator üretelim
    # --------------------------------------------------------
    all_cols = X_fe.columns.tolist()

    for col in all_cols:
        if X_fe[col].isnull().any() or X_test_fe[col].isnull().any():
            X_fe[f"{col}_missing"] = X_fe[col].isnull().astype(int)
            X_test_fe[f"{col}_missing"] = X_test_fe[col].isnull().astype(int)

    # --------------------------------------------------------
    # 2. Log transform - v1'de işe yarayan dönüşüm
    # --------------------------------------------------------
    log_cols = [
        "uyku_oncesi_kafein_mg",
        "uyku_oncesi_ekran_suresi_dk"
    ]

    for col in log_cols:
        if col in X_fe.columns:
            X_fe[col] = np.log1p(X_fe[col])
            X_test_fe[col] = np.log1p(X_test_fe[col])

    def add_features(df):
        df = df.copy()

        # ----------------------------------------------------
        # v1'de işe yarayan feature'lar
        # ----------------------------------------------------
        if "stres_skoru" in df.columns and "gunluk_calisma_saati" in df.columns:
            df["stres_calisma_yuku"] = df["stres_skoru"] * df["gunluk_calisma_saati"]

        if "rem_yuzdesi" in df.columns and "derin_uyku_yuzdesi" in df.columns:
            df["uyku_kalitesi_orani"] = df["rem_yuzdesi"] + df["derin_uyku_yuzdesi"]

        if "gecelik_uyanma_sayisi" in df.columns and "uykuya_dalma_suresi_dk" in df.columns:
            df["uyku_bozulma_skoru"] = df["gecelik_uyanma_sayisi"] + df["uykuya_dalma_suresi_dk"]

        if "uyku_oncesi_ekran_suresi_dk" in df.columns and "uyku_oncesi_kafein_mg" in df.columns:
            df["dijital_kafein_yuku"] = (
                df["uyku_oncesi_ekran_suresi_dk"] * df["uyku_oncesi_kafein_mg"]
            )

        if "gunluk_adim_sayisi" in df.columns and "stres_skoru" in df.columns:
            df["aktivite_stres_orani"] = df["gunluk_adim_sayisi"] / (df["stres_skoru"] + 1)

        # ----------------------------------------------------
        # Yeni: kategorik interaction feature'lar
        # CatBoost bunları native categorical olarak iyi kullanabilir
        # ----------------------------------------------------
        def safe_str_col(c):
            return df[c].fillna("Bilinmiyor").astype(str)

        if "meslek" in df.columns and "kronotip" in df.columns:
            df["meslek_kronotip"] = safe_str_col("meslek") + "_" + safe_str_col("kronotip")

        if "gun_tipi" in df.columns and "kronotip" in df.columns:
            df["gun_tipi_kronotip"] = safe_str_col("gun_tipi") + "_" + safe_str_col("kronotip")

        if "ruh_sagligi_durumu" in df.columns and "meslek" in df.columns:
            df["ruh_sagligi_meslek"] = safe_str_col("ruh_sagligi_durumu") + "_" + safe_str_col("meslek")

        if "cinsiyet" in df.columns and "kronotip" in df.columns:
            df["cinsiyet_kronotip"] = safe_str_col("cinsiyet") + "_" + safe_str_col("kronotip")

        return df

    X_fe = add_features(X_fe)
    X_test_fe = add_features(X_test_fe)

    return X_fe, X_test_fe


X_fe_v3, X_test_fe_v3 = prepare_features_v3(X, X_test)

print("X_fe_v3:", X_fe_v3.shape)
print("X_test_fe_v3:", X_test_fe_v3.shape)
print("New columns added:", X_fe_v3.shape[1] - X.shape[1])

X_fe_v3: (56000, 35)
X_test_fe_v3: (24000, 35)
New columns added: 12

In [15]:
import numpy as np

from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

def get_hgb_oof_dense(X_fe, y, X_test_fe, cv):
    num_cols = X_fe.select_dtypes(include=np.number).columns.tolist()
    cat_cols = X_fe.select_dtypes(include="object").columns.tolist()

    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median", add_indicator=True))
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="constant", fill_value="Bilinmiyor")),
        ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, num_cols),
            ("cat", categorical_transformer, cat_cols)
        ],
        sparse_threshold=0
    )

    oof_preds = np.zeros(len(X_fe))
    test_preds = np.zeros(len(X_test_fe))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_fe), 1):
        X_train_fold = X_fe.iloc[train_idx]
        X_val_fold = X_fe.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        model = HistGradientBoostingRegressor(
            max_iter=700,
            learning_rate=0.04,
            max_leaf_nodes=31,
            min_samples_leaf=20,
            l2_regularization=0.1,
            random_state=42
        )

        pipeline = Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("model", model)
        ])

        pipeline.fit(X_train_fold, y_train_fold)

        val_pred = pipeline.predict(X_val_fold)
        test_pred = pipeline.predict(X_test_fe)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"HGB Fold {fold} RMSE:", fold_rmse)

    print("HGB Mean RMSE:", np.mean(fold_scores))
    print("HGB OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores

# Deney 20A - CatBoost 3 Seed Ensemble with Feature v3

In [16]:
# CatBoost v3 kısmı aynı kalacak
seeds_v3 = [42, 2024, 3407]

cat_oof_list_v3 = []
cat_test_list_v3 = []
cat_seed_scores_v3 = {}

for seed in seeds_v3:
    print("=" * 70)
    print(f"Running CatBoost v3 seed: {seed}")
    print("=" * 70)

    oof_seed, test_seed, scores_seed = get_catboost_oof_with_seed(
        X_fe_v3,
        y,
        X_test_fe_v3,
        cv,
        seed
    )

    cat_oof_list_v3.append(oof_seed)
    cat_test_list_v3.append(test_seed)

    cat_seed_scores_v3[seed] = {
        "fold_scores": scores_seed,
        "mean_rmse": np.mean(scores_seed),
        "oof_rmse": rmse(y, oof_seed)
    }

oof_cat_seed_ensemble_v3 = np.mean(cat_oof_list_v3, axis=0)
test_cat_seed_ensemble_v3 = np.mean(cat_test_list_v3, axis=0)

print("=" * 70)
print("CatBoost v3 Seed Scores")
print("=" * 70)

for seed, result in cat_seed_scores_v3.items():
    print(f"Seed {seed}")
    print("Mean RMSE:", result["mean_rmse"])
    print("OOF RMSE:", result["oof_rmse"])
    print()

print("Old v1 3-seed CatBoost OOF: 1.216103")
print("CatBoost v3 3-Seed Ensemble OOF RMSE:", rmse(y, oof_cat_seed_ensemble_v3))


# BURASI DEĞİŞTİ: get_hgb_oof yerine get_hgb_oof_dense
oof_hgb_v3, test_hgb_v3, scores_hgb_v3 = get_hgb_oof_dense(
    X_fe_v3,
    y,
    X_test_fe_v3,
    cv
)

# LightGBM aynı kalabilir
oof_lgbm_v3, test_lgbm_v3, scores_lgbm_v3 = get_lgbm_oof(
    X_fe_v3,
    y,
    X_test_fe_v3,
    cv
)

======================================================================
Running CatBoost v3 seed: 42
======================================================================

NameError: name 'get_catboost_oof_with_seed' is not defined

# Deney 20B - HGB and LightGBM with Feature v3

In [17]:
oof_hgb_v3, test_hgb_v3, scores_hgb_v3 = get_hgb_oof_dense(
    X_fe_v3,
    y,
    X_test_fe_v3,
    cv
)

oof_lgbm_v3, test_lgbm_v3, scores_lgbm_v3 = get_lgbm_oof(
    X_fe_v3,
    y,
    X_test_fe_v3,
    cv
)

HGB Fold 1 RMSE: 1.2307257608746391
HGB Fold 2 RMSE: 1.2279666280094808
HGB Fold 3 RMSE: 1.2180883161193514
HGB Fold 4 RMSE: 1.2249099451212055
HGB Fold 5 RMSE: 1.2450940604787741
HGB Mean RMSE: 1.22935694212069
HGB OOF RMSE: 1.2293893343402866

NameError: name 'get_lgbm_oof' is not defined

# Deney 20C - OOF Optimized Blend with Feature v3

In [ ]:
from scipy.optimize import minimize

oof_matrix_v3 = np.column_stack([
    oof_cat_seed_ensemble_v3,
    oof_hgb_v3,
    oof_lgbm_v3
])

test_matrix_v3 = np.column_stack([
    test_cat_seed_ensemble_v3,
    test_hgb_v3,
    test_lgbm_v3
])

model_names_v3 = [
    "CatBoost 3 Seed Ensemble v3",
    "HGB v3",
    "LightGBM v3"
]

def blend_rmse_v3(weights):
    preds = oof_matrix_v3 @ weights
    return rmse(y, preds)

n_models = oof_matrix_v3.shape[1]
initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result_v3 = minimize(
    blend_rmse_v3,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights_v3 = result_v3.x
best_oof_preds_v3 = oof_matrix_v3 @ best_weights_v3
best_test_preds_v3 = test_matrix_v3 @ best_weights_v3

print("Optimization success:", result_v3.success)
print("Best weights:")

for name, weight in zip(model_names_v3, best_weights_v3):
    print(f"{name}: {weight:.6f}")

print("Feature v3 Blend OOF RMSE:", rmse(y, best_oof_preds_v3))

Optimization success: True
Best weights:
CatBoost 3 Seed Ensemble v3: 0.871066
HGB v3: 0.089645
LightGBM v3: 0.039289
Feature v3 Blend OOF RMSE: 1.215493973927574

# Deney 20D - CatBoost v3 5 Seed Ensemble

In [18]:
seeds_v3_5 = [42, 2024, 3407, 777, 999]

cat_oof_list_v3_5 = []
cat_test_list_v3_5 = []
cat_seed_scores_v3_5 = {}

for seed in seeds_v3_5:
    print("=" * 70)
    print(f"Running CatBoost v3 seed: {seed}")
    print("=" * 70)

    oof_seed, test_seed, scores_seed = get_catboost_oof_with_seed(
        X_fe_v3,
        y,
        X_test_fe_v3,
        cv,
        seed
    )

    cat_oof_list_v3_5.append(oof_seed)
    cat_test_list_v3_5.append(test_seed)

    cat_seed_scores_v3_5[seed] = {
        "fold_scores": scores_seed,
        "mean_rmse": np.mean(scores_seed),
        "oof_rmse": rmse(y, oof_seed)
    }

oof_cat_seed_ensemble_v3_5 = np.mean(cat_oof_list_v3_5, axis=0)
test_cat_seed_ensemble_v3_5 = np.mean(cat_test_list_v3_5, axis=0)

print("=" * 70)
print("CatBoost v3 5 Seed Scores")
print("=" * 70)

for seed, result in cat_seed_scores_v3_5.items():
    print(f"Seed {seed}")
    print("Mean RMSE:", result["mean_rmse"])
    print("OOF RMSE:", result["oof_rmse"])
    print()

print("CatBoost v3 3-Seed Ensemble OOF eski:", rmse(y, oof_cat_seed_ensemble_v3))
print("CatBoost v3 5-Seed Ensemble OOF RMSE:", rmse(y, oof_cat_seed_ensemble_v3_5))

======================================================================
Running CatBoost v3 seed: 42
======================================================================

NameError: name 'get_catboost_oof_with_seed' is not defined

# Deney 20E - v3 5 Seed CatBoost + HGB v3 + LightGBM v3 Blend

In [19]:
from scipy.optimize import minimize

oof_matrix_v3_5 = np.column_stack([
    oof_cat_seed_ensemble_v3_5,
    oof_hgb_v3,
    oof_lgbm_v3
])

test_matrix_v3_5 = np.column_stack([
    test_cat_seed_ensemble_v3_5,
    test_hgb_v3,
    test_lgbm_v3
])

model_names_v3_5 = [
    "CatBoost v3 5 Seed Ensemble",
    "HGB v3",
    "LightGBM v3"
]

def blend_rmse_v3_5(weights):
    preds = oof_matrix_v3_5 @ weights
    return rmse(y, preds)

n_models = oof_matrix_v3_5.shape[1]
initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result_v3_5 = minimize(
    blend_rmse_v3_5,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights_v3_5 = result_v3_5.x
best_oof_preds_v3_5 = oof_matrix_v3_5 @ best_weights_v3_5
best_test_preds_v3_5 = test_matrix_v3_5 @ best_weights_v3_5

print("Optimization success:", result_v3_5.success)
print("Best weights:")

for name, weight in zip(model_names_v3_5, best_weights_v3_5):
    print(f"{name}: {weight:.6f}")

print("Deney 20C v3 3-seed blend OOF:", rmse(y, best_oof_preds_v3))
print("Deney 20E v3 5-seed blend OOF:", rmse(y, best_oof_preds_v3_5))

NameError: name 'oof_cat_seed_ensemble_v3_5' is not defined

In [ ]:
submission_exp20e = pd.DataFrame({
    "id": test_ids,
    TARGET: best_test_preds_v3_5
})

submission_exp20e[TARGET] = submission_exp20e[TARGET].clip(0, 10)

print(submission_exp20e.shape)
print(submission_exp20e.head())
print(submission_exp20e[TARGET].describe())

submission_exp20e.to_csv("submission_exp20e_v3_5seed_blend.csv", index=False)

(24000, 2)
   id  bilissel_performans_skoru
0   1                   5.995484
1   2                   6.766010
2   3                   3.037712
3   4                   7.159019
4   5                   3.628314
count    24000.000000
mean         5.936977
std          1.862729
min          0.000000
25%          4.641429
50%          6.044348
75%          7.327849
max         10.000000
Name: bilissel_performans_skoru, dtype: float64

# Deney 21 - CatBoost v3 + Numeric Median Imputation

In [ ]:
from catboost import CatBoostRegressor
import numpy as np

def get_catboost_oof_with_seed_median(X_fe, y, X_test_fe, cv, seed):
    X_cb = X_fe.copy()
    X_test_cb = X_test_fe.copy()

    cat_cols = X_cb.select_dtypes(include="object").columns.tolist()
    num_cols = X_cb.select_dtypes(include=np.number).columns.tolist()

    # Categorical NaN -> Bilinmiyor
    for col in cat_cols:
        X_cb[col] = X_cb[col].fillna("Bilinmiyor").astype(str)
        X_test_cb[col] = X_test_cb[col].fillna("Bilinmiyor").astype(str)

    cat_features_idx = [X_cb.columns.get_loc(col) for col in cat_cols]

    oof_preds = np.zeros(len(X_cb))
    test_preds = np.zeros(len(X_test_cb))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_cb), 1):
        X_train_fold = X_cb.iloc[train_idx].copy()
        X_val_fold = X_cb.iloc[val_idx].copy()

        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        X_test_fold = X_test_cb.copy()

        # Numeric median sadece train fold üzerinden öğreniliyor
        medians = X_train_fold[num_cols].median()

        X_train_fold[num_cols] = X_train_fold[num_cols].fillna(medians)
        X_val_fold[num_cols] = X_val_fold[num_cols].fillna(medians)
        X_test_fold[num_cols] = X_test_fold[num_cols].fillna(medians)

        model = CatBoostRegressor(
            loss_function="RMSE",
            eval_metric="RMSE",
            iterations=1500,
            learning_rate=0.035,
            depth=6,
            l2_leaf_reg=5,
            random_seed=seed,
            verbose=200,
            early_stopping_rounds=100
        )

        model.fit(
            X_train_fold,
            y_train_fold,
            cat_features=cat_features_idx,
            eval_set=(X_val_fold, y_val_fold),
            use_best_model=True
        )

        val_pred = model.predict(X_val_fold)
        test_pred = model.predict(X_test_fold)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"Seed {seed} - Fold {fold} RMSE:", fold_rmse)

    print(f"Seed {seed} Mean RMSE:", np.mean(fold_scores))
    print(f"Seed {seed} OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores

# Deney 21A - CatBoost v3 + Median Imputation - 3 Seed

In [ ]:
seeds_median_3 = [42, 2024, 3407]

cat_oof_list_median_3 = []
cat_test_list_median_3 = []
cat_seed_scores_median_3 = {}

for seed in seeds_median_3:
    print("=" * 70)
    print(f"Running CatBoost v3 median seed: {seed}")
    print("=" * 70)

    oof_seed, test_seed, scores_seed = get_catboost_oof_with_seed_median(
        X_fe_v3,
        y,
        X_test_fe_v3,
        cv,
        seed
    )

    cat_oof_list_median_3.append(oof_seed)
    cat_test_list_median_3.append(test_seed)

    cat_seed_scores_median_3[seed] = {
        "fold_scores": scores_seed,
        "mean_rmse": np.mean(scores_seed),
        "oof_rmse": rmse(y, oof_seed)
    }

oof_cat_median_3 = np.mean(cat_oof_list_median_3, axis=0)
test_cat_median_3 = np.mean(cat_test_list_median_3, axis=0)

print("=" * 70)
print("CatBoost v3 Median 3 Seed Scores")
print("=" * 70)

for seed, result in cat_seed_scores_median_3.items():
    print(f"Seed {seed}")
    print("Mean RMSE:", result["mean_rmse"])
    print("OOF RMSE:", result["oof_rmse"])
    print()

print("Eski v3 3-seed CatBoost OOF:", rmse(y, oof_cat_seed_ensemble_v3))
print("Median v3 3-seed CatBoost OOF:", rmse(y, oof_cat_median_3))

======================================================================
Running CatBoost v3 median seed: 42
======================================================================
0:	learn: 2.1884436	test: 2.1992729	best: 2.1992729 (0)	total: 9.24ms	remaining: 13.9s
200:	learn: 1.2209683	test: 1.2374999	best: 1.2374999 (200)	total: 2.63s	remaining: 17s
400:	learn: 1.2004931	test: 1.2257634	best: 1.2257634 (400)	total: 4.77s	remaining: 13.1s
600:	learn: 1.1892405	test: 1.2228999	best: 1.2228999 (600)	total: 6.92s	remaining: 10.4s
800:	learn: 1.1801532	test: 1.2219336	best: 1.2218889 (775)	total: 9.1s	remaining: 7.94s
1000:	learn: 1.1723566	test: 1.2214341	best: 1.2214273 (997)	total: 11.5s	remaining: 5.72s
1200:	learn: 1.1635280	test: 1.2211876	best: 1.2211876 (1199)	total: 13.7s	remaining: 3.42s
1400:	learn: 1.1553360	test: 1.2209921	best: 1.2209284 (1338)	total: 16s	remaining: 1.13s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.220928352
bestIteration = 1338

Shrink model to first 1339 iterations.
Seed 42 - Fold 1 RMSE: 1.220928353241764
0:	learn: 2.1924236	test: 2.1834872	best: 2.1834872 (0)	total: 11.7ms	remaining: 17.5s
200:	learn: 1.2213765	test: 1.2305610	best: 1.2305610 (200)	total: 2.91s	remaining: 18.8s
400:	learn: 1.2014089	test: 1.2199910	best: 1.2199910 (400)	total: 5.06s	remaining: 13.9s
600:	learn: 1.1891744	test: 1.2178847	best: 1.2178847 (600)	total: 7.2s	remaining: 10.8s
800:	learn: 1.1788491	test: 1.2172837	best: 1.2172647 (786)	total: 9.59s	remaining: 8.37s
1000:	learn: 1.1701008	test: 1.2168334	best: 1.2167869 (969)	total: 11.8s	remaining: 5.87s
1200:	learn: 1.1605273	test: 1.2166926	best: 1.2166623 (1151)	total: 14.1s	remaining: 3.5s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.216617213
bestIteration = 1232

Shrink model to first 1233 iterations.
Seed 42 - Fold 2 RMSE: 1.2166172138355522
0:	learn: 2.1908350	test: 2.1894935	best: 2.1894935 (0)	total: 9.84ms	remaining: 14.7s
200:	learn: 1.2259194	test: 1.2178046	best: 1.2178046 (200)	total: 2.2s	remaining: 14.2s
400:	learn: 1.2062125	test: 1.2058317	best: 1.2058317 (400)	total: 4.31s	remaining: 11.8s
600:	learn: 1.1942443	test: 1.2034210	best: 1.2034210 (600)	total: 6.47s	remaining: 9.68s
800:	learn: 1.1848497	test: 1.2026583	best: 1.2026454 (795)	total: 8.59s	remaining: 7.5s
1000:	learn: 1.1764048	test: 1.2019143	best: 1.2018966 (976)	total: 10.8s	remaining: 5.36s
1200:	learn: 1.1673833	test: 1.2017929	best: 1.2015498 (1110)	total: 12.9s	remaining: 3.22s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.201549754
bestIteration = 1110

Shrink model to first 1111 iterations.
Seed 42 - Fold 3 RMSE: 1.2015497536961652
0:	learn: 2.1924372	test: 2.1825034	best: 2.1825034 (0)	total: 10.1ms	remaining: 15.1s
200:	learn: 1.2229029	test: 1.2240767	best: 1.2240767 (200)	total: 2.2s	remaining: 14.2s
400:	learn: 1.2014133	test: 1.2123858	best: 1.2123858 (400)	total: 4.36s	remaining: 11.9s
600:	learn: 1.1898515	test: 1.2105435	best: 1.2105435 (600)	total: 6.53s	remaining: 9.77s
800:	learn: 1.1800858	test: 1.2096243	best: 1.2095821 (788)	total: 8.67s	remaining: 7.57s
1000:	learn: 1.1713726	test: 1.2095016	best: 1.2094052 (970)	total: 10.9s	remaining: 5.43s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.209405204
bestIteration = 970

Shrink model to first 971 iterations.
Seed 42 - Fold 4 RMSE: 1.2094052038881296
0:	learn: 2.1884614	test: 2.1981775	best: 2.1981775 (0)	total: 10.6ms	remaining: 15.9s
200:	learn: 1.2179723	test: 1.2452316	best: 1.2452316 (200)	total: 2.22s	remaining: 14.4s
400:	learn: 1.1977249	test: 1.2333702	best: 1.2333702 (400)	total: 4.37s	remaining: 12s
600:	learn: 1.1862519	test: 1.2313939	best: 1.2313908 (598)	total: 6.53s	remaining: 9.77s
800:	learn: 1.1764312	test: 1.2307790	best: 1.2307122 (765)	total: 8.73s	remaining: 7.62s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.230712194
bestIteration = 765

Shrink model to first 766 iterations.
Seed 42 - Fold 5 RMSE: 1.2307121942429744
Seed 42 Mean RMSE: 1.215842543780917
Seed 42 OOF RMSE: 1.2158831154027914
======================================================================
Running CatBoost v3 median seed: 2024
======================================================================
0:	learn: 2.1875262	test: 2.1985510	best: 2.1985510 (0)	total: 8.49ms	remaining: 12.7s
200:	learn: 1.2194189	test: 1.2363728	best: 1.2363728 (200)	total: 2.19s	remaining: 14.2s
400:	learn: 1.1986757	test: 1.2239276	best: 1.2239276 (400)	total: 4.4s	remaining: 12.1s
600:	learn: 1.1862688	test: 1.2216425	best: 1.2216425 (600)	total: 6.56s	remaining: 9.82s
800:	learn: 1.1758457	test: 1.2204349	best: 1.2204349 (800)	total: 8.72s	remaining: 7.61s
1000:	learn: 1.1672874	test: 1.2197889	best: 1.2197889 (1000)	total: 10.9s	remaining: 5.43s
1200:	learn: 1.1582558	test: 1.2195142	best: 1.2193770 (1149)	total: 13.1s	remaining: 3.26s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.219377007
bestIteration = 1149

Shrink model to first 1150 iterations.
Seed 2024 - Fold 1 RMSE: 1.2193770080950292
0:	learn: 2.1913993	test: 2.1827076	best: 2.1827076 (0)	total: 9.89ms	remaining: 14.8s
200:	learn: 1.2206714	test: 1.2304168	best: 1.2304168 (200)	total: 2.18s	remaining: 14.1s
400:	learn: 1.2000176	test: 1.2202112	best: 1.2202057 (399)	total: 4.37s	remaining: 12s
600:	learn: 1.1879177	test: 1.2180032	best: 1.2180020 (599)	total: 6.55s	remaining: 9.79s
800:	learn: 1.1778329	test: 1.2170178	best: 1.2169658 (780)	total: 8.7s	remaining: 7.59s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.216907385
bestIteration = 864

Shrink model to first 865 iterations.
Seed 2024 - Fold 2 RMSE: 1.2169073861191935
0:	learn: 2.1899546	test: 2.1887732	best: 2.1887732 (0)	total: 8.73ms	remaining: 13.1s
200:	learn: 1.2249870	test: 1.2182402	best: 1.2182402 (200)	total: 2.97s	remaining: 19.2s
400:	learn: 1.2046403	test: 1.2060493	best: 1.2060385 (399)	total: 5.12s	remaining: 14s
600:	learn: 1.1921440	test: 1.2032172	best: 1.2032004 (592)	total: 7.5s	remaining: 11.2s
800:	learn: 1.1807317	test: 1.2025596	best: 1.2024015 (770)	total: 9.7s	remaining: 8.46s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.202401495
bestIteration = 770

Shrink model to first 771 iterations.
Seed 2024 - Fold 3 RMSE: 1.202401494067007
0:	learn: 2.1919318	test: 2.1817968	best: 2.1817968 (0)	total: 9.29ms	remaining: 13.9s
200:	learn: 1.2238059	test: 1.2241771	best: 1.2241771 (200)	total: 2.69s	remaining: 17.4s
400:	learn: 1.2031668	test: 1.2117743	best: 1.2117743 (400)	total: 4.87s	remaining: 13.4s
600:	learn: 1.1909776	test: 1.2099876	best: 1.2099876 (600)	total: 7s	remaining: 10.5s
800:	learn: 1.1800836	test: 1.2092478	best: 1.2092292 (785)	total: 9.2s	remaining: 8.03s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.209208966
bestIteration = 813

Shrink model to first 814 iterations.
Seed 2024 - Fold 4 RMSE: 1.2092089657793577
0:	learn: 2.1878057	test: 2.1974765	best: 2.1974765 (0)	total: 8.81ms	remaining: 13.2s
200:	learn: 1.2166483	test: 1.2455801	best: 1.2455801 (200)	total: 2.4s	remaining: 15.5s
400:	learn: 1.1962746	test: 1.2341302	best: 1.2341302 (400)	total: 4.55s	remaining: 12.5s
600:	learn: 1.1834770	test: 1.2319705	best: 1.2319705 (600)	total: 6.72s	remaining: 10s
800:	learn: 1.1733180	test: 1.2316861	best: 1.2315972 (776)	total: 8.94s	remaining: 7.8s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.231535644
bestIteration = 893

Shrink model to first 894 iterations.
Seed 2024 - Fold 5 RMSE: 1.231535644214578
Seed 2024 Mean RMSE: 1.2158860996550331
Seed 2024 OOF RMSE: 1.2159259511244098
======================================================================
Running CatBoost v3 median seed: 3407
======================================================================
0:	learn: 2.1874644	test: 2.1985725	best: 2.1985725 (0)	total: 10.2ms	remaining: 15.2s
200:	learn: 1.2205419	test: 1.2373269	best: 1.2373269 (200)	total: 2.16s	remaining: 14s
400:	learn: 1.2005500	test: 1.2255549	best: 1.2255549 (400)	total: 4.34s	remaining: 11.9s
600:	learn: 1.1883781	test: 1.2230374	best: 1.2230304 (599)	total: 6.56s	remaining: 9.81s
800:	learn: 1.1792344	test: 1.2217195	best: 1.2217093 (796)	total: 8.76s	remaining: 7.64s
1000:	learn: 1.1705839	test: 1.2213322	best: 1.2213155 (994)	total: 11s	remaining: 5.47s
1200:	learn: 1.1619650	test: 1.2209355	best: 1.2209245 (1197)	total: 13.2s	remaining: 3.29s
1400:	learn: 1.1534020	test: 1.2208732	best: 1.2207789 (1321)	total: 15.5s	remaining: 1.09s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.220778912
bestIteration = 1321

Shrink model to first 1322 iterations.
Seed 3407 - Fold 1 RMSE: 1.2207789127766295
0:	learn: 2.1916689	test: 2.1828768	best: 2.1828768 (0)	total: 10.2ms	remaining: 15.3s
200:	learn: 1.2211174	test: 1.2308698	best: 1.2308698 (200)	total: 2.68s	remaining: 17.3s
400:	learn: 1.2005150	test: 1.2204325	best: 1.2204325 (400)	total: 4.87s	remaining: 13.3s
600:	learn: 1.1880735	test: 1.2178620	best: 1.2178620 (600)	total: 7.22s	remaining: 10.8s
800:	learn: 1.1779909	test: 1.2172580	best: 1.2172106 (751)	total: 9.5s	remaining: 8.29s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.217210581
bestIteration = 751

Shrink model to first 752 iterations.
Seed 3407 - Fold 2 RMSE: 1.217210581846897
0:	learn: 2.1899910	test: 2.1886711	best: 2.1886711 (0)	total: 9.15ms	remaining: 13.7s
200:	learn: 1.2250835	test: 1.2171552	best: 1.2171552 (200)	total: 2.68s	remaining: 17.3s
400:	learn: 1.2041901	test: 1.2053000	best: 1.2053000 (400)	total: 5.01s	remaining: 13.7s
600:	learn: 1.1918966	test: 1.2027149	best: 1.2027148 (599)	total: 7.25s	remaining: 10.9s
800:	learn: 1.1814344	test: 1.2022270	best: 1.2021104 (784)	total: 9.53s	remaining: 8.31s
1000:	learn: 1.1723116	test: 1.2020426	best: 1.2019823 (986)	total: 11.7s	remaining: 5.84s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.201982312
bestIteration = 986

Shrink model to first 987 iterations.
Seed 3407 - Fold 3 RMSE: 1.2019823113014911
0:	learn: 2.1920106	test: 2.1817579	best: 2.1817579 (0)	total: 10.2ms	remaining: 15.3s
200:	learn: 1.2234295	test: 1.2230516	best: 1.2230516 (200)	total: 2.93s	remaining: 18.9s
400:	learn: 1.2017141	test: 1.2116024	best: 1.2116024 (400)	total: 5.11s	remaining: 14s
600:	learn: 1.1901477	test: 1.2103621	best: 1.2102581 (553)	total: 7.26s	remaining: 10.9s
800:	learn: 1.1802632	test: 1.2101159	best: 1.2099913 (763)	total: 9.47s	remaining: 8.27s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.209951486
bestIteration = 846

Shrink model to first 847 iterations.
Seed 3407 - Fold 4 RMSE: 1.209951485657742
0:	learn: 2.1880261	test: 2.1975760	best: 2.1975760 (0)	total: 9.57ms	remaining: 14.3s
200:	learn: 1.2175899	test: 1.2466285	best: 1.2466285 (200)	total: 2.28s	remaining: 14.7s
400:	learn: 1.1970499	test: 1.2352115	best: 1.2352115 (400)	total: 4.48s	remaining: 12.3s
600:	learn: 1.1848644	test: 1.2330009	best: 1.2329999 (599)	total: 6.74s	remaining: 10.1s
800:	learn: 1.1749606	test: 1.2327898	best: 1.2327433 (753)	total: 8.92s	remaining: 7.78s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.232743273
bestIteration = 753

Shrink model to first 754 iterations.
Seed 3407 - Fold 5 RMSE: 1.2327432734533346
Seed 3407 Mean RMSE: 1.216533313007219
Seed 3407 OOF RMSE: 1.216577396388051
======================================================================
CatBoost v3 Median 3 Seed Scores
======================================================================
Seed 42
Mean RMSE: 1.215842543780917
OOF RMSE: 1.2158831154027914

Seed 2024
Mean RMSE: 1.2158860996550331
OOF RMSE: 1.2159259511244098

Seed 3407
Mean RMSE: 1.216533313007219
OOF RMSE: 1.216577396388051

Eski v3 3-seed CatBoost OOF: 1.2157046029670755
Median v3 3-seed CatBoost OOF: 1.2153365137912049

# Deney 21B - Median CatBoost v3 3 Seed + HGB v3 + LGBM v3 Blend

In [ ]:
from scipy.optimize import minimize

oof_matrix_median_3 = np.column_stack([
    oof_cat_median_3,
    oof_hgb_v3,
    oof_lgbm_v3
])

test_matrix_median_3 = np.column_stack([
    test_cat_median_3,
    test_hgb_v3,
    test_lgbm_v3
])

model_names_median_3 = [
    "CatBoost v3 Median 3 Seed",
    "HGB v3",
    "LightGBM v3"
]

def blend_rmse_median_3(weights):
    preds = oof_matrix_median_3 @ weights
    return rmse(y, preds)

n_models = oof_matrix_median_3.shape[1]
initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result_median_3 = minimize(
    blend_rmse_median_3,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights_median_3 = result_median_3.x
best_oof_preds_median_3 = oof_matrix_median_3 @ best_weights_median_3
best_test_preds_median_3 = test_matrix_median_3 @ best_weights_median_3

print("Optimization success:", result_median_3.success)
print("Best weights:")

for name, weight in zip(model_names_median_3, best_weights_median_3):
    print(f"{name}: {weight:.6f}")

print("Eski en iyi Deney 20E OOF:", rmse(y, best_oof_preds_v3_5))
print("Median 3-seed blend OOF:", rmse(y, best_oof_preds_median_3))

Optimization success: True
Best weights:
CatBoost v3 Median 3 Seed: 0.910760
HGB v3: 0.070544
LightGBM v3: 0.018697
Eski en iyi Deney 20E OOF: 1.2153820986053874
Median 3-seed blend OOF: 1.2152609001670303

# Deney 21C - CatBoost v3 + Median Imputation - 5 Seed

In [ ]:
seeds_median_5 = [42, 2024, 3407, 777, 999]

cat_oof_list_median_5 = []
cat_test_list_median_5 = []
cat_seed_scores_median_5 = {}

for seed in seeds_median_5:
    print("=" * 70)
    print(f"Running CatBoost v3 median seed: {seed}")
    print("=" * 70)

    oof_seed, test_seed, scores_seed = get_catboost_oof_with_seed_median(
        X_fe_v3,
        y,
        X_test_fe_v3,
        cv,
        seed
    )

    cat_oof_list_median_5.append(oof_seed)
    cat_test_list_median_5.append(test_seed)

    cat_seed_scores_median_5[seed] = {
        "fold_scores": scores_seed,
        "mean_rmse": np.mean(scores_seed),
        "oof_rmse": rmse(y, oof_seed)
    }

oof_cat_median_5 = np.mean(cat_oof_list_median_5, axis=0)
test_cat_median_5 = np.mean(cat_test_list_median_5, axis=0)

print("=" * 70)
print("CatBoost v3 Median 5 Seed Scores")
print("=" * 70)

for seed, result in cat_seed_scores_median_5.items():
    print(f"Seed {seed}")
    print("Mean RMSE:", result["mean_rmse"])
    print("OOF RMSE:", result["oof_rmse"])
    print()

print("Median v3 3-seed CatBoost OOF:", rmse(y, oof_cat_median_3))
print("Median v3 5-seed CatBoost OOF:", rmse(y, oof_cat_median_5))

======================================================================
Running CatBoost v3 median seed: 42
======================================================================
0:	learn: 2.1884436	test: 2.1992729	best: 2.1992729 (0)	total: 10.9ms	remaining: 16.3s
200:	learn: 1.2209683	test: 1.2374999	best: 1.2374999 (200)	total: 2.18s	remaining: 14.1s
400:	learn: 1.2004931	test: 1.2257634	best: 1.2257634 (400)	total: 4.35s	remaining: 11.9s
600:	learn: 1.1892405	test: 1.2228999	best: 1.2228999 (600)	total: 6.54s	remaining: 9.79s
800:	learn: 1.1801532	test: 1.2219336	best: 1.2218889 (775)	total: 8.71s	remaining: 7.61s
1000:	learn: 1.1723566	test: 1.2214341	best: 1.2214273 (997)	total: 10.9s	remaining: 5.45s
1200:	learn: 1.1635280	test: 1.2211876	best: 1.2211876 (1199)	total: 13.2s	remaining: 3.28s
1400:	learn: 1.1553360	test: 1.2209921	best: 1.2209284 (1338)	total: 15.4s	remaining: 1.09s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.220928352
bestIteration = 1338

Shrink model to first 1339 iterations.
Seed 42 - Fold 1 RMSE: 1.220928353241764
0:	learn: 2.1924236	test: 2.1834872	best: 2.1834872 (0)	total: 10.4ms	remaining: 15.5s
200:	learn: 1.2213765	test: 1.2305610	best: 1.2305610 (200)	total: 2.24s	remaining: 14.5s
400:	learn: 1.2014089	test: 1.2199910	best: 1.2199910 (400)	total: 4.39s	remaining: 12s
600:	learn: 1.1891744	test: 1.2178847	best: 1.2178847 (600)	total: 6.57s	remaining: 9.82s
800:	learn: 1.1788491	test: 1.2172837	best: 1.2172647 (786)	total: 8.85s	remaining: 7.73s
1000:	learn: 1.1701008	test: 1.2168334	best: 1.2167869 (969)	total: 11.1s	remaining: 5.52s
1200:	learn: 1.1605273	test: 1.2166926	best: 1.2166623 (1151)	total: 13.3s	remaining: 3.31s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.216617213
bestIteration = 1232

Shrink model to first 1233 iterations.
Seed 42 - Fold 2 RMSE: 1.2166172138355522
0:	learn: 2.1908350	test: 2.1894935	best: 2.1894935 (0)	total: 9.88ms	remaining: 14.8s
200:	learn: 1.2259194	test: 1.2178046	best: 1.2178046 (200)	total: 2.5s	remaining: 16.1s
400:	learn: 1.2062125	test: 1.2058317	best: 1.2058317 (400)	total: 4.66s	remaining: 12.8s
600:	learn: 1.1942443	test: 1.2034210	best: 1.2034210 (600)	total: 6.84s	remaining: 10.2s
800:	learn: 1.1848497	test: 1.2026583	best: 1.2026454 (795)	total: 9.08s	remaining: 7.92s
1000:	learn: 1.1764048	test: 1.2019143	best: 1.2018966 (976)	total: 11.3s	remaining: 5.64s
1200:	learn: 1.1673833	test: 1.2017929	best: 1.2015498 (1110)	total: 13.5s	remaining: 3.37s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.201549754
bestIteration = 1110

Shrink model to first 1111 iterations.
Seed 42 - Fold 3 RMSE: 1.2015497536961652
0:	learn: 2.1924372	test: 2.1825034	best: 2.1825034 (0)	total: 10.3ms	remaining: 15.5s
200:	learn: 1.2229029	test: 1.2240767	best: 1.2240767 (200)	total: 2.22s	remaining: 14.3s
400:	learn: 1.2014133	test: 1.2123858	best: 1.2123858 (400)	total: 4.42s	remaining: 12.1s
600:	learn: 1.1898515	test: 1.2105435	best: 1.2105435 (600)	total: 6.57s	remaining: 9.83s
800:	learn: 1.1800858	test: 1.2096243	best: 1.2095821 (788)	total: 8.78s	remaining: 7.66s
1000:	learn: 1.1713726	test: 1.2095016	best: 1.2094052 (970)	total: 11s	remaining: 5.47s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.209405204
bestIteration = 970

Shrink model to first 971 iterations.
Seed 42 - Fold 4 RMSE: 1.2094052038881296
0:	learn: 2.1884614	test: 2.1981775	best: 2.1981775 (0)	total: 10.5ms	remaining: 15.8s
200:	learn: 1.2179723	test: 1.2452316	best: 1.2452316 (200)	total: 2.19s	remaining: 14.2s
400:	learn: 1.1977249	test: 1.2333702	best: 1.2333702 (400)	total: 4.34s	remaining: 11.9s
600:	learn: 1.1862519	test: 1.2313939	best: 1.2313908 (598)	total: 6.51s	remaining: 9.74s
800:	learn: 1.1764312	test: 1.2307790	best: 1.2307122 (765)	total: 8.77s	remaining: 7.66s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.230712194
bestIteration = 765

Shrink model to first 766 iterations.
Seed 42 - Fold 5 RMSE: 1.2307121942429744
Seed 42 Mean RMSE: 1.215842543780917
Seed 42 OOF RMSE: 1.2158831154027914
======================================================================
Running CatBoost v3 median seed: 2024
======================================================================
0:	learn: 2.1875262	test: 2.1985510	best: 2.1985510 (0)	total: 9.33ms	remaining: 14s
200:	learn: 1.2194189	test: 1.2363728	best: 1.2363728 (200)	total: 2.17s	remaining: 14s
400:	learn: 1.1986757	test: 1.2239276	best: 1.2239276 (400)	total: 4.3s	remaining: 11.8s
600:	learn: 1.1862688	test: 1.2216425	best: 1.2216425 (600)	total: 6.47s	remaining: 9.69s
800:	learn: 1.1758457	test: 1.2204349	best: 1.2204349 (800)	total: 8.64s	remaining: 7.54s
1000:	learn: 1.1672874	test: 1.2197889	best: 1.2197889 (1000)	total: 10.9s	remaining: 5.41s
1200:	learn: 1.1582558	test: 1.2195142	best: 1.2193770 (1149)	total: 13.1s	remaining: 3.26s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.219377007
bestIteration = 1149

Shrink model to first 1150 iterations.
Seed 2024 - Fold 1 RMSE: 1.2193770080950292
0:	learn: 2.1913993	test: 2.1827076	best: 2.1827076 (0)	total: 10.4ms	remaining: 15.7s
200:	learn: 1.2206714	test: 1.2304168	best: 1.2304168 (200)	total: 2.19s	remaining: 14.2s
400:	learn: 1.2000176	test: 1.2202112	best: 1.2202057 (399)	total: 4.82s	remaining: 13.2s
600:	learn: 1.1879177	test: 1.2180032	best: 1.2180020 (599)	total: 7.24s	remaining: 10.8s
800:	learn: 1.1778329	test: 1.2170178	best: 1.2169658 (780)	total: 9.61s	remaining: 8.39s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.216907385
bestIteration = 864

Shrink model to first 865 iterations.
Seed 2024 - Fold 2 RMSE: 1.2169073861191935
0:	learn: 2.1899546	test: 2.1887732	best: 2.1887732 (0)	total: 8.35ms	remaining: 12.5s
200:	learn: 1.2249870	test: 1.2182402	best: 1.2182402 (200)	total: 2.17s	remaining: 14s
400:	learn: 1.2046403	test: 1.2060493	best: 1.2060385 (399)	total: 4.34s	remaining: 11.9s
600:	learn: 1.1921440	test: 1.2032172	best: 1.2032004 (592)	total: 6.52s	remaining: 9.75s
800:	learn: 1.1807317	test: 1.2025596	best: 1.2024015 (770)	total: 8.73s	remaining: 7.62s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.202401495
bestIteration = 770

Shrink model to first 771 iterations.
Seed 2024 - Fold 3 RMSE: 1.202401494067007
0:	learn: 2.1919318	test: 2.1817968	best: 2.1817968 (0)	total: 11ms	remaining: 16.5s
200:	learn: 1.2238059	test: 1.2241771	best: 1.2241771 (200)	total: 2.22s	remaining: 14.3s
400:	learn: 1.2031668	test: 1.2117743	best: 1.2117743 (400)	total: 4.44s	remaining: 12.2s
600:	learn: 1.1909776	test: 1.2099876	best: 1.2099876 (600)	total: 6.6s	remaining: 9.88s
800:	learn: 1.1800836	test: 1.2092478	best: 1.2092292 (785)	total: 8.84s	remaining: 7.71s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.209208966
bestIteration = 813

Shrink model to first 814 iterations.
Seed 2024 - Fold 4 RMSE: 1.2092089657793577
0:	learn: 2.1878057	test: 2.1974765	best: 2.1974765 (0)	total: 11.3ms	remaining: 16.9s
200:	learn: 1.2166483	test: 1.2455801	best: 1.2455801 (200)	total: 2.2s	remaining: 14.2s
400:	learn: 1.1962746	test: 1.2341302	best: 1.2341302 (400)	total: 4.39s	remaining: 12s
600:	learn: 1.1834770	test: 1.2319705	best: 1.2319705 (600)	total: 6.59s	remaining: 9.86s
800:	learn: 1.1733180	test: 1.2316861	best: 1.2315972 (776)	total: 8.78s	remaining: 7.67s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.231535644
bestIteration = 893

Shrink model to first 894 iterations.
Seed 2024 - Fold 5 RMSE: 1.231535644214578
Seed 2024 Mean RMSE: 1.2158860996550331
Seed 2024 OOF RMSE: 1.2159259511244098
======================================================================
Running CatBoost v3 median seed: 3407
======================================================================
0:	learn: 2.1874644	test: 2.1985725	best: 2.1985725 (0)	total: 9.66ms	remaining: 14.5s
200:	learn: 1.2205419	test: 1.2373269	best: 1.2373269 (200)	total: 2.23s	remaining: 14.4s
400:	learn: 1.2005500	test: 1.2255549	best: 1.2255549 (400)	total: 4.41s	remaining: 12.1s
600:	learn: 1.1883781	test: 1.2230374	best: 1.2230304 (599)	total: 6.62s	remaining: 9.9s
800:	learn: 1.1792344	test: 1.2217195	best: 1.2217093 (796)	total: 8.82s	remaining: 7.7s
1000:	learn: 1.1705839	test: 1.2213322	best: 1.2213155 (994)	total: 11s	remaining: 5.51s
1200:	learn: 1.1619650	test: 1.2209355	best: 1.2209245 (1197)	total: 13.4s	remaining: 3.32s
1400:	learn: 1.1534020	test: 1.2208732	best: 1.2207789 (1321)	total: 15.6s	remaining: 1.1s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.220778912
bestIteration = 1321

Shrink model to first 1322 iterations.
Seed 3407 - Fold 1 RMSE: 1.2207789127766295
0:	learn: 2.1916689	test: 2.1828768	best: 2.1828768 (0)	total: 10.2ms	remaining: 15.2s
200:	learn: 1.2211174	test: 1.2308698	best: 1.2308698 (200)	total: 2.53s	remaining: 16.3s
400:	learn: 1.2005150	test: 1.2204325	best: 1.2204325 (400)	total: 4.72s	remaining: 12.9s
600:	learn: 1.1880735	test: 1.2178620	best: 1.2178620 (600)	total: 7.12s	remaining: 10.7s
800:	learn: 1.1779909	test: 1.2172580	best: 1.2172106 (751)	total: 9.32s	remaining: 8.13s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.217210581
bestIteration = 751

Shrink model to first 752 iterations.
Seed 3407 - Fold 2 RMSE: 1.217210581846897
0:	learn: 2.1899910	test: 2.1886711	best: 2.1886711 (0)	total: 9.68ms	remaining: 14.5s
200:	learn: 1.2250835	test: 1.2171552	best: 1.2171552 (200)	total: 2.15s	remaining: 13.9s
400:	learn: 1.2041901	test: 1.2053000	best: 1.2053000 (400)	total: 4.3s	remaining: 11.8s
600:	learn: 1.1918966	test: 1.2027149	best: 1.2027148 (599)	total: 6.43s	remaining: 9.62s
800:	learn: 1.1814344	test: 1.2022270	best: 1.2021104 (784)	total: 8.65s	remaining: 7.55s
1000:	learn: 1.1723116	test: 1.2020426	best: 1.2019823 (986)	total: 10.9s	remaining: 5.42s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.201982312
bestIteration = 986

Shrink model to first 987 iterations.
Seed 3407 - Fold 3 RMSE: 1.2019823113014911
0:	learn: 2.1920106	test: 2.1817579	best: 2.1817579 (0)	total: 9.99ms	remaining: 15s
200:	learn: 1.2234295	test: 1.2230516	best: 1.2230516 (200)	total: 2.21s	remaining: 14.3s
400:	learn: 1.2017141	test: 1.2116024	best: 1.2116024 (400)	total: 4.38s	remaining: 12s
600:	learn: 1.1901477	test: 1.2103621	best: 1.2102581 (553)	total: 6.54s	remaining: 9.78s
800:	learn: 1.1802632	test: 1.2101159	best: 1.2099913 (763)	total: 8.75s	remaining: 7.63s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.209951486
bestIteration = 846

Shrink model to first 847 iterations.
Seed 3407 - Fold 4 RMSE: 1.209951485657742
0:	learn: 2.1880261	test: 2.1975760	best: 2.1975760 (0)	total: 9.98ms	remaining: 15s
200:	learn: 1.2175899	test: 1.2466285	best: 1.2466285 (200)	total: 2.16s	remaining: 14s
400:	learn: 1.1970499	test: 1.2352115	best: 1.2352115 (400)	total: 4.32s	remaining: 11.9s
600:	learn: 1.1848644	test: 1.2330009	best: 1.2329999 (599)	total: 6.54s	remaining: 9.78s
800:	learn: 1.1749606	test: 1.2327898	best: 1.2327433 (753)	total: 8.75s	remaining: 7.63s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.232743273
bestIteration = 753

Shrink model to first 754 iterations.
Seed 3407 - Fold 5 RMSE: 1.2327432734533346
Seed 3407 Mean RMSE: 1.216533313007219
Seed 3407 OOF RMSE: 1.216577396388051
======================================================================
Running CatBoost v3 median seed: 777
======================================================================
0:	learn: 2.1875120	test: 2.1985543	best: 2.1985543 (0)	total: 9.53ms	remaining: 14.3s
200:	learn: 1.2196395	test: 1.2374841	best: 1.2374841 (200)	total: 2.27s	remaining: 14.7s
400:	learn: 1.2001531	test: 1.2259427	best: 1.2259427 (400)	total: 4.46s	remaining: 12.2s
600:	learn: 1.1885333	test: 1.2229666	best: 1.2229666 (600)	total: 6.68s	remaining: 9.99s
800:	learn: 1.1784751	test: 1.2217371	best: 1.2217371 (800)	total: 8.88s	remaining: 7.75s
1000:	learn: 1.1694952	test: 1.2212875	best: 1.2212573 (987)	total: 11.1s	remaining: 5.54s
1200:	learn: 1.1614149	test: 1.2210919	best: 1.2209967 (1169)	total: 13.3s	remaining: 3.32s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.220996712
bestIteration = 1169

Shrink model to first 1170 iterations.
Seed 777 - Fold 1 RMSE: 1.2209967126983794
0:	learn: 2.1912152	test: 2.1825824	best: 2.1825824 (0)	total: 9.5ms	remaining: 14.2s
200:	learn: 1.2217078	test: 1.2311671	best: 1.2311671 (200)	total: 2.16s	remaining: 13.9s
400:	learn: 1.2003140	test: 1.2197291	best: 1.2197246 (398)	total: 4.41s	remaining: 12.1s
600:	learn: 1.1879122	test: 1.2171186	best: 1.2171126 (595)	total: 6.6s	remaining: 9.87s
800:	learn: 1.1782813	test: 1.2164849	best: 1.2164825 (799)	total: 8.8s	remaining: 7.68s
1000:	learn: 1.1686030	test: 1.2164698	best: 1.2163822 (921)	total: 11s	remaining: 5.5s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.216382173
bestIteration = 921

Shrink model to first 922 iterations.
Seed 777 - Fold 2 RMSE: 1.2163821743066494
0:	learn: 2.1900325	test: 2.1887787	best: 2.1887787 (0)	total: 9.4ms	remaining: 14.1s
200:	learn: 1.2259931	test: 1.2176363	best: 1.2176363 (200)	total: 2.51s	remaining: 16.2s
400:	learn: 1.2055110	test: 1.2057875	best: 1.2057875 (400)	total: 4.81s	remaining: 13.2s
600:	learn: 1.1939328	test: 1.2035935	best: 1.2035935 (600)	total: 7.07s	remaining: 10.6s
800:	learn: 1.1837861	test: 1.2023488	best: 1.2023400 (798)	total: 9.29s	remaining: 8.11s
1000:	learn: 1.1744618	test: 1.2019194	best: 1.2017793 (961)	total: 11.5s	remaining: 5.75s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.201779349
bestIteration = 961

Shrink model to first 962 iterations.
Seed 777 - Fold 3 RMSE: 1.2017793487947332
0:	learn: 2.1918164	test: 2.1814392	best: 2.1814392 (0)	total: 10.3ms	remaining: 15.5s
200:	learn: 1.2225420	test: 1.2237879	best: 1.2237879 (200)	total: 2.18s	remaining: 14.1s
400:	learn: 1.2019023	test: 1.2126941	best: 1.2126941 (400)	total: 4.38s	remaining: 12s
600:	learn: 1.1902533	test: 1.2109212	best: 1.2108864 (596)	total: 6.59s	remaining: 9.86s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.210609907
bestIteration = 665

Shrink model to first 666 iterations.
Seed 777 - Fold 4 RMSE: 1.2106099069704834
0:	learn: 2.1874960	test: 2.1974088	best: 2.1974088 (0)	total: 9.85ms	remaining: 14.8s
200:	learn: 1.2167201	test: 1.2448587	best: 1.2448587 (200)	total: 2.84s	remaining: 18.4s
400:	learn: 1.1963162	test: 1.2333981	best: 1.2333981 (400)	total: 5s	remaining: 13.7s
600:	learn: 1.1841359	test: 1.2316604	best: 1.2316578 (599)	total: 7.21s	remaining: 10.8s
800:	learn: 1.1745173	test: 1.2310952	best: 1.2310073 (783)	total: 9.65s	remaining: 8.42s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.23100733
bestIteration = 783

Shrink model to first 784 iterations.
Seed 777 - Fold 5 RMSE: 1.2310073302126006
Seed 777 Mean RMSE: 1.2161550945965691
Seed 777 OOF RMSE: 1.2161946853586354
======================================================================
Running CatBoost v3 median seed: 999
======================================================================
0:	learn: 2.1874811	test: 2.1987006	best: 2.1987006 (0)	total: 9.69ms	remaining: 14.5s
200:	learn: 1.2203645	test: 1.2375724	best: 1.2375724 (200)	total: 2.17s	remaining: 14s
400:	learn: 1.1994219	test: 1.2260236	best: 1.2260016 (399)	total: 4.38s	remaining: 12s
600:	learn: 1.1876360	test: 1.2228867	best: 1.2228794 (598)	total: 6.55s	remaining: 9.8s
800:	learn: 1.1783241	test: 1.2220559	best: 1.2220440 (799)	total: 8.74s	remaining: 7.63s
1000:	learn: 1.1696065	test: 1.2212897	best: 1.2212381 (997)	total: 11s	remaining: 5.49s
1200:	learn: 1.1607638	test: 1.2213472	best: 1.2211848 (1131)	total: 13.3s	remaining: 3.31s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.221184754
bestIteration = 1131

Shrink model to first 1132 iterations.
Seed 999 - Fold 1 RMSE: 1.2211847546523011
0:	learn: 2.1913945	test: 2.1827176	best: 2.1827176 (0)	total: 10ms	remaining: 15s
200:	learn: 1.2211846	test: 1.2306349	best: 1.2306349 (200)	total: 2.33s	remaining: 15.1s
400:	learn: 1.2003926	test: 1.2203969	best: 1.2203932 (399)	total: 4.59s	remaining: 12.6s
600:	learn: 1.1886635	test: 1.2184057	best: 1.2184057 (600)	total: 6.79s	remaining: 10.2s
800:	learn: 1.1783537	test: 1.2176352	best: 1.2176265 (794)	total: 8.97s	remaining: 7.83s
1000:	learn: 1.1691905	test: 1.2173752	best: 1.2173008 (952)	total: 11.2s	remaining: 5.56s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.217260112
bestIteration = 1028

Shrink model to first 1029 iterations.
Seed 999 - Fold 2 RMSE: 1.2172601131140117
0:	learn: 2.1896462	test: 2.1885692	best: 2.1885692 (0)	total: 9.63ms	remaining: 14.4s
200:	learn: 1.2237184	test: 1.2179440	best: 1.2179440 (200)	total: 2.13s	remaining: 13.7s
400:	learn: 1.2037270	test: 1.2061907	best: 1.2061896 (398)	total: 4.26s	remaining: 11.7s
600:	learn: 1.1929556	test: 1.2041332	best: 1.2041332 (600)	total: 6.38s	remaining: 9.55s
800:	learn: 1.1837783	test: 1.2032703	best: 1.2032297 (757)	total: 8.56s	remaining: 7.47s
1000:	learn: 1.1750453	test: 1.2029096	best: 1.2028986 (999)	total: 10.8s	remaining: 5.36s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.202780736
bestIteration = 1033

Shrink model to first 1034 iterations.
Seed 999 - Fold 3 RMSE: 1.2027807349736557
0:	learn: 2.1916795	test: 2.1812084	best: 2.1812084 (0)	total: 9.73ms	remaining: 14.6s
200:	learn: 1.2241296	test: 1.2239421	best: 1.2239421 (200)	total: 2.1s	remaining: 13.6s
400:	learn: 1.2025627	test: 1.2116574	best: 1.2116574 (400)	total: 4.31s	remaining: 11.8s
600:	learn: 1.1897140	test: 1.2097920	best: 1.2097920 (600)	total: 6.47s	remaining: 9.68s
800:	learn: 1.1794177	test: 1.2091946	best: 1.2091770 (783)	total: 8.68s	remaining: 7.57s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.209130938
bestIteration = 810

Shrink model to first 811 iterations.
Seed 999 - Fold 4 RMSE: 1.2091309377091346
0:	learn: 2.1876352	test: 2.1973260	best: 2.1973260 (0)	total: 9.22ms	remaining: 13.8s
200:	learn: 1.2181254	test: 1.2457119	best: 1.2457119 (200)	total: 2.4s	remaining: 15.5s
400:	learn: 1.1977822	test: 1.2344354	best: 1.2344354 (400)	total: 4.68s	remaining: 12.8s
600:	learn: 1.1872487	test: 1.2322146	best: 1.2322146 (600)	total: 6.81s	remaining: 10.2s
800:	learn: 1.1779481	test: 1.2316520	best: 1.2315712 (763)	total: 8.98s	remaining: 7.83s
1000:	learn: 1.1684937	test: 1.2315049	best: 1.2314234 (925)	total: 11.2s	remaining: 5.6s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.231423394
bestIteration = 925

Shrink model to first 926 iterations.
Seed 999 - Fold 5 RMSE: 1.2314233946357611
Seed 999 Mean RMSE: 1.2163559870169727
Seed 999 OOF RMSE: 1.216396077417133
======================================================================
CatBoost v3 Median 5 Seed Scores
======================================================================
Seed 42
Mean RMSE: 1.215842543780917
OOF RMSE: 1.2158831154027914

Seed 2024
Mean RMSE: 1.2158860996550331
OOF RMSE: 1.2159259511244098

Seed 3407
Mean RMSE: 1.216533313007219
OOF RMSE: 1.216577396388051

Seed 777
Mean RMSE: 1.2161550945965691
OOF RMSE: 1.2161946853586354

Seed 999
Mean RMSE: 1.2163559870169727
OOF RMSE: 1.216396077417133

Median v3 3-seed CatBoost OOF: 1.2153365137912049
Median v3 5-seed CatBoost OOF: 1.2152369352820866

# Deney 21D - Median CatBoost v3 5 Seed + HGB v3 + LGBM v3 Blend

In [ ]:
from scipy.optimize import minimize

oof_matrix_median_5 = np.column_stack([
    oof_cat_median_5,
    oof_hgb_v3,
    oof_lgbm_v3
])

test_matrix_median_5 = np.column_stack([
    test_cat_median_5,
    test_hgb_v3,
    test_lgbm_v3
])

model_names_median_5 = [
    "CatBoost v3 Median 5 Seed",
    "HGB v3",
    "LightGBM v3"
]

def blend_rmse_median_5(weights):
    preds = oof_matrix_median_5 @ weights
    return rmse(y, preds)

n_models = oof_matrix_median_5.shape[1]
initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result_median_5 = minimize(
    blend_rmse_median_5,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights_median_5 = result_median_5.x
best_oof_preds_median_5 = oof_matrix_median_5 @ best_weights_median_5
best_test_preds_median_5 = test_matrix_median_5 @ best_weights_median_5

print("Optimization success:", result_median_5.success)
print("Best weights:")

for name, weight in zip(model_names_median_5, best_weights_median_5):
    print(f"{name}: {weight:.6f}")

print("Eski en iyi Median 3-seed blend OOF:", rmse(y, best_oof_preds_median_3))
print("Median 5-seed blend OOF:", rmse(y, best_oof_preds_median_5))

Optimization success: True
Best weights:
CatBoost v3 Median 5 Seed: 0.918478
HGB v3: 0.066655
LightGBM v3: 0.014867
Eski en iyi Median 3-seed blend OOF: 1.2152609001670303
Median 5-seed blend OOF: 1.215180348002664

# Deney 22 - Feature v4
# Feature v3 + group-based relative numeric features

In [ ]:
def prepare_features_v4_group_relative(X, X_test):
    # Önce mevcut başarılı v3 feature setini üret
    X_fe, X_test_fe = prepare_features_v3(X, X_test)

    def add_group_relative_feature(train_df, test_df, group_col, num_col):
        if group_col not in train_df.columns or num_col not in train_df.columns:
            return train_df, test_df

        train_df = train_df.copy()
        test_df = test_df.copy()

        train_group = train_df[group_col].fillna("Bilinmiyor").astype(str)
        test_group = test_df[group_col].fillna("Bilinmiyor").astype(str)

        global_median = train_df[num_col].median()

        group_mean = train_df.groupby(train_group)[num_col].mean()

        train_group_mean = train_group.map(group_mean).fillna(global_median)
        test_group_mean = test_group.map(group_mean).fillna(global_median)

        base_name = f"{num_col}_rel_{group_col}"

        train_df[f"{base_name}_diff"] = train_df[num_col] - train_group_mean
        test_df[f"{base_name}_diff"] = test_df[num_col] - test_group_mean

        train_df[f"{base_name}_ratio"] = train_df[num_col] / (train_group_mean + 1)
        test_df[f"{base_name}_ratio"] = test_df[num_col] / (test_group_mean + 1)

        return train_df, test_df

    # Kontrollü kombinasyonlar
    group_numeric_pairs = [
        ("meslek", "stres_skoru"),
        ("meslek", "gunluk_adim_sayisi"),
        ("meslek", "gunluk_calisma_saati"),

        ("kronotip", "uyku_oncesi_kafein_mg"),
        ("kronotip", "uyku_oncesi_ekran_suresi_dk"),
        ("kronotip", "uyku_kalitesi_orani"),
        ("kronotip", "uyku_bozulma_skoru"),

        ("gun_tipi", "gunluk_calisma_saati"),
        ("gun_tipi", "uyku_oncesi_kafein_mg"),
        ("gun_tipi", "uyku_oncesi_ekran_suresi_dk"),

        ("meslek_kronotip", "stres_skoru"),
        ("meslek_kronotip", "gunluk_adim_sayisi"),
        ("meslek_kronotip", "gunluk_calisma_saati"),
    ]

    for group_col, num_col in group_numeric_pairs:
        X_fe, X_test_fe = add_group_relative_feature(
            X_fe,
            X_test_fe,
            group_col,
            num_col
        )

    return X_fe, X_test_fe


X_fe_v4, X_test_fe_v4 = prepare_features_v4_group_relative(X, X_test)

print("X_fe_v4:", X_fe_v4.shape)
print("X_test_fe_v4:", X_test_fe_v4.shape)
print("New columns vs original:", X_fe_v4.shape[1] - X.shape[1])

X_fe_v4: (56000, 63)
X_test_fe_v4: (24000, 63)
New columns vs original: 41

# Deney 22A - CatBoost v4 + Median Imputation - 3 Seed

In [ ]:
seeds_v4_median_3 = [42, 2024, 3407]

cat_oof_list_v4_median_3 = []
cat_test_list_v4_median_3 = []
cat_seed_scores_v4_median_3 = {}

for seed in seeds_v4_median_3:
    print("=" * 70)
    print(f"Running CatBoost v4 median seed: {seed}")
    print("=" * 70)

    oof_seed, test_seed, scores_seed = get_catboost_oof_with_seed_median(
        X_fe_v4,
        y,
        X_test_fe_v4,
        cv,
        seed
    )

    cat_oof_list_v4_median_3.append(oof_seed)
    cat_test_list_v4_median_3.append(test_seed)

    cat_seed_scores_v4_median_3[seed] = {
        "fold_scores": scores_seed,
        "mean_rmse": np.mean(scores_seed),
        "oof_rmse": rmse(y, oof_seed)
    }

oof_cat_v4_median_3 = np.mean(cat_oof_list_v4_median_3, axis=0)
test_cat_v4_median_3 = np.mean(cat_test_list_v4_median_3, axis=0)

print("=" * 70)
print("CatBoost v4 Median 3 Seed Scores")
print("=" * 70)

for seed, result in cat_seed_scores_v4_median_3.items():
    print(f"Seed {seed}")
    print("Mean RMSE:", result["mean_rmse"])
    print("OOF RMSE:", result["oof_rmse"])
    print()

print("Eski v3 Median 3-seed CatBoost OOF:", rmse(y, oof_cat_median_3))
print("v4 Median 3-seed CatBoost OOF:", rmse(y, oof_cat_v4_median_3))

======================================================================
Running CatBoost v4 median seed: 42
======================================================================
0:	learn: 2.1874944	test: 2.1985876	best: 2.1985876 (0)	total: 10.9ms	remaining: 16.3s
200:	learn: 1.2212564	test: 1.2377082	best: 1.2377082 (200)	total: 2.84s	remaining: 18.4s
400:	learn: 1.1999816	test: 1.2261461	best: 1.2261461 (400)	total: 5.36s	remaining: 14.7s
600:	learn: 1.1877835	test: 1.2228349	best: 1.2227841 (583)	total: 7.7s	remaining: 11.5s
800:	learn: 1.1776386	test: 1.2219384	best: 1.2219384 (800)	total: 10s	remaining: 8.74s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.221799436
bestIteration = 829

Shrink model to first 830 iterations.
Seed 42 - Fold 1 RMSE: 1.221799436911277
0:	learn: 2.1914467	test: 2.1824660	best: 2.1824660 (0)	total: 10.9ms	remaining: 16.4s
200:	learn: 1.2215351	test: 1.2305462	best: 1.2305462 (200)	total: 2.34s	remaining: 15.1s
400:	learn: 1.2008059	test: 1.2198962	best: 1.2198946 (398)	total: 4.65s	remaining: 12.7s
600:	learn: 1.1878002	test: 1.2174478	best: 1.2174419 (598)	total: 6.94s	remaining: 10.4s
800:	learn: 1.1767332	test: 1.2166144	best: 1.2165574 (766)	total: 9.28s	remaining: 8.1s
1000:	learn: 1.1659957	test: 1.2164194	best: 1.2163403 (909)	total: 11.6s	remaining: 5.8s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.216340285
bestIteration = 909

Shrink model to first 910 iterations.
Seed 42 - Fold 2 RMSE: 1.216340286326346
0:	learn: 2.1899435	test: 2.1887052	best: 2.1887052 (0)	total: 9.35ms	remaining: 14s
200:	learn: 1.2252712	test: 1.2183174	best: 1.2183174 (200)	total: 2.36s	remaining: 15.3s
400:	learn: 1.2047897	test: 1.2061874	best: 1.2061874 (400)	total: 4.68s	remaining: 12.8s
600:	learn: 1.1915916	test: 1.2039251	best: 1.2039210 (598)	total: 7.03s	remaining: 10.5s
800:	learn: 1.1806457	test: 1.2034054	best: 1.2033476 (792)	total: 9.4s	remaining: 8.2s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.203286365
bestIteration = 819

Shrink model to first 820 iterations.
Seed 42 - Fold 3 RMSE: 1.2032863647140035
0:	learn: 2.1916805	test: 2.1814255	best: 2.1814255 (0)	total: 10.4ms	remaining: 15.6s
200:	learn: 1.2222817	test: 1.2235349	best: 1.2235349 (200)	total: 2.32s	remaining: 15s
400:	learn: 1.2001058	test: 1.2130589	best: 1.2130367 (398)	total: 4.62s	remaining: 12.7s
600:	learn: 1.1884022	test: 1.2114732	best: 1.2114470 (593)	total: 7.65s	remaining: 11.4s
800:	learn: 1.1780690	test: 1.2105677	best: 1.2105677 (800)	total: 10s	remaining: 8.74s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.210469579
bestIteration = 839

Shrink model to first 840 iterations.
Seed 42 - Fold 4 RMSE: 1.21046957894137
0:	learn: 2.1876555	test: 2.1970981	best: 2.1970981 (0)	total: 10.1ms	remaining: 15.2s
200:	learn: 1.2179090	test: 1.2457855	best: 1.2457855 (200)	total: 2.67s	remaining: 17.3s
400:	learn: 1.1972456	test: 1.2340734	best: 1.2340734 (400)	total: 5.22s	remaining: 14.3s
600:	learn: 1.1854017	test: 1.2321657	best: 1.2321657 (600)	total: 7.63s	remaining: 11.4s
800:	learn: 1.1742930	test: 1.2315149	best: 1.2314826 (795)	total: 10.1s	remaining: 8.77s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.23126006
bestIteration = 861

Shrink model to first 862 iterations.
Seed 42 - Fold 5 RMSE: 1.2312600604632504
Seed 42 Mean RMSE: 1.2166311454712493
Seed 42 OOF RMSE: 1.216668695226295
======================================================================
Running CatBoost v4 median seed: 2024
======================================================================
0:	learn: 2.1876147	test: 2.1988885	best: 2.1988885 (0)	total: 10.4ms	remaining: 15.6s
200:	learn: 1.2199418	test: 1.2369779	best: 1.2369779 (200)	total: 2.38s	remaining: 15.4s
400:	learn: 1.1987398	test: 1.2252639	best: 1.2252639 (400)	total: 4.82s	remaining: 13.2s
600:	learn: 1.1853517	test: 1.2219703	best: 1.2219636 (594)	total: 7.24s	remaining: 10.8s
800:	learn: 1.1745105	test: 1.2210469	best: 1.2210388 (798)	total: 9.58s	remaining: 8.36s
1000:	learn: 1.1639325	test: 1.2206090	best: 1.2205987 (999)	total: 11.9s	remaining: 5.95s
1200:	learn: 1.1551338	test: 1.2204467	best: 1.2203255 (1161)	total: 14.3s	remaining: 3.55s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.220325514
bestIteration = 1161

Shrink model to first 1162 iterations.
Seed 2024 - Fold 1 RMSE: 1.2203255150318026
0:	learn: 2.1915428	test: 2.1827732	best: 2.1827732 (0)	total: 9.19ms	remaining: 13.8s
200:	learn: 1.2206319	test: 1.2305677	best: 1.2305677 (200)	total: 2.35s	remaining: 15.2s
400:	learn: 1.1990491	test: 1.2194180	best: 1.2194148 (399)	total: 4.67s	remaining: 12.8s
600:	learn: 1.1868021	test: 1.2174293	best: 1.2174293 (600)	total: 6.99s	remaining: 10.5s
800:	learn: 1.1757829	test: 1.2165599	best: 1.2165395 (760)	total: 9.3s	remaining: 8.12s
1000:	learn: 1.1655780	test: 1.2165003	best: 1.2164466 (924)	total: 11.7s	remaining: 5.82s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.216180611
bestIteration = 1081

Shrink model to first 1082 iterations.
Seed 2024 - Fold 2 RMSE: 1.2161806115171876
0:	learn: 2.1901637	test: 2.1887825	best: 2.1887825 (0)	total: 10.4ms	remaining: 15.6s
200:	learn: 1.2239714	test: 1.2186621	best: 1.2186621 (200)	total: 2.83s	remaining: 18.3s
400:	learn: 1.2032485	test: 1.2067890	best: 1.2067868 (399)	total: 5.18s	remaining: 14.2s
600:	learn: 1.1897667	test: 1.2041654	best: 1.2041654 (600)	total: 7.7s	remaining: 11.5s
800:	learn: 1.1781416	test: 1.2034140	best: 1.2034037 (781)	total: 10.1s	remaining: 8.8s
1000:	learn: 1.1674215	test: 1.2032384	best: 1.2032341 (962)	total: 12.5s	remaining: 6.22s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.203073651
bestIteration = 1031

Shrink model to first 1032 iterations.
Seed 2024 - Fold 3 RMSE: 1.2030736504240334
0:	learn: 2.1917817	test: 2.1818650	best: 2.1818650 (0)	total: 9.2ms	remaining: 13.8s
200:	learn: 1.2232719	test: 1.2241300	best: 1.2241300 (200)	total: 3.09s	remaining: 20s
400:	learn: 1.2017788	test: 1.2129146	best: 1.2129115 (398)	total: 5.44s	remaining: 14.9s
600:	learn: 1.1885716	test: 1.2109334	best: 1.2109334 (600)	total: 7.73s	remaining: 11.6s
800:	learn: 1.1771817	test: 1.2104120	best: 1.2103923 (784)	total: 10.2s	remaining: 8.94s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.210332561
bestIteration = 824

Shrink model to first 825 iterations.
Seed 2024 - Fold 4 RMSE: 1.2103325606770623
0:	learn: 2.1878326	test: 2.1972152	best: 2.1972152 (0)	total: 10.6ms	remaining: 15.9s
200:	learn: 1.2164995	test: 1.2453406	best: 1.2453406 (200)	total: 2.39s	remaining: 15.5s
400:	learn: 1.1954426	test: 1.2341639	best: 1.2341639 (400)	total: 4.72s	remaining: 12.9s
600:	learn: 1.1823155	test: 1.2320559	best: 1.2320559 (600)	total: 7.15s	remaining: 10.7s
800:	learn: 1.1713374	test: 1.2314259	best: 1.2312815 (777)	total: 9.54s	remaining: 8.33s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.23128154
bestIteration = 777

Shrink model to first 778 iterations.
Seed 2024 - Fold 5 RMSE: 1.2312815400018955
Seed 2024 Mean RMSE: 1.2162387755303965
Seed 2024 OOF RMSE: 1.2162758724070044
======================================================================
Running CatBoost v4 median seed: 3407
======================================================================
0:	learn: 2.1873829	test: 2.1984093	best: 2.1984093 (0)	total: 11.6ms	remaining: 17.3s
200:	learn: 1.2201468	test: 1.2368588	best: 1.2368588 (200)	total: 2.35s	remaining: 15.2s
400:	learn: 1.1994233	test: 1.2251128	best: 1.2251028 (399)	total: 4.71s	remaining: 12.9s
600:	learn: 1.1864906	test: 1.2226665	best: 1.2226665 (600)	total: 7.06s	remaining: 10.6s
800:	learn: 1.1766592	test: 1.2220467	best: 1.2220159 (781)	total: 9.44s	remaining: 8.24s
1000:	learn: 1.1668271	test: 1.2217488	best: 1.2216416 (938)	total: 11.8s	remaining: 5.9s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.221641583
bestIteration = 938

Shrink model to first 939 iterations.
Seed 3407 - Fold 1 RMSE: 1.221641583810969
0:	learn: 2.1915421	test: 2.1823613	best: 2.1823613 (0)	total: 10.2ms	remaining: 15.3s
200:	learn: 1.2220867	test: 1.2308800	best: 1.2308800 (200)	total: 2.67s	remaining: 17.2s
400:	learn: 1.2006889	test: 1.2197053	best: 1.2197053 (400)	total: 5.21s	remaining: 14.3s
600:	learn: 1.1880645	test: 1.2176885	best: 1.2176885 (600)	total: 7.62s	remaining: 11.4s
800:	learn: 1.1773320	test: 1.2168820	best: 1.2168680 (761)	total: 10.1s	remaining: 8.83s
1000:	learn: 1.1671256	test: 1.2168338	best: 1.2165890 (903)	total: 12.6s	remaining: 6.27s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.216589049
bestIteration = 903

Shrink model to first 904 iterations.
Seed 3407 - Fold 2 RMSE: 1.2165890501523393
0:	learn: 2.1900082	test: 2.1888281	best: 2.1888281 (0)	total: 11.3ms	remaining: 16.9s
200:	learn: 1.2255455	test: 1.2175453	best: 1.2175453 (200)	total: 2.45s	remaining: 15.8s
400:	learn: 1.2034456	test: 1.2043096	best: 1.2043096 (400)	total: 4.8s	remaining: 13.2s
600:	learn: 1.1908272	test: 1.2022502	best: 1.2022502 (600)	total: 7.16s	remaining: 10.7s
800:	learn: 1.1801796	test: 1.2015101	best: 1.2014635 (790)	total: 9.56s	remaining: 8.34s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.201305517
bestIteration = 872

Shrink model to first 873 iterations.
Seed 3407 - Fold 3 RMSE: 1.2013055165684559
0:	learn: 2.1929045	test: 2.1830731	best: 2.1830731 (0)	total: 12.4ms	remaining: 18.6s
200:	learn: 1.2241210	test: 1.2245682	best: 1.2245682 (200)	total: 2.66s	remaining: 17.2s
400:	learn: 1.2020211	test: 1.2138959	best: 1.2138959 (400)	total: 5.09s	remaining: 13.9s
600:	learn: 1.1895400	test: 1.2120500	best: 1.2120146 (561)	total: 7.44s	remaining: 11.1s
800:	learn: 1.1791137	test: 1.2115358	best: 1.2114741 (783)	total: 9.84s	remaining: 8.58s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.211403411
bestIteration = 812

Shrink model to first 813 iterations.
Seed 3407 - Fold 4 RMSE: 1.211403410609949
0:	learn: 2.1876946	test: 2.1974876	best: 2.1974876 (0)	total: 9.83ms	remaining: 14.7s
200:	learn: 1.2187449	test: 1.2464122	best: 1.2464122 (200)	total: 2.4s	remaining: 15.5s
400:	learn: 1.1969002	test: 1.2347332	best: 1.2347332 (400)	total: 4.78s	remaining: 13.1s
600:	learn: 1.1836337	test: 1.2326919	best: 1.2326395 (593)	total: 7.2s	remaining: 10.8s
800:	learn: 1.1737413	test: 1.2321060	best: 1.2321060 (800)	total: 9.57s	remaining: 8.35s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.231986458
bestIteration = 829

Shrink model to first 830 iterations.
Seed 3407 - Fold 5 RMSE: 1.2319864586705316
Seed 3407 Mean RMSE: 1.216585203962449
Seed 3407 OOF RMSE: 1.2166281994076518
======================================================================
CatBoost v4 Median 3 Seed Scores
======================================================================
Seed 42
Mean RMSE: 1.2166311454712493
OOF RMSE: 1.216668695226295

Seed 2024
Mean RMSE: 1.2162387755303965
OOF RMSE: 1.2162758724070044

Seed 3407
Mean RMSE: 1.216585203962449
OOF RMSE: 1.2166281994076518

Eski v3 Median 3-seed CatBoost OOF: 1.2153365137912049
v4 Median 3-seed CatBoost OOF: 1.2156998421836094

# Deney 22B - HGB and LightGBM with Feature v4

In [ ]:
oof_hgb_v4, test_hgb_v4, scores_hgb_v4 = get_hgb_oof_dense(
    X_fe_v4,
    y,
    X_test_fe_v4,
    cv
)

oof_lgbm_v4, test_lgbm_v4, scores_lgbm_v4 = get_lgbm_oof(
    X_fe_v4,
    y,
    X_test_fe_v4,
    cv
)

HGB Fold 1 RMSE: 1.2279271466210597
HGB Fold 2 RMSE: 1.2298488684480025
HGB Fold 3 RMSE: 1.2173938338304113
HGB Fold 4 RMSE: 1.2260993255870685
HGB Fold 5 RMSE: 1.2453073298043114
HGB Mean RMSE: 1.2293153008581705
HGB OOF RMSE: 1.2293486865124543
LightGBM Fold 1 RMSE: 1.233485237452183
LightGBM Fold 2 RMSE: 1.2333902266646217
LightGBM Fold 3 RMSE: 1.2195575929910218
LightGBM Fold 4 RMSE: 1.2282222267143248
LightGBM Fold 5 RMSE: 1.2492219909564557
LightGBM Mean RMSE: 1.2327754549557215
LightGBM OOF RMSE: 1.2328133212900187

# Deney 22C - v4 Median 3 Seed CatBoost + HGB + LGBM Blend

In [ ]:
from scipy.optimize import minimize

oof_matrix_v4_median_3 = np.column_stack([
    oof_cat_v4_median_3,
    oof_hgb_v4,
    oof_lgbm_v4
])

test_matrix_v4_median_3 = np.column_stack([
    test_cat_v4_median_3,
    test_hgb_v4,
    test_lgbm_v4
])

model_names_v4_median_3 = [
    "CatBoost v4 Median 3 Seed",
    "HGB v4",
    "LightGBM v4"
]

def blend_rmse_v4_median_3(weights):
    preds = oof_matrix_v4_median_3 @ weights
    return rmse(y, preds)

n_models = oof_matrix_v4_median_3.shape[1]
initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result_v4_median_3 = minimize(
    blend_rmse_v4_median_3,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights_v4_median_3 = result_v4_median_3.x
best_oof_preds_v4_median_3 = oof_matrix_v4_median_3 @ best_weights_v4_median_3
best_test_preds_v4_median_3 = test_matrix_v4_median_3 @ best_weights_v4_median_3

print("Optimization success:", result_v4_median_3.success)
print("Best weights:")

for name, weight in zip(model_names_v4_median_3, best_weights_v4_median_3):
    print(f"{name}: {weight:.6f}")

print("Eski en iyi v3 Median 5-seed blend OOF:", rmse(y, best_oof_preds_median_5))
print("v4 Median 3-seed blend OOF:", rmse(y, best_oof_preds_v4_median_3))

Optimization success: True
Best weights:
CatBoost v4 Median 3 Seed: 0.934510
HGB v4: 0.055261
LightGBM v4: 0.010229
Eski en iyi v3 Median 5-seed blend OOF: 1.215180348002664
v4 Median 3-seed blend OOF: 1.215635479269378

# Deney 23 - Target Encoding for LightGBM
### Feature set: X_fe_v3 / X_test_fe_v3

In [ ]:
import numpy as np
import pandas as pd

from lightgbm import LGBMRegressor
from category_encoders import TargetEncoder

def get_lgbm_target_encoding_oof(X_fe, y, X_test_fe, cv):
    cat_cols = X_fe.select_dtypes(include="object").columns.tolist()
    num_cols = X_fe.select_dtypes(include=np.number).columns.tolist()

    oof_preds = np.zeros(len(X_fe))
    test_preds = np.zeros(len(X_test_fe))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_fe), 1):
        X_train_fold = X_fe.iloc[train_idx].copy()
        X_val_fold = X_fe.iloc[val_idx].copy()
        X_test_fold = X_test_fe.copy()

        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        # ----------------------------
        # 1. Categorical missing
        # ----------------------------
        for col in cat_cols:
            X_train_fold[col] = X_train_fold[col].fillna("Bilinmiyor").astype(str)
            X_val_fold[col] = X_val_fold[col].fillna("Bilinmiyor").astype(str)
            X_test_fold[col] = X_test_fold[col].fillna("Bilinmiyor").astype(str)

        # ----------------------------
        # 2. Numeric median imputation
        # Sadece train fold'dan öğreniyoruz
        # ----------------------------
        medians = X_train_fold[num_cols].median()

        X_train_fold[num_cols] = X_train_fold[num_cols].fillna(medians)
        X_val_fold[num_cols] = X_val_fold[num_cols].fillna(medians)
        X_test_fold[num_cols] = X_test_fold[num_cols].fillna(medians)

        # ----------------------------
        # 3. Target Encoding
        # Sadece train fold üzerinde fit edilir
        # ----------------------------
        encoder = TargetEncoder(
            cols=cat_cols,
            smoothing=10.0
        )

        X_train_enc = encoder.fit_transform(X_train_fold, y_train_fold)
        X_val_enc = encoder.transform(X_val_fold)
        X_test_enc = encoder.transform(X_test_fold)

        model = LGBMRegressor(
            objective="regression",
            n_estimators=2000,
            learning_rate=0.025,
            num_leaves=31,
            max_depth=-1,
            min_child_samples=25,
            subsample=0.9,
            colsample_bytree=0.9,
            reg_alpha=0.05,
            reg_lambda=0.1,
            random_state=42,
            n_jobs=-1,
            verbose=-1
        )

        model.fit(X_train_enc, y_train_fold)

        val_pred = model.predict(X_val_enc)
        test_pred = model.predict(X_test_enc)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"LightGBM TargetEncoding Fold {fold} RMSE:", fold_rmse)

    print("LightGBM TargetEncoding Fold RMSE:", fold_scores)
    print("LightGBM TargetEncoding Mean RMSE:", np.mean(fold_scores))
    print("LightGBM TargetEncoding OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores


oof_lgbm_te_v3, test_lgbm_te_v3, scores_lgbm_te_v3 = get_lgbm_target_encoding_oof(
    X_fe_v3,
    y,
    X_test_fe_v3,
    cv
)

LightGBM TargetEncoding Fold 1 RMSE: 1.2320133522655294
LightGBM TargetEncoding Fold 2 RMSE: 1.232165919212812
LightGBM TargetEncoding Fold 3 RMSE: 1.2165743791157237
LightGBM TargetEncoding Fold 4 RMSE: 1.2276290508535574
LightGBM TargetEncoding Fold 5 RMSE: 1.2479893559611543
LightGBM TargetEncoding Fold RMSE: [np.float64(1.2320133522655294), np.float64(1.232165919212812), np.float64(1.2165743791157237), np.float64(1.2276290508535574), np.float64(1.2479893559611543)]
LightGBM TargetEncoding Mean RMSE: 1.2312744114817555
LightGBM TargetEncoding OOF RMSE: 1.2313158402004625

# Deney 23B - CatBoost Median 5 Seed + HGB v3 + LightGBM Target Encoding Blend

In [ ]:
from scipy.optimize import minimize

oof_matrix_te = np.column_stack([
    oof_cat_median_5,
    oof_hgb_v3,
    oof_lgbm_te_v3
])

test_matrix_te = np.column_stack([
    test_cat_median_5,
    test_hgb_v3,
    test_lgbm_te_v3
])

model_names_te = [
    "CatBoost v3 Median 5 Seed",
    "HGB v3",
    "LightGBM TargetEncoding v3"
]

def blend_rmse_te(weights):
    preds = oof_matrix_te @ weights
    return rmse(y, preds)

n_models = oof_matrix_te.shape[1]
initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result_te = minimize(
    blend_rmse_te,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights_te = result_te.x
best_oof_preds_te = oof_matrix_te @ best_weights_te
best_test_preds_te = test_matrix_te @ best_weights_te

print("Optimization success:", result_te.success)
print("Best weights:")

for name, weight in zip(model_names_te, best_weights_te):
    print(f"{name}: {weight:.6f}")

print("Eski en iyi Median 5-seed blend OOF:", rmse(y, best_oof_preds_median_5))
print("Target Encoding blend OOF:", rmse(y, best_oof_preds_te))

Optimization success: True
Best weights:
CatBoost v3 Median 5 Seed: 0.915056
HGB v3: 0.037511
LightGBM TargetEncoding v3: 0.047434
Eski en iyi Median 5-seed blend OOF: 1.215180348002664
Target Encoding blend OOF: 1.2151543285184772

# Deney 23C - XGBoost with Out-of-Fold Target Encoding
### Feature set: X_fe_v3 / X_test_fe_v3

In [ ]:
import numpy as np
import pandas as pd

from xgboost import XGBRegressor
from category_encoders import TargetEncoder

def get_xgb_target_encoding_oof(X_fe, y, X_test_fe, cv):
    cat_cols = X_fe.select_dtypes(include="object").columns.tolist()
    num_cols = X_fe.select_dtypes(include=np.number).columns.tolist()

    oof_preds = np.zeros(len(X_fe))
    test_preds = np.zeros(len(X_test_fe))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_fe), 1):
        X_train_fold = X_fe.iloc[train_idx].copy()
        X_val_fold = X_fe.iloc[val_idx].copy()
        X_test_fold = X_test_fe.copy()

        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        # Categorical missing
        for col in cat_cols:
            X_train_fold[col] = X_train_fold[col].fillna("Bilinmiyor").astype(str)
            X_val_fold[col] = X_val_fold[col].fillna("Bilinmiyor").astype(str)
            X_test_fold[col] = X_test_fold[col].fillna("Bilinmiyor").astype(str)

        # Numeric median imputation - sadece train fold üzerinden
        medians = X_train_fold[num_cols].median()

        X_train_fold[num_cols] = X_train_fold[num_cols].fillna(medians)
        X_val_fold[num_cols] = X_val_fold[num_cols].fillna(medians)
        X_test_fold[num_cols] = X_test_fold[num_cols].fillna(medians)

        # Target Encoding - sadece train fold üzerinde fit
        encoder = TargetEncoder(
            cols=cat_cols,
            smoothing=10.0
        )

        X_train_enc = encoder.fit_transform(X_train_fold, y_train_fold)
        X_val_enc = encoder.transform(X_val_fold)
        X_test_enc = encoder.transform(X_test_fold)

        model = XGBRegressor(
            objective="reg:squarederror",
            eval_metric="rmse",
            n_estimators=1500,
            learning_rate=0.03,
            max_depth=5,
            min_child_weight=3,
            subsample=0.9,
            colsample_bytree=0.9,
            reg_alpha=0.05,
            reg_lambda=1.0,
            random_state=42,
            n_jobs=-1,
            tree_method="hist"
        )

        model.fit(X_train_enc, y_train_fold)

        val_pred = model.predict(X_val_enc)
        test_pred = model.predict(X_test_enc)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"XGBoost TargetEncoding Fold {fold} RMSE:", fold_rmse)

    print("XGBoost TargetEncoding Fold RMSE:", fold_scores)
    print("XGBoost TargetEncoding Mean RMSE:", np.mean(fold_scores))
    print("XGBoost TargetEncoding OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores


oof_xgb_te_v3, test_xgb_te_v3, scores_xgb_te_v3 = get_xgb_target_encoding_oof(
    X_fe_v3,
    y,
    X_test_fe_v3,
    cv
)

XGBoost TargetEncoding Fold 1 RMSE: 1.2303676018166907
XGBoost TargetEncoding Fold 2 RMSE: 1.2307845924687602
XGBoost TargetEncoding Fold 3 RMSE: 1.2165291194076377
XGBoost TargetEncoding Fold 4 RMSE: 1.2268646225831656
XGBoost TargetEncoding Fold 5 RMSE: 1.2445348064979067
XGBoost TargetEncoding Fold RMSE: [np.float64(1.2303676018166907), np.float64(1.2307845924687602), np.float64(1.2165291194076377), np.float64(1.2268646225831656), np.float64(1.2445348064979067)]
XGBoost TargetEncoding Mean RMSE: 1.2298161485548322
XGBoost TargetEncoding OOF RMSE: 1.229848928426275

# Deney 23D - CatBoost Median 5 Seed + HGB + LGBM TE + XGB TE Blend

In [ ]:
from scipy.optimize import minimize

oof_matrix_te_xgb = np.column_stack([
    oof_cat_median_5,
    oof_hgb_v3,
    oof_lgbm_te_v3,
    oof_xgb_te_v3
])

test_matrix_te_xgb = np.column_stack([
    test_cat_median_5,
    test_hgb_v3,
    test_lgbm_te_v3,
    test_xgb_te_v3
])

model_names_te_xgb = [
    "CatBoost v3 Median 5 Seed",
    "HGB v3",
    "LightGBM TargetEncoding v3",
    "XGBoost TargetEncoding v3"
]

def blend_rmse_te_xgb(weights):
    preds = oof_matrix_te_xgb @ weights
    return rmse(y, preds)

n_models = oof_matrix_te_xgb.shape[1]
initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result_te_xgb = minimize(
    blend_rmse_te_xgb,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights_te_xgb = result_te_xgb.x
best_oof_preds_te_xgb = oof_matrix_te_xgb @ best_weights_te_xgb
best_test_preds_te_xgb = test_matrix_te_xgb @ best_weights_te_xgb

print("Optimization success:", result_te_xgb.success)
print("Best weights:")

for name, weight in zip(model_names_te_xgb, best_weights_te_xgb):
    print(f"{name}: {weight:.6f}")

print("Eski en iyi TE blend OOF:", rmse(y, best_oof_preds_te))
print("XGB TE dahil blend OOF:", rmse(y, best_oof_preds_te_xgb))

Optimization success: True
Best weights:
CatBoost v3 Median 5 Seed: 0.916096
HGB v3: 0.034082
LightGBM TargetEncoding v3: 0.049822
XGBoost TargetEncoding v3: 0.000000
Eski en iyi TE blend OOF: 1.2151543285184772
XGB TE dahil blend OOF: 1.215154529218457

# Deney 24 - Residual Boosting

In [ ]:
import numpy as np
import pandas as pd

from lightgbm import LGBMRegressor
from category_encoders import TargetEncoder

def get_lgbm_residual_oof(X_fe, y, X_test_fe, cv, base_oof, base_test):
    cat_cols = X_fe.select_dtypes(include="object").columns.tolist()
    num_cols = X_fe.select_dtypes(include=np.number).columns.tolist()

    residual_target = y - base_oof

    oof_residual_preds = np.zeros(len(X_fe))
    test_residual_preds = np.zeros(len(X_test_fe))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_fe), 1):
        X_train_fold = X_fe.iloc[train_idx].copy()
        X_val_fold = X_fe.iloc[val_idx].copy()
        X_test_fold = X_test_fe.copy()

        y_train_residual = residual_target.iloc[train_idx]
        y_val_true = y.iloc[val_idx]
        base_val_pred = base_oof[val_idx]

        # Categorical missing
        for col in cat_cols:
            X_train_fold[col] = X_train_fold[col].fillna("Bilinmiyor").astype(str)
            X_val_fold[col] = X_val_fold[col].fillna("Bilinmiyor").astype(str)
            X_test_fold[col] = X_test_fold[col].fillna("Bilinmiyor").astype(str)

        # Numeric median imputation, only train fold
        medians = X_train_fold[num_cols].median()

        X_train_fold[num_cols] = X_train_fold[num_cols].fillna(medians)
        X_val_fold[num_cols] = X_val_fold[num_cols].fillna(medians)
        X_test_fold[num_cols] = X_test_fold[num_cols].fillna(medians)

        # Target encoding residual hedefe göre yapılır
        encoder = TargetEncoder(
            cols=cat_cols,
            smoothing=10.0
        )

        X_train_enc = encoder.fit_transform(X_train_fold, y_train_residual)
        X_val_enc = encoder.transform(X_val_fold)
        X_test_enc = encoder.transform(X_test_fold)

        model = LGBMRegressor(
            objective="regression",
            n_estimators=1500,
            learning_rate=0.02,
            num_leaves=31,
            max_depth=-1,
            min_child_samples=30,
            subsample=0.85,
            colsample_bytree=0.85,
            reg_alpha=0.1,
            reg_lambda=0.3,
            random_state=42,
            n_jobs=-1,
            verbose=-1
        )

        model.fit(X_train_enc, y_train_residual)

        val_residual_pred = model.predict(X_val_enc)
        test_residual_pred = model.predict(X_test_enc)

        oof_residual_preds[val_idx] = val_residual_pred
        test_residual_preds += test_residual_pred / cv.get_n_splits()

        final_val_pred = base_val_pred + val_residual_pred
        fold_rmse = rmse(y_val_true, final_val_pred)
        fold_scores.append(fold_rmse)

        print(f"LGBM Residual Fold {fold} Final RMSE:", fold_rmse)

    final_oof_preds = base_oof + oof_residual_preds
    final_test_preds = base_test + test_residual_preds

    print("LGBM Residual Fold RMSE:", fold_scores)
    print("LGBM Residual Mean RMSE:", np.mean(fold_scores))
    print("LGBM Residual Final OOF RMSE:", rmse(y, final_oof_preds))

    return final_oof_preds, final_test_preds, oof_residual_preds, test_residual_preds, fold_scores


oof_lgbm_residual_final, test_lgbm_residual_final, oof_lgbm_residual, test_lgbm_residual, scores_lgbm_residual = get_lgbm_residual_oof(
    X_fe_v3,
    y,
    X_test_fe_v3,
    cv,
    oof_cat_median_5,
    test_cat_median_5
)

LGBM Residual Fold 1 Final RMSE: 1.232101101786624
LGBM Residual Fold 2 Final RMSE: 1.2318187355529808
LGBM Residual Fold 3 Final RMSE: 1.2171533391009042
LGBM Residual Fold 4 Final RMSE: 1.2260492036337334
LGBM Residual Fold 5 Final RMSE: 1.246521112062133
LGBM Residual Fold RMSE: [np.float64(1.232101101786624), np.float64(1.2318187355529808), np.float64(1.2171533391009042), np.float64(1.2260492036337334), np.float64(1.246521112062133)]
LGBM Residual Mean RMSE: 1.230728698427275
LGBM Residual Final OOF RMSE: 1.2307659652196403

# Deney 24B - Add Residual Model to Existing Best Blend

In [ ]:

from scipy.optimize import minimize

oof_matrix_residual_blend = np.column_stack([
    oof_cat_median_5,
    oof_hgb_v3,
    oof_lgbm_te_v3,
    oof_lgbm_residual_final
])

test_matrix_residual_blend = np.column_stack([
    test_cat_median_5,
    test_hgb_v3,
    test_lgbm_te_v3,
    test_lgbm_residual_final
])

model_names_residual_blend = [
    "CatBoost v3 Median 5 Seed",
    "HGB v3",
    "LightGBM TargetEncoding v3",
    "CatBoost + LGBM Residual Final"
]

def blend_rmse_residual(weights):
    preds = oof_matrix_residual_blend @ weights
    return rmse(y, preds)

n_models = oof_matrix_residual_blend.shape[1]
initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result_residual_blend = minimize(
    blend_rmse_residual,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights_residual_blend = result_residual_blend.x
best_oof_preds_residual_blend = oof_matrix_residual_blend @ best_weights_residual_blend
best_test_preds_residual_blend = test_matrix_residual_blend @ best_weights_residual_blend

print("Optimization success:", result_residual_blend.success)
print("Best weights:")

for name, weight in zip(model_names_residual_blend, best_weights_residual_blend):
    print(f"{name}: {weight:.6f}")

print("Eski en iyi TE blend OOF:", rmse(y, best_oof_preds_te))
print("Residual dahil blend OOF:", rmse(y, best_oof_preds_residual_blend))

Optimization success: True
Best weights:
CatBoost v3 Median 5 Seed: 0.918982
HGB v3: 0.034794
LightGBM TargetEncoding v3: 0.046223
CatBoost + LGBM Residual Final: 0.000000
Eski en iyi TE blend OOF: 1.2151543285184772
Residual dahil blend OOF: 1.2151545065123193

# Deney 25 - Ridge Stacking on OOF Predictions

In [ ]:
import numpy as np
import pandas as pd

from sklearn.linear_model import Ridge, RidgeCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold

# ------------------------------------------------------------
# 1. Elimizde mevcut olan OOF/test tahminlerini otomatik topla
# ------------------------------------------------------------

stack_oof_list = []
stack_test_list = []
stack_model_names = []

def add_stack_model(name, oof_var_name, test_var_name):
    if oof_var_name in globals() and test_var_name in globals():
        oof_values = globals()[oof_var_name]
        test_values = globals()[test_var_name]

        if len(oof_values) == len(y) and len(test_values) == len(test_ids):
            stack_oof_list.append(oof_values)
            stack_test_list.append(test_values)
            stack_model_names.append(name)
            print(f"Added: {name}")
        else:
            print(f"Skipped {name}: length mismatch")
    else:
        print(f"Skipped {name}: variable not found")


add_stack_model(
    "CatBoost v3 Median 5 Seed",
    "oof_cat_median_5",
    "test_cat_median_5"
)

add_stack_model(
    "HGB v3",
    "oof_hgb_v3",
    "test_hgb_v3"
)

add_stack_model(
    "LightGBM TargetEncoding v3",
    "oof_lgbm_te_v3",
    "test_lgbm_te_v3"
)

add_stack_model(
    "XGBoost TargetEncoding v3",
    "oof_xgb_te_v3",
    "test_xgb_te_v3"
)

add_stack_model(
    "LightGBM v3",
    "oof_lgbm_v3",
    "test_lgbm_v3"
)

add_stack_model(
    "CatBoost + LGBM Residual Final",
    "oof_lgbm_residual_final",
    "test_lgbm_residual_final"
)

X_stack_oof = np.column_stack(stack_oof_list)
X_stack_test = np.column_stack(stack_test_list)

print("Stacking models:", stack_model_names)
print("X_stack_oof:", X_stack_oof.shape)
print("X_stack_test:", X_stack_test.shape)

# ------------------------------------------------------------
# 2. Meta model için OOF değerlendirme
# Burada Ridge'i de OOF mantığıyla test ediyoruz.
# ------------------------------------------------------------

meta_cv = KFold(n_splits=5, shuffle=True, random_state=42)

alphas = np.logspace(-4, 4, 30)

ridge_oof_preds = np.zeros(len(y))
ridge_fold_scores = []
ridge_fold_alphas = []
ridge_fold_coefs = []

for fold, (train_idx, val_idx) in enumerate(meta_cv.split(X_stack_oof), 1):
    X_train_meta = X_stack_oof[train_idx]
    X_val_meta = X_stack_oof[val_idx]

    y_train_meta = y.iloc[train_idx]
    y_val_meta = y.iloc[val_idx]

    ridge_model = Pipeline(steps=[
        ("scaler", StandardScaler()),
        ("ridge", RidgeCV(alphas=alphas))
    ])

    ridge_model.fit(X_train_meta, y_train_meta)

    val_pred = ridge_model.predict(X_val_meta)
    ridge_oof_preds[val_idx] = val_pred

    fold_rmse = rmse(y_val_meta, val_pred)
    ridge_fold_scores.append(fold_rmse)

    best_alpha = ridge_model.named_steps["ridge"].alpha_
    coefs = ridge_model.named_steps["ridge"].coef_

    ridge_fold_alphas.append(best_alpha)
    ridge_fold_coefs.append(coefs)

    print(f"Ridge Stacking Fold {fold} RMSE:", fold_rmse)
    print(f"Fold {fold} alpha:", best_alpha)

print("Ridge Stacking Fold RMSE:", ridge_fold_scores)
print("Ridge Stacking Mean RMSE:", np.mean(ridge_fold_scores))
print("Ridge Stacking OOF RMSE:", rmse(y, ridge_oof_preds))



if "best_oof_preds_te" in globals():
    print("Current best TE blend OOF:", rmse(y, best_oof_preds_te))

if "best_oof_preds_median_5" in globals():
    print("Median 5-seed blend OOF:", rmse(y, best_oof_preds_median_5))



coef_df = pd.DataFrame(
    ridge_fold_coefs,
    columns=stack_model_names
)

print("\nAverage Ridge coefficients:")
display(coef_df.mean().sort_values(ascending=False))

print("\nFold alphas:")
print(ridge_fold_alphas)


final_ridge_model = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("ridge", RidgeCV(alphas=alphas))
])

final_ridge_model.fit(X_stack_oof, y)

best_oof_preds_ridge_stack = ridge_oof_preds
best_test_preds_ridge_stack = final_ridge_model.predict(X_stack_test)

best_test_preds_ridge_stack = np.clip(best_test_preds_ridge_stack, 0, 10)

print("\nFinal Ridge alpha:", final_ridge_model.named_steps["ridge"].alpha_)
print("Final Ridge coefficients:")

final_coef_df = pd.DataFrame({
    "model": stack_model_names,
    "coef": final_ridge_model.named_steps["ridge"].coef_
}).sort_values("coef", ascending=False)

display(final_coef_df)

print("Ridge stacked test prediction summary:")
print(pd.Series(best_test_preds_ridge_stack).describe())

Added: CatBoost v3 Median 5 Seed
Added: HGB v3
Added: LightGBM TargetEncoding v3
Added: XGBoost TargetEncoding v3
Added: LightGBM v3
Added: CatBoost + LGBM Residual Final
Stacking models: ['CatBoost v3 Median 5 Seed', 'HGB v3', 'LightGBM TargetEncoding v3', 'XGBoost TargetEncoding v3', 'LightGBM v3', 'CatBoost + LGBM Residual Final']
X_stack_oof: (56000, 6)
X_stack_test: (24000, 6)
Ridge Stacking Fold 1 RMSE: 1.2192282930908693
Fold 1 alpha: 0.7278953843983146
Ridge Stacking Fold 2 RMSE: 1.2137686422510456
Fold 2 alpha: 0.7278953843983146
Ridge Stacking Fold 3 RMSE: 1.198562222003559
Fold 3 alpha: 0.7278953843983146
Ridge Stacking Fold 4 RMSE: 1.2064136993627548
Fold 4 alpha: 0.7278953843983146
Ridge Stacking Fold 5 RMSE: 1.22889688671241
Fold 5 alpha: 0.7278953843983146
Ridge Stacking Fold RMSE: [np.float64(1.2192282930908693), np.float64(1.2137686422510456), np.float64(1.198562222003559), np.float64(1.2064136993627548), np.float64(1.22889688671241)]
Ridge Stacking Mean RMSE: 1.2133739486841277
Ridge Stacking OOF RMSE: 1.2134187174904558
Current best TE blend OOF: 1.2151543285184772
Median 5-seed blend OOF: 1.215180348002664

Average Ridge coefficients:

CatBoost v3 Median 5 Seed         2.389292
LightGBM v3                       0.283433
LightGBM TargetEncoding v3        0.187199
XGBoost TargetEncoding v3         0.091384
HGB v3                           -0.112863
CatBoost + LGBM Residual Final   -0.966725
dtype: float64

Fold alphas:
[0.7278953843983146, 0.7278953843983146, 0.7278953843983146, 0.7278953843983146, 0.7278953843983146]

Final Ridge alpha: 0.7278953843983146
Final Ridge coefficients:

                            model      coef
0       CatBoost v3 Median 5 Seed  2.392633
4                     LightGBM v3  0.283836
2      LightGBM TargetEncoding v3  0.187594
3       XGBoost TargetEncoding v3  0.090863
1                          HGB v3 -0.114132
5  CatBoost + LGBM Residual Final -0.969080

Ridge stacked test prediction summary:
count    24000.000000
mean         5.939449
std          1.870360
min          0.000000
25%          4.635793
50%          6.051575
75%          7.333041
max         10.000000
dtype: float64

In [ ]:
submission_exp25_ridge = pd.DataFrame({
    "id": test_ids,
    TARGET: best_test_preds_ridge_stack
})

submission_exp25_ridge[TARGET] = submission_exp25_ridge[TARGET].clip(0, 10)

print(submission_exp25_ridge.shape)
print(submission_exp25_ridge.head())
print(submission_exp25_ridge[TARGET].describe())

submission_exp25_ridge.to_csv("submission_exp25_ridge_stacking.csv", index=False)

(24000, 2)
   id  bilissel_performans_skoru
0   1                   6.035980
1   2                   6.723272
2   3                   2.960330
3   4                   7.136152
4   5                   3.638989
count    24000.000000
mean         5.939449
std          1.870360
min          0.000000
25%          4.635793
50%          6.051575
75%          7.333041
max         10.000000
Name: bilissel_performans_skoru, dtype: float64

In [ ]:
import pandas as pd
import numpy as np

TARGET = "bilissel_performans_skoru"

In [ ]:
import pandas as pd
import numpy as np

TARGET = "bilissel_performans_skoru"

exp20e = pd.read_csv("submission_exp20e_v3_5seed_blend.csv")

print("exp20e public best prediction:")
print(exp20e[TARGET].describe())

print("\nexp23b te blend prediction:")

submission_exp23b_te_blend = pd.DataFrame({
    "id": exp20e["id"],
    TARGET: best_test_preds_te
})

submission_exp23b_te_blend[TARGET] = submission_exp23b_te_blend[TARGET].clip(0, 10)

print(submission_exp23b_te_blend[TARGET].describe())

diff = submission_exp23b_te_blend[TARGET].values - exp20e[TARGET].values

print("\nDifference exp23b - exp20e:")
print(pd.Series(diff).describe())

print("\nCorrelation:")
print(np.corrcoef(exp20e[TARGET].values, submission_exp23b_te_blend[TARGET].values)[0, 1])

exp20e public best prediction:
count    24000.000000
mean         5.936977
std          1.862729
min          0.000000
25%          4.641429
50%          6.044348
75%          7.327849
max         10.000000
Name: bilissel_performans_skoru, dtype: float64

exp23b te blend prediction:
count    24000.000000
mean         5.935936
std          1.865624
min          0.000000
25%          4.641019
50%          6.046583
75%          7.325603
max         10.000000
Name: bilissel_performans_skoru, dtype: float64

Difference exp23b - exp20e:
count    24000.000000
mean        -0.001042
std          0.034862
min         -0.416018
25%         -0.019370
50%         -0.002413
75%          0.015080
max          0.378444
dtype: float64

Correlation:
0.9998263421694981

# Deney 26 - Target Mechanism Based Feature Engineering

In [ ]:
# ============================================================
# CatBoost OOF with Numeric Median Imputation
# Kullanım: v3 / v5 gibi feature setleriyle çalışır
# ============================================================

from catboost import CatBoostRegressor
import numpy as np

def get_catboost_oof_with_seed_median(X_fe, y, X_test_fe, cv, seed):
    X_cb = X_fe.copy()
    X_test_cb = X_test_fe.copy()

    cat_cols = X_cb.select_dtypes(include="object").columns.tolist()
    num_cols = X_cb.select_dtypes(include=np.number).columns.tolist()


    for col in cat_cols:
        X_cb[col] = X_cb[col].fillna("Bilinmiyor").astype(str)
        X_test_cb[col] = X_test_cb[col].fillna("Bilinmiyor").astype(str)

    cat_features_idx = [X_cb.columns.get_loc(col) for col in cat_cols]

    oof_preds = np.zeros(len(X_cb))
    test_preds = np.zeros(len(X_test_cb))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_cb), 1):
        X_train_fold = X_cb.iloc[train_idx].copy()
        X_val_fold = X_cb.iloc[val_idx].copy()

        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        X_test_fold = X_test_cb.copy()

        medians = X_train_fold[num_cols].median()

        X_train_fold[num_cols] = X_train_fold[num_cols].fillna(medians)
        X_val_fold[num_cols] = X_val_fold[num_cols].fillna(medians)
        X_test_fold[num_cols] = X_test_fold[num_cols].fillna(medians)

        model = CatBoostRegressor(
            loss_function="RMSE",
            eval_metric="RMSE",
            iterations=1500,
            learning_rate=0.035,
            depth=6,
            l2_leaf_reg=5,
            random_seed=seed,
            verbose=200,
            early_stopping_rounds=100
        )

        model.fit(
            X_train_fold,
            y_train_fold,
            cat_features=cat_features_idx,
            eval_set=(X_val_fold, y_val_fold),
            use_best_model=True
        )

        val_pred = model.predict(X_val_fold)
        test_pred = model.predict(X_test_fold)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"Seed {seed} - Fold {fold} RMSE:", fold_rmse)

    print(f"Seed {seed} Mean RMSE:", np.mean(fold_scores))
    print(f"Seed {seed} OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores

In [ ]:
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
import numpy as np

def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

cv = KFold(n_splits=5, shuffle=True, random_state=42)

In [ ]:
from pathlib import Path
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore", category=FutureWarning)

DATA_DIR = Path("data")

train = pd.read_csv(DATA_DIR / "train.csv")
test = pd.read_csv(DATA_DIR / "test_x.csv")

TARGET = "bilissel_performans_skoru"

X = train.drop(columns=[TARGET])
X_test = test.copy()
y = train[TARGET]

test_ids = test["id"]

print("Train:", train.shape)
print("Test:", test.shape)
print("X:", X.shape)
print("X_test:", X_test.shape)

Train: (56000, 24)
Test: (24000, 23)
X: (56000, 23)
X_test: (24000, 23)

In [ ]:
# ============================================================
# Feature v3
# v1 feature set + missing indicators + categorical interactions
# ============================================================

def prepare_features_v3(X, X_test):
    X_fe = X.copy()
    X_test_fe = X_test.copy()

    # --------------------------------------------------------
    # 1. Missing indicator'ları ekle
    # --------------------------------------------------------
    all_cols = X_fe.columns.tolist()

    for col in all_cols:
        if X_fe[col].isnull().any() or X_test_fe[col].isnull().any():
            X_fe[f"{col}_missing"] = X_fe[col].isnull().astype(int)
            X_test_fe[f"{col}_missing"] = X_test_fe[col].isnull().astype(int)

    # --------------------------------------------------------
    # 2. Log transform - v1'de işe yarayan dönüşüm
    # --------------------------------------------------------
    log_cols = [
        "uyku_oncesi_kafein_mg",
        "uyku_oncesi_ekran_suresi_dk"
    ]

    for col in log_cols:
        if col in X_fe.columns:
            X_fe[col] = np.log1p(X_fe[col])
            X_test_fe[col] = np.log1p(X_test_fe[col])

    def add_features(df):
        df = df.copy()

        # ----------------------------------------------------
        # v1'de işe yarayan feature'lar
        # ----------------------------------------------------
        if "stres_skoru" in df.columns and "gunluk_calisma_saati" in df.columns:
            df["stres_calisma_yuku"] = df["stres_skoru"] * df["gunluk_calisma_saati"]

        if "rem_yuzdesi" in df.columns and "derin_uyku_yuzdesi" in df.columns:
            df["uyku_kalitesi_orani"] = df["rem_yuzdesi"] + df["derin_uyku_yuzdesi"]

        if "gecelik_uyanma_sayisi" in df.columns and "uykuya_dalma_suresi_dk" in df.columns:
            df["uyku_bozulma_skoru"] = df["gecelik_uyanma_sayisi"] + df["uykuya_dalma_suresi_dk"]

        if "uyku_oncesi_ekran_suresi_dk" in df.columns and "uyku_oncesi_kafein_mg" in df.columns:
            df["dijital_kafein_yuku"] = (
                df["uyku_oncesi_ekran_suresi_dk"] * df["uyku_oncesi_kafein_mg"]
            )

        if "gunluk_adim_sayisi" in df.columns and "stres_skoru" in df.columns:
            df["aktivite_stres_orani"] = df["gunluk_adim_sayisi"] / (df["stres_skoru"] + 1)

        # ----------------------------------------------------
        # Kategorik interaction feature'lar
        # ----------------------------------------------------
        def safe_str_col(c):
            return df[c].fillna("Bilinmiyor").astype(str)

        if "meslek" in df.columns and "kronotip" in df.columns:
            df["meslek_kronotip"] = safe_str_col("meslek") + "_" + safe_str_col("kronotip")

        if "gun_tipi" in df.columns and "kronotip" in df.columns:
            df["gun_tipi_kronotip"] = safe_str_col("gun_tipi") + "_" + safe_str_col("kronotip")

        if "ruh_sagligi_durumu" in df.columns and "meslek" in df.columns:
            df["ruh_sagligi_meslek"] = safe_str_col("ruh_sagligi_durumu") + "_" + safe_str_col("meslek")

        if "cinsiyet" in df.columns and "kronotip" in df.columns:
            df["cinsiyet_kronotip"] = safe_str_col("cinsiyet") + "_" + safe_str_col("kronotip")

        return df

    X_fe = add_features(X_fe)
    X_test_fe = add_features(X_test_fe)

    return X_fe, X_test_fe

In [ ]:
X_fe_v3, X_test_fe_v3 = prepare_features_v3(X, X_test)

print("X_fe_v3:", X_fe_v3.shape)
print("X_test_fe_v3:", X_test_fe_v3.shape)

X_fe_v3: (56000, 38)
X_test_fe_v3: (24000, 38)

In [ ]:
# ============================================================
# Deney 26 - Feature v5
# Target mechanism based controlled interactions
# Base: feature v3
# ============================================================

def prepare_features_v5_target_mechanism(X, X_test):

    X_fe, X_test_fe = prepare_features_v3(X, X_test)

    def add_target_mechanism_features(df):
        df = df.copy()



        if "rem_yuzdesi" in df.columns and "derin_uyku_yuzdesi" in df.columns:
            df["toplam_kaliteli_uyku"] = df["rem_yuzdesi"] + df["derin_uyku_yuzdesi"]

        if "gecelik_uyanma_sayisi" in df.columns and "uykuya_dalma_suresi_dk" in df.columns:
            df["uyku_kesinti_yuku"] = (
                df["gecelik_uyanma_sayisi"] * 2
                + df["uykuya_dalma_suresi_dk"] / 5
            )

        if "stres_skoru" in df.columns and "gunluk_calisma_saati" in df.columns:
            df["zihinsel_yuk"] = (
                df["stres_skoru"] * 2
                + df["gunluk_calisma_saati"]
            )

        if (
            "stres_skoru" in df.columns
            and "gunluk_calisma_saati" in df.columns
            and "uyku_kesinti_yuku" in df.columns
        ):
            df["toplam_risk_yuku"] = (
                df["stres_skoru"] * 2
                + df["gunluk_calisma_saati"]
                + df["uyku_kesinti_yuku"]
            )

        if "toplam_kaliteli_uyku" in df.columns and "toplam_risk_yuku" in df.columns:
            df["net_bilissel_denge"] = (
                df["toplam_kaliteli_uyku"] - df["toplam_risk_yuku"]
            )

        if "toplam_kaliteli_uyku" in df.columns and "stres_skoru" in df.columns:
            df["uyku_stres_dengesi"] = (
                df["toplam_kaliteli_uyku"] / (df["stres_skoru"] + 1)
            )

        if "gunluk_adim_sayisi" in df.columns and "zihinsel_yuk" in df.columns:
            df["aktivite_zihinsel_yuk_dengesi"] = (
                df["gunluk_adim_sayisi"] / (df["zihinsel_yuk"] + 1)
            )



        def safe_str_col(c):
            return df[c].fillna("Bilinmiyor").astype(str)

        if "ruh_sagligi_durumu" in df.columns and "gun_tipi" in df.columns:
            df["ruh_sagligi_gun_tipi"] = (
                safe_str_col("ruh_sagligi_durumu")
                + "_"
                + safe_str_col("gun_tipi")
            )

        if "meslek" in df.columns and "gun_tipi" in df.columns:
            df["meslek_gun_tipi"] = (
                safe_str_col("meslek")
                + "_"
                + safe_str_col("gun_tipi")
            )

        if "ruh_sagligi_durumu" in df.columns and "kronotip" in df.columns:
            df["ruh_sagligi_kronotip"] = (
                safe_str_col("ruh_sagligi_durumu")
                + "_"
                + safe_str_col("kronotip")
            )


        if "gun_tipi" in df.columns:
            is_weekend = (safe_str_col("gun_tipi") == "Hafta sonu").astype(int)

            if "toplam_kaliteli_uyku" in df.columns:
                df["hafta_sonu_uyku_kalitesi"] = df["toplam_kaliteli_uyku"] * is_weekend

            if "stres_skoru" in df.columns:
                df["hafta_sonu_stres"] = df["stres_skoru"] * is_weekend

            if "gunluk_calisma_saati" in df.columns:
                df["hafta_sonu_calisma"] = df["gunluk_calisma_saati"] * is_weekend

        if "ruh_sagligi_durumu" in df.columns:
            mental = safe_str_col("ruh_sagligi_durumu")

            is_saglikli = (mental == "Saglikli").astype(int)
            is_depresyon = mental.str.contains("Depresyon", case=False, na=False).astype(int)
            is_anksiyete = mental.str.contains("Anksiyete", case=False, na=False).astype(int)

            if "stres_skoru" in df.columns:
                df["stres_saglikli"] = df["stres_skoru"] * is_saglikli
                df["stres_depresyon"] = df["stres_skoru"] * is_depresyon
                df["stres_anksiyete"] = df["stres_skoru"] * is_anksiyete

            if "uyku_kesinti_yuku" in df.columns:
                df["uyku_kesinti_depresyon"] = df["uyku_kesinti_yuku"] * is_depresyon
                df["uyku_kesinti_anksiyete"] = df["uyku_kesinti_yuku"] * is_anksiyete

        return df

    X_fe = add_target_mechanism_features(X_fe)
    X_test_fe = add_target_mechanism_features(X_test_fe)

    return X_fe, X_test_fe


X_fe_v5, X_test_fe_v5 = prepare_features_v5_target_mechanism(X, X_test)

print("X_fe_v5:", X_fe_v5.shape)
print("X_test_fe_v5:", X_test_fe_v5.shape)
print("New columns vs original:", X_fe_v5.shape[1] - X.shape[1])
print("New columns vs v3:", X_fe_v5.shape[1] - X_fe_v3.shape[1])

X_fe_v5: (56000, 56)
X_test_fe_v5: (24000, 56)
New columns vs original: 33
New columns vs v3: 18

In [ ]:
# ============================================================
# Deney 26A - CatBoost v5 + Median Imputation - 3 Seed
# ============================================================

seeds_v5_median_3 = [42, 2024, 3407]

cat_oof_list_v5_median_3 = []
cat_test_list_v5_median_3 = []
cat_seed_scores_v5_median_3 = {}

for seed in seeds_v5_median_3:
    print("=" * 70)
    print(f"Running CatBoost v5 median seed: {seed}")
    print("=" * 70)

    oof_seed, test_seed, scores_seed = get_catboost_oof_with_seed_median(
        X_fe_v5,
        y,
        X_test_fe_v5,
        cv,
        seed
    )

    cat_oof_list_v5_median_3.append(oof_seed)
    cat_test_list_v5_median_3.append(test_seed)

    cat_seed_scores_v5_median_3[seed] = {
        "fold_scores": scores_seed,
        "mean_rmse": np.mean(scores_seed),
        "oof_rmse": rmse(y, oof_seed)
    }

oof_cat_v5_median_3 = np.mean(cat_oof_list_v5_median_3, axis=0)
test_cat_v5_median_3 = np.mean(cat_test_list_v5_median_3, axis=0)

print("=" * 70)
print("CatBoost v5 Median 3 Seed Scores")
print("=" * 70)

for seed, result in cat_seed_scores_v5_median_3.items():
    print(f"Seed {seed}")
    print("Mean RMSE:", result["mean_rmse"])
    print("OOF RMSE:", result["oof_rmse"])
    print()

print("Eski v3 Median 3-seed CatBoost OOF:", rmse(y, oof_cat_median_3))
print("v5 Median 3-seed CatBoost OOF:", rmse(y, oof_cat_v5_median_3))

In [ ]:
print("v5 Median 3-seed CatBoost OOF:", rmse(y, oof_cat_v5_median_3))

for seed, result in cat_seed_scores_v5_median_3.items():
    print(seed, result["oof_rmse"])

v5 Median 3-seed CatBoost OOF: 1.215253009557772
42 1.2161361543543805
2024 1.2158896104864432
3407 1.216337008606478

# Deney 26B - CatBoost v5 + Median Imputation - 5 Seed

In [31]:
seeds_v5_median_5 = [42, 2024, 3407, 777, 999]

cat_oof_list_v5_median_5 = []
cat_test_list_v5_median_5 = []
cat_seed_scores_v5_median_5 = {}

for seed in seeds_v5_median_5:
    print("=" * 70)
    print(f"Running CatBoost v5 median seed: {seed}")
    print("=" * 70)

    oof_seed, test_seed, scores_seed = get_catboost_oof_with_seed_median(
        X_fe_v5,
        y,
        X_test_fe_v5,
        cv,
        seed
    )

    cat_oof_list_v5_median_5.append(oof_seed)
    cat_test_list_v5_median_5.append(test_seed)

    cat_seed_scores_v5_median_5[seed] = {
        "fold_scores": scores_seed,
        "mean_rmse": np.mean(scores_seed),
        "oof_rmse": rmse(y, oof_seed)
    }

oof_cat_v5_median_5 = np.mean(cat_oof_list_v5_median_5, axis=0)
test_cat_v5_median_5 = np.mean(cat_test_list_v5_median_5, axis=0)

print("=" * 70)
print("CatBoost v5 Median 5 Seed Scores")
print("=" * 70)

for seed, result in cat_seed_scores_v5_median_5.items():
    print(f"Seed {seed}")
    print("Mean RMSE:", result["mean_rmse"])
    print("OOF RMSE:", result["oof_rmse"])
    print()

print("v5 Median 3-seed CatBoost OOF: 1.215253009557772")
print("v3 Median 5-seed CatBoost OOF: 1.2152369352820866")
print("v5 Median 5-seed CatBoost OOF:", rmse(y, oof_cat_v5_median_5))

======================================================================
Running CatBoost v5 median seed: 42
======================================================================
0:	learn: 2.1860157	test: 2.1969404	best: 2.1969404 (0)	total: 12.1ms	remaining: 18.1s
200:	learn: 1.2212698	test: 1.2398277	best: 1.2398277 (200)	total: 2.64s	remaining: 17.1s
400:	learn: 1.1987452	test: 1.2264998	best: 1.2264998 (400)	total: 6.09s	remaining: 16.7s
600:	learn: 1.1864098	test: 1.2236785	best: 1.2236785 (600)	total: 8.91s	remaining: 13.3s
800:	learn: 1.1757868	test: 1.2223439	best: 1.2223439 (800)	total: 11.8s	remaining: 10.3s
1000:	learn: 1.1658999	test: 1.2219821	best: 1.2219821 (1000)	total: 14.6s	remaining: 7.29s
1200:	learn: 1.1569284	test: 1.2215944	best: 1.2215544 (1194)	total: 17.6s	remaining: 4.38s
1400:	learn: 1.1487995	test: 1.2216265	best: 1.2214573 (1304)	total: 20.5s	remaining: 1.45s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.221457297
bestIteration = 1304

Shrink model to first 1305 iterations.
Seed 42 - Fold 1 RMSE: 1.2214572977120415
0:	learn: 2.1893572	test: 2.1805752	best: 2.1805752 (0)	total: 12.2ms	remaining: 18.2s
200:	learn: 1.2220376	test: 1.2324930	best: 1.2324930 (200)	total: 2.8s	remaining: 18.1s
400:	learn: 1.1998017	test: 1.2213248	best: 1.2213248 (400)	total: 5.61s	remaining: 15.4s
600:	learn: 1.1860437	test: 1.2190683	best: 1.2190683 (600)	total: 8.42s	remaining: 12.6s
800:	learn: 1.1746851	test: 1.2185342	best: 1.2184905 (795)	total: 11.3s	remaining: 9.88s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.218364532
bestIteration = 889

Shrink model to first 890 iterations.
Seed 42 - Fold 2 RMSE: 1.218364532455945
0:	learn: 2.1889821	test: 2.1871745	best: 2.1871745 (0)	total: 11.4ms	remaining: 17.2s
200:	learn: 1.2258539	test: 1.2158667	best: 1.2158667 (200)	total: 2.86s	remaining: 18.5s
400:	learn: 1.2044150	test: 1.2045150	best: 1.2045150 (400)	total: 5.66s	remaining: 15.5s
600:	learn: 1.1916059	test: 1.2023256	best: 1.2023255 (599)	total: 8.44s	remaining: 12.6s
800:	learn: 1.1801708	test: 1.2018582	best: 1.2017944 (787)	total: 11.3s	remaining: 9.84s
1000:	learn: 1.1707868	test: 1.2016675	best: 1.2016008 (908)	total: 14.2s	remaining: 7.05s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.201600824
bestIteration = 908

Shrink model to first 909 iterations.
Seed 42 - Fold 3 RMSE: 1.2016008230798565
0:	learn: 2.1901413	test: 2.1799307	best: 2.1799307 (0)	total: 12.8ms	remaining: 19.2s
200:	learn: 1.2248429	test: 1.2222736	best: 1.2222736 (200)	total: 2.86s	remaining: 18.5s
400:	learn: 1.2016612	test: 1.2105795	best: 1.2105795 (400)	total: 5.68s	remaining: 15.6s
600:	learn: 1.1887299	test: 1.2080154	best: 1.2080154 (600)	total: 8.46s	remaining: 12.6s
800:	learn: 1.1774185	test: 1.2073337	best: 1.2073240 (796)	total: 11.3s	remaining: 9.87s
1000:	learn: 1.1666820	test: 1.2070165	best: 1.2069062 (930)	total: 14.2s	remaining: 7.06s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.206906244
bestIteration = 930

Shrink model to first 931 iterations.
Seed 42 - Fold 4 RMSE: 1.2069062435174893
0:	learn: 2.1862563	test: 2.1961413	best: 2.1961413 (0)	total: 13.2ms	remaining: 19.8s
200:	learn: 1.2201248	test: 1.2492130	best: 1.2492130 (200)	total: 2.86s	remaining: 18.5s
400:	learn: 1.1972521	test: 1.2359036	best: 1.2359036 (400)	total: 5.72s	remaining: 15.7s
600:	learn: 1.1835023	test: 1.2332584	best: 1.2332540 (599)	total: 8.49s	remaining: 12.7s
800:	learn: 1.1723267	test: 1.2322550	best: 1.2322533 (766)	total: 11.4s	remaining: 9.91s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.232111377
bestIteration = 842

Shrink model to first 843 iterations.
Seed 42 - Fold 5 RMSE: 1.2321113776323254
Seed 42 Mean RMSE: 1.2160880548795316
Seed 42 OOF RMSE: 1.2161361543543805
======================================================================
Running CatBoost v5 median seed: 2024
======================================================================
0:	learn: 2.1857537	test: 2.1967851	best: 2.1967851 (0)	total: 11.1ms	remaining: 16.7s
200:	learn: 1.2213269	test: 1.2380341	best: 1.2380341 (200)	total: 2.82s	remaining: 18.2s
400:	learn: 1.1987474	test: 1.2249728	best: 1.2249716 (399)	total: 5.7s	remaining: 15.6s
600:	learn: 1.1837388	test: 1.2218841	best: 1.2218841 (600)	total: 8.58s	remaining: 12.8s
800:	learn: 1.1728860	test: 1.2207230	best: 1.2206184 (779)	total: 11.4s	remaining: 9.91s
1000:	learn: 1.1622507	test: 1.2204689	best: 1.2204078 (987)	total: 14.3s	remaining: 7.11s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.220279147
bestIteration = 1067

Shrink model to first 1068 iterations.
Seed 2024 - Fold 1 RMSE: 1.2202791482727582
0:	learn: 2.1900437	test: 2.1810351	best: 2.1810351 (0)	total: 12.3ms	remaining: 18.4s
200:	learn: 1.2221225	test: 1.2327295	best: 1.2327295 (200)	total: 2.85s	remaining: 18.4s
400:	learn: 1.2003737	test: 1.2220529	best: 1.2220529 (400)	total: 5.64s	remaining: 15.5s
600:	learn: 1.1873715	test: 1.2194261	best: 1.2194261 (600)	total: 8.44s	remaining: 12.6s
800:	learn: 1.1764980	test: 1.2186334	best: 1.2186210 (799)	total: 11.3s	remaining: 9.83s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.218598533
bestIteration = 849

Shrink model to first 850 iterations.
Seed 2024 - Fold 2 RMSE: 1.2185985338142964
0:	learn: 2.1882521	test: 2.1864332	best: 2.1864332 (0)	total: 11.8ms	remaining: 17.8s
200:	learn: 1.2245458	test: 1.2146567	best: 1.2146567 (200)	total: 2.82s	remaining: 18.2s
400:	learn: 1.2030090	test: 1.2036343	best: 1.2036343 (400)	total: 5.67s	remaining: 15.6s
600:	learn: 1.1892454	test: 1.2019152	best: 1.2018804 (580)	total: 8.53s	remaining: 12.8s
800:	learn: 1.1784434	test: 1.2010348	best: 1.2010348 (800)	total: 11.4s	remaining: 9.96s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.200848709
bestIteration = 890

Shrink model to first 891 iterations.
Seed 2024 - Fold 3 RMSE: 1.200848707839963
0:	learn: 2.1895196	test: 2.1794842	best: 2.1794842 (0)	total: 20.9ms	remaining: 31.4s
200:	learn: 1.2246767	test: 1.2225722	best: 1.2225722 (200)	total: 2.93s	remaining: 18.9s
400:	learn: 1.2015659	test: 1.2101077	best: 1.2101077 (400)	total: 5.74s	remaining: 15.7s
600:	learn: 1.1868135	test: 1.2073056	best: 1.2073008 (596)	total: 8.58s	remaining: 12.8s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.207273553
bestIteration = 608

Shrink model to first 609 iterations.
Seed 2024 - Fold 4 RMSE: 1.2072735524076215
0:	learn: 2.1855908	test: 2.1953170	best: 2.1953170 (0)	total: 11.1ms	remaining: 16.7s
200:	learn: 1.2189641	test: 1.2486133	best: 1.2486133 (200)	total: 2.92s	remaining: 18.9s
400:	learn: 1.1951188	test: 1.2351660	best: 1.2351660 (400)	total: 5.74s	remaining: 15.7s
600:	learn: 1.1819397	test: 1.2327336	best: 1.2326763 (585)	total: 8.56s	remaining: 12.8s
800:	learn: 1.1711157	test: 1.2322585	best: 1.2322158 (724)	total: 11.4s	remaining: 9.95s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.232204158
bestIteration = 827

Shrink model to first 828 iterations.
Seed 2024 - Fold 5 RMSE: 1.2322041586753811
Seed 2024 Mean RMSE: 1.2158408202020041
Seed 2024 OOF RMSE: 1.2158896104864432
======================================================================
Running CatBoost v5 median seed: 3407
======================================================================
0:	learn: 2.1851185	test: 2.1958848	best: 2.1958848 (0)	total: 9.87ms	remaining: 14.8s
200:	learn: 1.2210981	test: 1.2403153	best: 1.2403153 (200)	total: 2.85s	remaining: 18.4s
400:	learn: 1.1985683	test: 1.2273515	best: 1.2273515 (400)	total: 5.68s	remaining: 15.6s
600:	learn: 1.1855514	test: 1.2241516	best: 1.2241266 (589)	total: 8.51s	remaining: 12.7s
800:	learn: 1.1743261	test: 1.2231571	best: 1.2230820 (792)	total: 11.3s	remaining: 9.9s
1000:	learn: 1.1643566	test: 1.2225238	best: 1.2224440 (979)	total: 14.2s	remaining: 7.08s
1200:	learn: 1.1551216	test: 1.2221482	best: 1.2221322 (1183)	total: 17.2s	remaining: 4.28s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.222074735
bestIteration = 1214

Shrink model to first 1215 iterations.
Seed 3407 - Fold 1 RMSE: 1.2220747360620325
0:	learn: 2.1890186	test: 2.1801157	best: 2.1801157 (0)	total: 13ms	remaining: 19.4s
200:	learn: 1.2226021	test: 1.2332177	best: 1.2332177 (200)	total: 2.85s	remaining: 18.4s
400:	learn: 1.1997613	test: 1.2216849	best: 1.2216849 (400)	total: 5.72s	remaining: 15.7s
600:	learn: 1.1859992	test: 1.2190778	best: 1.2190778 (600)	total: 8.52s	remaining: 12.7s
800:	learn: 1.1749725	test: 1.2182998	best: 1.2182535 (790)	total: 11.4s	remaining: 9.96s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.218138094
bestIteration = 833

Shrink model to first 834 iterations.
Seed 3407 - Fold 2 RMSE: 1.2181380949711424
0:	learn: 2.1876306	test: 2.1859273	best: 2.1859273 (0)	total: 9.99ms	remaining: 15s
200:	learn: 1.2274469	test: 1.2172949	best: 1.2172949 (200)	total: 2.83s	remaining: 18.3s
400:	learn: 1.2039684	test: 1.2045341	best: 1.2045341 (400)	total: 5.71s	remaining: 15.7s
600:	learn: 1.1900066	test: 1.2023339	best: 1.2023339 (600)	total: 8.58s	remaining: 12.8s
800:	learn: 1.1789872	test: 1.2018450	best: 1.2017686 (775)	total: 11.4s	remaining: 9.99s
1000:	learn: 1.1678394	test: 1.2015232	best: 1.2014946 (998)	total: 14.4s	remaining: 7.19s
1200:	learn: 1.1577006	test: 1.2013363	best: 1.2012952 (1160)	total: 17.3s	remaining: 4.31s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.201295162
bestIteration = 1160

Shrink model to first 1161 iterations.
Seed 3407 - Fold 3 RMSE: 1.2012951614954568
0:	learn: 2.1890644	test: 2.1793891	best: 2.1793891 (0)	total: 10.8ms	remaining: 16.1s
200:	learn: 1.2266329	test: 1.2241865	best: 1.2241865 (200)	total: 2.8s	remaining: 18.1s
400:	learn: 1.2033800	test: 1.2123446	best: 1.2123446 (400)	total: 5.66s	remaining: 15.5s
600:	learn: 1.1916556	test: 1.2097487	best: 1.2097443 (599)	total: 8.35s	remaining: 12.5s
800:	learn: 1.1818149	test: 1.2091306	best: 1.2091263 (798)	total: 11.2s	remaining: 9.75s
1000:	learn: 1.1721213	test: 1.2088039	best: 1.2087102 (944)	total: 14s	remaining: 7s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.208710243
bestIteration = 944

Shrink model to first 945 iterations.
Seed 3407 - Fold 4 RMSE: 1.208710242597483
0:	learn: 2.1858860	test: 2.1958029	best: 2.1958029 (0)	total: 13.4ms	remaining: 20.1s
200:	learn: 1.2189827	test: 1.2474405	best: 1.2474405 (200)	total: 2.74s	remaining: 17.7s
400:	learn: 1.1969790	test: 1.2345761	best: 1.2345761 (400)	total: 6.02s	remaining: 16.5s
600:	learn: 1.1833614	test: 1.2320344	best: 1.2320344 (600)	total: 8.87s	remaining: 13.3s
800:	learn: 1.1724047	test: 1.2315632	best: 1.2315425 (797)	total: 11.9s	remaining: 10.4s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.231243679
bestIteration = 889

Shrink model to first 890 iterations.
Seed 3407 - Fold 5 RMSE: 1.2312436793727317
Seed 3407 Mean RMSE: 1.2162923828997692
Seed 3407 OOF RMSE: 1.216337008606478
======================================================================
Running CatBoost v5 median seed: 777
======================================================================
0:	learn: 2.1846081	test: 2.1953825	best: 2.1953825 (0)	total: 12.6ms	remaining: 18.9s
200:	learn: 1.2214376	test: 1.2398165	best: 1.2398165 (200)	total: 3.28s	remaining: 21.2s
400:	learn: 1.1984469	test: 1.2270002	best: 1.2270002 (400)	total: 6.51s	remaining: 17.9s
600:	learn: 1.1850768	test: 1.2236650	best: 1.2236650 (600)	total: 9.38s	remaining: 14s
800:	learn: 1.1742493	test: 1.2230515	best: 1.2229367 (782)	total: 12.3s	remaining: 10.7s
1000:	learn: 1.1643008	test: 1.2226150	best: 1.2224894 (967)	total: 15.3s	remaining: 7.62s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.222489375
bestIteration = 967

Shrink model to first 968 iterations.
Seed 777 - Fold 1 RMSE: 1.222489376227458
0:	learn: 2.1883200	test: 2.1794107	best: 2.1794107 (0)	total: 14.3ms	remaining: 21.5s
200:	learn: 1.2212660	test: 1.2320638	best: 1.2320638 (200)	total: 2.87s	remaining: 18.6s
400:	learn: 1.1983028	test: 1.2217609	best: 1.2217609 (400)	total: 5.78s	remaining: 15.9s
600:	learn: 1.1858310	test: 1.2194063	best: 1.2193966 (599)	total: 8.63s	remaining: 12.9s
800:	learn: 1.1760511	test: 1.2188533	best: 1.2188048 (780)	total: 11.5s	remaining: 10.1s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.218729691
bestIteration = 830

Shrink model to first 831 iterations.
Seed 777 - Fold 2 RMSE: 1.2187296914495336
0:	learn: 2.1869939	test: 2.1856614	best: 2.1856614 (0)	total: 12.3ms	remaining: 18.4s
200:	learn: 1.2271805	test: 1.2158184	best: 1.2158184 (200)	total: 2.9s	remaining: 18.7s
400:	learn: 1.2042698	test: 1.2039659	best: 1.2039659 (400)	total: 5.79s	remaining: 15.9s
600:	learn: 1.1915351	test: 1.2014458	best: 1.2014458 (600)	total: 8.57s	remaining: 12.8s
800:	learn: 1.1804287	test: 1.2007760	best: 1.2007685 (789)	total: 11.5s	remaining: 10.1s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.200523102
bestIteration = 896

Shrink model to first 897 iterations.
Seed 777 - Fold 3 RMSE: 1.2005231010041495
0:	learn: 2.1887806	test: 2.1783535	best: 2.1783535 (0)	total: 11.2ms	remaining: 16.7s
200:	learn: 1.2262105	test: 1.2235762	best: 1.2235762 (200)	total: 2.9s	remaining: 18.7s
400:	learn: 1.2025944	test: 1.2106935	best: 1.2106935 (400)	total: 5.83s	remaining: 16s
600:	learn: 1.1896580	test: 1.2088028	best: 1.2087919 (598)	total: 8.61s	remaining: 12.9s
800:	learn: 1.1781612	test: 1.2079768	best: 1.2079612 (796)	total: 11.5s	remaining: 10s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.20773957
bestIteration = 894

Shrink model to first 895 iterations.
Seed 777 - Fold 4 RMSE: 1.2077395702241953
0:	learn: 2.1859806	test: 2.1956602	best: 2.1956602 (0)	total: 13.3ms	remaining: 19.9s
200:	learn: 1.2203706	test: 1.2504268	best: 1.2504268 (200)	total: 3.1s	remaining: 20s
400:	learn: 1.1975745	test: 1.2366785	best: 1.2366785 (400)	total: 5.97s	remaining: 16.4s
600:	learn: 1.1847156	test: 1.2335700	best: 1.2335700 (600)	total: 8.8s	remaining: 13.2s
800:	learn: 1.1738678	test: 1.2330042	best: 1.2330042 (800)	total: 11.6s	remaining: 10.2s
1000:	learn: 1.1635263	test: 1.2325240	best: 1.2324099 (977)	total: 14.6s	remaining: 7.27s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.232409932
bestIteration = 977

Shrink model to first 978 iterations.
Seed 777 - Fold 5 RMSE: 1.2324099328029368
Seed 777 Mean RMSE: 1.2163783343416545
Seed 777 OOF RMSE: 1.216429789491441
======================================================================
Running CatBoost v5 median seed: 999
======================================================================
0:	learn: 2.1859727	test: 2.1968820	best: 2.1968820 (0)	total: 9.66ms	remaining: 14.5s
200:	learn: 1.2209319	test: 1.2397194	best: 1.2397194 (200)	total: 2.88s	remaining: 18.6s
400:	learn: 1.1979119	test: 1.2259695	best: 1.2259695 (400)	total: 5.76s	remaining: 15.8s
600:	learn: 1.1860449	test: 1.2232152	best: 1.2232152 (600)	total: 8.58s	remaining: 12.8s
800:	learn: 1.1757265	test: 1.2220434	best: 1.2220434 (800)	total: 11.5s	remaining: 10s
1000:	learn: 1.1644172	test: 1.2215039	best: 1.2214273 (990)	total: 14.4s	remaining: 7.19s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.221427329
bestIteration = 990

Shrink model to first 991 iterations.
Seed 999 - Fold 1 RMSE: 1.2214273294856133
0:	learn: 2.1906113	test: 2.1818862	best: 2.1818862 (0)	total: 11.4ms	remaining: 17.2s
200:	learn: 1.2224347	test: 1.2347605	best: 1.2347605 (200)	total: 3.18s	remaining: 20.6s
400:	learn: 1.1984159	test: 1.2226955	best: 1.2226955 (400)	total: 6.22s	remaining: 17s
600:	learn: 1.1847103	test: 1.2199178	best: 1.2199178 (600)	total: 9.06s	remaining: 13.5s
800:	learn: 1.1734194	test: 1.2190108	best: 1.2189826 (798)	total: 12s	remaining: 10.5s
1000:	learn: 1.1632122	test: 1.2187521	best: 1.2187312 (976)	total: 14.9s	remaining: 7.44s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.218674204
bestIteration = 1027

Shrink model to first 1028 iterations.
Seed 999 - Fold 2 RMSE: 1.2186742048402637
0:	learn: 2.1883180	test: 2.1868683	best: 2.1868683 (0)	total: 11.5ms	remaining: 17.2s
200:	learn: 1.2278643	test: 1.2162668	best: 1.2162668 (200)	total: 3.68s	remaining: 23.8s
400:	learn: 1.2052880	test: 1.2047781	best: 1.2047781 (400)	total: 6.53s	remaining: 17.9s
600:	learn: 1.1930956	test: 1.2027898	best: 1.2027898 (600)	total: 9.49s	remaining: 14.2s
800:	learn: 1.1828979	test: 1.2025147	best: 1.2024886 (796)	total: 12.5s	remaining: 10.9s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.20248863
bestIteration = 796

Shrink model to first 797 iterations.
Seed 999 - Fold 3 RMSE: 1.2024886289662884
0:	learn: 2.1907804	test: 2.1805533	best: 2.1805533 (0)	total: 11.2ms	remaining: 16.8s
200:	learn: 1.2252174	test: 1.2229953	best: 1.2229953 (200)	total: 2.87s	remaining: 18.5s
400:	learn: 1.2024200	test: 1.2105174	best: 1.2105174 (400)	total: 5.73s	remaining: 15.7s
600:	learn: 1.1869773	test: 1.2081217	best: 1.2081029 (593)	total: 8.63s	remaining: 12.9s
800:	learn: 1.1752794	test: 1.2074807	best: 1.2074542 (798)	total: 11.5s	remaining: 10s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.207454224
bestIteration = 798

Shrink model to first 799 iterations.
Seed 999 - Fold 4 RMSE: 1.2074542238195378
0:	learn: 2.1869922	test: 2.1966213	best: 2.1966213 (0)	total: 10.8ms	remaining: 16.2s
200:	learn: 1.2186145	test: 1.2483794	best: 1.2483794 (200)	total: 2.84s	remaining: 18.4s
400:	learn: 1.1955085	test: 1.2349659	best: 1.2349659 (400)	total: 5.7s	remaining: 15.6s
600:	learn: 1.1823783	test: 1.2325853	best: 1.2325853 (600)	total: 8.5s	remaining: 12.7s
800:	learn: 1.1724705	test: 1.2321981	best: 1.2319686 (732)	total: 11.3s	remaining: 9.86s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 1.231968616
bestIteration = 732

Shrink model to first 733 iterations.
Seed 999 - Fold 5 RMSE: 1.2319686165368071
Seed 999 Mean RMSE: 1.2164026007297022
Seed 999 OOF RMSE: 1.2164475176761131
======================================================================
CatBoost v5 Median 5 Seed Scores
======================================================================
Seed 42
Mean RMSE: 1.2160880548795316
OOF RMSE: 1.2161361543543805

Seed 2024
Mean RMSE: 1.2158408202020041
OOF RMSE: 1.2158896104864432

Seed 3407
Mean RMSE: 1.2162923828997692
OOF RMSE: 1.216337008606478

Seed 777
Mean RMSE: 1.2163783343416545
OOF RMSE: 1.216429789491441

Seed 999
Mean RMSE: 1.2164026007297022
OOF RMSE: 1.2164475176761131

v5 Median 3-seed CatBoost OOF: 1.215253009557772
v3 Median 5-seed CatBoost OOF: 1.2152369352820866
v5 Median 5-seed CatBoost OOF: 1.2152109610198838

# Deney 26C - v5 CatBoost 5 Seed + HGB v3 + LightGBM TE v3 Blend

In [33]:
for var in [
    "oof_cat_v5_median_5",
    "test_cat_v5_median_5",
    "oof_hgb_v3",
    "test_hgb_v3",
    "oof_lgbm_te_v3",
    "test_lgbm_te_v3"
]:
    print(var, var in globals())

oof_cat_v5_median_5 True
test_cat_v5_median_5 True
oof_hgb_v3 False
test_hgb_v3 False
oof_lgbm_te_v3 False
test_lgbm_te_v3 False

In [34]:
for var in [
    "X_fe_v3",
    "X_test_fe_v3",
    "get_hgb_oof_dense",
    "get_lgbm_target_encoding_oof"
]:
    print(var, var in globals())

X_fe_v3 True
X_test_fe_v3 True
get_hgb_oof_dense False
get_lgbm_target_encoding_oof False

In [ ]:
# ============================================================
# HGB OOF - Dense OneHotEncoder
# ============================================================

import numpy as np

from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

def get_hgb_oof_dense(X_fe, y, X_test_fe, cv):
    num_cols = X_fe.select_dtypes(include=np.number).columns.tolist()
    cat_cols = X_fe.select_dtypes(include="object").columns.tolist()

    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median", add_indicator=True))
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="constant", fill_value="Bilinmiyor")),
        ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, num_cols),
            ("cat", categorical_transformer, cat_cols)
        ],
        sparse_threshold=0
    )

    oof_preds = np.zeros(len(X_fe))
    test_preds = np.zeros(len(X_test_fe))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_fe), 1):
        X_train_fold = X_fe.iloc[train_idx]
        X_val_fold = X_fe.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        model = HistGradientBoostingRegressor(
            max_iter=700,
            learning_rate=0.04,
            max_leaf_nodes=31,
            min_samples_leaf=20,
            l2_regularization=0.1,
            random_state=42
        )

        pipeline = Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("model", model)
        ])

        pipeline.fit(X_train_fold, y_train_fold)

        val_pred = pipeline.predict(X_val_fold)
        test_pred = pipeline.predict(X_test_fe)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"HGB Fold {fold} RMSE:", fold_rmse)

    print("HGB Mean RMSE:", np.mean(fold_scores))
    print("HGB OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores

In [ ]:
# ============================================================
# LightGBM with Out-of-Fold Target Encoding
# ============================================================

import numpy as np
import pandas as pd

from lightgbm import LGBMRegressor
from category_encoders import TargetEncoder

def get_lgbm_target_encoding_oof(X_fe, y, X_test_fe, cv):
    cat_cols = X_fe.select_dtypes(include="object").columns.tolist()
    num_cols = X_fe.select_dtypes(include=np.number).columns.tolist()

    oof_preds = np.zeros(len(X_fe))
    test_preds = np.zeros(len(X_test_fe))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_fe), 1):
        X_train_fold = X_fe.iloc[train_idx].copy()
        X_val_fold = X_fe.iloc[val_idx].copy()
        X_test_fold = X_test_fe.copy()

        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]


        for col in cat_cols:
            X_train_fold[col] = X_train_fold[col].fillna("Bilinmiyor").astype(str)
            X_val_fold[col] = X_val_fold[col].fillna("Bilinmiyor").astype(str)
            X_test_fold[col] = X_test_fold[col].fillna("Bilinmiyor").astype(str)

        medians = X_train_fold[num_cols].median()

        X_train_fold[num_cols] = X_train_fold[num_cols].fillna(medians)
        X_val_fold[num_cols] = X_val_fold[num_cols].fillna(medians)
        X_test_fold[num_cols] = X_test_fold[num_cols].fillna(medians)

        encoder = TargetEncoder(
            cols=cat_cols,
            smoothing=10.0
        )

        X_train_enc = encoder.fit_transform(X_train_fold, y_train_fold)
        X_val_enc = encoder.transform(X_val_fold)
        X_test_enc = encoder.transform(X_test_fold)

        model = LGBMRegressor(
            objective="regression",
            n_estimators=2000,
            learning_rate=0.025,
            num_leaves=31,
            max_depth=-1,
            min_child_samples=25,
            subsample=0.9,
            colsample_bytree=0.9,
            reg_alpha=0.05,
            reg_lambda=0.1,
            random_state=42,
            n_jobs=-1,
            verbose=-1
        )

        model.fit(X_train_enc, y_train_fold)

        val_pred = model.predict(X_val_enc)
        test_pred = model.predict(X_test_enc)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"LightGBM TargetEncoding Fold {fold} RMSE:", fold_rmse)

    print("LightGBM TargetEncoding Mean RMSE:", np.mean(fold_scores))
    print("LightGBM TargetEncoding OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores

In [37]:
oof_hgb_v3, test_hgb_v3, scores_hgb_v3 = get_hgb_oof_dense(
    X_fe_v3,
    y,
    X_test_fe_v3,
    cv
)

oof_lgbm_te_v3, test_lgbm_te_v3, scores_lgbm_te_v3 = get_lgbm_target_encoding_oof(
    X_fe_v3,
    y,
    X_test_fe_v3,
    cv
)

HGB Fold 1 RMSE: 1.2307257608746391
HGB Fold 2 RMSE: 1.2279666280094808
HGB Fold 3 RMSE: 1.2180883161193514
HGB Fold 4 RMSE: 1.2249099451212055
HGB Fold 5 RMSE: 1.2450940604787741
HGB Mean RMSE: 1.22935694212069
HGB OOF RMSE: 1.2293893343402866
LightGBM TargetEncoding Fold 1 RMSE: 1.2321067384815605
LightGBM TargetEncoding Fold 2 RMSE: 1.2303617074700182
LightGBM TargetEncoding Fold 3 RMSE: 1.216124730155015
LightGBM TargetEncoding Fold 4 RMSE: 1.2273107472783782
LightGBM TargetEncoding Fold 5 RMSE: 1.2479365954034762
LightGBM TargetEncoding Mean RMSE: 1.2307681037576894
LightGBM TargetEncoding OOF RMSE: 1.2308106046055216

In [38]:
from scipy.optimize import minimize
import numpy as np

oof_matrix_v5_hybrid = np.column_stack([
    oof_cat_v5_median_5,
    oof_hgb_v3,
    oof_lgbm_te_v3
])

test_matrix_v5_hybrid = np.column_stack([
    test_cat_v5_median_5,
    test_hgb_v3,
    test_lgbm_te_v3
])

model_names_v5_hybrid = [
    "CatBoost v5 Median 5 Seed",
    "HGB v3",
    "LightGBM TargetEncoding v3"
]

def blend_rmse_v5_hybrid(weights):
    preds = oof_matrix_v5_hybrid @ weights
    return rmse(y, preds)

n_models = oof_matrix_v5_hybrid.shape[1]
initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result_v5_hybrid = minimize(
    blend_rmse_v5_hybrid,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights_v5_hybrid = result_v5_hybrid.x
best_oof_preds_v5_hybrid = oof_matrix_v5_hybrid @ best_weights_v5_hybrid
best_test_preds_v5_hybrid = test_matrix_v5_hybrid @ best_weights_v5_hybrid

print("Optimization success:", result_v5_hybrid.success)
print("Best weights:")

for name, weight in zip(model_names_v5_hybrid, best_weights_v5_hybrid):
    print(f"{name}: {weight:.6f}")

print("Eski en iyi TE blend OOF: 1.2151543285184772")
print("v5 hybrid blend OOF:", rmse(y, best_oof_preds_v5_hybrid))

Optimization success: True
Best weights:
CatBoost v5 Median 5 Seed: 0.844683
HGB v3: 0.059198
LightGBM TargetEncoding v3: 0.096119
Eski en iyi TE blend OOF: 1.2151543285184772
v5 hybrid blend OOF: 1.2148729252291883

In [39]:
import pandas as pd
import numpy as np

TARGET = "bilissel_performans_skoru"

exp20e = pd.read_csv("submission_exp20e_v3_5seed_blend.csv")

submission_exp26c_v5_hybrid = pd.DataFrame({
    "id": exp20e["id"],
    TARGET: best_test_preds_v5_hybrid
})

submission_exp26c_v5_hybrid[TARGET] = submission_exp26c_v5_hybrid[TARGET].clip(0, 10)

print("exp20E public best:")
print(exp20e[TARGET].describe())

print("\nexp26C v5 hybrid:")
print(submission_exp26c_v5_hybrid[TARGET].describe())

diff = submission_exp26c_v5_hybrid[TARGET].values - exp20e[TARGET].values

print("\nDifference exp26C - exp20E:")
print(pd.Series(diff).describe())

print("\nCorrelation:")
print(np.corrcoef(exp20e[TARGET].values, submission_exp26c_v5_hybrid[TARGET].values)[0, 1])

exp20E public best:
count    24000.000000
mean         5.936977
std          1.862729
min          0.000000
25%          4.641429
50%          6.044348
75%          7.327849
max         10.000000
Name: bilissel_performans_skoru, dtype: float64

exp26C v5 hybrid:
count    24000.000000
mean         5.942902
std          1.862127
min          0.036221
25%          4.639724
50%          6.041753
75%          7.340950
max         10.000000
Name: bilissel_performans_skoru, dtype: float64

Difference exp26C - exp20E:
count    24000.000000
mean         0.005925
std          0.087670
min         -0.515707
25%         -0.045300
50%          0.003504
75%          0.055709
max          0.573976
dtype: float64

Correlation:
0.9988921212494891

In [40]:
submission_exp26c_v5_hybrid.to_csv("submission_exp26c_v5_hybrid.csv", index=False)

# Deney 27 - Public Best Çizgisini Baştan Kurma

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

from catboost import CatBoostRegressor, Pool


# ============================================================
# EXP 27 - Clean CatBoost Native Pipeline
# ============================================================

EXP_NAME = "exp27_cat_native_clean"
SEEDS = [42, 2024, 3407, 777, 999]
N_SPLITS = 5

TARGET_COL = "Degerlendirme Puani"


def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))



print("X shape:", X.shape)
print("y shape:", y.shape)
print("X_test shape:", X_test.shape)



cat_features = X.select_dtypes(include=["object", "category"]).columns.tolist()

for col in cat_features:
    X[col] = X[col].fillna("missing").astype(str)
    X_test[col] = X_test[col].fillna("missing").astype(str)

print("Categorical features:", cat_features)
print("Number of categorical features:", len(cat_features))

print("Remaining categorical NaN in train:", X[cat_features].isna().sum().sum())
print("Remaining categorical NaN in test:", X_test[cat_features].isna().sum().sum())


cat_oof_list_exp27 = []
cat_test_list_exp27 = []
cat_seed_scores_exp27 = {}


for seed in SEEDS:
    print("=" * 70)
    print(f"Starting seed: {seed}")
    print("=" * 70)

    kf = KFold(
        n_splits=N_SPLITS,cat_features = X.select_dtypes(include=["object", "category"]).columns.tolist()

print("Categorical features:", cat_features)
print("Number of categorical features:", len(cat_features))
    test_pred = np.zeros(len(X_test))
    fold_scores = []

    for fold, (train_idx, valid_idx) in enumerate(kf.split(X, y), start=1):
        print(f"\nSeed {seed} | Fold {fold}")

        X_train = X.iloc[train_idx]
        y_train = y.iloc[train_idx]

        X_valid = X.iloc[valid_idx]
        y_valid = y.iloc[valid_idx]

        train_pool = Pool(
            X_train,
            y_train,
            cat_features=cat_features
        )

        valid_pool = Pool(
            X_valid,
            y_valid,
            cat_features=cat_features
        )

        test_pool = Pool(
            X_test,
            cat_features=cat_features
        )

        model = CatBoostRegressor(
            loss_function="RMSE",
            eval_metric="RMSE",
            iterations=5000,
            learning_rate=0.03,
            depth=6,
            l2_leaf_reg=3,
            random_seed=seed,
            verbose=500,
            early_stopping_rounds=300,
            allow_writing_files=False
        )

        model.fit(
            train_pool,
            eval_set=valid_pool,
            use_best_model=True
        )

        valid_pred = model.predict(valid_pool)
        fold_test_pred = model.predict(test_pool)

        oof_pred[valid_idx] = valid_pred
        test_pred += fold_test_pred / N_SPLITS

        fold_rmse = rmse(y_valid, valid_pred)
        fold_scores.append(fold_rmse)

        print(f"Seed {seed} | Fold {fold} RMSE: {fold_rmse:.5f}")

    seed_rmse = rmse(y, oof_pred)

    cat_oof_list_exp27.append(oof_pred)
    cat_test_list_exp27.append(test_pred)
    cat_seed_scores_exp27[seed] = {
        "fold_scores": fold_scores,
        "seed_rmse": seed_rmse
    }

    print(f"\nSeed {seed} OOF RMSE: {seed_rmse:.5f}")


# Güvenlik kontrolü
assert len(cat_oof_list_exp27) > 0, "cat_oof_list_exp27 boş! Model eğitimi çalışmamış."
assert len(cat_test_list_exp27) > 0, "cat_test_list_exp27 boş! Test tahminleri oluşmamış."


# 5 seed ortalaması
oof_cat_exp27_5seed = np.mean(cat_oof_list_exp27, axis=0)
test_cat_exp27_5seed = np.mean(cat_test_list_exp27, axis=0)

final_rmse = rmse(y, oof_cat_exp27_5seed)

print("\n" + "=" * 70)
print(f"{EXP_NAME} Final 5-seed OOF RMSE: {final_rmse:.5f}")
print("=" * 70)


# Kaydet
np.save(f"oof_{EXP_NAME}.npy", oof_cat_exp27_5seed)
np.save(f"test_{EXP_NAME}.npy", test_cat_exp27_5seed)

print(f"Saved: oof_{EXP_NAME}.npy")
print(f"Saved: test_{EXP_NAME}.npy")

X shape: (56000, 23)
y shape: (56000,)
X_test shape: (24000, 23)
Categorical features: ['cinsiyet', 'meslek', 'ulke', 'kronotip', 'ruh_sagligi_durumu', 'mevsim', 'gun_tipi']
Number of categorical features: 7
Remaining categorical NaN in train: 0
Remaining categorical NaN in test: 0
======================================================================
Starting seed: 42
======================================================================

Seed 42 | Fold 1
0:	learn: 2.1962065	test: 2.2069443	best: 2.2069443 (0)	total: 53.9ms	remaining: 4m 29s
500:	learn: 1.1958354	test: 1.2241326	best: 1.2241326 (500)	total: 4.65s	remaining: 41.8s
1000:	learn: 1.1711294	test: 1.2209564	best: 1.2209564 (1000)	total: 8.39s	remaining: 33.5s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.220786278
bestIteration = 1079

Shrink model to first 1080 iterations.
Seed 42 | Fold 1 RMSE: 1.22079

Seed 42 | Fold 2
0:	learn: 2.1998516	test: 2.1910527	best: 2.1910527 (0)	total: 7.03ms	remaining: 35.2s
500:	learn: 1.1975040	test: 1.2199261	best: 1.2199241 (498)	total: 3.69s	remaining: 33.2s
1000:	learn: 1.1703787	test: 1.2176194	best: 1.2175255 (978)	total: 7.42s	remaining: 29.7s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.217525462
bestIteration = 978

Shrink model to first 979 iterations.
Seed 42 | Fold 2 RMSE: 1.21753

Seed 42 | Fold 3
0:	learn: 2.1984890	test: 2.1967336	best: 2.1967336 (0)	total: 8.12ms	remaining: 40.6s
500:	learn: 1.2013709	test: 1.2055482	best: 1.2055482 (500)	total: 3.79s	remaining: 34s
1000:	learn: 1.1769459	test: 1.2022033	best: 1.2021440 (987)	total: 7.44s	remaining: 29.7s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.202014167
bestIteration = 1039

Shrink model to first 1040 iterations.
Seed 42 | Fold 3 RMSE: 1.20201

Seed 42 | Fold 4
0:	learn: 2.2000730	test: 2.1897877	best: 2.1897877 (0)	total: 7.73ms	remaining: 38.6s
500:	learn: 1.1969944	test: 1.2101345	best: 1.2101311 (499)	total: 3.75s	remaining: 33.7s
1000:	learn: 1.1710011	test: 1.2095256	best: 1.2090375 (763)	total: 7.44s	remaining: 29.7s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.209037463
bestIteration = 763

Shrink model to first 764 iterations.
Seed 42 | Fold 4 RMSE: 1.20904

Seed 42 | Fold 5
0:	learn: 2.1961241	test: 2.2058237	best: 2.2058237 (0)	total: 8.27ms	remaining: 41.3s
500:	learn: 1.1939402	test: 1.2347749	best: 1.2347749 (500)	total: 3.77s	remaining: 33.8s
1000:	learn: 1.1683380	test: 1.2321318	best: 1.2320437 (902)	total: 7.42s	remaining: 29.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.232043705
bestIteration = 902

Shrink model to first 903 iterations.
Seed 42 | Fold 5 RMSE: 1.23204

Seed 42 OOF RMSE: 1.21632
======================================================================
Starting seed: 2024
======================================================================

Seed 2024 | Fold 1
0:	learn: 2.1997709	test: 2.1864762	best: 2.1864762 (0)	total: 7.78ms	remaining: 38.9s
500:	learn: 1.1953426	test: 1.2262969	best: 1.2262969 (500)	total: 3.78s	remaining: 33.9s
1000:	learn: 1.1703534	test: 1.2232186	best: 1.2232168 (940)	total: 7.49s	remaining: 29.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.222700394
bestIteration = 1169

Shrink model to first 1170 iterations.
Seed 2024 | Fold 1 RMSE: 1.22270

Seed 2024 | Fold 2
0:	learn: 2.1967878	test: 2.1985992	best: 2.1985992 (0)	total: 7.48ms	remaining: 37.4s
500:	learn: 1.1981464	test: 1.2168220	best: 1.2168220 (500)	total: 3.81s	remaining: 34.2s
1000:	learn: 1.1699776	test: 1.2138154	best: 1.2137718 (994)	total: 7.57s	remaining: 30.2s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.213771777
bestIteration = 994

Shrink model to first 995 iterations.
Seed 2024 | Fold 2 RMSE: 1.21377

Seed 2024 | Fold 3
0:	learn: 2.1945370	test: 2.2079861	best: 2.2079861 (0)	total: 8.48ms	remaining: 42.4s
500:	learn: 1.1923063	test: 1.2316173	best: 1.2316110 (498)	total: 3.79s	remaining: 34s
1000:	learn: 1.1659564	test: 1.2297174	best: 1.2294303 (930)	total: 7.57s	remaining: 30.2s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.229430305
bestIteration = 930

Shrink model to first 931 iterations.
Seed 2024 | Fold 3 RMSE: 1.22943

Seed 2024 | Fold 4
0:	learn: 2.1978549	test: 2.1945188	best: 2.1945188 (0)	total: 7.84ms	remaining: 39.2s
500:	learn: 1.1995083	test: 1.2071674	best: 1.2071674 (500)	total: 3.75s	remaining: 33.7s
1000:	learn: 1.1736812	test: 1.2048819	best: 1.2048798 (998)	total: 7.51s	remaining: 30s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.204775879
bestIteration = 1150

Shrink model to first 1151 iterations.
Seed 2024 | Fold 4 RMSE: 1.20478

Seed 2024 | Fold 5
0:	learn: 2.1969158	test: 2.1985207	best: 2.1985207 (0)	total: 7.72ms	remaining: 38.6s
500:	learn: 1.1987382	test: 1.2128088	best: 1.2128088 (500)	total: 3.84s	remaining: 34.5s
1000:	learn: 1.1725086	test: 1.2100154	best: 1.2099598 (908)	total: 7.67s	remaining: 30.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.209886524
bestIteration = 1061

Shrink model to first 1062 iterations.
Seed 2024 | Fold 5 RMSE: 1.20989

Seed 2024 OOF RMSE: 1.21615
======================================================================
Starting seed: 3407
======================================================================

Seed 3407 | Fold 1
0:	learn: 2.1996540	test: 2.1907907	best: 2.1907907 (0)	total: 7.83ms	remaining: 39.1s
500:	learn: 1.1985392	test: 1.2095111	best: 1.2095111 (500)	total: 3.73s	remaining: 33.5s
1000:	learn: 1.1723972	test: 1.2072919	best: 1.2069394 (814)	total: 7.58s	remaining: 30.3s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.206939361
bestIteration = 814

Shrink model to first 815 iterations.
Seed 3407 | Fold 1 RMSE: 1.20694

Seed 3407 | Fold 2
0:	learn: 2.1940630	test: 2.2126590	best: 2.2126590 (0)	total: 7.78ms	remaining: 38.9s
500:	learn: 1.1954469	test: 1.2277162	best: 1.2277162 (500)	total: 3.8s	remaining: 34.1s
1000:	learn: 1.1680377	test: 1.2247940	best: 1.2247907 (989)	total: 7.7s	remaining: 30.8s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.224573625
bestIteration = 1170

Shrink model to first 1171 iterations.
Seed 3407 | Fold 2 RMSE: 1.22457

Seed 3407 | Fold 3
0:	learn: 2.2026834	test: 2.1772246	best: 2.1772246 (0)	total: 7.86ms	remaining: 39.3s
500:	learn: 1.1965206	test: 1.2213811	best: 1.2213693 (499)	total: 4.28s	remaining: 38.4s
1000:	learn: 1.1682628	test: 1.2184126	best: 1.2184126 (1000)	total: 8.19s	remaining: 32.7s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.218395983
bestIteration = 1005

Shrink model to first 1006 iterations.
Seed 3407 | Fold 3 RMSE: 1.21840

Seed 3407 | Fold 4
0:	learn: 2.1964525	test: 2.2030098	best: 2.2030098 (0)	total: 8.03ms	remaining: 40.2s
500:	learn: 1.1972627	test: 1.2170477	best: 1.2170477 (500)	total: 4.03s	remaining: 36.2s
1000:	learn: 1.1712218	test: 1.2149167	best: 1.2145033 (833)	total: 7.93s	remaining: 31.7s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.214503252
bestIteration = 833

Shrink model to first 834 iterations.
Seed 3407 | Fold 4 RMSE: 1.21450

Seed 3407 | Fold 5
0:	learn: 2.1959475	test: 2.2051805	best: 2.2051805 (0)	total: 7.44ms	remaining: 37.2s
500:	learn: 1.1987104	test: 1.2171464	best: 1.2171464 (500)	total: 3.83s	remaining: 34.4s
1000:	learn: 1.1722393	test: 1.2154940	best: 1.2153160 (826)	total: 7.63s	remaining: 30.5s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.215294299
bestIteration = 1034

Shrink model to first 1035 iterations.
Seed 3407 | Fold 5 RMSE: 1.21529

Seed 3407 OOF RMSE: 1.21595
======================================================================
Starting seed: 777
======================================================================

Seed 777 | Fold 1
0:	learn: 2.1982655	test: 2.1946882	best: 2.1946882 (0)	total: 8.4ms	remaining: 42s
500:	learn: 1.1936779	test: 1.2287975	best: 1.2287969 (499)	total: 3.9s	remaining: 35s
1000:	learn: 1.1672089	test: 1.2263681	best: 1.2263492 (998)	total: 7.77s	remaining: 31.1s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.226224292
bestIteration = 1074

Shrink model to first 1075 iterations.
Seed 777 | Fold 1 RMSE: 1.22622

Seed 777 | Fold 2
0:	learn: 2.1968354	test: 2.1999006	best: 2.1999006 (0)	total: 7.94ms	remaining: 39.7s
500:	learn: 1.1933980	test: 1.2320782	best: 1.2320187 (489)	total: 3.9s	remaining: 35s
1000:	learn: 1.1660734	test: 1.2298269	best: 1.2297763 (925)	total: 7.74s	remaining: 30.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.229717567
bestIteration = 1133

Shrink model to first 1134 iterations.
Seed 777 | Fold 2 RMSE: 1.22972

Seed 777 | Fold 3
0:	learn: 2.2021308	test: 2.1784269	best: 2.1784269 (0)	total: 8.64ms	remaining: 43.2s
500:	learn: 1.1986651	test: 1.2153741	best: 1.2153695 (499)	total: 3.9s	remaining: 35s
1000:	learn: 1.1731120	test: 1.2125570	best: 1.2124841 (994)	total: 7.73s	remaining: 30.9s
1500:	learn: 1.1519463	test: 1.2123715	best: 1.2121202 (1253)	total: 11.6s	remaining: 27s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.21212021
bestIteration = 1253

Shrink model to first 1254 iterations.
Seed 777 | Fold 3 RMSE: 1.21212

Seed 777 | Fold 4
0:	learn: 2.1958823	test: 2.2040075	best: 2.2040075 (0)	total: 7.91ms	remaining: 39.5s
500:	learn: 1.2012039	test: 1.2032160	best: 1.2032160 (500)	total: 3.88s	remaining: 34.8s
1000:	learn: 1.1756642	test: 1.2005319	best: 1.2004060 (945)	total: 7.7s	remaining: 30.8s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.200405994
bestIteration = 945

Shrink model to first 946 iterations.
Seed 777 | Fold 4 RMSE: 1.20041

Seed 777 | Fold 5
0:	learn: 2.1942502	test: 2.2105868	best: 2.2105868 (0)	total: 8.46ms	remaining: 42.3s
500:	learn: 1.1975289	test: 1.2156875	best: 1.2156875 (500)	total: 3.8s	remaining: 34.2s
1000:	learn: 1.1697200	test: 1.2130358	best: 1.2128738 (963)	total: 7.64s	remaining: 30.5s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.212873801
bestIteration = 963

Shrink model to first 964 iterations.
Seed 777 | Fold 5 RMSE: 1.21287

Seed 777 OOF RMSE: 1.21631
======================================================================
Starting seed: 999
======================================================================

Seed 999 | Fold 1
0:	learn: 2.1970783	test: 2.1969662	best: 2.1969662 (0)	total: 8.62ms	remaining: 43.1s
500:	learn: 1.1972836	test: 1.2210318	best: 1.2210318 (500)	total: 3.89s	remaining: 34.9s
1000:	learn: 1.1721233	test: 1.2180113	best: 1.2179424 (987)	total: 7.65s	remaining: 30.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.217839677
bestIteration = 1113

Shrink model to first 1114 iterations.
Seed 999 | Fold 1 RMSE: 1.21784

Seed 999 | Fold 2
0:	learn: 2.1945416	test: 2.2113935	best: 2.2113935 (0)	total: 8.71ms	remaining: 43.5s
500:	learn: 1.1998798	test: 1.2092016	best: 1.2092016 (500)	total: 3.89s	remaining: 34.9s
1000:	learn: 1.1735429	test: 1.2067189	best: 1.2065262 (946)	total: 7.66s	remaining: 30.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.206526241
bestIteration = 946

Shrink model to first 947 iterations.
Seed 999 | Fold 2 RMSE: 1.20653

Seed 999 | Fold 3
0:	learn: 2.2003914	test: 2.1872733	best: 2.1872733 (0)	total: 8.29ms	remaining: 41.5s
500:	learn: 1.1935075	test: 1.2257649	best: 1.2257649 (500)	total: 3.9s	remaining: 35.1s
1000:	learn: 1.1673388	test: 1.2227508	best: 1.2227508 (1000)	total: 7.64s	remaining: 30.5s
1500:	learn: 1.1457622	test: 1.2232491	best: 1.2226042 (1218)	total: 11.7s	remaining: 27.2s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.222604155
bestIteration = 1218

Shrink model to first 1219 iterations.
Seed 999 | Fold 3 RMSE: 1.22260

Seed 999 | Fold 4
0:	learn: 2.1945686	test: 2.2107857	best: 2.2107857 (0)	total: 8.85ms	remaining: 44.3s
500:	learn: 1.1957084	test: 1.2231821	best: 1.2231643 (499)	total: 3.83s	remaining: 34.4s
1000:	learn: 1.1678229	test: 1.2192904	best: 1.2192356 (969)	total: 7.73s	remaining: 30.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.219235626
bestIteration = 969

Shrink model to first 970 iterations.
Seed 999 | Fold 4 RMSE: 1.21924

Seed 999 | Fold 5
0:	learn: 2.2016671	test: 2.1819529	best: 2.1819529 (0)	total: 6.92ms	remaining: 34.6s
500:	learn: 1.1955383	test: 1.2184779	best: 1.2184636 (498)	total: 4.01s	remaining: 36s
1000:	learn: 1.1676223	test: 1.2165056	best: 1.2164839 (946)	total: 7.92s	remaining: 31.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.216351827
bestIteration = 1163

Shrink model to first 1164 iterations.
Seed 999 | Fold 5 RMSE: 1.21635

Seed 999 OOF RMSE: 1.21652

======================================================================
exp27_cat_native_clean Final 5-seed OOF RMSE: 1.21469
======================================================================
Saved: oof_exp27_cat_native_clean.npy
Saved: test_exp27_cat_native_clean.npy

In [7]:
exp_results = []

exp_results.append({
    "experiment": "exp27_cat_native_clean",
    "model": "CatBoost",
    "cv": "5-fold x 5-seed",
    "oof_rmse": 1.21469,
    "features": X.shape[1],
    "cat_features": len(cat_features),
    "notes": "Native categorical, categorical missing fixed"
})

pd.DataFrame(exp_results)

,experiment,model,cv,oof_rmse,features,cat_features,notes
0,exp27_cat_native_clean,CatBoost,5-fold x 5-seed,1.21469,23,7,"Native categorical, categorical missing fixed"

In [9]:
test_pred = np.load("test_exp27_cat_native_clean.npy")

submission = pd.DataFrame({
    "id": test["id"],
    "Degerlendirme Puani": test_pred
})

submission.to_csv("submission_exp27_cat_native_clean.csv", index=False)

submission.head()

   id  Degerlendirme Puani
0   1             6.064382
1   2             6.792259
2   3             3.055101
3   4             7.122827
4   5             3.753926

In [10]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error


def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

In [11]:
oof_27 = np.load("oof_exp27_cat_native_clean.npy")
test_27 = np.load("test_exp27_cat_native_clean.npy")

In [12]:
import os

[f for f in os.listdir() if f.endswith(".npy")]

['oof_hgb_v3.npy',
 'test_hgb_v3.npy',
 'test_lgbm_v3.npy',
 'oof_exp27_cat_native_clean.npy',
 'test_exp27_cat_native_clean.npy',
 'oof_lgbm_v3.npy']

In [ ]:
# ============================================================
# DENEY 20E - TEK HÜCRE CLEAN RECREATE
# CatBoost v3 5-seed + HGB v3 + LightGBM v3 optimized blend
# ============================================================

import os
import numpy as np
import pandas as pd

from scipy.optimize import minimize
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from catboost import CatBoostRegressor, Pool


# ------------------------------------------------------------
# Metric
# ------------------------------------------------------------

def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))


# ------------------------------------------------------------
# Basic checks
# ------------------------------------------------------------

assert "X" in globals(), "X değişkeni yok. Önce feature matrix X oluşturulmalı."
assert "X_test" in globals(), "X_test değişkeni yok. Önce test feature matrix X_test oluşturulmalı."
assert "y" in globals(), "y değişkeni yok. Önce target y oluşturulmalı."

print("X shape:", X.shape)
print("X_test shape:", X_test.shape)
print("y shape:", y.shape)


# ------------------------------------------------------------
# Load HGB and LGBM OOF/Test predictions
# ------------------------------------------------------------

if "oof_hgb_v3" not in globals():
    assert os.path.exists("oof_hgb_v3.npy"), "oof_hgb_v3.npy bulunamadı."
    oof_hgb_v3 = np.load("oof_hgb_v3.npy")

if "test_hgb_v3" not in globals():
    assert os.path.exists("test_hgb_v3.npy"), "test_hgb_v3.npy bulunamadı."
    test_hgb_v3 = np.load("test_hgb_v3.npy")

if "oof_lgbm_v3" not in globals():
    assert os.path.exists("oof_lgbm_v3.npy"), "oof_lgbm_v3.npy bulunamadı."
    oof_lgbm_v3 = np.load("oof_lgbm_v3.npy")

if "test_lgbm_v3" not in globals():
    assert os.path.exists("test_lgbm_v3.npy"), "test_lgbm_v3.npy bulunamadı."
    test_lgbm_v3 = np.load("test_lgbm_v3.npy")


print("\nLoaded base models:")
print("HGB OOF:", oof_hgb_v3.shape, "| Test:", test_hgb_v3.shape, "| RMSE:", rmse(y, oof_hgb_v3))
print("LGBM OOF:", oof_lgbm_v3.shape, "| Test:", test_lgbm_v3.shape, "| RMSE:", rmse(y, oof_lgbm_v3))



cat_oof_file = "oof_cat_seed_ensemble_v3_5.npy"
cat_test_file = "test_cat_seed_ensemble_v3_5.npy"

if "oof_cat_seed_ensemble_v3_5" in globals() and "test_cat_seed_ensemble_v3_5" in globals():
    print("\nUsing existing CatBoost v3 5-seed variables from memory.")

elif os.path.exists(cat_oof_file) and os.path.exists(cat_test_file):
    print("\nLoading CatBoost v3 5-seed predictions from npy files.")
    oof_cat_seed_ensemble_v3_5 = np.load(cat_oof_file)
    test_cat_seed_ensemble_v3_5 = np.load(cat_test_file)

else:
    print("\nCatBoost v3 5-seed predictions not found. Training from scratch...")

    SEEDS = [42, 2024, 3407, 777, 999]
    N_SPLITS = 5


    X_cb = X.copy()
    X_test_cb = X_test.copy()

    cat_features = X_cb.select_dtypes(include=["object", "category"]).columns.tolist()

    for col in cat_features:
        X_cb[col] = X_cb[col].fillna("missing").astype(str)
        X_test_cb[col] = X_test_cb[col].fillna("missing").astype(str)

    print("Categorical features:", cat_features)
    print("Number of categorical features:", len(cat_features))
    print("Remaining categorical NaN train:", X_cb[cat_features].isna().sum().sum())
    print("Remaining categorical NaN test:", X_test_cb[cat_features].isna().sum().sum())

    cat_oof_list_v3_5 = []
    cat_test_list_v3_5 = []
    cat_seed_scores_v3_5 = {}

    for seed in SEEDS:
        print("\n" + "=" * 70)
        print(f"CatBoost v3 5-seed training | Seed: {seed}")
        print("=" * 70)

        kf = KFold(
            n_splits=N_SPLITS,
            shuffle=True,
            random_state=seed
        )

        oof_pred = np.zeros(len(X_cb))
        test_pred = np.zeros(len(X_test_cb))
        fold_scores = []

        for fold, (train_idx, valid_idx) in enumerate(kf.split(X_cb, y), start=1):
            print(f"\nSeed {seed} | Fold {fold}")

            X_train = X_cb.iloc[train_idx]
            y_train = y.iloc[train_idx] if hasattr(y, "iloc") else y[train_idx]

            X_valid = X_cb.iloc[valid_idx]
            y_valid = y.iloc[valid_idx] if hasattr(y, "iloc") else y[valid_idx]

            train_pool = Pool(
                X_train,
                y_train,
                cat_features=cat_features
            )

            valid_pool = Pool(
                X_valid,
                y_valid,
                cat_features=cat_features
            )

            test_pool = Pool(
                X_test_cb,
                cat_features=cat_features
            )

            model = CatBoostRegressor(
                loss_function="RMSE",
                eval_metric="RMSE",
                iterations=5000,
                learning_rate=0.03,
                depth=6,
                l2_leaf_reg=3,
                random_seed=seed,
                verbose=500,
                early_stopping_rounds=300,
                allow_writing_files=False
            )

            model.fit(
                train_pool,
                eval_set=valid_pool,
                use_best_model=True
            )

            valid_pred = model.predict(valid_pool)
            fold_test_pred = model.predict(test_pool)

            oof_pred[valid_idx] = valid_pred
            test_pred += fold_test_pred / N_SPLITS

            fold_rmse = rmse(y_valid, valid_pred)
            fold_scores.append(fold_rmse)

            print(f"Seed {seed} | Fold {fold} RMSE: {fold_rmse:.6f}")

        seed_rmse = rmse(y, oof_pred)

        cat_oof_list_v3_5.append(oof_pred)
        cat_test_list_v3_5.append(test_pred)

        cat_seed_scores_v3_5[seed] = {
            "fold_scores": fold_scores,
            "seed_rmse": seed_rmse
        }

        print(f"\nSeed {seed} OOF RMSE: {seed_rmse:.6f}")

    assert len(cat_oof_list_v3_5) > 0, "CatBoost OOF listesi boş kaldı."
    assert len(cat_test_list_v3_5) > 0, "CatBoost test listesi boş kaldı."

    oof_cat_seed_ensemble_v3_5 = np.mean(cat_oof_list_v3_5, axis=0)
    test_cat_seed_ensemble_v3_5 = np.mean(cat_test_list_v3_5, axis=0)

    np.save(cat_oof_file, oof_cat_seed_ensemble_v3_5)
    np.save(cat_test_file, test_cat_seed_ensemble_v3_5)

    print("\nSaved:", cat_oof_file)
    print("Saved:", cat_test_file)


print("\nCatBoost v3 5-seed OOF:", rmse(y, oof_cat_seed_ensemble_v3_5))



assert oof_cat_seed_ensemble_v3_5.shape[0] == len(y), "CatBoost OOF shape hatalı."
assert oof_hgb_v3.shape[0] == len(y), "HGB OOF shape hatalı."
assert oof_lgbm_v3.shape[0] == len(y), "LGBM OOF shape hatalı."

assert test_cat_seed_ensemble_v3_5.shape[0] == len(X_test), "CatBoost test shape hatalı."
assert test_hgb_v3.shape[0] == len(X_test), "HGB test shape hatalı."
assert test_lgbm_v3.shape[0] == len(X_test), "LGBM test shape hatalı."




oof_matrix_v3_5 = np.column_stack([
    oof_cat_seed_ensemble_v3_5,
    oof_hgb_v3,
    oof_lgbm_v3
])

test_matrix_v3_5 = np.column_stack([
    test_cat_seed_ensemble_v3_5,
    test_hgb_v3,
    test_lgbm_v3
])

model_names_v3_5 = [
    "CatBoost v3 5 Seed Ensemble",
    "HGB v3",
    "LightGBM v3"
]


def blend_rmse_v3_5(weights):
    preds = oof_matrix_v3_5 @ weights
    return rmse(y, preds)


n_models = oof_matrix_v3_5.shape[1]
initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result_v3_5 = minimize(
    blend_rmse_v3_5,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights_v3_5 = result_v3_5.x
best_oof_preds_v3_5 = oof_matrix_v3_5 @ best_weights_v3_5
best_test_preds_v3_5 = test_matrix_v3_5 @ best_weights_v3_5


print("\n" + "=" * 70)
print("DENEY 20E v3 5-seed optimized blend")
print("=" * 70)

print("Optimization success:", result_v3_5.success)
print("Best weights:")

for name, weight in zip(model_names_v3_5, best_weights_v3_5):
    print(f"{name}: {weight:.6f}")

print("\nBase model OOF scores:")
print("CatBoost v3 5 Seed Ensemble:", rmse(y, oof_cat_seed_ensemble_v3_5))
print("HGB v3:", rmse(y, oof_hgb_v3))
print("LightGBM v3:", rmse(y, oof_lgbm_v3))

print("\nDeney 20E v3 5-seed blend OOF:", rmse(y, best_oof_preds_v3_5))



np.save("oof_20e_recreated.npy", best_oof_preds_v3_5)
np.save("test_20e_recreated.npy", best_test_preds_v3_5)

print("\nSaved: oof_20e_recreated.npy")
print("Saved: test_20e_recreated.npy")



submission_20e_recreated = pd.DataFrame({
    "id": test["id"],
    "Degerlendirme Puani": best_test_preds_v3_5
})

submission_20e_recreated.to_csv("submission_20e_recreated.csv", index=False)

print("\nSubmission saved: submission_20e_recreated.csv")
print(submission_20e_recreated.head())
print("\nSubmission shape:", submission_20e_recreated.shape)
print("\nMissing values:")
print(submission_20e_recreated.isna().sum())

X shape: (56000, 23)
X_test shape: (24000, 23)
y shape: (56000,)

Loaded base models:
HGB OOF: (56000,) | Test: (24000,) | RMSE: 1.2293893343402866
LGBM OOF: (56000,) | Test: (24000,) | RMSE: 1.2310131834046825

CatBoost v3 5-seed predictions not found. Training from scratch...
Categorical features: ['cinsiyet', 'meslek', 'ulke', 'kronotip', 'ruh_sagligi_durumu', 'mevsim', 'gun_tipi']
Number of categorical features: 7
Remaining categorical NaN train: 0
Remaining categorical NaN test: 0

======================================================================
CatBoost v3 5-seed training | Seed: 42
======================================================================

Seed 42 | Fold 1
0:	learn: 2.1962065	test: 2.2069443	best: 2.2069443 (0)	total: 8.11ms	remaining: 40.5s
500:	learn: 1.1958354	test: 1.2241326	best: 1.2241326 (500)	total: 3.67s	remaining: 33s
1000:	learn: 1.1711294	test: 1.2209564	best: 1.2209564 (1000)	total: 8.16s	remaining: 32.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.220786278
bestIteration = 1079

Shrink model to first 1080 iterations.
Seed 42 | Fold 1 RMSE: 1.220786

Seed 42 | Fold 2
0:	learn: 2.1998516	test: 2.1910527	best: 2.1910527 (0)	total: 8.89ms	remaining: 44.4s
500:	learn: 1.1975040	test: 1.2199261	best: 1.2199241 (498)	total: 3.91s	remaining: 35.1s
1000:	learn: 1.1703787	test: 1.2176194	best: 1.2175255 (978)	total: 7.78s	remaining: 31.1s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.217525462
bestIteration = 978

Shrink model to first 979 iterations.
Seed 42 | Fold 2 RMSE: 1.217525

Seed 42 | Fold 3
0:	learn: 2.1984890	test: 2.1967336	best: 2.1967336 (0)	total: 8.54ms	remaining: 42.7s
500:	learn: 1.2013709	test: 1.2055482	best: 1.2055482 (500)	total: 3.94s	remaining: 35.4s
1000:	learn: 1.1769459	test: 1.2022033	best: 1.2021440 (987)	total: 7.7s	remaining: 30.8s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.202014167
bestIteration = 1039

Shrink model to first 1040 iterations.
Seed 42 | Fold 3 RMSE: 1.202014

Seed 42 | Fold 4
0:	learn: 2.2000730	test: 2.1897877	best: 2.1897877 (0)	total: 7.43ms	remaining: 37.1s
500:	learn: 1.1969944	test: 1.2101345	best: 1.2101311 (499)	total: 3.96s	remaining: 35.6s
1000:	learn: 1.1710011	test: 1.2095256	best: 1.2090375 (763)	total: 7.81s	remaining: 31.2s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.209037463
bestIteration = 763

Shrink model to first 764 iterations.
Seed 42 | Fold 4 RMSE: 1.209037

Seed 42 | Fold 5
0:	learn: 2.1961241	test: 2.2058237	best: 2.2058237 (0)	total: 7.85ms	remaining: 39.2s
500:	learn: 1.1939402	test: 1.2347749	best: 1.2347749 (500)	total: 3.84s	remaining: 34.5s
1000:	learn: 1.1683380	test: 1.2321318	best: 1.2320437 (902)	total: 7.67s	remaining: 30.7s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.232043705
bestIteration = 902

Shrink model to first 903 iterations.
Seed 42 | Fold 5 RMSE: 1.232044

Seed 42 OOF RMSE: 1.216325

======================================================================
CatBoost v3 5-seed training | Seed: 2024
======================================================================

Seed 2024 | Fold 1
0:	learn: 2.1997709	test: 2.1864762	best: 2.1864762 (0)	total: 7.57ms	remaining: 37.8s
500:	learn: 1.1953426	test: 1.2262969	best: 1.2262969 (500)	total: 3.95s	remaining: 35.5s
1000:	learn: 1.1703534	test: 1.2232186	best: 1.2232168 (940)	total: 7.74s	remaining: 30.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.222700394
bestIteration = 1169

Shrink model to first 1170 iterations.
Seed 2024 | Fold 1 RMSE: 1.222700

Seed 2024 | Fold 2
0:	learn: 2.1967878	test: 2.1985992	best: 2.1985992 (0)	total: 8.48ms	remaining: 42.4s
500:	learn: 1.1981464	test: 1.2168220	best: 1.2168220 (500)	total: 3.91s	remaining: 35.1s
1000:	learn: 1.1699776	test: 1.2138154	best: 1.2137718 (994)	total: 7.73s	remaining: 30.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.213771777
bestIteration = 994

Shrink model to first 995 iterations.
Seed 2024 | Fold 2 RMSE: 1.213772

Seed 2024 | Fold 3
0:	learn: 2.1945370	test: 2.2079861	best: 2.2079861 (0)	total: 9.08ms	remaining: 45.4s
500:	learn: 1.1923063	test: 1.2316173	best: 1.2316110 (498)	total: 3.91s	remaining: 35.1s
1000:	learn: 1.1659564	test: 1.2297174	best: 1.2294303 (930)	total: 7.76s	remaining: 31s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.229430305
bestIteration = 930

Shrink model to first 931 iterations.
Seed 2024 | Fold 3 RMSE: 1.229430

Seed 2024 | Fold 4
0:	learn: 2.1978549	test: 2.1945188	best: 2.1945188 (0)	total: 7.49ms	remaining: 37.4s
500:	learn: 1.1995083	test: 1.2071674	best: 1.2071674 (500)	total: 3.79s	remaining: 34.1s
1000:	learn: 1.1736812	test: 1.2048819	best: 1.2048798 (998)	total: 7.57s	remaining: 30.2s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.204775879
bestIteration = 1150

Shrink model to first 1151 iterations.
Seed 2024 | Fold 4 RMSE: 1.204776

Seed 2024 | Fold 5
0:	learn: 2.1969158	test: 2.1985207	best: 2.1985207 (0)	total: 7.96ms	remaining: 39.8s
500:	learn: 1.1987382	test: 1.2128088	best: 1.2128088 (500)	total: 3.8s	remaining: 34.1s
1000:	learn: 1.1725086	test: 1.2100154	best: 1.2099598 (908)	total: 7.66s	remaining: 30.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.209886524
bestIteration = 1061

Shrink model to first 1062 iterations.
Seed 2024 | Fold 5 RMSE: 1.209887

Seed 2024 OOF RMSE: 1.216145

======================================================================
CatBoost v3 5-seed training | Seed: 3407
======================================================================

Seed 3407 | Fold 1
0:	learn: 2.1996540	test: 2.1907907	best: 2.1907907 (0)	total: 6.8ms	remaining: 34s
500:	learn: 1.1985392	test: 1.2095111	best: 1.2095111 (500)	total: 3.81s	remaining: 34.2s
1000:	learn: 1.1723972	test: 1.2072919	best: 1.2069394 (814)	total: 7.63s	remaining: 30.5s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.206939361
bestIteration = 814

Shrink model to first 815 iterations.
Seed 3407 | Fold 1 RMSE: 1.206939

Seed 3407 | Fold 2
0:	learn: 2.1940630	test: 2.2126590	best: 2.2126590 (0)	total: 8.38ms	remaining: 41.9s
500:	learn: 1.1954469	test: 1.2277162	best: 1.2277162 (500)	total: 3.82s	remaining: 34.3s
1000:	learn: 1.1680377	test: 1.2247940	best: 1.2247907 (989)	total: 7.66s	remaining: 30.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.224573625
bestIteration = 1170

Shrink model to first 1171 iterations.
Seed 3407 | Fold 2 RMSE: 1.224574

Seed 3407 | Fold 3
0:	learn: 2.2026834	test: 2.1772246	best: 2.1772246 (0)	total: 8.43ms	remaining: 42.1s
500:	learn: 1.1965206	test: 1.2213811	best: 1.2213693 (499)	total: 3.83s	remaining: 34.4s
1000:	learn: 1.1682628	test: 1.2184126	best: 1.2184126 (1000)	total: 7.73s	remaining: 30.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.218395983
bestIteration = 1005

Shrink model to first 1006 iterations.
Seed 3407 | Fold 3 RMSE: 1.218396

Seed 3407 | Fold 4
0:	learn: 2.1964525	test: 2.2030098	best: 2.2030098 (0)	total: 8.08ms	remaining: 40.4s
500:	learn: 1.1972627	test: 1.2170477	best: 1.2170477 (500)	total: 3.89s	remaining: 34.9s
1000:	learn: 1.1712218	test: 1.2149167	best: 1.2145033 (833)	total: 7.79s	remaining: 31.1s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.214503252
bestIteration = 833

Shrink model to first 834 iterations.
Seed 3407 | Fold 4 RMSE: 1.214503

Seed 3407 | Fold 5
0:	learn: 2.1959475	test: 2.2051805	best: 2.2051805 (0)	total: 9.03ms	remaining: 45.1s
500:	learn: 1.1987104	test: 1.2171464	best: 1.2171464 (500)	total: 4.05s	remaining: 36.4s
1000:	learn: 1.1722393	test: 1.2154940	best: 1.2153160 (826)	total: 8s	remaining: 32s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.215294299
bestIteration = 1034

Shrink model to first 1035 iterations.
Seed 3407 | Fold 5 RMSE: 1.215294

Seed 3407 OOF RMSE: 1.215955

======================================================================
CatBoost v3 5-seed training | Seed: 777
======================================================================

Seed 777 | Fold 1
0:	learn: 2.1982655	test: 2.1946882	best: 2.1946882 (0)	total: 8.68ms	remaining: 43.4s
500:	learn: 1.1936779	test: 1.2287975	best: 1.2287969 (499)	total: 3.9s	remaining: 35s
1000:	learn: 1.1672089	test: 1.2263681	best: 1.2263492 (998)	total: 7.78s	remaining: 31.1s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.226224292
bestIteration = 1074

Shrink model to first 1075 iterations.
Seed 777 | Fold 1 RMSE: 1.226224

Seed 777 | Fold 2
0:	learn: 2.1968354	test: 2.1999006	best: 2.1999006 (0)	total: 9.5ms	remaining: 47.5s
500:	learn: 1.1933980	test: 1.2320782	best: 1.2320187 (489)	total: 3.95s	remaining: 35.5s
1000:	learn: 1.1660734	test: 1.2298269	best: 1.2297763 (925)	total: 7.88s	remaining: 31.5s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.229717567
bestIteration = 1133

Shrink model to first 1134 iterations.
Seed 777 | Fold 2 RMSE: 1.229718

Seed 777 | Fold 3
0:	learn: 2.2021308	test: 2.1784269	best: 2.1784269 (0)	total: 9.87ms	remaining: 49.4s
500:	learn: 1.1986651	test: 1.2153741	best: 1.2153695 (499)	total: 4.13s	remaining: 37.1s
1000:	learn: 1.1731120	test: 1.2125570	best: 1.2124841 (994)	total: 8s	remaining: 32s
1500:	learn: 1.1519463	test: 1.2123715	best: 1.2121202 (1253)	total: 12.1s	remaining: 28.1s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.21212021
bestIteration = 1253

Shrink model to first 1254 iterations.
Seed 777 | Fold 3 RMSE: 1.212120

Seed 777 | Fold 4
0:	learn: 2.1958823	test: 2.2040075	best: 2.2040075 (0)	total: 8.23ms	remaining: 41.2s
500:	learn: 1.2012039	test: 1.2032160	best: 1.2032160 (500)	total: 3.88s	remaining: 34.9s
1000:	learn: 1.1756642	test: 1.2005319	best: 1.2004060 (945)	total: 7.71s	remaining: 30.8s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.200405994
bestIteration = 945

Shrink model to first 946 iterations.
Seed 777 | Fold 4 RMSE: 1.200406

Seed 777 | Fold 5
0:	learn: 2.1942502	test: 2.2105868	best: 2.2105868 (0)	total: 9.12ms	remaining: 45.6s
500:	learn: 1.1975289	test: 1.2156875	best: 1.2156875 (500)	total: 3.9s	remaining: 35s
1000:	learn: 1.1697200	test: 1.2130358	best: 1.2128738 (963)	total: 7.92s	remaining: 31.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.212873801
bestIteration = 963

Shrink model to first 964 iterations.
Seed 777 | Fold 5 RMSE: 1.212874

Seed 777 OOF RMSE: 1.216314

======================================================================
CatBoost v3 5-seed training | Seed: 999
======================================================================

Seed 999 | Fold 1
0:	learn: 2.1970783	test: 2.1969662	best: 2.1969662 (0)	total: 8.94ms	remaining: 44.7s
500:	learn: 1.1972836	test: 1.2210318	best: 1.2210318 (500)	total: 3.76s	remaining: 33.8s
1000:	learn: 1.1721233	test: 1.2180113	best: 1.2179424 (987)	total: 7.48s	remaining: 29.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.217839677
bestIteration = 1113

Shrink model to first 1114 iterations.
Seed 999 | Fold 1 RMSE: 1.217840

Seed 999 | Fold 2
0:	learn: 2.1945416	test: 2.2113935	best: 2.2113935 (0)	total: 8.16ms	remaining: 40.8s
500:	learn: 1.1998798	test: 1.2092016	best: 1.2092016 (500)	total: 3.89s	remaining: 34.9s
1000:	learn: 1.1735429	test: 1.2067189	best: 1.2065262 (946)	total: 7.71s	remaining: 30.8s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.206526241
bestIteration = 946

Shrink model to first 947 iterations.
Seed 999 | Fold 2 RMSE: 1.206526

Seed 999 | Fold 3
0:	learn: 2.2003914	test: 2.1872733	best: 2.1872733 (0)	total: 9.19ms	remaining: 45.9s
500:	learn: 1.1935075	test: 1.2257649	best: 1.2257649 (500)	total: 3.99s	remaining: 35.9s
1000:	learn: 1.1673388	test: 1.2227508	best: 1.2227508 (1000)	total: 8.12s	remaining: 32.4s
1500:	learn: 1.1457622	test: 1.2232491	best: 1.2226042 (1218)	total: 12.4s	remaining: 28.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.222604155
bestIteration = 1218

Shrink model to first 1219 iterations.
Seed 999 | Fold 3 RMSE: 1.222604

Seed 999 | Fold 4
0:	learn: 2.1945686	test: 2.2107857	best: 2.2107857 (0)	total: 8.9ms	remaining: 44.5s
500:	learn: 1.1957084	test: 1.2231821	best: 1.2231643 (499)	total: 3.94s	remaining: 35.4s
1000:	learn: 1.1678229	test: 1.2192904	best: 1.2192356 (969)	total: 7.93s	remaining: 31.7s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.219235626
bestIteration = 969

Shrink model to first 970 iterations.
Seed 999 | Fold 4 RMSE: 1.219236

Seed 999 | Fold 5
0:	learn: 2.2016671	test: 2.1819529	best: 2.1819529 (0)	total: 8.52ms	remaining: 42.6s
500:	learn: 1.1955383	test: 1.2184779	best: 1.2184636 (498)	total: 4.05s	remaining: 36.4s
1000:	learn: 1.1676223	test: 1.2165056	best: 1.2164839 (946)	total: 7.98s	remaining: 31.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.216351827
bestIteration = 1163

Shrink model to first 1164 iterations.
Seed 999 | Fold 5 RMSE: 1.216352

Seed 999 OOF RMSE: 1.216524

Saved: oof_cat_seed_ensemble_v3_5.npy
Saved: test_cat_seed_ensemble_v3_5.npy

CatBoost v3 5-seed OOF: 1.2146874339867157

======================================================================
DENEY 20E v3 5-seed optimized blend
======================================================================
Optimization success: True
Best weights:
CatBoost v3 5 Seed Ensemble: 0.866057
HGB v3: 0.081900
LightGBM v3: 0.052043

Base model OOF scores:
CatBoost v3 5 Seed Ensemble: 1.2146874339867157
HGB v3: 1.2293893343402866
LightGBM v3: 1.2310131834046825

Deney 20E v3 5-seed blend OOF: 1.214421487375675

Saved: oof_20e_recreated.npy
Saved: test_20e_recreated.npy

Submission saved: submission_20e_recreated.csv
   id  Degerlendirme Puani
0   1             6.035060
1   2             6.775595
2   3             3.072751
3   4             7.137003
4   5             3.750433

Submission shape: (24000, 2)

Missing values:
id                     0
Degerlendirme Puani    0
dtype: int64

In [21]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error


def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))


oof_20e = np.load("oof_20e_recreated.npy")
test_20e = np.load("test_20e_recreated.npy")

oof_27 = np.load("oof_exp27_cat_native_clean.npy")
test_27 = np.load("test_exp27_cat_native_clean.npy")


print("20E recreated OOF:", rmse(y, oof_20e))
print("Exp27 OOF:", rmse(y, oof_27))


best_score = 999
best_w = None
blend_results = []

for w27 in np.arange(0, 1.001, 0.001):
    blend_oof = (1 - w27) * oof_20e + w27 * oof_27
    score = rmse(y, blend_oof)

    blend_results.append({
        "w_20e": 1 - w27,
        "w_27": w27,
        "rmse": score
    })

    if score < best_score:
        best_score = score
        best_w = w27

blend_results_df = pd.DataFrame(blend_results).sort_values("rmse")

print("Best weight for Exp27:", best_w)
print("Best weight for 20E:", 1 - best_w)
print("Best blend OOF:", best_score)

blend_results_df.head(20)

20E recreated OOF: 1.214421487375675
Exp27 OOF: 1.2146874339867157
Best weight for Exp27: 0.033
Best weight for 20E: 0.967
Best blend OOF: 1.2144211697595806

    w_20e   w_27      rmse
33  0.967  0.033  1.214421
34  0.966  0.034  1.214421
32  0.968  0.032  1.214421
35  0.965  0.035  1.214421
31  0.969  0.031  1.214421
36  0.964  0.036  1.214421
30  0.970  0.030  1.214421
37  0.963  0.037  1.214421
29  0.971  0.029  1.214421
38  0.962  0.038  1.214421
28  0.972  0.028  1.214421
39  0.961  0.039  1.214421
27  0.973  0.027  1.214421
40  0.960  0.040  1.214421
26  0.974  0.026  1.214421
41  0.959  0.041  1.214421
25  0.975  0.025  1.214421
42  0.958  0.042  1.214421
24  0.976  0.024  1.214421
43  0.957  0.043  1.214421

In [22]:
best_w_27 = 0.033
best_w_20e = 0.967

oof_20e = np.load("oof_20e_recreated.npy")
test_20e = np.load("test_20e_recreated.npy")

oof_27 = np.load("oof_exp27_cat_native_clean.npy")
test_27 = np.load("test_exp27_cat_native_clean.npy")

final_oof_blend = best_w_20e * oof_20e + best_w_27 * oof_27
final_test_blend = best_w_20e * test_20e + best_w_27 * test_27

print("Final blend OOF:", rmse(y, final_oof_blend))

Final blend OOF: 1.2144211697595806

In [25]:
submission_final_blend = pd.DataFrame({
    "id": test["id"],
    "Degerlendirme Puani": final_test_blend
})

submission_final_blend.to_csv("submission_20e_recreated_exp27_blend.csv", index=False)

submission_final_blend.head()

   id  Degerlendirme Puani
0   1             6.036028
1   2             6.776145
2   3             3.072168
3   4             7.136535
4   5             3.750549

In [26]:
submission_final_blend = pd.DataFrame({
    "id": test["id"],
    "bilissel_performans_skoru": final_test_blend
})

submission_final_blend.to_csv("submission_20e_recreated_exp27_blend_fixed.csv", index=False)

submission_final_blend.head()

   id  bilissel_performans_skoru
0   1                   6.036028
1   2                   6.776145
2   3                   3.072168
3   4                   7.136535
4   5                   3.750549

In [27]:
print(submission_final_blend.shape)
print(submission_final_blend.isna().sum())
print(submission_final_blend.head())

(24000, 2)
id                           0
bilissel_performans_skoru    0
dtype: int64
   id  bilissel_performans_skoru
0   1                   6.036028
1   2                   6.776145
2   3                   3.072168
3   4                   7.136535
4   5                   3.750549

In [28]:
exp_results.append({
    "experiment": "20E_recreated_exp27_blend",
    "model": "20E recreated + Exp27",
    "local_oof_rmse": 1.2144211697595806,
    "public_lb": 1.20268,
    "weights": "20E=0.967, Exp27=0.033",
    "submission": "submission_20e_recreated_exp27_blend_fixed.csv",
    "notes": "Improved public score from 1.20273 to 1.20268"
})

pd.DataFrame(exp_results)

,experiment,model,cv,oof_rmse,features,cat_features,notes,local_oof_rmse,public_lb,weights,submission
0,exp27_cat_native_clean,CatBoost,5-fold x 5-seed,1.21469,23.0,7.0,"Native categorical, categorical missing fixed",NaN,NaN,NaN,NaN
1,20E_recreated_exp27_blend,20E recreated + Exp27,NaN,NaN,NaN,NaN,Improved public score from 1.20273 to 1.20268,1.214421,1.20268,"20E=0.967, Exp27=0.033",submission_20e_recreated_exp27_blend_fixed.csv

In [ ]:
# ============================================================
# DENEY 28
# CatBoost 5-seed + Feature Engineering + Best Blend Comparison
# ============================================================

import os
import numpy as np
import pandas as pd

from itertools import combinations
from scipy.optimize import minimize
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from catboost import CatBoostRegressor, Pool




def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))



assert "X" in globals(), "X yok."
assert "X_test" in globals(), "X_test yok."
assert "y" in globals(), "y yok."
assert "test" in globals(), "test yok."

print("Original X:", X.shape)
print("Original X_test:", X_test.shape)
print("y:", y.shape)



def safe_div(a, b):
    return a / (b.replace(0, np.nan) + 1e-6)


def find_col(columns, keywords):
    """
    Kolon isimlerinde verilen keyword'leri arar.
    Örn: keywords=["uyku", "süre"] -> uyku_suresi gibi kolonları yakalamaya çalışır.
    """
    cols_lower = {c: c.lower() for c in columns}

    for original_col, lower_col in cols_lower.items():
        ok = True
        for kw in keywords:
            if kw.lower() not in lower_col:
                ok = False
                break
        if ok:
            return original_col

    return None


def add_if_exists_ratio(X_train_fe, X_test_fe, numerator_col, denominator_col, new_col):
    if numerator_col is not None and denominator_col is not None:
        X_train_fe[new_col] = safe_div(X_train_fe[numerator_col], X_train_fe[denominator_col])
        X_test_fe[new_col] = safe_div(X_test_fe[numerator_col], X_test_fe[denominator_col])
        print("Added ratio:", new_col)


def add_if_exists_interaction(X_train_fe, X_test_fe, col1, col2, new_col):
    if col1 is not None and col2 is not None:
        X_train_fe[new_col] = X_train_fe[col1] * X_train_fe[col2]
        X_test_fe[new_col] = X_test_fe[col1] * X_test_fe[col2]
        print("Added interaction:", new_col)



def make_exp28_features(X_base, X_test_base):
    X_fe = X_base.copy()
    X_test_fe = X_test_base.copy()

    for df in [X_fe, X_test_fe]:
        if "id" in df.columns:
            df.drop(columns=["id"], inplace=True)

    cat_cols = X_fe.select_dtypes(include=["object", "category"]).columns.tolist()

    print("\nOriginal categorical columns:", cat_cols)

    for col in cat_cols:
        X_fe[col] = X_fe[col].fillna("missing").astype(str)
        X_test_fe[col] = X_test_fe[col].fillna("missing").astype(str)


    preferred_cat_pairs = [
        ("kronotip", "gun_tipi"),
        ("mevsim", "kronotip"),
        ("meslek", "gun_tipi"),
        ("ruh_sagligi_durumu", "gun_tipi"),
        ("cinsiyet", "meslek"),
        ("ulke", "meslek"),
        ("mevsim", "gun_tipi"),
        ("ruh_sagligi_durumu", "kronotip"),
    ]

    for c1, c2 in preferred_cat_pairs:
        if c1 in X_fe.columns and c2 in X_fe.columns:
            new_col = f"{c1}__{c2}"
            X_fe[new_col] = X_fe[c1].astype(str) + "__" + X_fe[c2].astype(str)
            X_test_fe[new_col] = X_test_fe[c1].astype(str) + "__" + X_test_fe[c2].astype(str)
            print("Added cat combo:", new_col)


    num_cols = X_fe.select_dtypes(include=[np.number]).columns.tolist()

    print("\nOriginal numeric columns:", num_cols)

    X_fe["num_missing_count"] = X_fe[num_cols].isna().sum(axis=1)
    X_test_fe["num_missing_count"] = X_test_fe[num_cols].isna().sum(axis=1)

    X_fe["num_mean"] = X_fe[num_cols].mean(axis=1)
    X_test_fe["num_mean"] = X_test_fe[num_cols].mean(axis=1)

    X_fe["num_std"] = X_fe[num_cols].std(axis=1)
    X_test_fe["num_std"] = X_test_fe[num_cols].std(axis=1)

    X_fe["num_min"] = X_fe[num_cols].min(axis=1)
    X_test_fe["num_min"] = X_test_fe[num_cols].min(axis=1)

    X_fe["num_max"] = X_fe[num_cols].max(axis=1)
    X_test_fe["num_max"] = X_test_fe[num_cols].max(axis=1)

    X_fe["num_range"] = X_fe["num_max"] - X_fe["num_min"]
    X_test_fe["num_range"] = X_test_fe["num_max"] - X_test_fe["num_min"]


    columns = X_fe.columns.tolist()

    sleep_col = find_col(columns, ["uyku"])
    screen_col = find_col(columns, ["ekran"])
    physical_col = find_col(columns, ["fizik"])
    stress_col = find_col(columns, ["stres"])
    age_col = find_col(columns, ["yaş"]) or find_col(columns, ["yas"])
    social_col = find_col(columns, ["sosyal"])
    work_col = find_col(columns, ["çalış"]) or find_col(columns, ["calis"])
    caffeine_col = find_col(columns, ["kafe"]) or find_col(columns, ["kahve"])

    print("\nDetected special columns:")
    print("sleep_col:", sleep_col)
    print("screen_col:", screen_col)
    print("physical_col:", physical_col)
    print("stress_col:", stress_col)
    print("age_col:", age_col)
    print("social_col:", social_col)
    print("work_col:", work_col)
    print("caffeine_col:", caffeine_col)

    add_if_exists_ratio(X_fe, X_test_fe, screen_col, sleep_col, "screen_sleep_ratio")
    add_if_exists_ratio(X_fe, X_test_fe, physical_col, sleep_col, "physical_sleep_ratio")
    add_if_exists_ratio(X_fe, X_test_fe, social_col, screen_col, "social_screen_ratio")
    add_if_exists_ratio(X_fe, X_test_fe, work_col, sleep_col, "work_sleep_ratio")
    add_if_exists_ratio(X_fe, X_test_fe, caffeine_col, sleep_col, "caffeine_sleep_ratio")

    add_if_exists_interaction(X_fe, X_test_fe, stress_col, screen_col, "stress_x_screen")
    add_if_exists_interaction(X_fe, X_test_fe, stress_col, sleep_col, "stress_x_sleep")
    add_if_exists_interaction(X_fe, X_test_fe, stress_col, physical_col, "stress_x_physical")
    add_if_exists_interaction(X_fe, X_test_fe, screen_col, physical_col, "screen_x_physical")
    add_if_exists_interaction(X_fe, X_test_fe, age_col, sleep_col, "age_x_sleep")
    add_if_exists_interaction(X_fe, X_test_fe, age_col, screen_col, "age_x_screen")

    # --------------------------------------------------------
    # 4) Yaş bin feature'ı varsa
    # --------------------------------------------------------

    if age_col is not None:
        X_fe["age_bin"] = pd.cut(
            X_fe[age_col],
            bins=[-np.inf, 18, 25, 35, 45, 60, np.inf],
            labels=["age_0_18", "age_19_25", "age_26_35", "age_36_45", "age_46_60", "age_60_plus"]
        ).astype(str)

        X_test_fe["age_bin"] = pd.cut(
            X_test_fe[age_col],
            bins=[-np.inf, 18, 25, 35, 45, 60, np.inf],
            labels=["age_0_18", "age_19_25", "age_26_35", "age_36_45", "age_46_60", "age_60_plus"]
        ).astype(str)

        print("Added categorical age_bin")

    # --------------------------------------------------------
    # 5) Inf temizliği
    # --------------------------------------------------------

    X_fe = X_fe.replace([np.inf, -np.inf], np.nan)
    X_test_fe = X_test_fe.replace([np.inf, -np.inf], np.nan)

    # Son kategorik kolonlar
    final_cat_cols = X_fe.select_dtypes(include=["object", "category"]).columns.tolist()

    for col in final_cat_cols:
        X_fe[col] = X_fe[col].fillna("missing").astype(str)
        X_test_fe[col] = X_test_fe[col].fillna("missing").astype(str)

    return X_fe, X_test_fe, final_cat_cols


# ------------------------------------------------------------
# Create Exp28 features
# ------------------------------------------------------------

X28, X_test28, cat_features28 = make_exp28_features(X, X_test)

print("\nExp28 X shape:", X28.shape)
print("Exp28 X_test shape:", X_test28.shape)
print("Exp28 categorical feature count:", len(cat_features28))
print("Exp28 categorical features:", cat_features28)
print("Remaining categorical NaN train:", X28[cat_features28].isna().sum().sum())
print("Remaining categorical NaN test:", X_test28[cat_features28].isna().sum().sum())


# ------------------------------------------------------------
# Train CatBoost 5-seed on Exp28 features
# ------------------------------------------------------------

EXP_NAME = "exp28_cat_fe_clean"
SEEDS = [42, 2024, 3407, 777, 999]
N_SPLITS = 5

cat_oof_list_exp28 = []
cat_test_list_exp28 = []
cat_seed_scores_exp28 = {}

for seed in SEEDS:
    print("\n" + "=" * 70)
    print(f"{EXP_NAME} | Seed: {seed}")
    print("=" * 70)

    kf = KFold(
        n_splits=N_SPLITS,
        shuffle=True,
        random_state=seed
    )

    oof_pred = np.zeros(len(X28))
    test_pred = np.zeros(len(X_test28))
    fold_scores = []

    for fold, (train_idx, valid_idx) in enumerate(kf.split(X28, y), start=1):
        print(f"\nSeed {seed} | Fold {fold}")

        X_train = X28.iloc[train_idx]
        y_train = y.iloc[train_idx] if hasattr(y, "iloc") else y[train_idx]

        X_valid = X28.iloc[valid_idx]
        y_valid = y.iloc[valid_idx] if hasattr(y, "iloc") else y[valid_idx]

        train_pool = Pool(
            X_train,
            y_train,
            cat_features=cat_features28
        )

        valid_pool = Pool(
            X_valid,
            y_valid,
            cat_features=cat_features28
        )

        test_pool = Pool(
            X_test28,
            cat_features=cat_features28
        )

        model = CatBoostRegressor(
            loss_function="RMSE",
            eval_metric="RMSE",
            iterations=6000,
            learning_rate=0.025,
            depth=6,
            l2_leaf_reg=4,
            random_seed=seed,
            verbose=500,
            early_stopping_rounds=350,
            allow_writing_files=False
        )

        model.fit(
            train_pool,
            eval_set=valid_pool,
            use_best_model=True
        )

        valid_pred = model.predict(valid_pool)
        fold_test_pred = model.predict(test_pool)

        oof_pred[valid_idx] = valid_pred
        test_pred += fold_test_pred / N_SPLITS

        fold_rmse = rmse(y_valid, valid_pred)
        fold_scores.append(fold_rmse)

        print(f"Seed {seed} | Fold {fold} RMSE: {fold_rmse:.6f}")

    seed_rmse = rmse(y, oof_pred)

    cat_oof_list_exp28.append(oof_pred)
    cat_test_list_exp28.append(test_pred)

    cat_seed_scores_exp28[seed] = {
        "fold_scores": fold_scores,
        "seed_rmse": seed_rmse
    }

    print(f"\nSeed {seed} OOF RMSE: {seed_rmse:.6f}")


assert len(cat_oof_list_exp28) > 0, "Exp28 OOF listesi boş kaldı."
assert len(cat_test_list_exp28) > 0, "Exp28 test listesi boş kaldı."

oof_exp28_cat_fe_clean = np.mean(cat_oof_list_exp28, axis=0)
test_exp28_cat_fe_clean = np.mean(cat_test_list_exp28, axis=0)

exp28_score = rmse(y, oof_exp28_cat_fe_clean)

print("\n" + "=" * 70)
print(f"{EXP_NAME} OOF RMSE:", exp28_score)
print("=" * 70)

np.save("oof_exp28_cat_fe_clean.npy", oof_exp28_cat_fe_clean)
np.save("test_exp28_cat_fe_clean.npy", test_exp28_cat_fe_clean)

print("Saved: oof_exp28_cat_fe_clean.npy")
print("Saved: test_exp28_cat_fe_clean.npy")


# ------------------------------------------------------------
# Compare with current best
# Current best = 20E recreated + Exp27 blend
# ------------------------------------------------------------

oof_20e = np.load("oof_20e_recreated.npy")
test_20e = np.load("test_20e_recreated.npy")

oof_27 = np.load("oof_exp27_cat_native_clean.npy")
test_27 = np.load("test_exp27_cat_native_clean.npy")

current_best_oof = 0.967 * oof_20e + 0.033 * oof_27
current_best_test = 0.967 * test_20e + 0.033 * test_27

current_best_score = rmse(y, current_best_oof)

print("\nCurrent best OOF:", current_best_score)
print("Exp28 OOF:", exp28_score)


# ------------------------------------------------------------
# Blend current best with Exp28
# ------------------------------------------------------------

best_score = 999
best_w_exp28 = None
blend_results_exp28 = []

for w_exp28 in np.arange(0, 1.001, 0.001):
    blend_oof = (1 - w_exp28) * current_best_oof + w_exp28 * oof_exp28_cat_fe_clean
    score = rmse(y, blend_oof)

    blend_results_exp28.append({
        "w_current_best": 1 - w_exp28,
        "w_exp28": w_exp28,
        "rmse": score
    })

    if score < best_score:
        best_score = score
        best_w_exp28 = w_exp28

blend_results_exp28_df = pd.DataFrame(blend_results_exp28).sort_values("rmse")

print("\n" + "=" * 70)
print("Current Best + Exp28 Blend")
print("=" * 70)

print("Best weight for Exp28:", best_w_exp28)
print("Best weight for current best:", 1 - best_w_exp28)
print("Best blend OOF:", best_score)

display(blend_results_exp28_df.head(20))


# ------------------------------------------------------------
# Save final candidate submission
# ------------------------------------------------------------

final_oof_exp28_blend = (1 - best_w_exp28) * current_best_oof + best_w_exp28 * oof_exp28_cat_fe_clean
final_test_exp28_blend = (1 - best_w_exp28) * current_best_test + best_w_exp28 * test_exp28_cat_fe_clean

print("\nFinal Exp28 blend OOF:", rmse(y, final_oof_exp28_blend))

submission_exp28_blend = pd.DataFrame({
    "id": test["id"],
    "bilissel_performans_skoru": final_test_exp28_blend
})

submission_exp28_blend.to_csv("submission_exp28_current_best_blend.csv", index=False)

print("\nSaved: submission_exp28_current_best_blend.csv")
print(submission_exp28_blend.head())
print("\nShape:", submission_exp28_blend.shape)
print("\nMissing:")
print(submission_exp28_blend.isna().sum())
print("\nPrediction describe:")
print(submission_exp28_blend["bilissel_performans_skoru"].describe())

Original X: (56000, 23)
Original X_test: (24000, 23)
y: (56000,)

Original categorical columns: ['cinsiyet', 'meslek', 'ulke', 'kronotip', 'ruh_sagligi_durumu', 'mevsim', 'gun_tipi']
Added cat combo: kronotip__gun_tipi
Added cat combo: mevsim__kronotip
Added cat combo: meslek__gun_tipi
Added cat combo: ruh_sagligi_durumu__gun_tipi
Added cat combo: cinsiyet__meslek
Added cat combo: ulke__meslek
Added cat combo: mevsim__gun_tipi
Added cat combo: ruh_sagligi_durumu__kronotip

Original numeric columns: ['yas', 'vucut_kitle_indeksi', 'rem_yuzdesi', 'derin_uyku_yuzdesi', 'uykuya_dalma_suresi_dk', 'gecelik_uyanma_sayisi', 'uyku_oncesi_kafein_mg', 'uyku_oncesi_ekran_suresi_dk', 'gunluk_adim_sayisi', 'sekerleme_suresi_dk', 'stres_skoru', 'gunluk_calisma_saati', 'dinlenik_nabiz_bpm', 'oda_sicakligi_celsius', 'hafta_sonu_uyku_farki_saat']

Detected special columns:
sleep_col: derin_uyku_yuzdesi
screen_col: uyku_oncesi_ekran_suresi_dk
physical_col: None
stress_col: stres_skoru
age_col: yas
social_col: None
work_col: gunluk_calisma_saati
caffeine_col: uyku_oncesi_kafein_mg
Added ratio: screen_sleep_ratio
Added ratio: work_sleep_ratio
Added ratio: caffeine_sleep_ratio
Added interaction: stress_x_screen
Added interaction: stress_x_sleep
Added interaction: age_x_sleep
Added interaction: age_x_screen
Added categorical age_bin

Exp28 X shape: (56000, 44)
Exp28 X_test shape: (24000, 44)
Exp28 categorical feature count: 16
Exp28 categorical features: ['cinsiyet', 'meslek', 'ulke', 'kronotip', 'ruh_sagligi_durumu', 'mevsim', 'gun_tipi', 'kronotip__gun_tipi', 'mevsim__kronotip', 'meslek__gun_tipi', 'ruh_sagligi_durumu__gun_tipi', 'cinsiyet__meslek', 'ulke__meslek', 'mevsim__gun_tipi', 'ruh_sagligi_durumu__kronotip', 'age_bin']
Remaining categorical NaN train: 0
Remaining categorical NaN test: 0

======================================================================
exp28_cat_fe_clean | Seed: 42
======================================================================

Seed 42 | Fold 1
0:	learn: 2.1996216	test: 2.2108905	best: 2.2108905 (0)	total: 12.9ms	remaining: 1m 17s
500:	learn: 1.2031533	test: 1.2250634	best: 1.2250634 (500)	total: 8.65s	remaining: 1m 35s
1000:	learn: 1.1827451	test: 1.2204497	best: 1.2204337 (997)	total: 17s	remaining: 1m 24s
1500:	learn: 1.1677591	test: 1.2198824	best: 1.2198437 (1498)	total: 25.3s	remaining: 1m 15s
2000:	learn: 1.1531286	test: 1.2197641	best: 1.2196130 (1928)	total: 33.9s	remaining: 1m 7s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.219613043
bestIteration = 1928

Shrink model to first 1929 iterations.
Seed 42 | Fold 1 RMSE: 1.219613

Seed 42 | Fold 2
0:	learn: 2.2028303	test: 2.1937731	best: 2.1937731 (0)	total: 14.6ms	remaining: 1m 27s
500:	learn: 1.2031181	test: 1.2211022	best: 1.2211022 (500)	total: 8.16s	remaining: 1m 29s
1000:	learn: 1.1817318	test: 1.2175042	best: 1.2174889 (998)	total: 16.4s	remaining: 1m 21s
1500:	learn: 1.1654114	test: 1.2171720	best: 1.2168503 (1399)	total: 25.1s	remaining: 1m 15s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.216850297
bestIteration = 1399

Shrink model to first 1400 iterations.
Seed 42 | Fold 2 RMSE: 1.216850

Seed 42 | Fold 3
0:	learn: 2.2014373	test: 2.2002063	best: 2.2002063 (0)	total: 13.3ms	remaining: 1m 20s
500:	learn: 1.2077519	test: 1.2063755	best: 1.2063755 (500)	total: 8.53s	remaining: 1m 33s
1000:	learn: 1.1871390	test: 1.2014798	best: 1.2014694 (995)	total: 16.8s	remaining: 1m 23s
1500:	learn: 1.1714814	test: 1.2005664	best: 1.2005656 (1499)	total: 25.2s	remaining: 1m 15s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.20041386
bestIteration = 1603

Shrink model to first 1604 iterations.
Seed 42 | Fold 3 RMSE: 1.200414

Seed 42 | Fold 4
0:	learn: 2.2035169	test: 2.1931507	best: 2.1931507 (0)	total: 16.5ms	remaining: 1m 39s
500:	learn: 1.2057376	test: 1.2112535	best: 1.2112535 (500)	total: 8.03s	remaining: 1m 28s
1000:	learn: 1.1839437	test: 1.2076895	best: 1.2076895 (1000)	total: 16.1s	remaining: 1m 20s
1500:	learn: 1.1667629	test: 1.2075070	best: 1.2074720 (1493)	total: 24.4s	remaining: 1m 13s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.207471994
bestIteration = 1493

Shrink model to first 1494 iterations.
Seed 42 | Fold 4 RMSE: 1.207472

Seed 42 | Fold 5
0:	learn: 2.1994604	test: 2.2092109	best: 2.2092109 (0)	total: 13.9ms	remaining: 1m 23s
500:	learn: 1.2009089	test: 1.2371614	best: 1.2371614 (500)	total: 8.21s	remaining: 1m 30s
1000:	learn: 1.1790960	test: 1.2325108	best: 1.2325032 (996)	total: 16.3s	remaining: 1m 21s
1500:	learn: 1.1626510	test: 1.2320227	best: 1.2318904 (1448)	total: 24.6s	remaining: 1m 13s
2000:	learn: 1.1476377	test: 1.2319222	best: 1.2318052 (1747)	total: 32.9s	remaining: 1m 5s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.231805224
bestIteration = 1747

Shrink model to first 1748 iterations.
Seed 42 | Fold 5 RMSE: 1.231805

Seed 42 OOF RMSE: 1.215278

======================================================================
exp28_cat_fe_clean | Seed: 2024
======================================================================

Seed 2024 | Fold 1
0:	learn: 2.2038172	test: 2.1906612	best: 2.1906612 (0)	total: 13ms	remaining: 1m 18s
500:	learn: 1.2020806	test: 1.2268699	best: 1.2268699 (500)	total: 8.13s	remaining: 1m 29s
1000:	learn: 1.1821558	test: 1.2226290	best: 1.2226279 (997)	total: 16.4s	remaining: 1m 21s
1500:	learn: 1.1662592	test: 1.2216612	best: 1.2216457 (1462)	total: 24.6s	remaining: 1m 13s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.221610149
bestIteration = 1637

Shrink model to first 1638 iterations.
Seed 2024 | Fold 1 RMSE: 1.221610

Seed 2024 | Fold 2
0:	learn: 2.2016579	test: 2.2032262	best: 2.2032262 (0)	total: 12.9ms	remaining: 1m 17s
500:	learn: 1.2058907	test: 1.2187150	best: 1.2187150 (500)	total: 8.18s	remaining: 1m 29s
1000:	learn: 1.1834188	test: 1.2135899	best: 1.2135708 (994)	total: 16.5s	remaining: 1m 22s
1500:	learn: 1.1673197	test: 1.2129053	best: 1.2128659 (1495)	total: 24.8s	remaining: 1m 14s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.212865926
bestIteration = 1495

Shrink model to first 1496 iterations.
Seed 2024 | Fold 2 RMSE: 1.212866

Seed 2024 | Fold 3
0:	learn: 2.1990906	test: 2.2123919	best: 2.2123919 (0)	total: 11.9ms	remaining: 1m 11s
500:	learn: 1.1999389	test: 1.2328303	best: 1.2328303 (500)	total: 8.25s	remaining: 1m 30s
1000:	learn: 1.1779443	test: 1.2290270	best: 1.2290038 (999)	total: 16.5s	remaining: 1m 22s
1500:	learn: 1.1615111	test: 1.2290527	best: 1.2288520 (1153)	total: 25.1s	remaining: 1m 15s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.228851953
bestIteration = 1153

Shrink model to first 1154 iterations.
Seed 2024 | Fold 3 RMSE: 1.228852

Seed 2024 | Fold 4
0:	learn: 2.2030725	test: 2.1997425	best: 2.1997425 (0)	total: 14.4ms	remaining: 1m 26s
500:	learn: 1.2076365	test: 1.2086267	best: 1.2086267 (500)	total: 8.33s	remaining: 1m 31s
1000:	learn: 1.1842877	test: 1.2041459	best: 1.2041420 (999)	total: 16.7s	remaining: 1m 23s
1500:	learn: 1.1675667	test: 1.2033923	best: 1.2033560 (1481)	total: 25s	remaining: 1m 15s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.203356013
bestIteration = 1481

Shrink model to first 1482 iterations.
Seed 2024 | Fold 4 RMSE: 1.203356

Seed 2024 | Fold 5
0:	learn: 2.2010985	test: 2.2030065	best: 2.2030065 (0)	total: 12.7ms	remaining: 1m 16s
500:	learn: 1.2051756	test: 1.2149300	best: 1.2149300 (500)	total: 8.2s	remaining: 1m 30s
1000:	learn: 1.1847061	test: 1.2108280	best: 1.2108014 (989)	total: 16.6s	remaining: 1m 23s
1500:	learn: 1.1666831	test: 1.2102067	best: 1.2101428 (1240)	total: 25s	remaining: 1m 15s
2000:	learn: 1.1510045	test: 1.2102627	best: 1.2099261 (1805)	total: 33.6s	remaining: 1m 7s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.209926104
bestIteration = 1805

Shrink model to first 1806 iterations.
Seed 2024 | Fold 5 RMSE: 1.209926

Seed 2024 OOF RMSE: 1.215355

======================================================================
exp28_cat_fe_clean | Seed: 3407
======================================================================

Seed 3407 | Fold 1
0:	learn: 2.2030592	test: 2.1942925	best: 2.1942925 (0)	total: 16.9ms	remaining: 1m 41s
500:	learn: 1.2061451	test: 1.2128820	best: 1.2128820 (500)	total: 8.26s	remaining: 1m 30s
1000:	learn: 1.1851610	test: 1.2078210	best: 1.2078031 (989)	total: 16.4s	remaining: 1m 22s
1500:	learn: 1.1678763	test: 1.2068702	best: 1.2067628 (1468)	total: 24.8s	remaining: 1m 14s
2000:	learn: 1.1522813	test: 1.2065661	best: 1.2064942 (1913)	total: 33.4s	remaining: 1m 6s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.206476551
bestIteration = 2094

Shrink model to first 2095 iterations.
Seed 3407 | Fold 1 RMSE: 1.206477

Seed 3407 | Fold 2
0:	learn: 2.1976876	test: 2.2162607	best: 2.2162607 (0)	total: 15.3ms	remaining: 1m 32s
500:	learn: 1.2036875	test: 1.2299431	best: 1.2299431 (500)	total: 8.21s	remaining: 1m 30s
1000:	learn: 1.1810770	test: 1.2254092	best: 1.2254085 (999)	total: 16.5s	remaining: 1m 22s
1500:	learn: 1.1639530	test: 1.2244104	best: 1.2243527 (1378)	total: 24.9s	remaining: 1m 14s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.224352703
bestIteration = 1378

Shrink model to first 1379 iterations.
Seed 3407 | Fold 2 RMSE: 1.224353

Seed 3407 | Fold 3
0:	learn: 2.2062431	test: 2.1804636	best: 2.1804636 (0)	total: 15.6ms	remaining: 1m 33s
500:	learn: 1.2054917	test: 1.2231450	best: 1.2231450 (500)	total: 8.37s	remaining: 1m 31s
1000:	learn: 1.1830731	test: 1.2184080	best: 1.2184080 (1000)	total: 16.9s	remaining: 1m 24s
1500:	learn: 1.1667924	test: 1.2177607	best: 1.2177594 (1445)	total: 25.6s	remaining: 1m 16s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.217756678
bestIteration = 1514

Shrink model to first 1515 iterations.
Seed 3407 | Fold 3 RMSE: 1.217757

Seed 3407 | Fold 4
0:	learn: 2.2001026	test: 2.2070525	best: 2.2070525 (0)	total: 14.8ms	remaining: 1m 29s
500:	learn: 1.2047553	test: 1.2183207	best: 1.2183207 (500)	total: 8.49s	remaining: 1m 33s
1000:	learn: 1.1832673	test: 1.2138777	best: 1.2138677 (986)	total: 17s	remaining: 1m 24s
1500:	learn: 1.1664152	test: 1.2133388	best: 1.2133388 (1500)	total: 25.5s	remaining: 1m 16s
2000:	learn: 1.1516122	test: 1.2134906	best: 1.2132234 (1777)	total: 34s	remaining: 1m 7s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.213223391
bestIteration = 1777

Shrink model to first 1778 iterations.
Seed 3407 | Fold 4 RMSE: 1.213223

Seed 3407 | Fold 5
0:	learn: 2.2004043	test: 2.2092699	best: 2.2092699 (0)	total: 13.3ms	remaining: 1m 19s
500:	learn: 1.2058545	test: 1.2178591	best: 1.2178591 (500)	total: 8.03s	remaining: 1m 28s
1000:	learn: 1.1846244	test: 1.2149562	best: 1.2149528 (995)	total: 16.3s	remaining: 1m 21s
1500:	learn: 1.1695000	test: 1.2144887	best: 1.2143412 (1374)	total: 24.6s	remaining: 1m 13s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.21434123
bestIteration = 1374

Shrink model to first 1375 iterations.
Seed 3407 | Fold 5 RMSE: 1.214341

Seed 3407 OOF RMSE: 1.215244

======================================================================
exp28_cat_fe_clean | Seed: 777
======================================================================

Seed 777 | Fold 1
0:	learn: 2.2024307	test: 2.1988308	best: 2.1988308 (0)	total: 15.1ms	remaining: 1m 30s
500:	learn: 1.2024989	test: 1.2286639	best: 1.2286639 (500)	total: 8.41s	remaining: 1m 32s
1000:	learn: 1.1815718	test: 1.2255230	best: 1.2255230 (1000)	total: 16.7s	remaining: 1m 23s
1500:	learn: 1.1653434	test: 1.2252915	best: 1.2251244 (1375)	total: 25.1s	remaining: 1m 15s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.22512442
bestIteration = 1375

Shrink model to first 1376 iterations.
Seed 777 | Fold 1 RMSE: 1.225124

Seed 777 | Fold 2
0:	learn: 2.2009577	test: 2.2039397	best: 2.2039397 (0)	total: 16.2ms	remaining: 1m 36s
500:	learn: 1.2002425	test: 1.2363196	best: 1.2363196 (500)	total: 8.76s	remaining: 1m 36s
1000:	learn: 1.1791311	test: 1.2322399	best: 1.2321900 (967)	total: 17s	remaining: 1m 24s
1500:	learn: 1.1633449	test: 1.2316859	best: 1.2316399 (1409)	total: 25.4s	remaining: 1m 16s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.231639864
bestIteration = 1409

Shrink model to first 1410 iterations.
Seed 777 | Fold 2 RMSE: 1.231640

Seed 777 | Fold 3
0:	learn: 2.2060711	test: 2.1822618	best: 2.1822618 (0)	total: 15.3ms	remaining: 1m 31s
500:	learn: 1.2060661	test: 1.2172504	best: 1.2172464 (499)	total: 8.1s	remaining: 1m 28s
1000:	learn: 1.1852951	test: 1.2123106	best: 1.2123106 (1000)	total: 16.3s	remaining: 1m 21s
1500:	learn: 1.1693032	test: 1.2114821	best: 1.2114821 (1500)	total: 24.7s	remaining: 1m 13s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.211418964
bestIteration = 1595

Shrink model to first 1596 iterations.
Seed 777 | Fold 3 RMSE: 1.211419

Seed 777 | Fold 4
0:	learn: 2.1995401	test: 2.2076005	best: 2.2076005 (0)	total: 16.2ms	remaining: 1m 37s
500:	learn: 1.2072160	test: 1.2036822	best: 1.2036822 (500)	total: 8.15s	remaining: 1m 29s
1000:	learn: 1.1874227	test: 1.1994894	best: 1.1994430 (993)	total: 16.3s	remaining: 1m 21s
1500:	learn: 1.1712090	test: 1.1987640	best: 1.1987153 (1449)	total: 24.5s	remaining: 1m 13s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.198715273
bestIteration = 1449

Shrink model to first 1450 iterations.
Seed 777 | Fold 4 RMSE: 1.198715

Seed 777 | Fold 5
0:	learn: 2.1981978	test: 2.2146162	best: 2.2146162 (0)	total: 17.6ms	remaining: 1m 45s
500:	learn: 1.2045422	test: 1.2171369	best: 1.2171169 (498)	total: 8.18s	remaining: 1m 29s
1000:	learn: 1.1842566	test: 1.2127757	best: 1.2127756 (996)	total: 16.4s	remaining: 1m 21s
1500:	learn: 1.1677453	test: 1.2116324	best: 1.2116280 (1490)	total: 24.6s	remaining: 1m 13s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.211547542
bestIteration = 1546

Shrink model to first 1547 iterations.
Seed 777 | Fold 5 RMSE: 1.211548

Seed 777 OOF RMSE: 1.215744

======================================================================
exp28_cat_fe_clean | Seed: 999
======================================================================

Seed 999 | Fold 1
0:	learn: 2.2020455	test: 2.2016742	best: 2.2016742 (0)	total: 16.5ms	remaining: 1m 39s
500:	learn: 1.2043967	test: 1.2216270	best: 1.2216270 (500)	total: 8.12s	remaining: 1m 29s
1000:	learn: 1.1846953	test: 1.2168867	best: 1.2168867 (1000)	total: 16.3s	remaining: 1m 21s
1500:	learn: 1.1687269	test: 1.2157291	best: 1.2156859 (1450)	total: 24.5s	remaining: 1m 13s
2000:	learn: 1.1542092	test: 1.2159203	best: 1.2156348 (1728)	total: 33s	remaining: 1m 5s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.215634775
bestIteration = 1728

Shrink model to first 1729 iterations.
Seed 999 | Fold 1 RMSE: 1.215635

Seed 999 | Fold 2
0:	learn: 2.1991287	test: 2.2160736	best: 2.2160736 (0)	total: 16ms	remaining: 1m 36s
500:	learn: 1.2073398	test: 1.2074788	best: 1.2074788 (500)	total: 8.19s	remaining: 1m 29s
1000:	learn: 1.1871068	test: 1.2035243	best: 1.2035243 (1000)	total: 16.4s	remaining: 1m 22s
1500:	learn: 1.1716212	test: 1.2033936	best: 1.2033184 (1413)	total: 24.7s	remaining: 1m 14s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.203318372
bestIteration = 1413

Shrink model to first 1414 iterations.
Seed 999 | Fold 2 RMSE: 1.203318

Seed 999 | Fold 3
0:	learn: 2.2046131	test: 2.1913860	best: 2.1913860 (0)	total: 13.9ms	remaining: 1m 23s
500:	learn: 1.2014664	test: 1.2262251	best: 1.2262251 (500)	total: 8.47s	remaining: 1m 32s
1000:	learn: 1.1810261	test: 1.2219025	best: 1.2219025 (1000)	total: 16.7s	remaining: 1m 23s
1500:	learn: 1.1639523	test: 1.2209415	best: 1.2209051 (1491)	total: 25s	remaining: 1m 14s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.220905066
bestIteration = 1491

Shrink model to first 1492 iterations.
Seed 999 | Fold 3 RMSE: 1.220905

Seed 999 | Fold 4
0:	learn: 2.1988197	test: 2.2150356	best: 2.2150356 (0)	total: 14ms	remaining: 1m 24s
500:	learn: 1.2021201	test: 1.2242088	best: 1.2242088 (500)	total: 8.15s	remaining: 1m 29s
1000:	learn: 1.1824997	test: 1.2194697	best: 1.2194697 (1000)	total: 16.4s	remaining: 1m 21s
1500:	learn: 1.1658637	test: 1.2181106	best: 1.2181106 (1500)	total: 24.7s	remaining: 1m 14s
2000:	learn: 1.1509848	test: 1.2179840	best: 1.2179676 (1979)	total: 33.2s	remaining: 1m 6s
2500:	learn: 1.1363363	test: 1.2179535	best: 1.2179176 (2483)	total: 41.6s	remaining: 58.2s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.217852905
bestIteration = 2645

Shrink model to first 2646 iterations.
Seed 999 | Fold 4 RMSE: 1.217853

Seed 999 | Fold 5
0:	learn: 2.2061438	test: 2.1860145	best: 2.1860145 (0)	total: 14.2ms	remaining: 1m 25s
500:	learn: 1.2036684	test: 1.2198962	best: 1.2198962 (500)	total: 9.04s	remaining: 1m 39s
1000:	learn: 1.1807285	test: 1.2169083	best: 1.2168874 (988)	total: 17.5s	remaining: 1m 27s
1500:	learn: 1.1640818	test: 1.2169639	best: 1.2166423 (1230)	total: 26.1s	remaining: 1m 18s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.216642258
bestIteration = 1230

Shrink model to first 1231 iterations.
Seed 999 | Fold 5 RMSE: 1.216642

Seed 999 OOF RMSE: 1.214886

======================================================================
exp28_cat_fe_clean OOF RMSE: 1.2135815294276042
======================================================================
Saved: oof_exp28_cat_fe_clean.npy
Saved: test_exp28_cat_fe_clean.npy

Current best OOF: 1.2144211697595806
Exp28 OOF: 1.2135815294276042

======================================================================
Current Best + Exp28 Blend
======================================================================
Best weight for Exp28: 0.658
Best weight for current best: 0.34199999999999997
Best blend OOF: 1.2132691035554823

     w_current_best  w_exp28      rmse
658           0.342    0.658  1.213269
657           0.343    0.657  1.213269
659           0.341    0.659  1.213269
656           0.344    0.656  1.213269
660           0.340    0.660  1.213269
655           0.345    0.655  1.213269
661           0.339    0.661  1.213269
654           0.346    0.654  1.213269
662           0.338    0.662  1.213269
653           0.347    0.653  1.213269
663           0.337    0.663  1.213269
652           0.348    0.652  1.213269
664           0.336    0.664  1.213269
651           0.349    0.651  1.213269
665           0.335    0.665  1.213269
650           0.350    0.650  1.213269
666           0.334    0.666  1.213269
649           0.351    0.649  1.213269
667           0.333    0.667  1.213269
648           0.352    0.648  1.213269

Final Exp28 blend OOF: 1.2132691035554823

Saved: submission_exp28_current_best_blend.csv
   id  bilissel_performans_skoru
0   1                   6.001816
1   2                   6.737925
2   3                   3.044147
3   4                   7.158813
4   5                   3.694694

Shape: (24000, 2)

Missing:
id                           0
bilissel_performans_skoru    0
dtype: int64

Prediction describe:
count    24000.000000
mean         5.937791
std          1.864037
min         -0.229105
25%          4.645149
50%          6.045080
75%          7.321425
max         10.761977
Name: bilissel_performans_skoru, dtype: float64

In [30]:
submission_exp28_blend_clipped = submission_exp28_blend.copy()

submission_exp28_blend_clipped["bilissel_performans_skoru"] = (
    submission_exp28_blend_clipped["bilissel_performans_skoru"]
    .clip(0, 10)
)

submission_exp28_blend_clipped.to_csv(
    "submission_exp28_current_best_blend_clipped.csv",
    index=False
)

print(submission_exp28_blend_clipped.shape)
print(submission_exp28_blend_clipped.isna().sum())
print(submission_exp28_blend_clipped["bilissel_performans_skoru"].describe())

(24000, 2)
id                           0
bilissel_performans_skoru    0
dtype: int64
count    24000.000000
mean         5.937440
std          1.863110
min          0.000000
25%          4.645149
50%          6.045080
75%          7.321425
max         10.000000
Name: bilissel_performans_skoru, dtype: float64