In [27]:
from pathlib import Path
import warnings

import numpy as np
import pandas as pd

from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import HistGradientBoostingRegressor

warnings.filterwarnings("ignore")

DATA_DIR = Path("data")

train = pd.read_csv(DATA_DIR / "train.csv")
test = pd.read_csv(DATA_DIR / "test_x.csv")

TARGET = "bilissel_performans_skoru"

X = train.drop(columns=["id", TARGET])
y = train[TARGET]

test_ids = test["id"]
X_test = test.drop(columns=["id"])

print("Train:", X.shape)
print("Test:", X_test.shape)

Train: (56000, 22)
Test: (24000, 22)

In [28]:
def prepare_features(X, X_test):
    X_fe = X.copy()
    X_test_fe = X_test.copy()

    log_cols = [
        "uyku_oncesi_kafein_mg",
        "uyku_oncesi_ekran_suresi_dk"
    ]

    for col in log_cols:
        if col in X_fe.columns:
            X_fe[col] = np.log1p(X_fe[col])
            X_test_fe[col] = np.log1p(X_test_fe[col])

    def add_features(df):
        df = df.copy()

        if "stres_skoru" in df.columns and "gunluk_calisma_saati" in df.columns:
            df["stres_calisma_yuku"] = df["stres_skoru"] * df["gunluk_calisma_saati"]

        if "rem_yuzdesi" in df.columns and "derin_uyku_yuzdesi" in df.columns:
            df["uyku_kalitesi_orani"] = df["rem_yuzdesi"] + df["derin_uyku_yuzdesi"]

        if "gecelik_uyanma_sayisi" in df.columns and "uykuya_dalma_suresi_dk" in df.columns:
            df["uyku_bozulma_skoru"] = df["gecelik_uyanma_sayisi"] + df["uykuya_dalma_suresi_dk"]

        if "uyku_oncesi_ekran_suresi_dk" in df.columns and "uyku_oncesi_kafein_mg" in df.columns:
            df["dijital_kafein_yuku"] = df["uyku_oncesi_ekran_suresi_dk"] * df["uyku_oncesi_kafein_mg"]

        if "gunluk_adim_sayisi" in df.columns and "stres_skoru" in df.columns:
            df["aktivite_stres_orani"] = df["gunluk_adim_sayisi"] / (df["stres_skoru"] + 1)

        return df

    X_fe = add_features(X_fe)
    X_test_fe = add_features(X_test_fe)

    return X_fe, X_test_fe


X_fe, X_test_fe = prepare_features(X, X_test)

print("X_fe:", X_fe.shape)
print("X_test_fe:", X_test_fe.shape)

X_fe: (56000, 27)
X_test_fe: (24000, 27)

In [29]:
cv = KFold(n_splits=5, shuffle=True, random_state=42)

def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

In [ ]:
from catboost import CatBoostRegressor

def get_catboost_oof(X_fe, y, X_test_fe, cv):
    X_cb = X_fe.copy()
    X_test_cb = X_test_fe.copy()

    cat_cols = X_cb.select_dtypes(include="object").columns.tolist()

    for col in cat_cols:
        X_cb[col] = X_cb[col].fillna("Bilinmiyor").astype(str)
        X_test_cb[col] = X_test_cb[col].fillna("Bilinmiyor").astype(str)

    cat_features_idx = [X_cb.columns.get_loc(col) for col in cat_cols]

    oof_preds = np.zeros(len(X_cb))
    test_preds = np.zeros(len(X_test_cb))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_cb), 1):
        X_train_fold = X_cb.iloc[train_idx]
        X_val_fold = X_cb.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        model = CatBoostRegressor(
            loss_function="RMSE",
            eval_metric="RMSE",
            iterations=1500,
            learning_rate=0.035,
            depth=6,
            l2_leaf_reg=5,
            random_seed=42,
            verbose=200,
            early_stopping_rounds=100
        )

        model.fit(
            X_train_fold,
            y_train_fold,
            cat_features=cat_features_idx,
            eval_set=(X_val_fold, y_val_fold),
            use_best_model=True
        )

        val_pred = model.predict(X_val_fold)
        test_pred = model.predict(X_test_cb)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"CatBoost Fold {fold} RMSE:", fold_rmse)

    print("CatBoost Fold RMSE:", fold_scores)
    print("CatBoost Mean RMSE:", np.mean(fold_scores))
    print("CatBoost OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores


oof_cat, test_cat, scores_cat = get_catboost_oof(X_fe, y, X_test_fe, cv)

In [ ]:
def get_hgb_oof(X_fe, y, X_test_fe, cv):
    num_cols = X_fe.select_dtypes(include=np.number).columns.tolist()
    cat_cols = X_fe.select_dtypes(include="object").columns.tolist()

    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median", add_indicator=True))
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="constant", fill_value="Bilinmiyor")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, num_cols),
            ("cat", categorical_transformer, cat_cols)
        ]
    )

    oof_preds = np.zeros(len(X_fe))
    test_preds = np.zeros(len(X_test_fe))
    fold_scores = []

    for fold, (train_idx, val_idx) in enumerate(cv.split(X_fe), 1):
        X_train_fold = X_fe.iloc[train_idx]
        X_val_fold = X_fe.iloc[val_idx]
        y_train_fold = y.iloc[train_idx]
        y_val_fold = y.iloc[val_idx]

        model = HistGradientBoostingRegressor(
            max_iter=700,
            learning_rate=0.04,
            max_leaf_nodes=31,
            min_samples_leaf=20,
            l2_regularization=0.1,
            random_state=42
        )

        pipeline = Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("model", model)
        ])

        pipeline.fit(X_train_fold, y_train_fold)

        val_pred = pipeline.predict(X_val_fold)
        test_pred = pipeline.predict(X_test_fe)

        oof_preds[val_idx] = val_pred
        test_preds += test_pred / cv.get_n_splits()

        fold_rmse = rmse(y_val_fold, val_pred)
        fold_scores.append(fold_rmse)

        print(f"HGB Fold {fold} RMSE:", fold_rmse)

    print("HGB Fold RMSE:", fold_scores)
    print("HGB Mean RMSE:", np.mean(fold_scores))
    print("HGB OOF RMSE:", rmse(y, oof_preds))

    return oof_preds, test_preds, fold_scores


oof_hgb, test_hgb, scores_hgb = get_hgb_oof(X_fe, y, X_test_fe, cv)

HGB Fold 1 RMSE: 1.228499560987444
HGB Fold 2 RMSE: 1.2290440992060874
HGB Fold 3 RMSE: 1.2159707118361172
HGB Fold 4 RMSE: 1.2243227403073043
HGB Fold 5 RMSE: 1.2450227212554872
HGB Fold RMSE: [np.float64(1.228499560987444), np.float64(1.2290440992060874), np.float64(1.2159707118361172), np.float64(1.2243227403073043), np.float64(1.2450227212554872)]
HGB Mean RMSE: 1.228571966718488
HGB OOF RMSE: 1.2286084071060954

In [ ]:
from scipy.optimize import minimize

oof_matrix = np.column_stack([
    oof_cat,
    oof_hgb
])

test_matrix = np.column_stack([
    test_cat,
    test_hgb
])

def blend_rmse(weights):
    preds = oof_matrix @ weights
    return rmse(y, preds)

n_models = oof_matrix.shape[1]

initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result = minimize(
    blend_rmse,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights = result.x
best_oof_preds = oof_matrix @ best_weights
best_test_preds = test_matrix @ best_weights

print("Best weights:", best_weights)
print("Blend OOF RMSE:", rmse(y, best_oof_preds))

Best weights: [0.84412931 0.15587069]
Blend OOF RMSE: 1.2164008947511131

# Deney 27 - Public Best Çizgisini Baştan Kurma

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

from catboost import CatBoostRegressor, Pool


# ============================================================
# EXP 27 - Clean CatBoost Native Pipeline
# ============================================================

EXP_NAME = "exp27_cat_native_clean"
SEEDS = [42, 2024, 3407, 777, 999]
N_SPLITS = 5

TARGET_COL = "Degerlendirme Puani"


def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))



print("X shape:", X.shape)
print("y shape:", y.shape)
print("X_test shape:", X_test.shape)



cat_features = X.select_dtypes(include=["object", "category"]).columns.tolist()

for col in cat_features:
    X[col] = X[col].fillna("missing").astype(str)
    X_test[col] = X_test[col].fillna("missing").astype(str)

print("Categorical features:", cat_features)
print("Number of categorical features:", len(cat_features))

print("Remaining categorical NaN in train:", X[cat_features].isna().sum().sum())
print("Remaining categorical NaN in test:", X_test[cat_features].isna().sum().sum())


cat_oof_list_exp27 = []
cat_test_list_exp27 = []
cat_seed_scores_exp27 = {}


for seed in SEEDS:
    print("=" * 70)
    print(f"Starting seed: {seed}")
    print("=" * 70)

    kf = KFold(
        n_splits=N_SPLITS,cat_features = X.select_dtypes(include=["object", "category"]).columns.tolist()

print("Categorical features:", cat_features)
print("Number of categorical features:", len(cat_features))
    test_pred = np.zeros(len(X_test))
    fold_scores = []

    for fold, (train_idx, valid_idx) in enumerate(kf.split(X, y), start=1):
        print(f"\nSeed {seed} | Fold {fold}")

        X_train = X.iloc[train_idx]
        y_train = y.iloc[train_idx]

        X_valid = X.iloc[valid_idx]
        y_valid = y.iloc[valid_idx]

        train_pool = Pool(
            X_train,
            y_train,
            cat_features=cat_features
        )

        valid_pool = Pool(
            X_valid,
            y_valid,
            cat_features=cat_features
        )

        test_pool = Pool(
            X_test,
            cat_features=cat_features
        )

        model = CatBoostRegressor(
            loss_function="RMSE",
            eval_metric="RMSE",
            iterations=5000,
            learning_rate=0.03,
            depth=6,
            l2_leaf_reg=3,
            random_seed=seed,
            verbose=500,
            early_stopping_rounds=300,
            allow_writing_files=False
        )

        model.fit(
            train_pool,
            eval_set=valid_pool,
            use_best_model=True
        )

        valid_pred = model.predict(valid_pool)
        fold_test_pred = model.predict(test_pool)

        oof_pred[valid_idx] = valid_pred
        test_pred += fold_test_pred / N_SPLITS

        fold_rmse = rmse(y_valid, valid_pred)
        fold_scores.append(fold_rmse)

        print(f"Seed {seed} | Fold {fold} RMSE: {fold_rmse:.5f}")

    seed_rmse = rmse(y, oof_pred)

    cat_oof_list_exp27.append(oof_pred)
    cat_test_list_exp27.append(test_pred)
    cat_seed_scores_exp27[seed] = {
        "fold_scores": fold_scores,
        "seed_rmse": seed_rmse
    }

    print(f"\nSeed {seed} OOF RMSE: {seed_rmse:.5f}")


# Güvenlik kontrolü
assert len(cat_oof_list_exp27) > 0, "cat_oof_list_exp27 boş! Model eğitimi çalışmamış."
assert len(cat_test_list_exp27) > 0, "cat_test_list_exp27 boş! Test tahminleri oluşmamış."


# 5 seed ortalaması
oof_cat_exp27_5seed = np.mean(cat_oof_list_exp27, axis=0)
test_cat_exp27_5seed = np.mean(cat_test_list_exp27, axis=0)

final_rmse = rmse(y, oof_cat_exp27_5seed)

print("\n" + "=" * 70)
print(f"{EXP_NAME} Final 5-seed OOF RMSE: {final_rmse:.5f}")
print("=" * 70)


# Kaydet
np.save(f"oof_{EXP_NAME}.npy", oof_cat_exp27_5seed)
np.save(f"test_{EXP_NAME}.npy", test_cat_exp27_5seed)

print(f"Saved: oof_{EXP_NAME}.npy")
print(f"Saved: test_{EXP_NAME}.npy")

X shape: (56000, 23)
y shape: (56000,)
X_test shape: (24000, 23)
Categorical features: ['cinsiyet', 'meslek', 'ulke', 'kronotip', 'ruh_sagligi_durumu', 'mevsim', 'gun_tipi']
Number of categorical features: 7
Remaining categorical NaN in train: 0
Remaining categorical NaN in test: 0
======================================================================
Starting seed: 42
======================================================================

Seed 42 | Fold 1
0:	learn: 2.1962065	test: 2.2069443	best: 2.2069443 (0)	total: 53.9ms	remaining: 4m 29s
500:	learn: 1.1958354	test: 1.2241326	best: 1.2241326 (500)	total: 4.65s	remaining: 41.8s
1000:	learn: 1.1711294	test: 1.2209564	best: 1.2209564 (1000)	total: 8.39s	remaining: 33.5s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.220786278
bestIteration = 1079

Shrink model to first 1080 iterations.
Seed 42 | Fold 1 RMSE: 1.22079

Seed 42 | Fold 2
0:	learn: 2.1998516	test: 2.1910527	best: 2.1910527 (0)	total: 7.03ms	remaining: 35.2s
500:	learn: 1.1975040	test: 1.2199261	best: 1.2199241 (498)	total: 3.69s	remaining: 33.2s
1000:	learn: 1.1703787	test: 1.2176194	best: 1.2175255 (978)	total: 7.42s	remaining: 29.7s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.217525462
bestIteration = 978

Shrink model to first 979 iterations.
Seed 42 | Fold 2 RMSE: 1.21753

Seed 42 | Fold 3
0:	learn: 2.1984890	test: 2.1967336	best: 2.1967336 (0)	total: 8.12ms	remaining: 40.6s
500:	learn: 1.2013709	test: 1.2055482	best: 1.2055482 (500)	total: 3.79s	remaining: 34s
1000:	learn: 1.1769459	test: 1.2022033	best: 1.2021440 (987)	total: 7.44s	remaining: 29.7s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.202014167
bestIteration = 1039

Shrink model to first 1040 iterations.
Seed 42 | Fold 3 RMSE: 1.20201

Seed 42 | Fold 4
0:	learn: 2.2000730	test: 2.1897877	best: 2.1897877 (0)	total: 7.73ms	remaining: 38.6s
500:	learn: 1.1969944	test: 1.2101345	best: 1.2101311 (499)	total: 3.75s	remaining: 33.7s
1000:	learn: 1.1710011	test: 1.2095256	best: 1.2090375 (763)	total: 7.44s	remaining: 29.7s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.209037463
bestIteration = 763

Shrink model to first 764 iterations.
Seed 42 | Fold 4 RMSE: 1.20904

Seed 42 | Fold 5
0:	learn: 2.1961241	test: 2.2058237	best: 2.2058237 (0)	total: 8.27ms	remaining: 41.3s
500:	learn: 1.1939402	test: 1.2347749	best: 1.2347749 (500)	total: 3.77s	remaining: 33.8s
1000:	learn: 1.1683380	test: 1.2321318	best: 1.2320437 (902)	total: 7.42s	remaining: 29.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.232043705
bestIteration = 902

Shrink model to first 903 iterations.
Seed 42 | Fold 5 RMSE: 1.23204

Seed 42 OOF RMSE: 1.21632
======================================================================
Starting seed: 2024
======================================================================

Seed 2024 | Fold 1
0:	learn: 2.1997709	test: 2.1864762	best: 2.1864762 (0)	total: 7.78ms	remaining: 38.9s
500:	learn: 1.1953426	test: 1.2262969	best: 1.2262969 (500)	total: 3.78s	remaining: 33.9s
1000:	learn: 1.1703534	test: 1.2232186	best: 1.2232168 (940)	total: 7.49s	remaining: 29.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.222700394
bestIteration = 1169

Shrink model to first 1170 iterations.
Seed 2024 | Fold 1 RMSE: 1.22270

Seed 2024 | Fold 2
0:	learn: 2.1967878	test: 2.1985992	best: 2.1985992 (0)	total: 7.48ms	remaining: 37.4s
500:	learn: 1.1981464	test: 1.2168220	best: 1.2168220 (500)	total: 3.81s	remaining: 34.2s
1000:	learn: 1.1699776	test: 1.2138154	best: 1.2137718 (994)	total: 7.57s	remaining: 30.2s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.213771777
bestIteration = 994

Shrink model to first 995 iterations.
Seed 2024 | Fold 2 RMSE: 1.21377

Seed 2024 | Fold 3
0:	learn: 2.1945370	test: 2.2079861	best: 2.2079861 (0)	total: 8.48ms	remaining: 42.4s
500:	learn: 1.1923063	test: 1.2316173	best: 1.2316110 (498)	total: 3.79s	remaining: 34s
1000:	learn: 1.1659564	test: 1.2297174	best: 1.2294303 (930)	total: 7.57s	remaining: 30.2s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.229430305
bestIteration = 930

Shrink model to first 931 iterations.
Seed 2024 | Fold 3 RMSE: 1.22943

Seed 2024 | Fold 4
0:	learn: 2.1978549	test: 2.1945188	best: 2.1945188 (0)	total: 7.84ms	remaining: 39.2s
500:	learn: 1.1995083	test: 1.2071674	best: 1.2071674 (500)	total: 3.75s	remaining: 33.7s
1000:	learn: 1.1736812	test: 1.2048819	best: 1.2048798 (998)	total: 7.51s	remaining: 30s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.204775879
bestIteration = 1150

Shrink model to first 1151 iterations.
Seed 2024 | Fold 4 RMSE: 1.20478

Seed 2024 | Fold 5
0:	learn: 2.1969158	test: 2.1985207	best: 2.1985207 (0)	total: 7.72ms	remaining: 38.6s
500:	learn: 1.1987382	test: 1.2128088	best: 1.2128088 (500)	total: 3.84s	remaining: 34.5s
1000:	learn: 1.1725086	test: 1.2100154	best: 1.2099598 (908)	total: 7.67s	remaining: 30.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.209886524
bestIteration = 1061

Shrink model to first 1062 iterations.
Seed 2024 | Fold 5 RMSE: 1.20989

Seed 2024 OOF RMSE: 1.21615
======================================================================
Starting seed: 3407
======================================================================

Seed 3407 | Fold 1
0:	learn: 2.1996540	test: 2.1907907	best: 2.1907907 (0)	total: 7.83ms	remaining: 39.1s
500:	learn: 1.1985392	test: 1.2095111	best: 1.2095111 (500)	total: 3.73s	remaining: 33.5s
1000:	learn: 1.1723972	test: 1.2072919	best: 1.2069394 (814)	total: 7.58s	remaining: 30.3s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.206939361
bestIteration = 814

Shrink model to first 815 iterations.
Seed 3407 | Fold 1 RMSE: 1.20694

Seed 3407 | Fold 2
0:	learn: 2.1940630	test: 2.2126590	best: 2.2126590 (0)	total: 7.78ms	remaining: 38.9s
500:	learn: 1.1954469	test: 1.2277162	best: 1.2277162 (500)	total: 3.8s	remaining: 34.1s
1000:	learn: 1.1680377	test: 1.2247940	best: 1.2247907 (989)	total: 7.7s	remaining: 30.8s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.224573625
bestIteration = 1170

Shrink model to first 1171 iterations.
Seed 3407 | Fold 2 RMSE: 1.22457

Seed 3407 | Fold 3
0:	learn: 2.2026834	test: 2.1772246	best: 2.1772246 (0)	total: 7.86ms	remaining: 39.3s
500:	learn: 1.1965206	test: 1.2213811	best: 1.2213693 (499)	total: 4.28s	remaining: 38.4s
1000:	learn: 1.1682628	test: 1.2184126	best: 1.2184126 (1000)	total: 8.19s	remaining: 32.7s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.218395983
bestIteration = 1005

Shrink model to first 1006 iterations.
Seed 3407 | Fold 3 RMSE: 1.21840

Seed 3407 | Fold 4
0:	learn: 2.1964525	test: 2.2030098	best: 2.2030098 (0)	total: 8.03ms	remaining: 40.2s
500:	learn: 1.1972627	test: 1.2170477	best: 1.2170477 (500)	total: 4.03s	remaining: 36.2s
1000:	learn: 1.1712218	test: 1.2149167	best: 1.2145033 (833)	total: 7.93s	remaining: 31.7s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.214503252
bestIteration = 833

Shrink model to first 834 iterations.
Seed 3407 | Fold 4 RMSE: 1.21450

Seed 3407 | Fold 5
0:	learn: 2.1959475	test: 2.2051805	best: 2.2051805 (0)	total: 7.44ms	remaining: 37.2s
500:	learn: 1.1987104	test: 1.2171464	best: 1.2171464 (500)	total: 3.83s	remaining: 34.4s
1000:	learn: 1.1722393	test: 1.2154940	best: 1.2153160 (826)	total: 7.63s	remaining: 30.5s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.215294299
bestIteration = 1034

Shrink model to first 1035 iterations.
Seed 3407 | Fold 5 RMSE: 1.21529

Seed 3407 OOF RMSE: 1.21595
======================================================================
Starting seed: 777
======================================================================

Seed 777 | Fold 1
0:	learn: 2.1982655	test: 2.1946882	best: 2.1946882 (0)	total: 8.4ms	remaining: 42s
500:	learn: 1.1936779	test: 1.2287975	best: 1.2287969 (499)	total: 3.9s	remaining: 35s
1000:	learn: 1.1672089	test: 1.2263681	best: 1.2263492 (998)	total: 7.77s	remaining: 31.1s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.226224292
bestIteration = 1074

Shrink model to first 1075 iterations.
Seed 777 | Fold 1 RMSE: 1.22622

Seed 777 | Fold 2
0:	learn: 2.1968354	test: 2.1999006	best: 2.1999006 (0)	total: 7.94ms	remaining: 39.7s
500:	learn: 1.1933980	test: 1.2320782	best: 1.2320187 (489)	total: 3.9s	remaining: 35s
1000:	learn: 1.1660734	test: 1.2298269	best: 1.2297763 (925)	total: 7.74s	remaining: 30.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.229717567
bestIteration = 1133

Shrink model to first 1134 iterations.
Seed 777 | Fold 2 RMSE: 1.22972

Seed 777 | Fold 3
0:	learn: 2.2021308	test: 2.1784269	best: 2.1784269 (0)	total: 8.64ms	remaining: 43.2s
500:	learn: 1.1986651	test: 1.2153741	best: 1.2153695 (499)	total: 3.9s	remaining: 35s
1000:	learn: 1.1731120	test: 1.2125570	best: 1.2124841 (994)	total: 7.73s	remaining: 30.9s
1500:	learn: 1.1519463	test: 1.2123715	best: 1.2121202 (1253)	total: 11.6s	remaining: 27s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.21212021
bestIteration = 1253

Shrink model to first 1254 iterations.
Seed 777 | Fold 3 RMSE: 1.21212

Seed 777 | Fold 4
0:	learn: 2.1958823	test: 2.2040075	best: 2.2040075 (0)	total: 7.91ms	remaining: 39.5s
500:	learn: 1.2012039	test: 1.2032160	best: 1.2032160 (500)	total: 3.88s	remaining: 34.8s
1000:	learn: 1.1756642	test: 1.2005319	best: 1.2004060 (945)	total: 7.7s	remaining: 30.8s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.200405994
bestIteration = 945

Shrink model to first 946 iterations.
Seed 777 | Fold 4 RMSE: 1.20041

Seed 777 | Fold 5
0:	learn: 2.1942502	test: 2.2105868	best: 2.2105868 (0)	total: 8.46ms	remaining: 42.3s
500:	learn: 1.1975289	test: 1.2156875	best: 1.2156875 (500)	total: 3.8s	remaining: 34.2s
1000:	learn: 1.1697200	test: 1.2130358	best: 1.2128738 (963)	total: 7.64s	remaining: 30.5s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.212873801
bestIteration = 963

Shrink model to first 964 iterations.
Seed 777 | Fold 5 RMSE: 1.21287

Seed 777 OOF RMSE: 1.21631
======================================================================
Starting seed: 999
======================================================================

Seed 999 | Fold 1
0:	learn: 2.1970783	test: 2.1969662	best: 2.1969662 (0)	total: 8.62ms	remaining: 43.1s
500:	learn: 1.1972836	test: 1.2210318	best: 1.2210318 (500)	total: 3.89s	remaining: 34.9s
1000:	learn: 1.1721233	test: 1.2180113	best: 1.2179424 (987)	total: 7.65s	remaining: 30.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.217839677
bestIteration = 1113

Shrink model to first 1114 iterations.
Seed 999 | Fold 1 RMSE: 1.21784

Seed 999 | Fold 2
0:	learn: 2.1945416	test: 2.2113935	best: 2.2113935 (0)	total: 8.71ms	remaining: 43.5s
500:	learn: 1.1998798	test: 1.2092016	best: 1.2092016 (500)	total: 3.89s	remaining: 34.9s
1000:	learn: 1.1735429	test: 1.2067189	best: 1.2065262 (946)	total: 7.66s	remaining: 30.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.206526241
bestIteration = 946

Shrink model to first 947 iterations.
Seed 999 | Fold 2 RMSE: 1.20653

Seed 999 | Fold 3
0:	learn: 2.2003914	test: 2.1872733	best: 2.1872733 (0)	total: 8.29ms	remaining: 41.5s
500:	learn: 1.1935075	test: 1.2257649	best: 1.2257649 (500)	total: 3.9s	remaining: 35.1s
1000:	learn: 1.1673388	test: 1.2227508	best: 1.2227508 (1000)	total: 7.64s	remaining: 30.5s
1500:	learn: 1.1457622	test: 1.2232491	best: 1.2226042 (1218)	total: 11.7s	remaining: 27.2s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.222604155
bestIteration = 1218

Shrink model to first 1219 iterations.
Seed 999 | Fold 3 RMSE: 1.22260

Seed 999 | Fold 4
0:	learn: 2.1945686	test: 2.2107857	best: 2.2107857 (0)	total: 8.85ms	remaining: 44.3s
500:	learn: 1.1957084	test: 1.2231821	best: 1.2231643 (499)	total: 3.83s	remaining: 34.4s
1000:	learn: 1.1678229	test: 1.2192904	best: 1.2192356 (969)	total: 7.73s	remaining: 30.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.219235626
bestIteration = 969

Shrink model to first 970 iterations.
Seed 999 | Fold 4 RMSE: 1.21924

Seed 999 | Fold 5
0:	learn: 2.2016671	test: 2.1819529	best: 2.1819529 (0)	total: 6.92ms	remaining: 34.6s
500:	learn: 1.1955383	test: 1.2184779	best: 1.2184636 (498)	total: 4.01s	remaining: 36s
1000:	learn: 1.1676223	test: 1.2165056	best: 1.2164839 (946)	total: 7.92s	remaining: 31.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.216351827
bestIteration = 1163

Shrink model to first 1164 iterations.
Seed 999 | Fold 5 RMSE: 1.21635

Seed 999 OOF RMSE: 1.21652

======================================================================
exp27_cat_native_clean Final 5-seed OOF RMSE: 1.21469
======================================================================
Saved: oof_exp27_cat_native_clean.npy
Saved: test_exp27_cat_native_clean.npy

In [7]:
exp_results = []

exp_results.append({
    "experiment": "exp27_cat_native_clean",
    "model": "CatBoost",
    "cv": "5-fold x 5-seed",
    "oof_rmse": 1.21469,
    "features": X.shape[1],
    "cat_features": len(cat_features),
    "notes": "Native categorical, categorical missing fixed"
})

pd.DataFrame(exp_results)

,experiment,model,cv,oof_rmse,features,cat_features,notes
0,exp27_cat_native_clean,CatBoost,5-fold x 5-seed,1.21469,23,7,"Native categorical, categorical missing fixed"

In [9]:
test_pred = np.load("test_exp27_cat_native_clean.npy")

submission = pd.DataFrame({
    "id": test["id"],
    "Degerlendirme Puani": test_pred
})

submission.to_csv("submission_exp27_cat_native_clean.csv", index=False)

submission.head()

   id  Degerlendirme Puani
0   1             6.064382
1   2             6.792259
2   3             3.055101
3   4             7.122827
4   5             3.753926

In [10]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error


def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

In [11]:
oof_27 = np.load("oof_exp27_cat_native_clean.npy")
test_27 = np.load("test_exp27_cat_native_clean.npy")

In [12]:
import os

[f for f in os.listdir() if f.endswith(".npy")]

['oof_hgb_v3.npy',
 'test_hgb_v3.npy',
 'test_lgbm_v3.npy',
 'oof_exp27_cat_native_clean.npy',
 'test_exp27_cat_native_clean.npy',
 'oof_lgbm_v3.npy']

In [ ]:
# ============================================================
# DENEY 20E - TEK HÜCRE CLEAN RECREATE
# CatBoost v3 5-seed + HGB v3 + LightGBM v3 optimized blend
# ============================================================

import os
import numpy as np
import pandas as pd

from scipy.optimize import minimize
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from catboost import CatBoostRegressor, Pool


# ------------------------------------------------------------
# Metric
# ------------------------------------------------------------

def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))


# ------------------------------------------------------------
# Basic checks
# ------------------------------------------------------------

assert "X" in globals(), "X değişkeni yok. Önce feature matrix X oluşturulmalı."
assert "X_test" in globals(), "X_test değişkeni yok. Önce test feature matrix X_test oluşturulmalı."
assert "y" in globals(), "y değişkeni yok. Önce target y oluşturulmalı."

print("X shape:", X.shape)
print("X_test shape:", X_test.shape)
print("y shape:", y.shape)


# ------------------------------------------------------------
# Load HGB and LGBM OOF/Test predictions
# ------------------------------------------------------------

if "oof_hgb_v3" not in globals():
    assert os.path.exists("oof_hgb_v3.npy"), "oof_hgb_v3.npy bulunamadı."
    oof_hgb_v3 = np.load("oof_hgb_v3.npy")

if "test_hgb_v3" not in globals():
    assert os.path.exists("test_hgb_v3.npy"), "test_hgb_v3.npy bulunamadı."
    test_hgb_v3 = np.load("test_hgb_v3.npy")

if "oof_lgbm_v3" not in globals():
    assert os.path.exists("oof_lgbm_v3.npy"), "oof_lgbm_v3.npy bulunamadı."
    oof_lgbm_v3 = np.load("oof_lgbm_v3.npy")

if "test_lgbm_v3" not in globals():
    assert os.path.exists("test_lgbm_v3.npy"), "test_lgbm_v3.npy bulunamadı."
    test_lgbm_v3 = np.load("test_lgbm_v3.npy")


print("\nLoaded base models:")
print("HGB OOF:", oof_hgb_v3.shape, "| Test:", test_hgb_v3.shape, "| RMSE:", rmse(y, oof_hgb_v3))
print("LGBM OOF:", oof_lgbm_v3.shape, "| Test:", test_lgbm_v3.shape, "| RMSE:", rmse(y, oof_lgbm_v3))



cat_oof_file = "oof_cat_seed_ensemble_v3_5.npy"
cat_test_file = "test_cat_seed_ensemble_v3_5.npy"

if "oof_cat_seed_ensemble_v3_5" in globals() and "test_cat_seed_ensemble_v3_5" in globals():
    print("\nUsing existing CatBoost v3 5-seed variables from memory.")

elif os.path.exists(cat_oof_file) and os.path.exists(cat_test_file):
    print("\nLoading CatBoost v3 5-seed predictions from npy files.")
    oof_cat_seed_ensemble_v3_5 = np.load(cat_oof_file)
    test_cat_seed_ensemble_v3_5 = np.load(cat_test_file)

else:
    print("\nCatBoost v3 5-seed predictions not found. Training from scratch...")

    SEEDS = [42, 2024, 3407, 777, 999]
    N_SPLITS = 5


    X_cb = X.copy()
    X_test_cb = X_test.copy()

    cat_features = X_cb.select_dtypes(include=["object", "category"]).columns.tolist()

    for col in cat_features:
        X_cb[col] = X_cb[col].fillna("missing").astype(str)
        X_test_cb[col] = X_test_cb[col].fillna("missing").astype(str)

    print("Categorical features:", cat_features)
    print("Number of categorical features:", len(cat_features))
    print("Remaining categorical NaN train:", X_cb[cat_features].isna().sum().sum())
    print("Remaining categorical NaN test:", X_test_cb[cat_features].isna().sum().sum())

    cat_oof_list_v3_5 = []
    cat_test_list_v3_5 = []
    cat_seed_scores_v3_5 = {}

    for seed in SEEDS:
        print("\n" + "=" * 70)
        print(f"CatBoost v3 5-seed training | Seed: {seed}")
        print("=" * 70)

        kf = KFold(
            n_splits=N_SPLITS,
            shuffle=True,
            random_state=seed
        )

        oof_pred = np.zeros(len(X_cb))
        test_pred = np.zeros(len(X_test_cb))
        fold_scores = []

        for fold, (train_idx, valid_idx) in enumerate(kf.split(X_cb, y), start=1):
            print(f"\nSeed {seed} | Fold {fold}")

            X_train = X_cb.iloc[train_idx]
            y_train = y.iloc[train_idx] if hasattr(y, "iloc") else y[train_idx]

            X_valid = X_cb.iloc[valid_idx]
            y_valid = y.iloc[valid_idx] if hasattr(y, "iloc") else y[valid_idx]

            train_pool = Pool(
                X_train,
                y_train,
                cat_features=cat_features
            )

            valid_pool = Pool(
                X_valid,
                y_valid,
                cat_features=cat_features
            )

            test_pool = Pool(
                X_test_cb,
                cat_features=cat_features
            )

            model = CatBoostRegressor(
                loss_function="RMSE",
                eval_metric="RMSE",
                iterations=5000,
                learning_rate=0.03,
                depth=6,
                l2_leaf_reg=3,
                random_seed=seed,
                verbose=500,
                early_stopping_rounds=300,
                allow_writing_files=False
            )

            model.fit(
                train_pool,
                eval_set=valid_pool,
                use_best_model=True
            )

            valid_pred = model.predict(valid_pool)
            fold_test_pred = model.predict(test_pool)

            oof_pred[valid_idx] = valid_pred
            test_pred += fold_test_pred / N_SPLITS

            fold_rmse = rmse(y_valid, valid_pred)
            fold_scores.append(fold_rmse)

            print(f"Seed {seed} | Fold {fold} RMSE: {fold_rmse:.6f}")

        seed_rmse = rmse(y, oof_pred)

        cat_oof_list_v3_5.append(oof_pred)
        cat_test_list_v3_5.append(test_pred)

        cat_seed_scores_v3_5[seed] = {
            "fold_scores": fold_scores,
            "seed_rmse": seed_rmse
        }

        print(f"\nSeed {seed} OOF RMSE: {seed_rmse:.6f}")

    assert len(cat_oof_list_v3_5) > 0, "CatBoost OOF listesi boş kaldı."
    assert len(cat_test_list_v3_5) > 0, "CatBoost test listesi boş kaldı."

    oof_cat_seed_ensemble_v3_5 = np.mean(cat_oof_list_v3_5, axis=0)
    test_cat_seed_ensemble_v3_5 = np.mean(cat_test_list_v3_5, axis=0)

    np.save(cat_oof_file, oof_cat_seed_ensemble_v3_5)
    np.save(cat_test_file, test_cat_seed_ensemble_v3_5)

    print("\nSaved:", cat_oof_file)
    print("Saved:", cat_test_file)


print("\nCatBoost v3 5-seed OOF:", rmse(y, oof_cat_seed_ensemble_v3_5))



assert oof_cat_seed_ensemble_v3_5.shape[0] == len(y), "CatBoost OOF shape hatalı."
assert oof_hgb_v3.shape[0] == len(y), "HGB OOF shape hatalı."
assert oof_lgbm_v3.shape[0] == len(y), "LGBM OOF shape hatalı."

assert test_cat_seed_ensemble_v3_5.shape[0] == len(X_test), "CatBoost test shape hatalı."
assert test_hgb_v3.shape[0] == len(X_test), "HGB test shape hatalı."
assert test_lgbm_v3.shape[0] == len(X_test), "LGBM test shape hatalı."




oof_matrix_v3_5 = np.column_stack([
    oof_cat_seed_ensemble_v3_5,
    oof_hgb_v3,
    oof_lgbm_v3
])

test_matrix_v3_5 = np.column_stack([
    test_cat_seed_ensemble_v3_5,
    test_hgb_v3,
    test_lgbm_v3
])

model_names_v3_5 = [
    "CatBoost v3 5 Seed Ensemble",
    "HGB v3",
    "LightGBM v3"
]


def blend_rmse_v3_5(weights):
    preds = oof_matrix_v3_5 @ weights
    return rmse(y, preds)


n_models = oof_matrix_v3_5.shape[1]
initial_weights = np.ones(n_models) / n_models

constraints = {
    "type": "eq",
    "fun": lambda w: np.sum(w) - 1
}

bounds = [(0, 1)] * n_models

result_v3_5 = minimize(
    blend_rmse_v3_5,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

best_weights_v3_5 = result_v3_5.x
best_oof_preds_v3_5 = oof_matrix_v3_5 @ best_weights_v3_5
best_test_preds_v3_5 = test_matrix_v3_5 @ best_weights_v3_5


print("\n" + "=" * 70)
print("DENEY 20E v3 5-seed optimized blend")
print("=" * 70)

print("Optimization success:", result_v3_5.success)
print("Best weights:")

for name, weight in zip(model_names_v3_5, best_weights_v3_5):
    print(f"{name}: {weight:.6f}")

print("\nBase model OOF scores:")
print("CatBoost v3 5 Seed Ensemble:", rmse(y, oof_cat_seed_ensemble_v3_5))
print("HGB v3:", rmse(y, oof_hgb_v3))
print("LightGBM v3:", rmse(y, oof_lgbm_v3))

print("\nDeney 20E v3 5-seed blend OOF:", rmse(y, best_oof_preds_v3_5))



np.save("oof_20e_recreated.npy", best_oof_preds_v3_5)
np.save("test_20e_recreated.npy", best_test_preds_v3_5)

print("\nSaved: oof_20e_recreated.npy")
print("Saved: test_20e_recreated.npy")



submission_20e_recreated = pd.DataFrame({
    "id": test["id"],
    "Degerlendirme Puani": best_test_preds_v3_5
})

submission_20e_recreated.to_csv("submission_20e_recreated.csv", index=False)

print("\nSubmission saved: submission_20e_recreated.csv")
print(submission_20e_recreated.head())
print("\nSubmission shape:", submission_20e_recreated.shape)
print("\nMissing values:")
print(submission_20e_recreated.isna().sum())

X shape: (56000, 23)
X_test shape: (24000, 23)
y shape: (56000,)

Loaded base models:
HGB OOF: (56000,) | Test: (24000,) | RMSE: 1.2293893343402866
LGBM OOF: (56000,) | Test: (24000,) | RMSE: 1.2310131834046825

CatBoost v3 5-seed predictions not found. Training from scratch...
Categorical features: ['cinsiyet', 'meslek', 'ulke', 'kronotip', 'ruh_sagligi_durumu', 'mevsim', 'gun_tipi']
Number of categorical features: 7
Remaining categorical NaN train: 0
Remaining categorical NaN test: 0

======================================================================
CatBoost v3 5-seed training | Seed: 42
======================================================================

Seed 42 | Fold 1
0:	learn: 2.1962065	test: 2.2069443	best: 2.2069443 (0)	total: 8.11ms	remaining: 40.5s
500:	learn: 1.1958354	test: 1.2241326	best: 1.2241326 (500)	total: 3.67s	remaining: 33s
1000:	learn: 1.1711294	test: 1.2209564	best: 1.2209564 (1000)	total: 8.16s	remaining: 32.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.220786278
bestIteration = 1079

Shrink model to first 1080 iterations.
Seed 42 | Fold 1 RMSE: 1.220786

Seed 42 | Fold 2
0:	learn: 2.1998516	test: 2.1910527	best: 2.1910527 (0)	total: 8.89ms	remaining: 44.4s
500:	learn: 1.1975040	test: 1.2199261	best: 1.2199241 (498)	total: 3.91s	remaining: 35.1s
1000:	learn: 1.1703787	test: 1.2176194	best: 1.2175255 (978)	total: 7.78s	remaining: 31.1s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.217525462
bestIteration = 978

Shrink model to first 979 iterations.
Seed 42 | Fold 2 RMSE: 1.217525

Seed 42 | Fold 3
0:	learn: 2.1984890	test: 2.1967336	best: 2.1967336 (0)	total: 8.54ms	remaining: 42.7s
500:	learn: 1.2013709	test: 1.2055482	best: 1.2055482 (500)	total: 3.94s	remaining: 35.4s
1000:	learn: 1.1769459	test: 1.2022033	best: 1.2021440 (987)	total: 7.7s	remaining: 30.8s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.202014167
bestIteration = 1039

Shrink model to first 1040 iterations.
Seed 42 | Fold 3 RMSE: 1.202014

Seed 42 | Fold 4
0:	learn: 2.2000730	test: 2.1897877	best: 2.1897877 (0)	total: 7.43ms	remaining: 37.1s
500:	learn: 1.1969944	test: 1.2101345	best: 1.2101311 (499)	total: 3.96s	remaining: 35.6s
1000:	learn: 1.1710011	test: 1.2095256	best: 1.2090375 (763)	total: 7.81s	remaining: 31.2s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.209037463
bestIteration = 763

Shrink model to first 764 iterations.
Seed 42 | Fold 4 RMSE: 1.209037

Seed 42 | Fold 5
0:	learn: 2.1961241	test: 2.2058237	best: 2.2058237 (0)	total: 7.85ms	remaining: 39.2s
500:	learn: 1.1939402	test: 1.2347749	best: 1.2347749 (500)	total: 3.84s	remaining: 34.5s
1000:	learn: 1.1683380	test: 1.2321318	best: 1.2320437 (902)	total: 7.67s	remaining: 30.7s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.232043705
bestIteration = 902

Shrink model to first 903 iterations.
Seed 42 | Fold 5 RMSE: 1.232044

Seed 42 OOF RMSE: 1.216325

======================================================================
CatBoost v3 5-seed training | Seed: 2024
======================================================================

Seed 2024 | Fold 1
0:	learn: 2.1997709	test: 2.1864762	best: 2.1864762 (0)	total: 7.57ms	remaining: 37.8s
500:	learn: 1.1953426	test: 1.2262969	best: 1.2262969 (500)	total: 3.95s	remaining: 35.5s
1000:	learn: 1.1703534	test: 1.2232186	best: 1.2232168 (940)	total: 7.74s	remaining: 30.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.222700394
bestIteration = 1169

Shrink model to first 1170 iterations.
Seed 2024 | Fold 1 RMSE: 1.222700

Seed 2024 | Fold 2
0:	learn: 2.1967878	test: 2.1985992	best: 2.1985992 (0)	total: 8.48ms	remaining: 42.4s
500:	learn: 1.1981464	test: 1.2168220	best: 1.2168220 (500)	total: 3.91s	remaining: 35.1s
1000:	learn: 1.1699776	test: 1.2138154	best: 1.2137718 (994)	total: 7.73s	remaining: 30.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.213771777
bestIteration = 994

Shrink model to first 995 iterations.
Seed 2024 | Fold 2 RMSE: 1.213772

Seed 2024 | Fold 3
0:	learn: 2.1945370	test: 2.2079861	best: 2.2079861 (0)	total: 9.08ms	remaining: 45.4s
500:	learn: 1.1923063	test: 1.2316173	best: 1.2316110 (498)	total: 3.91s	remaining: 35.1s
1000:	learn: 1.1659564	test: 1.2297174	best: 1.2294303 (930)	total: 7.76s	remaining: 31s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.229430305
bestIteration = 930

Shrink model to first 931 iterations.
Seed 2024 | Fold 3 RMSE: 1.229430

Seed 2024 | Fold 4
0:	learn: 2.1978549	test: 2.1945188	best: 2.1945188 (0)	total: 7.49ms	remaining: 37.4s
500:	learn: 1.1995083	test: 1.2071674	best: 1.2071674 (500)	total: 3.79s	remaining: 34.1s
1000:	learn: 1.1736812	test: 1.2048819	best: 1.2048798 (998)	total: 7.57s	remaining: 30.2s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.204775879
bestIteration = 1150

Shrink model to first 1151 iterations.
Seed 2024 | Fold 4 RMSE: 1.204776

Seed 2024 | Fold 5
0:	learn: 2.1969158	test: 2.1985207	best: 2.1985207 (0)	total: 7.96ms	remaining: 39.8s
500:	learn: 1.1987382	test: 1.2128088	best: 1.2128088 (500)	total: 3.8s	remaining: 34.1s
1000:	learn: 1.1725086	test: 1.2100154	best: 1.2099598 (908)	total: 7.66s	remaining: 30.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.209886524
bestIteration = 1061

Shrink model to first 1062 iterations.
Seed 2024 | Fold 5 RMSE: 1.209887

Seed 2024 OOF RMSE: 1.216145

======================================================================
CatBoost v3 5-seed training | Seed: 3407
======================================================================

Seed 3407 | Fold 1
0:	learn: 2.1996540	test: 2.1907907	best: 2.1907907 (0)	total: 6.8ms	remaining: 34s
500:	learn: 1.1985392	test: 1.2095111	best: 1.2095111 (500)	total: 3.81s	remaining: 34.2s
1000:	learn: 1.1723972	test: 1.2072919	best: 1.2069394 (814)	total: 7.63s	remaining: 30.5s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.206939361
bestIteration = 814

Shrink model to first 815 iterations.
Seed 3407 | Fold 1 RMSE: 1.206939

Seed 3407 | Fold 2
0:	learn: 2.1940630	test: 2.2126590	best: 2.2126590 (0)	total: 8.38ms	remaining: 41.9s
500:	learn: 1.1954469	test: 1.2277162	best: 1.2277162 (500)	total: 3.82s	remaining: 34.3s
1000:	learn: 1.1680377	test: 1.2247940	best: 1.2247907 (989)	total: 7.66s	remaining: 30.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.224573625
bestIteration = 1170

Shrink model to first 1171 iterations.
Seed 3407 | Fold 2 RMSE: 1.224574

Seed 3407 | Fold 3
0:	learn: 2.2026834	test: 2.1772246	best: 2.1772246 (0)	total: 8.43ms	remaining: 42.1s
500:	learn: 1.1965206	test: 1.2213811	best: 1.2213693 (499)	total: 3.83s	remaining: 34.4s
1000:	learn: 1.1682628	test: 1.2184126	best: 1.2184126 (1000)	total: 7.73s	remaining: 30.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.218395983
bestIteration = 1005

Shrink model to first 1006 iterations.
Seed 3407 | Fold 3 RMSE: 1.218396

Seed 3407 | Fold 4
0:	learn: 2.1964525	test: 2.2030098	best: 2.2030098 (0)	total: 8.08ms	remaining: 40.4s
500:	learn: 1.1972627	test: 1.2170477	best: 1.2170477 (500)	total: 3.89s	remaining: 34.9s
1000:	learn: 1.1712218	test: 1.2149167	best: 1.2145033 (833)	total: 7.79s	remaining: 31.1s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.214503252
bestIteration = 833

Shrink model to first 834 iterations.
Seed 3407 | Fold 4 RMSE: 1.214503

Seed 3407 | Fold 5
0:	learn: 2.1959475	test: 2.2051805	best: 2.2051805 (0)	total: 9.03ms	remaining: 45.1s
500:	learn: 1.1987104	test: 1.2171464	best: 1.2171464 (500)	total: 4.05s	remaining: 36.4s
1000:	learn: 1.1722393	test: 1.2154940	best: 1.2153160 (826)	total: 8s	remaining: 32s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.215294299
bestIteration = 1034

Shrink model to first 1035 iterations.
Seed 3407 | Fold 5 RMSE: 1.215294

Seed 3407 OOF RMSE: 1.215955

======================================================================
CatBoost v3 5-seed training | Seed: 777
======================================================================

Seed 777 | Fold 1
0:	learn: 2.1982655	test: 2.1946882	best: 2.1946882 (0)	total: 8.68ms	remaining: 43.4s
500:	learn: 1.1936779	test: 1.2287975	best: 1.2287969 (499)	total: 3.9s	remaining: 35s
1000:	learn: 1.1672089	test: 1.2263681	best: 1.2263492 (998)	total: 7.78s	remaining: 31.1s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.226224292
bestIteration = 1074

Shrink model to first 1075 iterations.
Seed 777 | Fold 1 RMSE: 1.226224

Seed 777 | Fold 2
0:	learn: 2.1968354	test: 2.1999006	best: 2.1999006 (0)	total: 9.5ms	remaining: 47.5s
500:	learn: 1.1933980	test: 1.2320782	best: 1.2320187 (489)	total: 3.95s	remaining: 35.5s
1000:	learn: 1.1660734	test: 1.2298269	best: 1.2297763 (925)	total: 7.88s	remaining: 31.5s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.229717567
bestIteration = 1133

Shrink model to first 1134 iterations.
Seed 777 | Fold 2 RMSE: 1.229718

Seed 777 | Fold 3
0:	learn: 2.2021308	test: 2.1784269	best: 2.1784269 (0)	total: 9.87ms	remaining: 49.4s
500:	learn: 1.1986651	test: 1.2153741	best: 1.2153695 (499)	total: 4.13s	remaining: 37.1s
1000:	learn: 1.1731120	test: 1.2125570	best: 1.2124841 (994)	total: 8s	remaining: 32s
1500:	learn: 1.1519463	test: 1.2123715	best: 1.2121202 (1253)	total: 12.1s	remaining: 28.1s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.21212021
bestIteration = 1253

Shrink model to first 1254 iterations.
Seed 777 | Fold 3 RMSE: 1.212120

Seed 777 | Fold 4
0:	learn: 2.1958823	test: 2.2040075	best: 2.2040075 (0)	total: 8.23ms	remaining: 41.2s
500:	learn: 1.2012039	test: 1.2032160	best: 1.2032160 (500)	total: 3.88s	remaining: 34.9s
1000:	learn: 1.1756642	test: 1.2005319	best: 1.2004060 (945)	total: 7.71s	remaining: 30.8s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.200405994
bestIteration = 945

Shrink model to first 946 iterations.
Seed 777 | Fold 4 RMSE: 1.200406

Seed 777 | Fold 5
0:	learn: 2.1942502	test: 2.2105868	best: 2.2105868 (0)	total: 9.12ms	remaining: 45.6s
500:	learn: 1.1975289	test: 1.2156875	best: 1.2156875 (500)	total: 3.9s	remaining: 35s
1000:	learn: 1.1697200	test: 1.2130358	best: 1.2128738 (963)	total: 7.92s	remaining: 31.6s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.212873801
bestIteration = 963

Shrink model to first 964 iterations.
Seed 777 | Fold 5 RMSE: 1.212874

Seed 777 OOF RMSE: 1.216314

======================================================================
CatBoost v3 5-seed training | Seed: 999
======================================================================

Seed 999 | Fold 1
0:	learn: 2.1970783	test: 2.1969662	best: 2.1969662 (0)	total: 8.94ms	remaining: 44.7s
500:	learn: 1.1972836	test: 1.2210318	best: 1.2210318 (500)	total: 3.76s	remaining: 33.8s
1000:	learn: 1.1721233	test: 1.2180113	best: 1.2179424 (987)	total: 7.48s	remaining: 29.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.217839677
bestIteration = 1113

Shrink model to first 1114 iterations.
Seed 999 | Fold 1 RMSE: 1.217840

Seed 999 | Fold 2
0:	learn: 2.1945416	test: 2.2113935	best: 2.2113935 (0)	total: 8.16ms	remaining: 40.8s
500:	learn: 1.1998798	test: 1.2092016	best: 1.2092016 (500)	total: 3.89s	remaining: 34.9s
1000:	learn: 1.1735429	test: 1.2067189	best: 1.2065262 (946)	total: 7.71s	remaining: 30.8s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.206526241
bestIteration = 946

Shrink model to first 947 iterations.
Seed 999 | Fold 2 RMSE: 1.206526

Seed 999 | Fold 3
0:	learn: 2.2003914	test: 2.1872733	best: 2.1872733 (0)	total: 9.19ms	remaining: 45.9s
500:	learn: 1.1935075	test: 1.2257649	best: 1.2257649 (500)	total: 3.99s	remaining: 35.9s
1000:	learn: 1.1673388	test: 1.2227508	best: 1.2227508 (1000)	total: 8.12s	remaining: 32.4s
1500:	learn: 1.1457622	test: 1.2232491	best: 1.2226042 (1218)	total: 12.4s	remaining: 28.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.222604155
bestIteration = 1218

Shrink model to first 1219 iterations.
Seed 999 | Fold 3 RMSE: 1.222604

Seed 999 | Fold 4
0:	learn: 2.1945686	test: 2.2107857	best: 2.2107857 (0)	total: 8.9ms	remaining: 44.5s
500:	learn: 1.1957084	test: 1.2231821	best: 1.2231643 (499)	total: 3.94s	remaining: 35.4s
1000:	learn: 1.1678229	test: 1.2192904	best: 1.2192356 (969)	total: 7.93s	remaining: 31.7s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.219235626
bestIteration = 969

Shrink model to first 970 iterations.
Seed 999 | Fold 4 RMSE: 1.219236

Seed 999 | Fold 5
0:	learn: 2.2016671	test: 2.1819529	best: 2.1819529 (0)	total: 8.52ms	remaining: 42.6s
500:	learn: 1.1955383	test: 1.2184779	best: 1.2184636 (498)	total: 4.05s	remaining: 36.4s
1000:	learn: 1.1676223	test: 1.2165056	best: 1.2164839 (946)	total: 7.98s	remaining: 31.9s
Stopped by overfitting detector  (300 iterations wait)

bestTest = 1.216351827
bestIteration = 1163

Shrink model to first 1164 iterations.
Seed 999 | Fold 5 RMSE: 1.216352

Seed 999 OOF RMSE: 1.216524

Saved: oof_cat_seed_ensemble_v3_5.npy
Saved: test_cat_seed_ensemble_v3_5.npy

CatBoost v3 5-seed OOF: 1.2146874339867157

======================================================================
DENEY 20E v3 5-seed optimized blend
======================================================================
Optimization success: True
Best weights:
CatBoost v3 5 Seed Ensemble: 0.866057
HGB v3: 0.081900
LightGBM v3: 0.052043

Base model OOF scores:
CatBoost v3 5 Seed Ensemble: 1.2146874339867157
HGB v3: 1.2293893343402866
LightGBM v3: 1.2310131834046825

Deney 20E v3 5-seed blend OOF: 1.214421487375675

Saved: oof_20e_recreated.npy
Saved: test_20e_recreated.npy

Submission saved: submission_20e_recreated.csv
   id  Degerlendirme Puani
0   1             6.035060
1   2             6.775595
2   3             3.072751
3   4             7.137003
4   5             3.750433

Submission shape: (24000, 2)

Missing values:
id                     0
Degerlendirme Puani    0
dtype: int64

In [21]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error


def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))


oof_20e = np.load("oof_20e_recreated.npy")
test_20e = np.load("test_20e_recreated.npy")

oof_27 = np.load("oof_exp27_cat_native_clean.npy")
test_27 = np.load("test_exp27_cat_native_clean.npy")


print("20E recreated OOF:", rmse(y, oof_20e))
print("Exp27 OOF:", rmse(y, oof_27))


best_score = 999
best_w = None
blend_results = []

for w27 in np.arange(0, 1.001, 0.001):
    blend_oof = (1 - w27) * oof_20e + w27 * oof_27
    score = rmse(y, blend_oof)

    blend_results.append({
        "w_20e": 1 - w27,
        "w_27": w27,
        "rmse": score
    })

    if score < best_score:
        best_score = score
        best_w = w27

blend_results_df = pd.DataFrame(blend_results).sort_values("rmse")

print("Best weight for Exp27:", best_w)
print("Best weight for 20E:", 1 - best_w)
print("Best blend OOF:", best_score)

blend_results_df.head(20)

20E recreated OOF: 1.214421487375675
Exp27 OOF: 1.2146874339867157
Best weight for Exp27: 0.033
Best weight for 20E: 0.967
Best blend OOF: 1.2144211697595806

    w_20e   w_27      rmse
33  0.967  0.033  1.214421
34  0.966  0.034  1.214421
32  0.968  0.032  1.214421
35  0.965  0.035  1.214421
31  0.969  0.031  1.214421
36  0.964  0.036  1.214421
30  0.970  0.030  1.214421
37  0.963  0.037  1.214421
29  0.971  0.029  1.214421
38  0.962  0.038  1.214421
28  0.972  0.028  1.214421
39  0.961  0.039  1.214421
27  0.973  0.027  1.214421
40  0.960  0.040  1.214421
26  0.974  0.026  1.214421
41  0.959  0.041  1.214421
25  0.975  0.025  1.214421
42  0.958  0.042  1.214421
24  0.976  0.024  1.214421
43  0.957  0.043  1.214421

In [22]:
best_w_27 = 0.033
best_w_20e = 0.967

oof_20e = np.load("oof_20e_recreated.npy")
test_20e = np.load("test_20e_recreated.npy")

oof_27 = np.load("oof_exp27_cat_native_clean.npy")
test_27 = np.load("test_exp27_cat_native_clean.npy")

final_oof_blend = best_w_20e * oof_20e + best_w_27 * oof_27
final_test_blend = best_w_20e * test_20e + best_w_27 * test_27

print("Final blend OOF:", rmse(y, final_oof_blend))

Final blend OOF: 1.2144211697595806

In [25]:
submission_final_blend = pd.DataFrame({
    "id": test["id"],
    "Degerlendirme Puani": final_test_blend
})

submission_final_blend.to_csv("submission_20e_recreated_exp27_blend.csv", index=False)

submission_final_blend.head()

   id  Degerlendirme Puani
0   1             6.036028
1   2             6.776145
2   3             3.072168
3   4             7.136535
4   5             3.750549

In [26]:
submission_final_blend = pd.DataFrame({
    "id": test["id"],
    "bilissel_performans_skoru": final_test_blend
})

submission_final_blend.to_csv("submission_20e_recreated_exp27_blend_fixed.csv", index=False)

submission_final_blend.head()

   id  bilissel_performans_skoru
0   1                   6.036028
1   2                   6.776145
2   3                   3.072168
3   4                   7.136535
4   5                   3.750549

In [27]:
print(submission_final_blend.shape)
print(submission_final_blend.isna().sum())
print(submission_final_blend.head())

(24000, 2)
id                           0
bilissel_performans_skoru    0
dtype: int64
   id  bilissel_performans_skoru
0   1                   6.036028
1   2                   6.776145
2   3                   3.072168
3   4                   7.136535
4   5                   3.750549

In [28]:
exp_results.append({
    "experiment": "20E_recreated_exp27_blend",
    "model": "20E recreated + Exp27",
    "local_oof_rmse": 1.2144211697595806,
    "public_lb": 1.20268,
    "weights": "20E=0.967, Exp27=0.033",
    "submission": "submission_20e_recreated_exp27_blend_fixed.csv",
    "notes": "Improved public score from 1.20273 to 1.20268"
})

pd.DataFrame(exp_results)

,experiment,model,cv,oof_rmse,features,cat_features,notes,local_oof_rmse,public_lb,weights,submission
0,exp27_cat_native_clean,CatBoost,5-fold x 5-seed,1.21469,23.0,7.0,"Native categorical, categorical missing fixed",NaN,NaN,NaN,NaN
1,20E_recreated_exp27_blend,20E recreated + Exp27,NaN,NaN,NaN,NaN,Improved public score from 1.20273 to 1.20268,1.214421,1.20268,"20E=0.967, Exp27=0.033",submission_20e_recreated_exp27_blend_fixed.csv

In [ ]:
# ============================================================
# DENEY 28
# CatBoost 5-seed + Feature Engineering + Best Blend Comparison
# ============================================================

import os
import numpy as np
import pandas as pd

from itertools import combinations
from scipy.optimize import minimize
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from catboost import CatBoostRegressor, Pool




def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))



assert "X" in globals(), "X yok."
assert "X_test" in globals(), "X_test yok."
assert "y" in globals(), "y yok."
assert "test" in globals(), "test yok."

print("Original X:", X.shape)
print("Original X_test:", X_test.shape)
print("y:", y.shape)



def safe_div(a, b):
    return a / (b.replace(0, np.nan) + 1e-6)


def find_col(columns, keywords):
    """
    Kolon isimlerinde verilen keyword'leri arar.
    Örn: keywords=["uyku", "süre"] -> uyku_suresi gibi kolonları yakalamaya çalışır.
    """
    cols_lower = {c: c.lower() for c in columns}

    for original_col, lower_col in cols_lower.items():
        ok = True
        for kw in keywords:
            if kw.lower() not in lower_col:
                ok = False
                break
        if ok:
            return original_col

    return None


def add_if_exists_ratio(X_train_fe, X_test_fe, numerator_col, denominator_col, new_col):
    if numerator_col is not None and denominator_col is not None:
        X_train_fe[new_col] = safe_div(X_train_fe[numerator_col], X_train_fe[denominator_col])
        X_test_fe[new_col] = safe_div(X_test_fe[numerator_col], X_test_fe[denominator_col])
        print("Added ratio:", new_col)


def add_if_exists_interaction(X_train_fe, X_test_fe, col1, col2, new_col):
    if col1 is not None and col2 is not None:
        X_train_fe[new_col] = X_train_fe[col1] * X_train_fe[col2]
        X_test_fe[new_col] = X_test_fe[col1] * X_test_fe[col2]
        print("Added interaction:", new_col)



def make_exp28_features(X_base, X_test_base):
    X_fe = X_base.copy()
    X_test_fe = X_test_base.copy()

    for df in [X_fe, X_test_fe]:
        if "id" in df.columns:
            df.drop(columns=["id"], inplace=True)

    cat_cols = X_fe.select_dtypes(include=["object", "category"]).columns.tolist()

    print("\nOriginal categorical columns:", cat_cols)

    for col in cat_cols:
        X_fe[col] = X_fe[col].fillna("missing").astype(str)
        X_test_fe[col] = X_test_fe[col].fillna("missing").astype(str)


    preferred_cat_pairs = [
        ("kronotip", "gun_tipi"),
        ("mevsim", "kronotip"),
        ("meslek", "gun_tipi"),
        ("ruh_sagligi_durumu", "gun_tipi"),
        ("cinsiyet", "meslek"),
        ("ulke", "meslek"),
        ("mevsim", "gun_tipi"),
        ("ruh_sagligi_durumu", "kronotip"),
    ]

    for c1, c2 in preferred_cat_pairs:
        if c1 in X_fe.columns and c2 in X_fe.columns:
            new_col = f"{c1}__{c2}"
            X_fe[new_col] = X_fe[c1].astype(str) + "__" + X_fe[c2].astype(str)
            X_test_fe[new_col] = X_test_fe[c1].astype(str) + "__" + X_test_fe[c2].astype(str)
            print("Added cat combo:", new_col)


    num_cols = X_fe.select_dtypes(include=[np.number]).columns.tolist()

    print("\nOriginal numeric columns:", num_cols)

    X_fe["num_missing_count"] = X_fe[num_cols].isna().sum(axis=1)
    X_test_fe["num_missing_count"] = X_test_fe[num_cols].isna().sum(axis=1)

    X_fe["num_mean"] = X_fe[num_cols].mean(axis=1)
    X_test_fe["num_mean"] = X_test_fe[num_cols].mean(axis=1)

    X_fe["num_std"] = X_fe[num_cols].std(axis=1)
    X_test_fe["num_std"] = X_test_fe[num_cols].std(axis=1)

    X_fe["num_min"] = X_fe[num_cols].min(axis=1)
    X_test_fe["num_min"] = X_test_fe[num_cols].min(axis=1)

    X_fe["num_max"] = X_fe[num_cols].max(axis=1)
    X_test_fe["num_max"] = X_test_fe[num_cols].max(axis=1)

    X_fe["num_range"] = X_fe["num_max"] - X_fe["num_min"]
    X_test_fe["num_range"] = X_test_fe["num_max"] - X_test_fe["num_min"]


    columns = X_fe.columns.tolist()

    sleep_col = find_col(columns, ["uyku"])
    screen_col = find_col(columns, ["ekran"])
    physical_col = find_col(columns, ["fizik"])
    stress_col = find_col(columns, ["stres"])
    age_col = find_col(columns, ["yaş"]) or find_col(columns, ["yas"])
    social_col = find_col(columns, ["sosyal"])
    work_col = find_col(columns, ["çalış"]) or find_col(columns, ["calis"])
    caffeine_col = find_col(columns, ["kafe"]) or find_col(columns, ["kahve"])

    print("\nDetected special columns:")
    print("sleep_col:", sleep_col)
    print("screen_col:", screen_col)
    print("physical_col:", physical_col)
    print("stress_col:", stress_col)
    print("age_col:", age_col)
    print("social_col:", social_col)
    print("work_col:", work_col)
    print("caffeine_col:", caffeine_col)

    add_if_exists_ratio(X_fe, X_test_fe, screen_col, sleep_col, "screen_sleep_ratio")
    add_if_exists_ratio(X_fe, X_test_fe, physical_col, sleep_col, "physical_sleep_ratio")
    add_if_exists_ratio(X_fe, X_test_fe, social_col, screen_col, "social_screen_ratio")
    add_if_exists_ratio(X_fe, X_test_fe, work_col, sleep_col, "work_sleep_ratio")
    add_if_exists_ratio(X_fe, X_test_fe, caffeine_col, sleep_col, "caffeine_sleep_ratio")

    add_if_exists_interaction(X_fe, X_test_fe, stress_col, screen_col, "stress_x_screen")
    add_if_exists_interaction(X_fe, X_test_fe, stress_col, sleep_col, "stress_x_sleep")
    add_if_exists_interaction(X_fe, X_test_fe, stress_col, physical_col, "stress_x_physical")
    add_if_exists_interaction(X_fe, X_test_fe, screen_col, physical_col, "screen_x_physical")
    add_if_exists_interaction(X_fe, X_test_fe, age_col, sleep_col, "age_x_sleep")
    add_if_exists_interaction(X_fe, X_test_fe, age_col, screen_col, "age_x_screen")

    # --------------------------------------------------------
    # 4) Yaş bin feature'ı varsa
    # --------------------------------------------------------

    if age_col is not None:
        X_fe["age_bin"] = pd.cut(
            X_fe[age_col],
            bins=[-np.inf, 18, 25, 35, 45, 60, np.inf],
            labels=["age_0_18", "age_19_25", "age_26_35", "age_36_45", "age_46_60", "age_60_plus"]
        ).astype(str)

        X_test_fe["age_bin"] = pd.cut(
            X_test_fe[age_col],
            bins=[-np.inf, 18, 25, 35, 45, 60, np.inf],
            labels=["age_0_18", "age_19_25", "age_26_35", "age_36_45", "age_46_60", "age_60_plus"]
        ).astype(str)

        print("Added categorical age_bin")

    # --------------------------------------------------------
    # 5) Inf temizliği
    # --------------------------------------------------------

    X_fe = X_fe.replace([np.inf, -np.inf], np.nan)
    X_test_fe = X_test_fe.replace([np.inf, -np.inf], np.nan)

    # Son kategorik kolonlar
    final_cat_cols = X_fe.select_dtypes(include=["object", "category"]).columns.tolist()

    for col in final_cat_cols:
        X_fe[col] = X_fe[col].fillna("missing").astype(str)
        X_test_fe[col] = X_test_fe[col].fillna("missing").astype(str)

    return X_fe, X_test_fe, final_cat_cols


# ------------------------------------------------------------
# Create Exp28 features
# ------------------------------------------------------------

X28, X_test28, cat_features28 = make_exp28_features(X, X_test)

print("\nExp28 X shape:", X28.shape)
print("Exp28 X_test shape:", X_test28.shape)
print("Exp28 categorical feature count:", len(cat_features28))
print("Exp28 categorical features:", cat_features28)
print("Remaining categorical NaN train:", X28[cat_features28].isna().sum().sum())
print("Remaining categorical NaN test:", X_test28[cat_features28].isna().sum().sum())


# ------------------------------------------------------------
# Train CatBoost 5-seed on Exp28 features
# ------------------------------------------------------------

EXP_NAME = "exp28_cat_fe_clean"
SEEDS = [42, 2024, 3407, 777, 999]
N_SPLITS = 5

cat_oof_list_exp28 = []
cat_test_list_exp28 = []
cat_seed_scores_exp28 = {}

for seed in SEEDS:
    print("\n" + "=" * 70)
    print(f"{EXP_NAME} | Seed: {seed}")
    print("=" * 70)

    kf = KFold(
        n_splits=N_SPLITS,
        shuffle=True,
        random_state=seed
    )

    oof_pred = np.zeros(len(X28))
    test_pred = np.zeros(len(X_test28))
    fold_scores = []

    for fold, (train_idx, valid_idx) in enumerate(kf.split(X28, y), start=1):
        print(f"\nSeed {seed} | Fold {fold}")

        X_train = X28.iloc[train_idx]
        y_train = y.iloc[train_idx] if hasattr(y, "iloc") else y[train_idx]

        X_valid = X28.iloc[valid_idx]
        y_valid = y.iloc[valid_idx] if hasattr(y, "iloc") else y[valid_idx]

        train_pool = Pool(
            X_train,
            y_train,
            cat_features=cat_features28
        )

        valid_pool = Pool(
            X_valid,
            y_valid,
            cat_features=cat_features28
        )

        test_pool = Pool(
            X_test28,
            cat_features=cat_features28
        )

        model = CatBoostRegressor(
            loss_function="RMSE",
            eval_metric="RMSE",
            iterations=6000,
            learning_rate=0.025,
            depth=6,
            l2_leaf_reg=4,
            random_seed=seed,
            verbose=500,
            early_stopping_rounds=350,
            allow_writing_files=False
        )

        model.fit(
            train_pool,
            eval_set=valid_pool,
            use_best_model=True
        )

        valid_pred = model.predict(valid_pool)
        fold_test_pred = model.predict(test_pool)

        oof_pred[valid_idx] = valid_pred
        test_pred += fold_test_pred / N_SPLITS

        fold_rmse = rmse(y_valid, valid_pred)
        fold_scores.append(fold_rmse)

        print(f"Seed {seed} | Fold {fold} RMSE: {fold_rmse:.6f}")

    seed_rmse = rmse(y, oof_pred)

    cat_oof_list_exp28.append(oof_pred)
    cat_test_list_exp28.append(test_pred)

    cat_seed_scores_exp28[seed] = {
        "fold_scores": fold_scores,
        "seed_rmse": seed_rmse
    }

    print(f"\nSeed {seed} OOF RMSE: {seed_rmse:.6f}")


assert len(cat_oof_list_exp28) > 0, "Exp28 OOF listesi boş kaldı."
assert len(cat_test_list_exp28) > 0, "Exp28 test listesi boş kaldı."

oof_exp28_cat_fe_clean = np.mean(cat_oof_list_exp28, axis=0)
test_exp28_cat_fe_clean = np.mean(cat_test_list_exp28, axis=0)

exp28_score = rmse(y, oof_exp28_cat_fe_clean)

print("\n" + "=" * 70)
print(f"{EXP_NAME} OOF RMSE:", exp28_score)
print("=" * 70)

np.save("oof_exp28_cat_fe_clean.npy", oof_exp28_cat_fe_clean)
np.save("test_exp28_cat_fe_clean.npy", test_exp28_cat_fe_clean)

print("Saved: oof_exp28_cat_fe_clean.npy")
print("Saved: test_exp28_cat_fe_clean.npy")


# ------------------------------------------------------------
# Compare with current best
# Current best = 20E recreated + Exp27 blend
# ------------------------------------------------------------

oof_20e = np.load("oof_20e_recreated.npy")
test_20e = np.load("test_20e_recreated.npy")

oof_27 = np.load("oof_exp27_cat_native_clean.npy")
test_27 = np.load("test_exp27_cat_native_clean.npy")

current_best_oof = 0.967 * oof_20e + 0.033 * oof_27
current_best_test = 0.967 * test_20e + 0.033 * test_27

current_best_score = rmse(y, current_best_oof)

print("\nCurrent best OOF:", current_best_score)
print("Exp28 OOF:", exp28_score)


# ------------------------------------------------------------
# Blend current best with Exp28
# ------------------------------------------------------------

best_score = 999
best_w_exp28 = None
blend_results_exp28 = []

for w_exp28 in np.arange(0, 1.001, 0.001):
    blend_oof = (1 - w_exp28) * current_best_oof + w_exp28 * oof_exp28_cat_fe_clean
    score = rmse(y, blend_oof)

    blend_results_exp28.append({
        "w_current_best": 1 - w_exp28,
        "w_exp28": w_exp28,
        "rmse": score
    })

    if score < best_score:
        best_score = score
        best_w_exp28 = w_exp28

blend_results_exp28_df = pd.DataFrame(blend_results_exp28).sort_values("rmse")

print("\n" + "=" * 70)
print("Current Best + Exp28 Blend")
print("=" * 70)

print("Best weight for Exp28:", best_w_exp28)
print("Best weight for current best:", 1 - best_w_exp28)
print("Best blend OOF:", best_score)

display(blend_results_exp28_df.head(20))


# ------------------------------------------------------------
# Save final candidate submission
# ------------------------------------------------------------

final_oof_exp28_blend = (1 - best_w_exp28) * current_best_oof + best_w_exp28 * oof_exp28_cat_fe_clean
final_test_exp28_blend = (1 - best_w_exp28) * current_best_test + best_w_exp28 * test_exp28_cat_fe_clean

print("\nFinal Exp28 blend OOF:", rmse(y, final_oof_exp28_blend))

submission_exp28_blend = pd.DataFrame({
    "id": test["id"],
    "bilissel_performans_skoru": final_test_exp28_blend
})

submission_exp28_blend.to_csv("submission_exp28_current_best_blend.csv", index=False)

print("\nSaved: submission_exp28_current_best_blend.csv")
print(submission_exp28_blend.head())
print("\nShape:", submission_exp28_blend.shape)
print("\nMissing:")
print(submission_exp28_blend.isna().sum())
print("\nPrediction describe:")
print(submission_exp28_blend["bilissel_performans_skoru"].describe())

Original X: (56000, 23)
Original X_test: (24000, 23)
y: (56000,)

Original categorical columns: ['cinsiyet', 'meslek', 'ulke', 'kronotip', 'ruh_sagligi_durumu', 'mevsim', 'gun_tipi']
Added cat combo: kronotip__gun_tipi
Added cat combo: mevsim__kronotip
Added cat combo: meslek__gun_tipi
Added cat combo: ruh_sagligi_durumu__gun_tipi
Added cat combo: cinsiyet__meslek
Added cat combo: ulke__meslek
Added cat combo: mevsim__gun_tipi
Added cat combo: ruh_sagligi_durumu__kronotip

Original numeric columns: ['yas', 'vucut_kitle_indeksi', 'rem_yuzdesi', 'derin_uyku_yuzdesi', 'uykuya_dalma_suresi_dk', 'gecelik_uyanma_sayisi', 'uyku_oncesi_kafein_mg', 'uyku_oncesi_ekran_suresi_dk', 'gunluk_adim_sayisi', 'sekerleme_suresi_dk', 'stres_skoru', 'gunluk_calisma_saati', 'dinlenik_nabiz_bpm', 'oda_sicakligi_celsius', 'hafta_sonu_uyku_farki_saat']

Detected special columns:
sleep_col: derin_uyku_yuzdesi
screen_col: uyku_oncesi_ekran_suresi_dk
physical_col: None
stress_col: stres_skoru
age_col: yas
social_col: None
work_col: gunluk_calisma_saati
caffeine_col: uyku_oncesi_kafein_mg
Added ratio: screen_sleep_ratio
Added ratio: work_sleep_ratio
Added ratio: caffeine_sleep_ratio
Added interaction: stress_x_screen
Added interaction: stress_x_sleep
Added interaction: age_x_sleep
Added interaction: age_x_screen
Added categorical age_bin

Exp28 X shape: (56000, 44)
Exp28 X_test shape: (24000, 44)
Exp28 categorical feature count: 16
Exp28 categorical features: ['cinsiyet', 'meslek', 'ulke', 'kronotip', 'ruh_sagligi_durumu', 'mevsim', 'gun_tipi', 'kronotip__gun_tipi', 'mevsim__kronotip', 'meslek__gun_tipi', 'ruh_sagligi_durumu__gun_tipi', 'cinsiyet__meslek', 'ulke__meslek', 'mevsim__gun_tipi', 'ruh_sagligi_durumu__kronotip', 'age_bin']
Remaining categorical NaN train: 0
Remaining categorical NaN test: 0

======================================================================
exp28_cat_fe_clean | Seed: 42
======================================================================

Seed 42 | Fold 1
0:	learn: 2.1996216	test: 2.2108905	best: 2.2108905 (0)	total: 12.9ms	remaining: 1m 17s
500:	learn: 1.2031533	test: 1.2250634	best: 1.2250634 (500)	total: 8.65s	remaining: 1m 35s
1000:	learn: 1.1827451	test: 1.2204497	best: 1.2204337 (997)	total: 17s	remaining: 1m 24s
1500:	learn: 1.1677591	test: 1.2198824	best: 1.2198437 (1498)	total: 25.3s	remaining: 1m 15s
2000:	learn: 1.1531286	test: 1.2197641	best: 1.2196130 (1928)	total: 33.9s	remaining: 1m 7s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.219613043
bestIteration = 1928

Shrink model to first 1929 iterations.
Seed 42 | Fold 1 RMSE: 1.219613

Seed 42 | Fold 2
0:	learn: 2.2028303	test: 2.1937731	best: 2.1937731 (0)	total: 14.6ms	remaining: 1m 27s
500:	learn: 1.2031181	test: 1.2211022	best: 1.2211022 (500)	total: 8.16s	remaining: 1m 29s
1000:	learn: 1.1817318	test: 1.2175042	best: 1.2174889 (998)	total: 16.4s	remaining: 1m 21s
1500:	learn: 1.1654114	test: 1.2171720	best: 1.2168503 (1399)	total: 25.1s	remaining: 1m 15s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.216850297
bestIteration = 1399

Shrink model to first 1400 iterations.
Seed 42 | Fold 2 RMSE: 1.216850

Seed 42 | Fold 3
0:	learn: 2.2014373	test: 2.2002063	best: 2.2002063 (0)	total: 13.3ms	remaining: 1m 20s
500:	learn: 1.2077519	test: 1.2063755	best: 1.2063755 (500)	total: 8.53s	remaining: 1m 33s
1000:	learn: 1.1871390	test: 1.2014798	best: 1.2014694 (995)	total: 16.8s	remaining: 1m 23s
1500:	learn: 1.1714814	test: 1.2005664	best: 1.2005656 (1499)	total: 25.2s	remaining: 1m 15s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.20041386
bestIteration = 1603

Shrink model to first 1604 iterations.
Seed 42 | Fold 3 RMSE: 1.200414

Seed 42 | Fold 4
0:	learn: 2.2035169	test: 2.1931507	best: 2.1931507 (0)	total: 16.5ms	remaining: 1m 39s
500:	learn: 1.2057376	test: 1.2112535	best: 1.2112535 (500)	total: 8.03s	remaining: 1m 28s
1000:	learn: 1.1839437	test: 1.2076895	best: 1.2076895 (1000)	total: 16.1s	remaining: 1m 20s
1500:	learn: 1.1667629	test: 1.2075070	best: 1.2074720 (1493)	total: 24.4s	remaining: 1m 13s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.207471994
bestIteration = 1493

Shrink model to first 1494 iterations.
Seed 42 | Fold 4 RMSE: 1.207472

Seed 42 | Fold 5
0:	learn: 2.1994604	test: 2.2092109	best: 2.2092109 (0)	total: 13.9ms	remaining: 1m 23s
500:	learn: 1.2009089	test: 1.2371614	best: 1.2371614 (500)	total: 8.21s	remaining: 1m 30s
1000:	learn: 1.1790960	test: 1.2325108	best: 1.2325032 (996)	total: 16.3s	remaining: 1m 21s
1500:	learn: 1.1626510	test: 1.2320227	best: 1.2318904 (1448)	total: 24.6s	remaining: 1m 13s
2000:	learn: 1.1476377	test: 1.2319222	best: 1.2318052 (1747)	total: 32.9s	remaining: 1m 5s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.231805224
bestIteration = 1747

Shrink model to first 1748 iterations.
Seed 42 | Fold 5 RMSE: 1.231805

Seed 42 OOF RMSE: 1.215278

======================================================================
exp28_cat_fe_clean | Seed: 2024
======================================================================

Seed 2024 | Fold 1
0:	learn: 2.2038172	test: 2.1906612	best: 2.1906612 (0)	total: 13ms	remaining: 1m 18s
500:	learn: 1.2020806	test: 1.2268699	best: 1.2268699 (500)	total: 8.13s	remaining: 1m 29s
1000:	learn: 1.1821558	test: 1.2226290	best: 1.2226279 (997)	total: 16.4s	remaining: 1m 21s
1500:	learn: 1.1662592	test: 1.2216612	best: 1.2216457 (1462)	total: 24.6s	remaining: 1m 13s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.221610149
bestIteration = 1637

Shrink model to first 1638 iterations.
Seed 2024 | Fold 1 RMSE: 1.221610

Seed 2024 | Fold 2
0:	learn: 2.2016579	test: 2.2032262	best: 2.2032262 (0)	total: 12.9ms	remaining: 1m 17s
500:	learn: 1.2058907	test: 1.2187150	best: 1.2187150 (500)	total: 8.18s	remaining: 1m 29s
1000:	learn: 1.1834188	test: 1.2135899	best: 1.2135708 (994)	total: 16.5s	remaining: 1m 22s
1500:	learn: 1.1673197	test: 1.2129053	best: 1.2128659 (1495)	total: 24.8s	remaining: 1m 14s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.212865926
bestIteration = 1495

Shrink model to first 1496 iterations.
Seed 2024 | Fold 2 RMSE: 1.212866

Seed 2024 | Fold 3
0:	learn: 2.1990906	test: 2.2123919	best: 2.2123919 (0)	total: 11.9ms	remaining: 1m 11s
500:	learn: 1.1999389	test: 1.2328303	best: 1.2328303 (500)	total: 8.25s	remaining: 1m 30s
1000:	learn: 1.1779443	test: 1.2290270	best: 1.2290038 (999)	total: 16.5s	remaining: 1m 22s
1500:	learn: 1.1615111	test: 1.2290527	best: 1.2288520 (1153)	total: 25.1s	remaining: 1m 15s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.228851953
bestIteration = 1153

Shrink model to first 1154 iterations.
Seed 2024 | Fold 3 RMSE: 1.228852

Seed 2024 | Fold 4
0:	learn: 2.2030725	test: 2.1997425	best: 2.1997425 (0)	total: 14.4ms	remaining: 1m 26s
500:	learn: 1.2076365	test: 1.2086267	best: 1.2086267 (500)	total: 8.33s	remaining: 1m 31s
1000:	learn: 1.1842877	test: 1.2041459	best: 1.2041420 (999)	total: 16.7s	remaining: 1m 23s
1500:	learn: 1.1675667	test: 1.2033923	best: 1.2033560 (1481)	total: 25s	remaining: 1m 15s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.203356013
bestIteration = 1481

Shrink model to first 1482 iterations.
Seed 2024 | Fold 4 RMSE: 1.203356

Seed 2024 | Fold 5
0:	learn: 2.2010985	test: 2.2030065	best: 2.2030065 (0)	total: 12.7ms	remaining: 1m 16s
500:	learn: 1.2051756	test: 1.2149300	best: 1.2149300 (500)	total: 8.2s	remaining: 1m 30s
1000:	learn: 1.1847061	test: 1.2108280	best: 1.2108014 (989)	total: 16.6s	remaining: 1m 23s
1500:	learn: 1.1666831	test: 1.2102067	best: 1.2101428 (1240)	total: 25s	remaining: 1m 15s
2000:	learn: 1.1510045	test: 1.2102627	best: 1.2099261 (1805)	total: 33.6s	remaining: 1m 7s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.209926104
bestIteration = 1805

Shrink model to first 1806 iterations.
Seed 2024 | Fold 5 RMSE: 1.209926

Seed 2024 OOF RMSE: 1.215355

======================================================================
exp28_cat_fe_clean | Seed: 3407
======================================================================

Seed 3407 | Fold 1
0:	learn: 2.2030592	test: 2.1942925	best: 2.1942925 (0)	total: 16.9ms	remaining: 1m 41s
500:	learn: 1.2061451	test: 1.2128820	best: 1.2128820 (500)	total: 8.26s	remaining: 1m 30s
1000:	learn: 1.1851610	test: 1.2078210	best: 1.2078031 (989)	total: 16.4s	remaining: 1m 22s
1500:	learn: 1.1678763	test: 1.2068702	best: 1.2067628 (1468)	total: 24.8s	remaining: 1m 14s
2000:	learn: 1.1522813	test: 1.2065661	best: 1.2064942 (1913)	total: 33.4s	remaining: 1m 6s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.206476551
bestIteration = 2094

Shrink model to first 2095 iterations.
Seed 3407 | Fold 1 RMSE: 1.206477

Seed 3407 | Fold 2
0:	learn: 2.1976876	test: 2.2162607	best: 2.2162607 (0)	total: 15.3ms	remaining: 1m 32s
500:	learn: 1.2036875	test: 1.2299431	best: 1.2299431 (500)	total: 8.21s	remaining: 1m 30s
1000:	learn: 1.1810770	test: 1.2254092	best: 1.2254085 (999)	total: 16.5s	remaining: 1m 22s
1500:	learn: 1.1639530	test: 1.2244104	best: 1.2243527 (1378)	total: 24.9s	remaining: 1m 14s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.224352703
bestIteration = 1378

Shrink model to first 1379 iterations.
Seed 3407 | Fold 2 RMSE: 1.224353

Seed 3407 | Fold 3
0:	learn: 2.2062431	test: 2.1804636	best: 2.1804636 (0)	total: 15.6ms	remaining: 1m 33s
500:	learn: 1.2054917	test: 1.2231450	best: 1.2231450 (500)	total: 8.37s	remaining: 1m 31s
1000:	learn: 1.1830731	test: 1.2184080	best: 1.2184080 (1000)	total: 16.9s	remaining: 1m 24s
1500:	learn: 1.1667924	test: 1.2177607	best: 1.2177594 (1445)	total: 25.6s	remaining: 1m 16s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.217756678
bestIteration = 1514

Shrink model to first 1515 iterations.
Seed 3407 | Fold 3 RMSE: 1.217757

Seed 3407 | Fold 4
0:	learn: 2.2001026	test: 2.2070525	best: 2.2070525 (0)	total: 14.8ms	remaining: 1m 29s
500:	learn: 1.2047553	test: 1.2183207	best: 1.2183207 (500)	total: 8.49s	remaining: 1m 33s
1000:	learn: 1.1832673	test: 1.2138777	best: 1.2138677 (986)	total: 17s	remaining: 1m 24s
1500:	learn: 1.1664152	test: 1.2133388	best: 1.2133388 (1500)	total: 25.5s	remaining: 1m 16s
2000:	learn: 1.1516122	test: 1.2134906	best: 1.2132234 (1777)	total: 34s	remaining: 1m 7s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.213223391
bestIteration = 1777

Shrink model to first 1778 iterations.
Seed 3407 | Fold 4 RMSE: 1.213223

Seed 3407 | Fold 5
0:	learn: 2.2004043	test: 2.2092699	best: 2.2092699 (0)	total: 13.3ms	remaining: 1m 19s
500:	learn: 1.2058545	test: 1.2178591	best: 1.2178591 (500)	total: 8.03s	remaining: 1m 28s
1000:	learn: 1.1846244	test: 1.2149562	best: 1.2149528 (995)	total: 16.3s	remaining: 1m 21s
1500:	learn: 1.1695000	test: 1.2144887	best: 1.2143412 (1374)	total: 24.6s	remaining: 1m 13s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.21434123
bestIteration = 1374

Shrink model to first 1375 iterations.
Seed 3407 | Fold 5 RMSE: 1.214341

Seed 3407 OOF RMSE: 1.215244

======================================================================
exp28_cat_fe_clean | Seed: 777
======================================================================

Seed 777 | Fold 1
0:	learn: 2.2024307	test: 2.1988308	best: 2.1988308 (0)	total: 15.1ms	remaining: 1m 30s
500:	learn: 1.2024989	test: 1.2286639	best: 1.2286639 (500)	total: 8.41s	remaining: 1m 32s
1000:	learn: 1.1815718	test: 1.2255230	best: 1.2255230 (1000)	total: 16.7s	remaining: 1m 23s
1500:	learn: 1.1653434	test: 1.2252915	best: 1.2251244 (1375)	total: 25.1s	remaining: 1m 15s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.22512442
bestIteration = 1375

Shrink model to first 1376 iterations.
Seed 777 | Fold 1 RMSE: 1.225124

Seed 777 | Fold 2
0:	learn: 2.2009577	test: 2.2039397	best: 2.2039397 (0)	total: 16.2ms	remaining: 1m 36s
500:	learn: 1.2002425	test: 1.2363196	best: 1.2363196 (500)	total: 8.76s	remaining: 1m 36s
1000:	learn: 1.1791311	test: 1.2322399	best: 1.2321900 (967)	total: 17s	remaining: 1m 24s
1500:	learn: 1.1633449	test: 1.2316859	best: 1.2316399 (1409)	total: 25.4s	remaining: 1m 16s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.231639864
bestIteration = 1409

Shrink model to first 1410 iterations.
Seed 777 | Fold 2 RMSE: 1.231640

Seed 777 | Fold 3
0:	learn: 2.2060711	test: 2.1822618	best: 2.1822618 (0)	total: 15.3ms	remaining: 1m 31s
500:	learn: 1.2060661	test: 1.2172504	best: 1.2172464 (499)	total: 8.1s	remaining: 1m 28s
1000:	learn: 1.1852951	test: 1.2123106	best: 1.2123106 (1000)	total: 16.3s	remaining: 1m 21s
1500:	learn: 1.1693032	test: 1.2114821	best: 1.2114821 (1500)	total: 24.7s	remaining: 1m 13s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.211418964
bestIteration = 1595

Shrink model to first 1596 iterations.
Seed 777 | Fold 3 RMSE: 1.211419

Seed 777 | Fold 4
0:	learn: 2.1995401	test: 2.2076005	best: 2.2076005 (0)	total: 16.2ms	remaining: 1m 37s
500:	learn: 1.2072160	test: 1.2036822	best: 1.2036822 (500)	total: 8.15s	remaining: 1m 29s
1000:	learn: 1.1874227	test: 1.1994894	best: 1.1994430 (993)	total: 16.3s	remaining: 1m 21s
1500:	learn: 1.1712090	test: 1.1987640	best: 1.1987153 (1449)	total: 24.5s	remaining: 1m 13s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.198715273
bestIteration = 1449

Shrink model to first 1450 iterations.
Seed 777 | Fold 4 RMSE: 1.198715

Seed 777 | Fold 5
0:	learn: 2.1981978	test: 2.2146162	best: 2.2146162 (0)	total: 17.6ms	remaining: 1m 45s
500:	learn: 1.2045422	test: 1.2171369	best: 1.2171169 (498)	total: 8.18s	remaining: 1m 29s
1000:	learn: 1.1842566	test: 1.2127757	best: 1.2127756 (996)	total: 16.4s	remaining: 1m 21s
1500:	learn: 1.1677453	test: 1.2116324	best: 1.2116280 (1490)	total: 24.6s	remaining: 1m 13s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.211547542
bestIteration = 1546

Shrink model to first 1547 iterations.
Seed 777 | Fold 5 RMSE: 1.211548

Seed 777 OOF RMSE: 1.215744

======================================================================
exp28_cat_fe_clean | Seed: 999
======================================================================

Seed 999 | Fold 1
0:	learn: 2.2020455	test: 2.2016742	best: 2.2016742 (0)	total: 16.5ms	remaining: 1m 39s
500:	learn: 1.2043967	test: 1.2216270	best: 1.2216270 (500)	total: 8.12s	remaining: 1m 29s
1000:	learn: 1.1846953	test: 1.2168867	best: 1.2168867 (1000)	total: 16.3s	remaining: 1m 21s
1500:	learn: 1.1687269	test: 1.2157291	best: 1.2156859 (1450)	total: 24.5s	remaining: 1m 13s
2000:	learn: 1.1542092	test: 1.2159203	best: 1.2156348 (1728)	total: 33s	remaining: 1m 5s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.215634775
bestIteration = 1728

Shrink model to first 1729 iterations.
Seed 999 | Fold 1 RMSE: 1.215635

Seed 999 | Fold 2
0:	learn: 2.1991287	test: 2.2160736	best: 2.2160736 (0)	total: 16ms	remaining: 1m 36s
500:	learn: 1.2073398	test: 1.2074788	best: 1.2074788 (500)	total: 8.19s	remaining: 1m 29s
1000:	learn: 1.1871068	test: 1.2035243	best: 1.2035243 (1000)	total: 16.4s	remaining: 1m 22s
1500:	learn: 1.1716212	test: 1.2033936	best: 1.2033184 (1413)	total: 24.7s	remaining: 1m 14s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.203318372
bestIteration = 1413

Shrink model to first 1414 iterations.
Seed 999 | Fold 2 RMSE: 1.203318

Seed 999 | Fold 3
0:	learn: 2.2046131	test: 2.1913860	best: 2.1913860 (0)	total: 13.9ms	remaining: 1m 23s
500:	learn: 1.2014664	test: 1.2262251	best: 1.2262251 (500)	total: 8.47s	remaining: 1m 32s
1000:	learn: 1.1810261	test: 1.2219025	best: 1.2219025 (1000)	total: 16.7s	remaining: 1m 23s
1500:	learn: 1.1639523	test: 1.2209415	best: 1.2209051 (1491)	total: 25s	remaining: 1m 14s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.220905066
bestIteration = 1491

Shrink model to first 1492 iterations.
Seed 999 | Fold 3 RMSE: 1.220905

Seed 999 | Fold 4
0:	learn: 2.1988197	test: 2.2150356	best: 2.2150356 (0)	total: 14ms	remaining: 1m 24s
500:	learn: 1.2021201	test: 1.2242088	best: 1.2242088 (500)	total: 8.15s	remaining: 1m 29s
1000:	learn: 1.1824997	test: 1.2194697	best: 1.2194697 (1000)	total: 16.4s	remaining: 1m 21s
1500:	learn: 1.1658637	test: 1.2181106	best: 1.2181106 (1500)	total: 24.7s	remaining: 1m 14s
2000:	learn: 1.1509848	test: 1.2179840	best: 1.2179676 (1979)	total: 33.2s	remaining: 1m 6s
2500:	learn: 1.1363363	test: 1.2179535	best: 1.2179176 (2483)	total: 41.6s	remaining: 58.2s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.217852905
bestIteration = 2645

Shrink model to first 2646 iterations.
Seed 999 | Fold 4 RMSE: 1.217853

Seed 999 | Fold 5
0:	learn: 2.2061438	test: 2.1860145	best: 2.1860145 (0)	total: 14.2ms	remaining: 1m 25s
500:	learn: 1.2036684	test: 1.2198962	best: 1.2198962 (500)	total: 9.04s	remaining: 1m 39s
1000:	learn: 1.1807285	test: 1.2169083	best: 1.2168874 (988)	total: 17.5s	remaining: 1m 27s
1500:	learn: 1.1640818	test: 1.2169639	best: 1.2166423 (1230)	total: 26.1s	remaining: 1m 18s
Stopped by overfitting detector  (350 iterations wait)

bestTest = 1.216642258
bestIteration = 1230

Shrink model to first 1231 iterations.
Seed 999 | Fold 5 RMSE: 1.216642

Seed 999 OOF RMSE: 1.214886

======================================================================
exp28_cat_fe_clean OOF RMSE: 1.2135815294276042
======================================================================
Saved: oof_exp28_cat_fe_clean.npy
Saved: test_exp28_cat_fe_clean.npy

Current best OOF: 1.2144211697595806
Exp28 OOF: 1.2135815294276042

======================================================================
Current Best + Exp28 Blend
======================================================================
Best weight for Exp28: 0.658
Best weight for current best: 0.34199999999999997
Best blend OOF: 1.2132691035554823

     w_current_best  w_exp28      rmse
658           0.342    0.658  1.213269
657           0.343    0.657  1.213269
659           0.341    0.659  1.213269
656           0.344    0.656  1.213269
660           0.340    0.660  1.213269
655           0.345    0.655  1.213269
661           0.339    0.661  1.213269
654           0.346    0.654  1.213269
662           0.338    0.662  1.213269
653           0.347    0.653  1.213269
663           0.337    0.663  1.213269
652           0.348    0.652  1.213269
664           0.336    0.664  1.213269
651           0.349    0.651  1.213269
665           0.335    0.665  1.213269
650           0.350    0.650  1.213269
666           0.334    0.666  1.213269
649           0.351    0.649  1.213269
667           0.333    0.667  1.213269
648           0.352    0.648  1.213269

Final Exp28 blend OOF: 1.2132691035554823

Saved: submission_exp28_current_best_blend.csv
   id  bilissel_performans_skoru
0   1                   6.001816
1   2                   6.737925
2   3                   3.044147
3   4                   7.158813
4   5                   3.694694

Shape: (24000, 2)

Missing:
id                           0
bilissel_performans_skoru    0
dtype: int64

Prediction describe:
count    24000.000000
mean         5.937791
std          1.864037
min         -0.229105
25%          4.645149
50%          6.045080
75%          7.321425
max         10.761977
Name: bilissel_performans_skoru, dtype: float64

In [30]:
submission_exp28_blend_clipped = submission_exp28_blend.copy()

submission_exp28_blend_clipped["bilissel_performans_skoru"] = (
    submission_exp28_blend_clipped["bilissel_performans_skoru"]
    .clip(0, 10)
)

submission_exp28_blend_clipped.to_csv(
    "submission_exp28_current_best_blend_clipped.csv",
    index=False
)

print(submission_exp28_blend_clipped.shape)
print(submission_exp28_blend_clipped.isna().sum())
print(submission_exp28_blend_clipped["bilissel_performans_skoru"].describe())

(24000, 2)
id                           0
bilissel_performans_skoru    0
dtype: int64
count    24000.000000
mean         5.937440
std          1.863110
min          0.000000
25%          4.645149
50%          6.045080
75%          7.321425
max         10.000000
Name: bilissel_performans_skoru, dtype: float64